
var BlinkCardWasmSDK = (() => {
  var _scriptDir = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {

/*

 Copyright 2019 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2024 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2013 The Emscripten Authors
 SPDX-License-Identifier: MIT

 This file gets implicatly injected as a `--post-js` file when
 emcc is run with `--emrun`
*/
function h(){v.buffer!=aa.buffer&&ba();return aa}function w(){v.buffer!=aa.buffer&&ba();return ca}function y(){v.buffer!=aa.buffer&&ba();return da}function ea(){v.buffer!=aa.buffer&&ba();return fa}function A(){v.buffer!=aa.buffer&&ba();return ha}function C(){v.buffer!=aa.buffer&&ba();return ia}function ja(){v.buffer!=aa.buffer&&ba();return ka}var D=moduleArg,la,ma,readyPromise=new Promise((a,b)=>{la=a;ma=b});D.ec||(D.ec=0);D.ec++;
D.ENVIRONMENT_IS_PTHREAD||D.$ww||function(a){function b(m,n,q){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(r){var k=n;r.total&&(k=r.total);if(r.loaded){p.Nc?D.Eb[m].loaded=r.loaded:(p.Nc=!0,D.Eb||(D.Eb={}),D.Eb[m]={loaded:r.loaded,total:k});var t=k=r=0,u;for(u in D.Eb){var z=D.Eb[u];r+=z.total;k+=z.loaded;t++}r=Math.ceil(r*D.ec/t);D.setStatus&&D.setStatus(`Downloading data... (${k}/${r})`)}else!D.Eb&&D.setStatus&&D.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)q(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(r,k,t){this.start=r;this.end=k;this.audio=t}function n(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
r=new Uint8Array(r);m.prototype.Qc=r;r=a.files;for(var k=0;k<r.length;++k)m.prototype.nc[r[k].filename].onload();D.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E6/sdk-blinkcard-in-browser/resources/advanced-threads/BlinkCardWasmSDK.data")}D.FS_createPath("/","microblink",!0,!0);m.prototype={nc:{},open:function(r,k){this.name=k;this.nc[k]=this;D.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.Qc.subarray(this.start,this.end))},finish:function(r){D.FS_createDataFile(this.name,
null,r,!0,!0,!0);D.removeRunDependency(`fp ${this.name}`);this.nc[this.name]=null}};for(var q=a.files,p=0;p<q.length;++p)(new m(q[p].start,q[p].end,q[p].audio||0)).open("GET",q[p].filename);D.addRunDependency("datafile_/opt/jenkins/jenkinsData/E6/sdk-blinkcard-in-browser/resources/advanced-threads/BlinkCardWasmSDK.data");D.Dc||(D.Dc={});D.Dc["/opt/jenkins/jenkinsData/E6/sdk-blinkcard-in-browser/resources/advanced-threads/BlinkCardWasmSDK.data"]={Kd:!1};l?(n(l),l=null):g=n}"object"===typeof window?
window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof D.locateFilePackage||D.locateFile||(D.locateFile=D.locateFilePackage,E("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=D.locateFile?D.locateFile("BlinkCardWasmSDK.data",""):"BlinkCardWasmSDK.data",f=a.remote_package_size,g=null,l=D.getPreloadedPackage?D.getPreloadedPackage(e,f):null;l||b(e,f,function(m){g?(g(m),g=null):l=m},c);D.calledRun?d():(D.preRun||(D.preRun=[]),D.preRun.push(d))}({files:[{filename:"/microblink/Model_1118d9d674e23996f70c6416b2bf5a6ce6ef24a6ad2c92f0ddd1e198e5f05305.strop",start:0,end:19102},{filename:"/microblink/Model_349432d66ef2b216155673b634f7d5c47795bed35719b954f726b5f0856740f3.strop",
start:19102,end:67413},{filename:"/microblink/Model_3b11c3ffacbbf390b932fb9a7024f1a0016f66281ea8c790f8b5903374ad89c2.strop",start:67413,end:336121},{filename:"/microblink/Model_47a2b4fe3503a673b9119db53c50711a9f9ae9b3ada515a534fdbd8013623d43.strop",start:336121,end:673075},{filename:"/microblink/Model_830c13896f96c1cb6d5cad725f44e6aae470f8672d640d20b3272ed4bb839699.strop",start:673075,end:930096},{filename:"/microblink/Model_9f6734be0f5c1e4f3c6c621f4a72db8241feaf7c8705dc68a9cc07a7b634ee85.strop",
start:930096,end:1013725},{filename:"/microblink/Model_b9263312a9b623d1a3b75b643ccdcbc36aae52c278d721443468147c50e44583.strop",start:1013725,end:1281994},{filename:"/microblink/Model_cc1fab8df49d9a21de6c7b76ccf0dac40b17fcfb7073cc520eca073cbf8e33e9.strop",start:1281994,end:1285728},{filename:"/microblink/Model_e946dc0b1d15d7dd6ab8b936593bd77a07a9d8a5fa7a803e531713a6f5d2eab6.strop",start:1285728,end:2313807},{filename:"/microblink/Model_ee471cb6e7b68287281f761c2b05221043b9b059c6cea9132523ab2981f9a7ca.strop",
start:2313807,end:4558823},{filename:"/microblink/Model_f132d1bd7614b1274fafb8a41ec6c047b84b2a43654ae2da5ddd78a2765601c6.strop",start:4558823,end:5393636}],remote_package_size:5393636});D.onAbort=function(a){E("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){E("Stacktrace: "+b.stack)}};
if("object"==typeof window){D.arguments=window.location.search.substr(1).trim().split("&");for(let a=0;a<D.arguments.length;++a)D.arguments[a]=decodeURI(D.arguments[a]);D.arguments[0]||(D.arguments=[])}var na=Object.assign({},D),oa="./this.program",pa=(a,b)=>{throw b;},qa="object"==typeof window,ra="function"==typeof importScripts,sa="object"==typeof process&&"object"==typeof process.xd&&"string"==typeof process.xd.node,F=D.ENVIRONMENT_IS_PTHREAD||!1,ta="";
function ua(a){return D.locateFile?D.locateFile(a,ta):ta+a}var va,wa,xa;
if(qa||ra)ra?ta=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptDir&&(ta=_scriptDir),ta=ta.startsWith("blob:")?"":ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1),va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ra&&(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),wa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ya=D.print||console.log.bind(console),E=D.printErr||console.error.bind(console);Object.assign(D,na);na=null;D.thisProgram&&(oa=D.thisProgram);D.quit&&(pa=D.quit);var za;D.wasmBinary&&(za=D.wasmBinary);var v,Aa,Ba=!1,Ca,aa,ca,da,fa,ha,ia,Da,ka;
function ba(){var a=v.buffer;D.HEAP8=aa=new Int8Array(a);D.HEAP16=da=new Int16Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=Da=new Float32Array(a);D.HEAPF64=ka=new Float64Array(a)}var Ea=D.INITIAL_MEMORY||209715200;
if(F)v=D.wasmMemory;else if(D.wasmMemory)v=D.wasmMemory;else if(v=new WebAssembly.Memory({initial:Ea/65536,maximum:32768,shared:!0}),!(v.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),sa&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");ba();Ea=v.buffer.byteLength;var Fa=[],Ga=[],Ha=[],Ia=[],Ja=!1;function Ka(){F||(D.noFSInit||La||(La=!0,D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?Ma("/dev","stdin",D.stdin):Na("/dev/tty","/dev/stdin"),D.stdout?Ma("/dev","stdout",null,D.stdout):Na("/dev/tty","/dev/stdout"),D.stderr?Ma("/dev","stderr",null,D.stderr):Na("/dev/tty1","/dev/stderr"),Oa("/dev/stdin",0),Oa("/dev/stdout",1),Oa("/dev/stderr",1)),Pa=!1,Qa(Ga))}var Ra=0,Sa=null,Ta=null;
function Ua(){Ra++;D.monitorRunDependencies?.(Ra)}function Va(){Ra--;D.monitorRunDependencies?.(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}function Wa(a){D.onAbort?.(a);a="Aborted("+a+")";E(a);Ba=!0;Ca=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma(a);throw a;}var Xa=a=>a.startsWith("data:application/octet-stream;base64,"),Ya;Ya="BlinkCardWasmSDK.wasm";Xa(Ya)||(Ya=ua(Ya));
function $a(a){if(a==Ya&&za)return new Uint8Array(za);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}function ab(a){return za||!qa&&!ra||"function"!=typeof fetch?Promise.resolve().then(()=>$a(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>$a(a))}
function bb(a,b,c){return ab(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{E(`failed to asynchronously prepare wasm: ${d}`);Wa(d)})}function cb(a,b){var c=Ya;return za||"function"!=typeof WebAssembly.instantiateStreaming||Xa(c)||"function"!=typeof fetch?bb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){E(`wasm streaming compile failed: ${e}`);E("falling back to ArrayBuffer instantiation");return bb(c,a,b)}))}
var G,db,eb={184065:a=>{a=H(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},184201:(a,b,c,d)=>{a=H(a);b=H(b);c=H(c);d=H(d);throw Error(a+b+c+d);},184417:(a,b)=>{a=H(a);b=H(b);throw Error(a+b);},184527:a=>{throw Error(H(a));},184570:()=>{throw Error("Unable to perform that operation while recognizer is in use!");}};function fb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var gb=a=>{a.terminate();a.onmessage=()=>{}},ib=a=>{0==L.xb.length&&(hb(),L.Ac(L.xb[0]));var b=L.xb.pop();if(!b)return 6;L.Bb.push(b);L.pb[a.Ab]=b;b.Ab=a.Ab;b.postMessage({cmd:"run",start_routine:a.qd,arg:a.Oc,pthread_ptr:a.Ab},a.vd);return 0},M=0,lb=a=>{var b=jb();a=a();kb(b);return a},mb=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN,N=(a,b,...c)=>lb(()=>{for(var d=c.length,e=nb(8*d),f=e>>3,g=0;g<c.length;g++){var l=c[g];ja()[f+g]=l}return ob(a,0,d,e,b)});
function pb(a){if(F)return N(0,1,a);Ca=a;qb||0<M||(L.Kc(),D.onExit?.(a),Ba=!0);pa(a,new fb(a))}var wb=a=>{Ca=a;if(F)throw rb(a),"unwind";if(!(qb||0<M||F)){sb();Qa(Ha);La=!1;tb(0);for(var b=0;b<ub.length;b++){var c=ub[b];c&&vb(c)}L.Kc();Ja=!0}pb(a)};function xb(){L.receiveObjectTransfer=L.kd;L.threadInitTLS=L.Lc;L.setExitStatus=L.Jc;qb=!1}function yb(){for(var a=navigator.hardwareConcurrency;a--;)hb();Fa.unshift(()=>{Ua("loading-workers");zb(()=>Va("loading-workers"))})}
function hb(){var a=ua("BlinkCardWasmSDK.worker.js");a=new Worker(a);L.xb.push(a)}function zb(a){F?a():Promise.all(L.xb.map(L.Ac)).then(a)}
var L={xb:[],Bb:[],Mc:[],pb:{},Jc:a=>Ca=a,Td:["$terminateWorker"],Kc:()=>{for(var a of L.Bb)gb(a);for(a of L.xb)gb(a);L.xb=[];L.Bb=[];L.pb=[]},Hc:a=>{var b=a.Ab;delete L.pb[b];L.xb.push(a);L.Bb.splice(L.Bb.indexOf(a),1);a.Ab=0;Ab(b)},kd(){},Lc(){L.Mc.forEach(a=>a())},Ac:a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=Bb()){var l=L.pb[f.targetThread];l?l.postMessage(f,f.transferList):E(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===
g)Cb();else if("spawnThread"===g)ib(f);else if("cleanupThread"===g)L.Hc(L.pb[f.thread]);else if("killThread"===g)f=f.thread,g=L.pb[f],delete L.pb[f],gb(g),Ab(f),L.Bb.splice(L.Bb.indexOf(g),1),g.Ab=0;else if("cancelThread"===g)L.pb[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)D[f.handler](...f.args);else g&&E(`worker sent an unknown command ${g}`)};
a.onerror=f=>{E(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)D.hasOwnProperty(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,urlOrBlob:D.mainScriptUrlOrBlob||_scriptDir,wasmMemory:v,wasmModule:Aa})})};D.PThread=L;var Qa=a=>{for(;0<a.length;)a.shift()(D)};D.establishStackSpace=()=>{var a=Bb(),b=C()[a+52>>2];a=C()[a+56>>2];Db(b,b-a);kb(b)};function rb(a){if(F)return N(1,0,a);wb(a)}
var Eb=[],Fb,P=a=>{var b=Eb[a];b||(a>=Eb.length&&(Eb.length=a+1),Eb[a]=b=Fb.get(a));return b};D.invokeEntryPoint=(a,b)=>{M=0;a=P(a)(b);qb||0<M?L.Jc(a):Gb(a)};var qb=D.noExitRuntime||!1;function Hb(a,b,c,d){return F?N(2,1,a,b,c,d):Ib(a,b,c,d)}
var Ib=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(F&&0===e.length)return Hb(a,b,c,d);a={qd:c,Ab:a,Oc:d,vd:e};return F?(a.Gd="spawnThread",postMessage(a,e),0):ib(a)};function Jb(){var a=A()[+Kb>>2];Kb+=4;return a}
var Lb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Mb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Lb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Nb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ob=a=>{if("/"===
a)return"/";a=Mb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Pb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);Wa("initRandomDevice")},Qb=a=>(Qb=Pb())(a),Rb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Lb(b.split("/").filter(e=>
!!e),!c).join("/");return(c?"/":"")+b||"."},Sb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Tb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Sb)return Sb.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,
d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ub=[],Vb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Wb(a,b){var c=Array(Vb(a)+1);a=Q(a,c,0,c.length);b&&(c.length=a);return c}var Xb=[];function Yb(a,b){Xb[a]={input:[],hb:[],tb:b};Zb(a,$b)}
var $b={open(a){var b=Xb[a.node.Xb];if(!b)throw new S(43);a.cb=b;a.seekable=!1},close(a){a.cb.tb.Sb(a.cb)},Sb(a){a.cb.tb.Sb(a.cb)},read(a,b,c,d){if(!a.cb||!a.cb.tb.zc)throw new S(60);for(var e=0,f=0;f<d;f++){try{var g=a.cb.tb.zc(a.cb)}catch(l){throw new S(29);}if(void 0===g&&0===e)throw new S(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.cb||!a.cb.tb.kc)throw new S(60);try{for(var e=0;e<d;e++)a.cb.tb.kc(a.cb,b[c+e])}catch(f){throw new S(29);
}d&&(a.node.timestamp=Date.now());return e}},ac={zc(){a:{if(!Ub.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Ub=Wb(a,!0)}a=Ub.shift()}return a},kc(a,b){null===b||10===b?(ya(Tb(a.hb,0)),a.hb=[]):0!=b&&a.hb.push(b)},Sb(a){a.hb&&0<a.hb.length&&(ya(Tb(a.hb,0)),a.hb=[])},ad(){return{Dd:25856,Fd:5,Cd:191,Ed:35387,Bd:[3,28,127,21,4,0,1,
0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},bd(){return 0},cd(){return[24,80]}},bc={kc(a,b){null===b||10===b?(E(Tb(a.hb,0)),a.hb=[]):0!=b&&a.hb.push(b)},Sb(a){a.hb&&0<a.hb.length&&(E(Tb(a.hb,0)),a.hb=[])}},dc=a=>{a=65536*Math.ceil(a/65536);var b=cc(65536,a);b?w().fill(0,b,b+a):b=0;return b};function ec(a,b){var c=a.Ya?a.Ya.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ya,a.Ya=new Uint8Array(b),0<a.eb&&a.Ya.set(c.subarray(0,a.eb),0))}
var T={ob:null,sb(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.ob||(T.ob={dir:{node:{wb:T.$a.wb,kb:T.$a.kb,Jb:T.$a.Jb,Vb:T.$a.Vb,Gc:T.$a.Gc,cc:T.$a.cc,Ic:T.$a.Ic,Fc:T.$a.Fc,$b:T.$a.$b},stream:{zb:T.Za.zb}},file:{node:{wb:T.$a.wb,kb:T.$a.kb},stream:{zb:T.Za.zb,read:T.Za.read,write:T.Za.write,Pb:T.Za.Pb,Kb:T.Za.Kb,Wb:T.Za.Wb}},link:{node:{wb:T.$a.wb,kb:T.$a.kb,Nb:T.$a.Nb},stream:{}},tc:{node:{wb:T.$a.wb,kb:T.$a.kb},stream:fc}});
c=gc(a,b,c,d);U(c.mode)?(c.$a=T.ob.dir.node,c.Za=T.ob.dir.stream,c.Ya={}):32768===(c.mode&61440)?(c.$a=T.ob.file.node,c.Za=T.ob.file.stream,c.eb=0,c.Ya=null):40960===(c.mode&61440)?(c.$a=T.ob.link.node,c.Za=T.ob.link.stream):8192===(c.mode&61440)&&(c.$a=T.ob.tc.node,c.Za=T.ob.tc.stream);c.timestamp=Date.now();a&&(a.Ya[b]=c,a.timestamp=c.timestamp);return c},Ld(a){return a.Ya?a.Ya.subarray?a.Ya.subarray(0,a.eb):new Uint8Array(a.Ya):new Uint8Array(0)},$a:{wb(a){var b={};b.Id=8192===(a.mode&61440)?a.id:
1;b.Nd=a.id;b.mode=a.mode;b.Qd=1;b.uid=0;b.Md=0;b.Xb=a.Xb;b.size=U(a.mode)?4096:32768===(a.mode&61440)?a.eb:40960===(a.mode&61440)?a.link.length:0;b.zd=new Date(a.timestamp);b.Pd=new Date(a.timestamp);b.Hd=new Date(a.timestamp);b.Pc=4096;b.Ad=Math.ceil(b.size/b.Pc);return b},kb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.eb!=b))if(0==b)a.Ya=null,a.eb=0;else{var c=a.Ya;a.Ya=new Uint8Array(b);c&&a.Ya.set(c.subarray(0,Math.min(b,
a.eb)));a.eb=b}},Jb(){throw hc[44];},Vb(a,b,c,d){return T.createNode(a,b,c,d)},Gc(a,b,c){if(U(a.mode)){try{var d=ic(b,c)}catch(f){}if(d)for(var e in d.Ya)throw new S(55);}delete a.parent.Ya[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ya[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},cc(a,b){delete a.Ya[b];a.timestamp=Date.now()},Ic(a,b){var c=ic(a,b),d;for(d in c.Ya)throw new S(55);delete a.Ya[b];a.timestamp=Date.now()},Fc(a){var b=[".",".."],c;for(c of Object.keys(a.Ya))b.push(c);return b},
$b(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},Nb(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},Za:{read(a,b,c,d,e){var f=a.node.Ya;if(e>=a.node.eb)return 0;a=Math.min(a.node.eb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===h().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ya||a.Ya.subarray)){if(f)return a.Ya=b.subarray(c,c+d),a.eb=d;if(0===a.eb&&0===e)return a.Ya=
b.slice(c,c+d),a.eb=d;if(e+d<=a.eb)return a.Ya.set(b.subarray(c,c+d),e),d}ec(a,e+d);if(a.Ya.subarray&&b.subarray)a.Ya.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ya[e+f]=b[c+f];a.eb=Math.max(a.eb,e+d);return d},zb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.eb);if(0>b)throw new S(28);return b},Pb(a,b,c){ec(a.node,b+c);a.node.eb=Math.max(a.node.eb,b+c)},Kb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.Ya;if(e&2||a.buffer!==h().buffer){if(0<c||
c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=dc(b);if(!b)throw new S(48);h().set(a,b)}else c=!1,b=a.byteOffset;return{bb:b,ub:c}},Wb(a,b,c,d){T.Za.write(a,b,0,d,c,!1);return 0}}},jc=(a,b,c)=>{var d=`al ${a}`;wa(a,e=>{b(new Uint8Array(e));d&&Va(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ua(d)},kc=D.preloadPlugins||[],lc=(a,b,c,d)=>{"undefined"!=typeof Browser&&(F?xb():yb());var e=!1;kc.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,
c,d),e=!0)});return e},nc=(a,b,c,d,e,f,g,l,m,n)=>{function q(k){function t(u){n?.();l||mc(a,b,u,d,e,m);f?.();Va(r)}lc(k,p,t,()=>{g?.();Va(r)})||t(k)}var p=b?Rb(Mb(a+"/"+b)):a,r=`cp ${p}`;Ua(r);"string"==typeof c?jc(c,q,g):q(c)},oc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},pc=null,qc={},ub=[],rc=1,sc=null,Pa=!0,S=class{constructor(a){this.name="ErrnoError";this.nb=a}},hc={},tc=class{constructor(){this.Zb={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.Zb.flags}set flags(a){this.Zb.flags=
a}get position(){return this.Zb.position}set position(a){this.Zb.position=a}},uc=class{constructor(a,b,c,d){a||=this;this.parent=a;this.sb=a.sb;this.Lb=null;this.id=rc++;this.name=b;this.mode=c;this.$a={};this.Za={};this.Xb=d;this.Yb=365;this.dc=146}get read(){return(this.mode&this.Yb)===this.Yb}set read(a){a?this.mode|=this.Yb:this.mode&=~this.Yb}get write(){return(this.mode&this.dc)===this.dc}set write(a){a?this.mode|=this.dc:this.mode&=~this.dc}get ed(){return U(this.mode)}get dd(){return 8192===
(this.mode&61440)}};function vc(a,b={}){a=Rb(a);if(!a)return{path:"",node:null};b=Object.assign({xc:!0,mc:0},b);if(8<b.mc)throw new S(32);a=a.split("/").filter(g=>!!g);for(var c=pc,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=ic(c,a[e]);d=Mb(d+"/"+a[e]);c.Lb&&(!f||f&&b.xc)&&(c=c.Lb.root);if(!f||b.fc)for(f=0;40960===(c.mode&61440);)if(c=wc(d),d=Rb(Nb(d),c),c=vc(d,{mc:b.mc+1}).node,40<f++)throw new S(32);}return{path:d,node:c}}
function xc(a){for(var b;;){if(a===a.parent)return a=a.sb.Cc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function yc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sc.length}function ic(a,b){var c=U(a.mode)?(c=zc(a,"x"))?c:a.$a.Jb?0:2:54;if(c)throw new S(c);for(c=sc[yc(a.id,b)];c;c=c.Hb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$a.Jb(a,b)}
function gc(a,b,c,d){a=new uc(a,b,c,d);b=yc(a.parent.id,a.name);a.Hb=sc[b];return sc[b]=a}function U(a){return 16384===(a&61440)}function Ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zc(a,b){if(Pa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Bc(a,b){try{return ic(a,b),20}catch(c){}return zc(a,"wx")}function Cc(a){a=ub[a];if(!a)throw new S(8);return a}
function Dc(a,b=-1){a=Object.assign(new tc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!ub[b])break a;throw new S(33);}a.vb=b;return ub[b]=a}function Ec(a,b=-1){a=Dc(a,b);a.Za?.Jd?.(a);return a}var fc={open(a){a.Za=qc[a.node.Xb].Za;a.Za.open?.(a)},zb(){throw new S(70);}};function Zb(a,b){qc[a]={Za:b}}
function Fc(a,b){var c="/"===b;if(c&&pc)throw new S(10);if(!c&&b){var d=vc(b,{xc:!1});b=d.path;d=d.node;if(d.Lb)throw new S(10);if(!U(d.mode))throw new S(54);}b={type:a,Sd:{},Cc:b,fd:[]};a=a.sb(b);a.sb=b;b.root=a;c?pc=a:d&&(d.Lb=b,d.sb&&d.sb.fd.push(b))}function Gc(a,b,c){var d=vc(a,{parent:!0}).node;a=Ob(a);if(!a||"."===a||".."===a)throw new S(28);var e=Bc(d,a);if(e)throw new S(e);if(!d.$a.Vb)throw new S(63);return d.$a.Vb(d,a,b,c)}function Hc(a){return Gc(a,16895,0)}
function Ic(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Gc(a,b|8192,c)}function Na(a,b){if(!Rb(a))throw new S(44);var c=vc(b,{parent:!0}).node;if(!c)throw new S(44);b=Ob(b);var d=Bc(c,b);if(d)throw new S(d);if(!c.$a.$b)throw new S(63);c.$a.$b(c,b,a)}
function Jc(a){var b=vc(a,{parent:!0}).node;if(!b)throw new S(44);var c=Ob(a);a=ic(b,c);a:{try{var d=ic(b,c)}catch(f){d=f.nb;break a}var e=zc(b,"wx");d=e?e:U(d.mode)?31:0}if(d)throw new S(d);if(!b.$a.cc)throw new S(63);if(a.Lb)throw new S(10);b.$a.cc(b,c);b=yc(a.parent.id,a.name);if(sc[b]===a)sc[b]=a.Hb;else for(b=sc[b];b;){if(b.Hb===a){b.Hb=a.Hb;break}b=b.Hb}}function wc(a){a=vc(a).node;if(!a)throw new S(44);if(!a.$a.Nb)throw new S(28);return Rb(xc(a.parent),a.$a.Nb(a))}
function Kc(a,b){a="string"==typeof a?vc(a,{fc:!0}).node:a;if(!a.$a.kb)throw new S(63);a.$a.kb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Oa(a,b,c){if(""===a)throw new S(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Mb(a);try{e=vc(a,{fc:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new S(20);}else e=Gc(a,c,0),d=!0;if(!e)throw new S(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!U(e.mode))throw new S(54);if(!d&&
(c=e?40960===(e.mode&61440)?32:U(e.mode)&&("r"!==Ac(b)||b&512)?31:zc(e,Ac(b)):44))throw new S(c);if(b&512&&!d){c=e;c="string"==typeof c?vc(c,{fc:!0}).node:c;if(!c.$a.kb)throw new S(63);if(U(c.mode))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(d=zc(c,"w"))throw new S(d);c.$a.kb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Dc({node:e,path:xc(e),flags:b,seekable:!0,position:0,Za:e.Za,wd:[],error:!1});e.Za.open&&e.Za.open(e);!D.logReadFiles||b&1||(Lc||={},a in Lc||(Lc[a]=1));return e}
function vb(a){if(null===a.vb)throw new S(8);a.hc&&(a.hc=null);try{a.Za.close&&a.Za.close(a)}catch(b){throw b;}finally{ub[a.vb]=null}a.vb=null}function Mc(a,b,c){if(null===a.vb)throw new S(8);if(!a.seekable||!a.Za.zb)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.Za.zb(a,b,c);a.wd=[]}
function Nc(a,b,c,d,e,f){if(0>d||0>e)throw new S(28);if(null===a.vb)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(U(a.node.mode))throw new S(31);if(!a.Za.write)throw new S(28);a.seekable&&a.flags&1024&&Mc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S(70);b=a.Za.write(a,b,c,d,e,f);g||(a.position+=b);return b}var La;
function Oc(a,b){a="string"==typeof a?a:xc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Mb(a+"/"+c);try{Hc(d)}catch(e){}a=d}}return d}function Pc(a,b,c,d){a=Mb(("string"==typeof a?a:xc(a))+"/"+b);c=oc(c,d);return Gc(a,(void 0!==c?c:438)&4095|32768,0)}
function mc(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:xc(a),g=b?Mb(a+"/"+b):a);a=oc(d,e);g=Gc(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Kc(g,a|146);b=Oa(g,577);Nc(b,c,0,c.length,0,f);vb(b);Kc(g,a)}}
function Ma(a,b,c,d){a=Mb(("string"==typeof a?a:xc(a))+"/"+b);b=oc(!!c,!!d);Ma.Bc||(Ma.Bc=64);var e=Ma.Bc++<<8|0;Zb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var p=c()}catch(r){throw new S(29);}if(void 0===p&&0===n)throw new S(6);if(null===p||void 0===p)break;n++;g[l+q]=p}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(q){throw new S(29);}m&&(f.node.timestamp=Date.now());return n}});return Ic(a,
b,e)}function Qc(a){if(!(a.dd||a.ed||a.link||a.Ya)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(va)try{a.Ya=Wb(va(a.url),!0),a.eb=a.Ya.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Rc(a,b,c,d,e){function f(p,r,k,t,u){p=p.node.Ya;if(u>=p.length)return 0;t=Math.min(p.length-u,t);if(p.slice)for(var z=0;z<t;z++)r[k+z]=p[u+z];else for(z=0;z<t;z++)r[k+z]=p.get(u+z);return t}class g{constructor(){this.jc=!1;this.Rb=[];this.Ib=void 0;this.qc=this.rc=0}get(p){if(!(p>this.length-1||0>p)){var r=p%this.uc;return this.Ib(p/this.uc|0)[r]}}ld(p){this.Ib=p}sc(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+
c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),k,t=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var u=1048576;t||(u=r);var z=this;z.ld(K=>{var J=K*u,x=(K+1)*u-1;x=Math.min(x,r-1);if("undefined"==typeof z.Rb[K]){var O=z.Rb;if(J>x)throw Error("invalid range ("+J+", "+x+") or no bytes requested!");if(x>r-1)throw Error("only "+r+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",
c,!1);r!==u&&B.setRequestHeader("Range","bytes="+J+"-"+x);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);J=void 0!==B.response?new Uint8Array(B.response||[]):Wb(B.responseText||"",!0);O[K]=J}if("undefined"==typeof z.Rb[K])throw Error("doXHR failed!");return z.Rb[K]});if(p||!r)u=r=1,u=r=this.Ib(0).length,ya("LazyFiles on gzip forces download of the whole file when length is accessed");
this.rc=r;this.qc=u;this.jc=!0}get length(){this.jc||this.sc();return this.rc}get uc(){this.jc||this.sc();return this.qc}}if("undefined"!=typeof XMLHttpRequest){if(!ra)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new g;var m=void 0}else m=c,l=void 0;var n=Pc(a,b,d,e);l?n.Ya=l:m&&(n.Ya=null,n.url=m);Object.defineProperties(n,{eb:{get:function(){return this.Ya.length}}});var q={};Object.keys(n.Za).forEach(p=>{var r=
n.Za[p];q[p]=(...k)=>{Qc(n);return r(...k)}});q.read=(p,r,k,t,u)=>{Qc(n);return f(p,r,k,t,u)};q.Kb=(p,r,k)=>{Qc(n);var t=dc(r);if(!t)throw new S(48);f(p,h(),t,r,k);return{bb:t,ub:!0}};n.Za=q;return n}var Sc={},Lc,H=(a,b)=>a?Tb(w(),a,b):"",Kb=void 0;
function Tc(a,b,c){if(F)return N(3,1,a,b,c);Kb=c;try{var d=Cc(a);switch(b){case 0:var e=Jb();if(0>e)break;for(;ub[e];)e++;return Ec(d,e).vb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Jb(),d.flags|=e,0;case 12:return e=Jb(),y()[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Sc||"ErrnoError"!==f.name)throw f;return-f.nb}}
function Uc(a,b,c){if(F)return N(4,1,a,b,c);Kb=c;try{var d=Cc(a);switch(b){case 21509:return d.cb?0:-59;case 21505:if(!d.cb)return-59;if(d.cb.tb.ad){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Jb();A()[e>>2]=25856;A()[e+4>>2]=5;A()[e+8>>2]=191;A()[e+12>>2]=35387;for(var f=0;32>f;f++)h()[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.cb?0:-59;case 21506:case 21507:case 21508:if(!d.cb)return-59;if(d.cb.tb.bd)for(e=Jb(),A(),A(),A(),A(),a=[],
f=0;32>f;f++)a.push(h()[e+f+17]);return 0;case 21519:if(!d.cb)return-59;e=Jb();return A()[e>>2]=0;case 21520:return d.cb?-28:-59;case 21531:e=Jb();if(!d.Za.$c)throw new S(59);return d.Za.$c(d,b,e);case 21523:if(!d.cb)return-59;d.cb.tb.cd&&(f=[24,80],e=Jb(),y()[e>>1]=f[0],y()[e+2>>1]=f[1]);return 0;case 21524:return d.cb?0:-59;case 21515:return d.cb?0:-59;default:return-28}}catch(g){if("undefined"==typeof Sc||"ErrnoError"!==g.name)throw g;return-g.nb}}
function Vc(a,b,c,d){if(F)return N(5,1,a,b,c,d);Kb=d;try{b=H(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Cc(a).path;if(0==e.length)throw new S(44);b=Mb(f+"/"+e)}var g=d?Jb():0;return Oa(b,c,g).vb}catch(l){if("undefined"==typeof Sc||"ErrnoError"!==l.name)throw l;return-l.nb}}var Wc={},Xc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Yc(a){return this.fromWireType(C()[a>>2])}
var Zc={},$c={},ad={},bd,dd=(a,b,c)=>{function d(l){l=c(l);if(l.length!==a.length)throw new bd("Mismatched type converter count");for(var m=0;m<a.length;++m)cd(a[m],l[m])}a.forEach(function(l){ad[l]=b});var e=Array(b.length),f=[],g=0;b.forEach((l,m)=>{$c.hasOwnProperty(l)?e[m]=$c[l]:(f.push(l),Zc.hasOwnProperty(l)||(Zc[l]=[]),Zc[l].push(()=>{e[m]=$c[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},ed,V=a=>{for(var b="";w()[a];)b+=ed[w()[a++]];return b},W;
function fd(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if($c.hasOwnProperty(a)){if(c.Zc)return;throw new W(`Cannot register type '${d}' twice`);}$c[a]=b;delete ad[a];Zc.hasOwnProperty(a)&&(b=Zc[a],delete Zc[a],b.forEach(e=>e()))}function cd(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return fd(a,b,c)}
var gd=a=>{throw new W(a.Xa.fb.ab.name+" instance already deleted");},hd=!1,jd=()=>{},kd=(a,b,c)=>{if(b===c)return a;if(void 0===c.jb)return null;a=kd(a,b,c.jb);return null===a?null:c.Tc(a)},ld={},md=[],nd=()=>{for(;md.length;){var a=md.pop();a.Xa.Fb=!1;a["delete"]()}},od,pd={},qd=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.jb;)b=a.Ob(b),a=a.jb;return pd[b]},sd=(a,b)=>{if(!b.fb||!b.bb)throw new bd("makeClassHandle requires ptr and ptrType");if(!!b.lb!==!!b.gb)throw new bd("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return rd(Object.create(a,{Xa:{value:b,writable:!0}}))},rd=a=>{if("undefined"===typeof FinalizationRegistry)return rd=b=>b,a;hd=new FinalizationRegistry(b=>{b=b.Xa;--b.count.value;0===b.count.value&&(b.gb?b.lb.qb(b.gb):b.fb.ab.qb(b.bb))});rd=b=>{var c=b.Xa;c.gb&&hd.register(b,{Xa:c},b);return b};jd=b=>{hd.unregister(b)};return rd(a)};function td(){}
var ud=(a,b)=>Object.defineProperty(b,"name",{value:a}),vd=(a,b,c)=>{if(void 0===a[b].ib){var d=a[b];a[b]=function(...e){if(!a[b].ib.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ib})!`);return a[b].ib[e.length].apply(this,e)};a[b].ib=[];a[b].ib[d.Qb]=d}},wd=(a,b,c)=>{if(D.hasOwnProperty(a)){if(void 0===c||void 0!==D[a].ib&&void 0!==D[a].ib[c])throw new W(`Cannot register public name '${a}' twice`);vd(D,a,a);
if(D.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);D[a].ib[c]=b}else D[a]=b,void 0!==c&&(D[a].Rd=c)},xd=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function yd(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.Gb=c;this.qb=d;this.jb=e;this.Vc=f;this.Ob=g;this.Tc=l;this.hd=[]}
var zd=(a,b,c)=>{for(;b!==c;){if(!b.Ob)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Ob(a);b=b.jb}return a};function Ad(a,b){if(null===b){if(this.ic)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.Xa)throw new W(`Cannot pass "${Bd(b)}" as a ${this.name}`);if(!b.Xa.bb)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return zd(b.Xa.bb,b.Xa.fb.ab,this.ab)}
function Cd(a,b){if(null===b){if(this.ic)throw new W(`null is not a valid ${this.name}`);if(this.Ub){var c=this.lc();null!==a&&a.push(this.qb,c);return c}return 0}if(!b||!b.Xa)throw new W(`Cannot pass "${Bd(b)}" as a ${this.name}`);if(!b.Xa.bb)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Tb&&b.Xa.fb.Tb)throw new W(`Cannot convert argument of type ${b.Xa.lb?b.Xa.lb.name:b.Xa.fb.name} to parameter type ${this.name}`);c=zd(b.Xa.bb,b.Xa.fb.ab,this.ab);if(this.Ub){if(void 0===
b.Xa.gb)throw new W("Passing raw pointer to smart pointer is illegal");switch(this.pd){case 0:if(b.Xa.lb===this)c=b.Xa.gb;else throw new W(`Cannot convert argument of type ${b.Xa.lb?b.Xa.lb.name:b.Xa.fb.name} to parameter type ${this.name}`);break;case 1:c=b.Xa.gb;break;case 2:if(b.Xa.lb===this)c=b.Xa.gb;else{var d=b.clone();c=this.jd(c,Dd(()=>d["delete"]()));null!==a&&a.push(this.qb,c)}break;default:throw new W("Unsupporting sharing policy");}}return c}
function Ed(a,b){if(null===b){if(this.ic)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.Xa)throw new W(`Cannot pass "${Bd(b)}" as a ${this.name}`);if(!b.Xa.bb)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Xa.fb.Tb)throw new W(`Cannot convert argument of type ${b.Xa.fb.name} to parameter type ${this.name}`);return zd(b.Xa.bb,b.Xa.fb.ab,this.ab)}
function Fd(a,b,c,d,e,f,g,l,m,n,q){this.name=a;this.ab=b;this.ic=c;this.Tb=d;this.Ub=e;this.gd=f;this.pd=g;this.Ec=l;this.lc=m;this.jd=n;this.qb=q;e||void 0!==b.jb?this.toWireType=Cd:(this.toWireType=d?Ad:Ed,this.mb=null)}
var Gd=(a,b,c)=>{if(!D.hasOwnProperty(a))throw new bd("Replacing nonexistent public symbol");void 0!==D[a].ib&&void 0!==c?D[a].ib[c]=b:(D[a]=b,D[a].Qb=c)},Hd=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,D["dynCall_"+a])(b,...c)):b=P(b)(...c);return b},Id=(a,b)=>(...c)=>Hd(a,b,c),Jd=(a,b)=>{a=V(a);var c=a.includes("j")?Id(a,b):P(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c},Kd,Nd=a=>{a=Ld(a);var b=V(a);Md(a);return b},Od=(a,b)=>{function c(f){e[f]||
$c[f]||(ad[f]?ad[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Kd(`${a}: `+d.map(Nd).join([", "]));},Pd=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C()[b+4*d>>2]);return c};function Qd(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].mb)return!0;return!1}
function Rd(a,b,c,d,e){var f=b.length;if(2>f)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=Qd(b),m="void"!==b[0].name,n=f-2,q=Array(n),p=[],r=[];return ud(a,function(...k){if(k.length!==n)throw new W(`function ${a} called with ${k.length} arguments, expected ${n}`);r.length=0;p.length=g?2:1;p[0]=e;if(g){var t=b[1].toWireType(r,this);p[1]=t}for(var u=0;u<n;++u)q[u]=b[u+2].toWireType(r,k[u]),p.push(q[u]);k=d(...p);if(l)Xc(r);
else for(u=g?1:2;u<b.length;u++){var z=1===u?t:q[u-2];null!==b[u].mb&&b[u].mb(z)}t=m?b[0].fromWireType(k):void 0;return t})}
var Sd=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Td=[],Ud=[],Vd=a=>{9<a&&0===--Ud[a+1]&&(Ud[a]=void 0,Td.push(a))},X=a=>{if(!a)throw new W("Cannot use deleted val. handle = "+a);return Ud[a]},Dd=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Td.pop()||Ud.length;Ud[b]=a;Ud[b+1]=1;return b}},Wd={name:"emscripten::val",fromWireType:a=>{var b=X(a);Vd(a);return b},toWireType:(a,b)=>Dd(b),argPackAdvance:8,readValueFromPointer:Yc,
mb:null},Bd=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Xd=(a,b)=>{switch(b){case 4:return function(c){var d=this.fromWireType;v.buffer!=aa.buffer&&ba();return d.call(this,Da[c>>2])};case 8:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Yd=(a,b,c)=>{switch(b){case 1:return c?d=>h()[d]:d=>w()[d];case 2:return c?d=>y()[d>>1]:d=>ea()[d>>1];case 4:return c?d=>
A()[d>>2]:d=>C()[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Zd=(a,b)=>{Q(a,w(),b,17)},$d="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,ae=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ea()[c];)++c;c<<=1;if(32<c-a&&$d)return $d.decode(w().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=y()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},be=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=
a.charCodeAt(e);y()[b>>1]=f;b+=2}y()[b>>1]=0;return b-d},ce=a=>2*a.length,de=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ee=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d},fe=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},ge=a=>{if(!Ja&&!Ba)try{if(a(),!(Ja||qb||0<M))try{F?Gb(Ca):wb(Ca)}catch(b){b instanceof fb||"unwind"==b||pa(1,b)}}catch(b){b instanceof fb||"unwind"==b||pa(1,b)}},he=a=>{"function"===typeof Atomics.yd&&(Atomics.yd(A(),a>>2,a).value.then(Cb),a+=128,Atomics.store(A(),a>>2,1))};D.__emscripten_thread_mailbox_await=he;var Cb=()=>{var a=Bb();a&&(he(a),ge(ie))};D.checkMailbox=Cb;
var je=[],ke=(a,b)=>{var c=$c[a];if(void 0===c)throw a=`${b} has unknown type ${Nd(a)}`,new W(a);return c},le=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(C()[b>>2]=Dd(d));return a},me=[],ne={},oe=a=>{var b=ne[a];return void 0===b?V(a):b},pe=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},qe=a=>{var b=me.length;me.push(a);return b},re=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=ke(C()[b+4*d>>2],"parameter "+d);return c},se=Reflect.construct,te=a=>0===a%4&&(0!==a%100||0===a%400),ue=[0,31,60,91,121,152,182,213,244,274,305,335],ve=[0,31,59,90,120,151,181,
212,243,273,304,334],we=[];class xe{constructor(){this.ub=[void 0];this.yc=[]}get(a){return this.ub[a]}has(a){return void 0!==this.ub[a]}Pb(a){var b=this.yc.pop()||this.ub.length;this.ub[b]=a;return b}}function ye(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b}var ze,Ae;
function Be(a,b,c,d,e){function f(){var B=0,R=0;x.response&&K&&0===C()[a+12>>2]&&(R=x.response.byteLength);0<R&&(B=Ce(R),w().set(new Uint8Array(x.response),B));C()[a+12>>2]=B;Y(a+16,R);Y(a+24,0);(B=x.response?x.response.byteLength:0)&&Y(a+32,B);y()[a+40>>1]=x.readyState;y()[a+42>>1]=x.status;x.statusText&&(B=a+44,Q(x.statusText,w(),B,64))}var g=C()[a+8>>2];if(g){var l=H(g),m=a+112,n=H(m+0);n||="GET";var q=C()[m+56>>2],p=C()[m+68>>2],r=C()[m+72>>2];g=C()[m+76>>2];var k=C()[m+80>>2],t=C()[m+84>>2],
u=C()[m+88>>2],z=C()[m+52>>2],K=!!(z&1),J=!!(z&2);z=!!(z&64);p=p?H(p):void 0;r=r?H(r):void 0;var x=new XMLHttpRequest;x.withCredentials=!!w()[m+60];x.open(n,l,!z,p,r);z||(x.timeout=q);x.Vd=l;x.responseType="arraybuffer";k&&(l=H(k),x.overrideMimeType(l));if(g)for(;;){m=C()[g>>2];if(!m)break;l=C()[g+4>>2];if(!l)break;g+=8;m=H(m);l=H(l);x.setRequestHeader(m,l)}var O=ze.Pb(x);C()[a>>2]=O;g=t&&u?w().slice(t,t+u):null;x.onload=B=>{ze.has(O)&&(f(),200<=x.status&&300>x.status?b?.(a,x,B):c?.(a,x,B))};x.onerror=
B=>{ze.has(O)&&(f(),c?.(a,x,B))};x.ontimeout=B=>{ze.has(O)&&c?.(a,x,B)};x.onprogress=B=>{if(ze.has(O)){var R=K&&J&&x.response?x.response.byteLength:0,I=0;0<R&&K&&J&&(I=Ce(R),w().set(new Uint8Array(x.response),I));C()[a+12>>2]=I;Y(a+16,R);Y(a+24,B.loaded-R);Y(a+32,B.total);y()[a+40>>1]=x.readyState;3<=x.readyState&&0===x.status&&0<B.loaded&&(x.status=200);y()[a+42>>1]=x.status;x.statusText&&(R=a+44,Q(x.statusText,w(),R,64));d?.(a,x,B);I&&Md(I)}};x.onreadystatechange=B=>{ze.has(O)?(y()[a+40>>1]=x.readyState,
2<=x.readyState&&(y()[a+42>>1]=x.status),e?.(a,x,B)):--M};try{x.send(g)}catch(B){c?.(a,x,B)}}else c(a,0,"no url specified!")}var Y=(a,b)=>{C()[a>>2]=b;var c=C()[a>>2];C()[a+4>>2]=(b-c)/4294967296};
function De(a,b,c,d){var e=Ae;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var g=H(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=()=>{y()[a+40>>1]=4;y()[a+42>>1]=200;var m=a+44;Q("OK",w(),m,64);c(a,0,g)};l.onerror=m=>{y()[a+40>>1]=4;y()[a+42>>1]=413;var n=a+44;Q("Payload Too Large",w(),n,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ee(a,b,c){var d=Ae;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=H(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Ce(l);w().set(new Uint8Array(g),m);C()[a+12>>2]=m;Y(a+16,l);Y(a+24,0);Y(a+32,l);y()[a+40>>1]=4;y()[a+42>>1]=200;l=a+44;Q("OK",w(),l,64);b(a,0,g)}else y()[a+40>>1]=4,y()[a+42>>1]=404,g=a+44,Q("Not Found",w(),g,64),c(a,0,"no data")};f.onerror=g=>{y()[a+40>>
1]=4;y()[a+42>>1]=404;var l=a+44;Q("Not Found",w(),l,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Fe(a,b,c){var d=Ae;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=H(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;C()[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);y()[a+40>>1]=4;y()[a+42>>1]=200;var l=a+44;Q("OK",w(),l,64);b(a,0,g)};f.onerror=g=>{y()[a+40>>1]=4;y()[a+42>>1]=404;var l=a+44;Q("Not Found",w(),l,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var Ge={},Ie=()=>{if(!He){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:oa||"./this.program"},b;for(b in Ge)void 0===Ge[b]?delete a[b]:a[b]=Ge[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);He=c}return He},He;
function Je(a,b){if(F)return N(8,1,a,b);var c=0;Ie().forEach((d,e)=>{var f=b+c;e=C()[a+4*e>>2]=f;for(f=0;f<d.length;++f)h()[e++]=d.charCodeAt(f);h()[e]=0;c+=d.length+1});return 0}function Ke(a,b){if(F)return N(9,1,a,b);var c=Ie();C()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);C()[b>>2]=d;return 0}function Le(a){if(F)return N(10,1,a);try{var b=Cc(a);vb(b);return 0}catch(c){if("undefined"==typeof Sc||"ErrnoError"!==c.name)throw c;return c.nb}}
function Me(a,b,c,d){if(F)return N(11,1,a,b,c,d);try{a:{var e=Cc(a);a=b;for(var f,g=b=0;g<c;g++){var l=C()[a>>2],m=C()[a+4>>2];a+=8;var n=e,q=h(),p=f;if(0>m||0>p)throw new S(28);if(null===n.vb)throw new S(8);if(1===(n.flags&2097155))throw new S(8);if(U(n.node.mode))throw new S(31);if(!n.Za.read)throw new S(28);var r="undefined"!=typeof p;if(!r)p=n.position;else if(!n.seekable)throw new S(70);var k=n.Za.read(n,q,l,m,p);r||(n.position+=k);var t=k;if(0>t){var u=-1;break a}b+=t;if(t<m)break;"undefined"!=
typeof f&&(f+=t)}u=b}C()[d>>2]=u;return 0}catch(z){if("undefined"==typeof Sc||"ErrnoError"!==z.name)throw z;return z.nb}}
function Ne(a,b,c,d,e){if(F)return N(12,1,a,b,c,d,e);b=mb(b,c);try{if(isNaN(b))return 61;var f=Cc(a);Mc(f,b,d);db=[f.position>>>0,(G=f.position,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A()[e>>2]=db[0];A()[e+4>>2]=db[1];f.hc&&0===b&&0===d&&(f.hc=null);return 0}catch(g){if("undefined"==typeof Sc||"ErrnoError"!==g.name)throw g;return g.nb}}
function Oe(a,b,c,d){if(F)return N(13,1,a,b,c,d);try{a:{var e=Cc(a);a=b;for(var f,g=b=0;g<c;g++){var l=C()[a>>2],m=C()[a+4>>2];a+=8;var n=Nc(e,h(),l,m,f);if(0>n){var q=-1;break a}b+=n;"undefined"!=typeof f&&(f+=n)}q=b}C()[d>>2]=q;return 0}catch(p){if("undefined"==typeof Sc||"ErrnoError"!==p.name)throw p;return p.nb}}
var Pe=[31,29,31,30,31,30,31,31,30,31,30,31],Qe=[31,28,31,30,31,30,31,31,30,31,30,31],Re=(a,b)=>{h().set(a,b)},Se=(a,b,c,d)=>{function e(k,t,u){for(k="number"==typeof k?k.toString():k||"";k.length<t;)k=u[0]+k;return k}function f(k,t){return e(k,t,"0")}function g(k,t){function u(K){return 0>K?-1:0<K?1:0}var z;0===(z=u(k.getFullYear()-t.getFullYear()))&&0===(z=u(k.getMonth()-t.getMonth()))&&(z=u(k.getDate()-t.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-
1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var t=k.Cb;for(k=new Date((new Date(k.Db+1900,0,1)).getTime());0<t;){var u=k.getMonth(),z=(te(k.getFullYear())?Pe:Qe)[u];if(t>z-k.getDate())t-=z-k.getDate()+1,k.setDate(1),11>u?k.setMonth(u+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+
1));else{k.setDate(k.getDate()+t);break}}u=new Date(k.getFullYear()+1,0,4);t=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=g(t,k)?0>=g(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=C()[d+40>>2];d={td:A()[d>>2],sd:A()[d+4>>2],ac:A()[d+8>>2],oc:A()[d+12>>2],bc:A()[d+16>>2],Db:A()[d+20>>2],rb:A()[d+24>>2],Cb:A()[d+28>>2],Ud:A()[d+32>>2],rd:A()[d+36>>2],ud:n?H(n):""};c=H(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");n={"%a":k=>p[k.rb].substring(0,
3),"%A":k=>p[k.rb],"%b":k=>r[k.bc].substring(0,3),"%B":k=>r[k.bc],"%C":k=>f((k.Db+1900)/100|0,2),"%d":k=>f(k.oc,2),"%e":k=>e(k.oc,2," "),"%g":k=>m(k).toString().substring(2),"%G":m,"%H":k=>f(k.ac,2),"%I":k=>{k=k.ac;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var t=0,u=0;u<=k.bc-1;t+=(te(k.Db+1900)?Pe:Qe)[u++]);return f(k.oc+t,3)},"%m":k=>f(k.bc+1,2),"%M":k=>f(k.sd,2),"%n":()=>"\n","%p":k=>0<=k.ac&&12>k.ac?"AM":"PM","%S":k=>f(k.td,2),"%t":()=>"\t","%u":k=>k.rb||7,"%U":k=>f(Math.floor((k.Cb+
7-k.rb)/7),2),"%V":k=>{var t=Math.floor((k.Cb+7-(k.rb+6)%7)/7);2>=(k.rb+371-k.Cb-2)%7&&t++;if(t)53==t&&(u=(k.rb+371-k.Cb)%7,4==u||3==u&&te(k.Db)||(t=1));else{t=52;var u=(k.rb+7-k.Cb-1)%7;(4==u||5==u&&te(k.Db%400-1))&&t++}return f(t,2)},"%w":k=>k.rb,"%W":k=>f(Math.floor((k.Cb+7-(k.rb+6)%7)/7),2),"%y":k=>(k.Db+1900).toString().substring(2),"%Y":k=>k.Db+1900,"%z":k=>{k=k.rd;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.ud,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=Wb(c,!1);if(q.length>b)return 0;Re(q,a);return q.length-1};F?xb():yb();[44].forEach(a=>{hc[a]=new S(a);hc[a].stack="<generic error, no stack>"});sc=Array(4096);Fc(T,"/");Hc("/tmp");Hc("/home");Hc("/home/web_user");
(function(){Hc("/dev");Zb(259,{read:()=>0,write:(d,e,f,g)=>g});Ic("/dev/null",259);Yb(1280,ac);Yb(1536,bc);Ic("/dev/tty",1280);Ic("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Qb(a).byteLength);return a[--b]};Ma("/dev","random",c);Ma("/dev","urandom",c);Hc("/dev/shm");Hc("/dev/shm/tmp")})();
(function(){Hc("/proc");var a=Hc("/proc/self");Hc("/proc/self/fd");Fc({sb(){var b=gc(a,"fd",16895,73);b.$a={Jb(c,d){var e=Cc(+d);c={parent:null,sb:{Cc:"fake"},$a:{Nb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();D.FS_createPath=Oc;D.FS_createDataFile=mc;D.FS_createPreloadedFile=nc;D.FS_unlink=Jc;D.FS_createLazyFile=Rc;D.FS_createDevice=Ma;bd=D.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Te=Array(256),Ue=0;256>Ue;++Ue)Te[Ue]=String.fromCharCode(Ue);
ed=Te;W=D.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(td.prototype,{isAliasOf:function(a){if(!(this instanceof td&&a instanceof td))return!1;var b=this.Xa.fb.ab,c=this.Xa.bb;a.Xa=a.Xa;var d=a.Xa.fb.ab;for(a=a.Xa.bb;b.jb;)c=b.Ob(c),b=b.jb;for(;d.jb;)a=d.Ob(a),d=d.jb;return b===d&&c===a},clone:function(){this.Xa.bb||gd(this);if(this.Xa.Mb)return this.Xa.count.value+=1,this;var a=rd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Xa;a=a(c.call(b,d,{Xa:{value:{count:e.count,Fb:e.Fb,Mb:e.Mb,bb:e.bb,fb:e.fb,gb:e.gb,lb:e.lb}}}));a.Xa.count.value+=
1;a.Xa.Fb=!1;return a},["delete"](){this.Xa.bb||gd(this);if(this.Xa.Fb&&!this.Xa.Mb)throw new W("Object already scheduled for deletion");jd(this);var a=this.Xa;--a.count.value;0===a.count.value&&(a.gb?a.lb.qb(a.gb):a.fb.ab.qb(a.bb));this.Xa.Mb||(this.Xa.gb=void 0,this.Xa.bb=void 0)},isDeleted:function(){return!this.Xa.bb},deleteLater:function(){this.Xa.bb||gd(this);if(this.Xa.Fb&&!this.Xa.Mb)throw new W("Object already scheduled for deletion");md.push(this);1===md.length&&od&&od(nd);this.Xa.Fb=!0;
return this}});D.getInheritedInstanceCount=()=>Object.keys(pd).length;D.getLiveInheritedInstances=()=>{var a=[],b;for(b in pd)pd.hasOwnProperty(b)&&a.push(pd[b]);return a};D.flushPendingDeletes=nd;D.setDelayFunction=a=>{od=a;md.length&&od&&od(nd)};
Object.assign(Fd.prototype,{Wc(a){this.Ec&&(a=this.Ec(a));return a},vc(a){this.qb?.(a)},argPackAdvance:8,readValueFromPointer:Yc,fromWireType:function(a){function b(){return this.Ub?sd(this.ab.Gb,{fb:this.gd,bb:c,lb:this,gb:a}):sd(this.ab.Gb,{fb:this,bb:a})}var c=this.Wc(a);if(!c)return this.vc(a),null;var d=qd(this.ab,c);if(void 0!==d){if(0===d.Xa.count.value)return d.Xa.bb=c,d.Xa.gb=a,d.clone();d=d.clone();this.vc(a);return d}d=this.ab.Vc(c);d=ld[d];if(!d)return b.call(this);d=this.Tb?d.Rc:d.pointerType;
var e=kd(c,this.ab,d.ab);return null===e?b.call(this):this.Ub?sd(d.ab.Gb,{fb:d,bb:e,lb:this,gb:a}):sd(d.ab.Gb,{fb:d,bb:e})}});Kd=D.UnboundTypeError=((a,b)=>{var c=ud(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Ud.push(0,1,void 0,1,null,1,!0,1,!1,1);D.count_emval_handles=()=>Ud.length/2-5-Td.length;ze=new xe;F||(Ua("library_fetch_init"),ye(a=>{Ae=a;Va("library_fetch_init")},()=>{Ae=!1;Va("library_fetch_init")}));
var Ve=[pb,rb,Hb,Tc,Uc,Vc,function(a,b,c,d,e,f,g,l){if(F)return N(6,1,a,b,c,d,e,f,g,l);e=mb(e,f);try{if(isNaN(e))return 61;var m=Cc(d);if(0!==(b&2)&&0===(c&2)&&2!==(m.flags&2097155))throw new S(2);if(1===(m.flags&2097155))throw new S(2);if(!m.Za.Kb)throw new S(43);var n=m.Za.Kb(m,a,e,b,c);var q=n.bb;A()[g>>2]=n.ub;C()[l>>2]=q;return 0}catch(p){if("undefined"==typeof Sc||"ErrnoError"!==p.name)throw p;return-p.nb}},function(a,b,c,d,e,f,g){if(F)return N(7,1,a,b,c,d,e,f,g);f=mb(f,g);try{var l=Cc(e);if(c&
2){if(32768!==(l.node.mode&61440))throw new S(43);if(!(d&2)){var m=w().slice(a,a+b);l.Za.Wb&&l.Za.Wb(l,m,f,b,d)}}}catch(n){if("undefined"==typeof Sc||"ErrnoError"!==n.name)throw n;return-n.nb}},Je,Ke,Le,Me,Ne,Oe],cf={$:a=>{We(a,!ra,1,!qa,5242880,!1);L.Lc()},x:a=>{F?postMessage({cmd:"cleanupThread",thread:a}):L.Hc(L.pb[a])},Y:Ib,B:Tc,ca:Uc,C:Vc,f:a=>{var b=Wc[a];delete Wc[a];var c=b.lc,d=b.qb,e=b.wc,f=e.map(g=>g.Yc).concat(e.map(g=>g.nd));dd([a],f,g=>{var l={};e.forEach((m,n)=>{var q=g[n],p=m.Ib,r=
m.Xc,k=g[n+e.length],t=m.md,u=m.od;l[m.Uc]={read:z=>q.fromWireType(p(r,z)),write:(z,K)=>{var J=[];t(u,z,k.toWireType(J,K));Xc(J)}}});return[{name:b.name,fromWireType:m=>{var n={},q;for(q in l)n[q]=l[q].read(m);d(m);return n},toWireType:(m,n)=>{for(var q in l)if(!(q in n))throw new TypeError(`Missing field: "${q}"`);var p=c();for(q in l)l[q].write(p,n[q]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:Yc,mb:d}]})},N:()=>{},sa:(a,b,c,d)=>{b=V(b);cd(a,{name:b,fromWireType:function(e){return!!e},
toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(w()[e])},mb:null})},q:(a,b,c,d,e,f,g,l,m,n,q,p,r)=>{q=V(q);f=Jd(e,f);l&&=Jd(g,l);n&&=Jd(m,n);r=Jd(p,r);var k=xd(q);wd(k,function(){Od(`Cannot construct ${q} due to unbound types`,[d])});dd([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var u=t.ab;var z=u.Gb}else z=td.prototype;t=ud(q,function(...O){if(Object.getPrototypeOf(this)!==K)throw new W("Use 'new' to construct "+q);if(void 0===J.yb)throw new W(q+
" has no accessible constructor");var B=J.yb[O.length];if(void 0===B)throw new W(`Tried to invoke ctor of ${q} with invalid number of parameters (${O.length}) - expected (${Object.keys(J.yb).toString()}) parameters instead!`);return B.apply(this,O)});var K=Object.create(z,{constructor:{value:t}});t.prototype=K;var J=new yd(q,t,K,r,u,f,l,n);if(J.jb){var x;(x=J.jb).pc??(x.pc=[]);J.jb.pc.push(J)}u=new Fd(q,J,!0,!1,!1);x=new Fd(q+"*",J,!1,!1,!1);z=new Fd(q+" const*",J,!1,!0,!1);ld[a]={pointerType:x,Rc:z};
Gd(k,t);return[u,x,z]})},u:(a,b,c,d,e,f)=>{var g=Pd(b,c);e=Jd(d,e);dd([],[a],l=>{l=l[0];var m=`constructor ${l.name}`;void 0===l.ab.yb&&(l.ab.yb=[]);if(void 0!==l.ab.yb[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${l.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);l.ab.yb[b-1]=()=>{Od(`Cannot construct ${l.name} due to unbound types`,g)};dd([],g,n=>{n.splice(1,0,null);l.ab.yb[b-
1]=Rd(m,n,null,e,f);return[]});return[]})},i:(a,b,c,d,e,f,g,l)=>{var m=Pd(c,d);b=V(b);b=Sd(b);f=Jd(e,f);dd([],[a],n=>{function q(){Od(`Cannot call ${p} due to unbound types`,m)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.ab.hd.push(b);var r=n.ab.Gb,k=r[b];void 0===k||void 0===k.ib&&k.className!==n.name&&k.Qb===c-2?(q.Qb=c-2,q.className=n.name,r[b]=q):(vd(r,b,p),r[b].ib[c-2]=q);dd([],m,t=>{t=Rd(p,t,n,f,g);void 0===r[b].ib?(t.Qb=c-2,r[b]=t):r[b].ib[c-2]=t;return[]});
return[]})},ra:a=>cd(a,Wd),G:(a,b,c)=>{b=V(b);cd(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Xd(b,c),mb:null})},s:(a,b,c,d,e,f)=>{var g=Pd(b,c);a=V(a);a=Sd(a);e=Jd(d,e);wd(a,function(){Od(`Cannot call ${a} due to unbound types`,g)},b-1);dd([],g,l=>{Gd(a,Rd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},j:(a,b,c,d,e)=>{b=V(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?function(l,m){return m>>>
0}:function(l,m){return m};cd(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:Yd(b,c,0!==d),mb:null})},d:(a,b,c)=>{function d(f){var g=C()[f>>2];f=C()[f+4>>2];return new e(h().buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);cd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Zc:!0})},H:(a,b)=>{b=V(b);var c="std::string"===b;cd(a,{name:b,fromWireType:function(d){var e=C()[d>>2],
f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==w()[m]){g=H(g,m-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(w()[f+l]);n=n.join("")}Md(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new W("Cannot pass non-string to std::string");var g=c&&f?Vb(e):e.length;
var l=Ce(4+g+1),m=l+4;C()[l>>2]=g;if(c&&f)g+=1,Q(e,w(),m,g);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);if(255<n)throw Md(m),new W("String has UTF-16 code units that do not fit in 8 bits");w()[m+f]=n}else for(f=0;f<g;++f)w()[m+f]=e[f];null!==d&&d.push(Md,l);return l},argPackAdvance:8,readValueFromPointer:Yc,mb(d){Md(d)}})},v:(a,b,c)=>{c=V(c);if(2===b){var d=ae;var e=be;var f=ce;var g=l=>ea()[l>>1]}else 4===b&&(d=de,e=ee,f=fe,g=l=>C()[l>>2]);cd(a,{name:c,fromWireType:l=>{for(var m=C()[l>>2],n,
q=l+4,p=0;p<=m;++p){var r=l+4+p*b;if(p==m||0==g(r))q=d(q,r-q),void 0===n?n=q:(n+=String.fromCharCode(0),n+=q),q=r+b}Md(l);return n},toWireType:(l,m)=>{if("string"!=typeof m)throw new W(`Cannot pass non-string to C++ string type ${c}`);var n=f(m),q=Ce(4+n+b);C()[q>>2]=n/b;e(m,q+4,n+b);null!==l&&l.push(Md,q);return q},argPackAdvance:8,readValueFromPointer:Yc,mb(l){Md(l)}})},e:(a,b,c,d,e,f)=>{Wc[a]={name:V(b),lc:Jd(c,d),qb:Jd(e,f),wc:[]}},c:(a,b,c,d,e,f,g,l,m,n)=>{Wc[a].wc.push({Uc:V(b),Yc:c,Ib:Jd(d,
e),Xc:f,nd:g,md:Jd(l,m),od:n})},ta:(a,b)=>{b=V(b);cd(a,{Od:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},ja:function(a){if(ze.has(a)){var b=ze.get(a),c=ze;c.ub[a]=void 0;c.yc.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},fa:()=>1,X:(a,b)=>{a==b?setTimeout(Cb):F?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=L.pb[a])&&a.postMessage({cmd:"checkMailbox"})},Z:(a,b,c,d,e)=>{je.length=d;e>>=3;for(var f=0;f<d;f++)je[f]=ja()[e+f];a=b?eb[b]:Ve[a];L.Sc=c;c=a(...je);L.Sc=0;return c},
_:he,ea:()=>{},R:()=>{throw Infinity;},l:(a,b,c)=>{a=X(a);b=ke(b,"emval::as");return le(b,c,a)},o:(a,b,c,d)=>{a=me[a];b=X(b);return a(null,b,c,d)},n:(a,b,c,d,e)=>{a=me[a];b=X(b);c=oe(c);return a(b,b[c],d,e)},W:Vd,la:(a,b)=>{a=X(a);b=X(b);return a==b},oa:a=>{if(0===a)return Dd(pe());a=oe(a);return Dd(pe()[a])},h:(a,b,c)=>{var d=re(a,b),e=d.shift();a--;var f=Array(a);b=`methodCaller<(${d.map(g=>g.name).join(", ")}) => ${e.name}>`;return qe(ud(b,(g,l,m,n)=>{for(var q=0,p=0;p<a;++p)f[p]=d[p].readValueFromPointer(n+
q),q+=d[p].argPackAdvance;g=1===c?se(l,f):l.apply(g,f);return le(e,m,g)}))},t:(a,b)=>{a=X(a);b=X(b);return Dd(a[b])},F:a=>{9<a&&(Ud[a+1]+=1)},M:()=>Dd([]),qa:a=>Dd(oe(a)),na:()=>Dd({}),pa:a=>{var b=X(a);Xc(b);Vd(a)},m:(a,b,c)=>{a=X(a);b=X(b);c=X(c);a[b]=c},k:(a,b)=>{a=ke(a,"_emval_take_value");a=a.readValueFromPointer(b);return Dd(a)},ma:a=>{a=X(a);return Dd(typeof a)},J:function(a,b,c){a=new Date(1E3*mb(a,b));A()[c>>2]=a.getSeconds();A()[c+4>>2]=a.getMinutes();A()[c+8>>2]=a.getHours();A()[c+12>>
2]=a.getDate();A()[c+16>>2]=a.getMonth();A()[c+20>>2]=a.getFullYear()-1900;A()[c+24>>2]=a.getDay();b=(te(a.getFullYear())?ue:ve)[a.getMonth()]+a.getDate()-1|0;A()[c+28>>2]=b;A()[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0;A()[c+32>>2]=a},K:function(a){var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),
c=A()[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?A()[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));A()[a+24>>2]=b.getDay();c=(te(b.getFullYear())?ue:ve)[b.getMonth()]+b.getDate()-1|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();A()[a+
20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;Xe((G=a,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0));return a>>>0},V:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset(),m=Math.max(e,l);C()[a>>2]=60*m;A()[b>>2]=Number(e!=l);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);g=a(g);l<e?(Zd(f,c),Zd(g,d)):(Zd(f,d),Zd(g,c))},b:()=>
{Wa("")},I:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},p:(a,b,c)=>{we.length=0;for(var d;d=w()[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;we.push(112==d?C()[c>>2]:105==d?A()[c>>2]:ja()[c>>3]);c+=e?8:4}return eb[a](...we)},y:()=>{},ga:()=>Date.now(),da:()=>{M+=1;throw"unwind";},g:()=>performance.timeOrigin+performance.now(),E:()=>"undefined"!=typeof SharedArrayBuffer,U:a=>{var b=w().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=Math,e=Math.max(a,
b+2097152/c);a:{d=(d.min.call(d,2147483648,e+(65536-e%65536)%65536)-v.buffer.byteLength+65535)/65536;try{v.grow(d);ba();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ka:function(a,b,c,d,e){function f(I){r?I():ge(I)}M+=1;var g=a+112,l=C()[g+36>>2],m=C()[g+40>>2],n=C()[g+44>>2],q=C()[g+48>>2],p=C()[g+52>>2],r=!!(p&64),k=I=>{--M;f(()=>{l?P(l)(I):b?.(I)})},t=I=>{f(()=>{n?P(n)(I):d?.(I)})},u=I=>{--M;f(()=>{m?P(m)(I):c?.(I)})},z=I=>{f(()=>{q?P(q)(I):e?.(I)})},K=I=>{Be(I,k,u,t,z)},J=(I,af)=>
{De(I,af.response,Za=>{--M;f(()=>{l?P(l)(Za):b?.(Za)})},Za=>{--M;f(()=>{l?P(l)(Za):b?.(Za)})})},x=I=>{Be(I,J,u,t,z)},O=H(g+0),B=!!(p&16),R=!!(p&4);p=!!(p&32);if("EM_IDB_STORE"===O)K=C()[g+84>>2],g=C()[g+88>>2],De(a,w().slice(K,K+g),k,u);else if("EM_IDB_DELETE"===O)Fe(a,k,u);else if(B){if(p)return 0;Be(a,R?J:k,u,t,z)}else Ee(a,k,p?u:R?x:K);return a},aa:Je,ba:Ke,D:wb,r:Le,A:Me,L:Ne,z:Oe,ha:function(){var a=stackTrace(),b=Vb(a)+1,c=Ce(b);Q(a,w(),c,b);return c},S:(a,b)=>{Qb(w().subarray(a,a+b));return 0},
O:Ye,w:Ze,P:$e,Q:bf,a:v||D.wasmMemory,ia:Se,T:(a,b,c,d)=>Se(a,b,c,d)},Z=function(){function a(c,d){Z=c.exports;L.Mc.push(Z.Ba);Fb=Z.Da;Ga.unshift(Z.ua);Aa=d;Va("wasm-instantiate");return Z}var b={a:cf};Ua("wasm-instantiate");if(D.instantiateWasm)try{return D.instantiateWasm(b,a)}catch(c){E(`Module.instantiateWasm callback failed with error: ${c}`),ma(c)}cb(b,function(c){a(c.instance,c.module)}).catch(ma);return{}}(),Ld=a=>(Ld=Z.va)(a);
D.__embind_initialize_bindings=()=>(D.__embind_initialize_bindings=Z.wa)();var Md=a=>(Md=Z.xa)(a),Ce=a=>(Ce=Z.ya)(a),Bb=D._pthread_self=()=>(Bb=D._pthread_self=Z.za)(),tb=a=>(tb=Z.Aa)(a);D.__emscripten_tls_init=()=>(D.__emscripten_tls_init=Z.Ba)();var cc=(a,b)=>(cc=Z.Ca)(a,b),sb=()=>(sb=Z.Ea)(),We=D.__emscripten_thread_init=(a,b,c,d,e,f)=>(We=D.__emscripten_thread_init=Z.Fa)(a,b,c,d,e,f);D.__emscripten_thread_crashed=()=>(D.__emscripten_thread_crashed=Z.Ga)();
var ob=(a,b,c,d,e)=>(ob=Z.Ha)(a,b,c,d,e),Ab=a=>(Ab=Z.Ia)(a),Gb=D.__emscripten_thread_exit=a=>(Gb=D.__emscripten_thread_exit=Z.Ja)(a),ie=()=>(ie=Z.Ka)(),df=(a,b)=>(df=Z.La)(a,b),Xe=a=>(Xe=Z.Ma)(a),Db=(a,b)=>(Db=Z.Na)(a,b),kb=a=>(kb=Z.Oa)(a),nb=a=>(nb=Z.Pa)(a),jb=()=>(jb=Z.Qa)();D.dynCall_ji=(a,b)=>(D.dynCall_ji=Z.Ra)(a,b);D.dynCall_jiji=(a,b,c,d,e)=>(D.dynCall_jiji=Z.Sa)(a,b,c,d,e);D.dynCall_viijii=(a,b,c,d,e,f,g)=>(D.dynCall_viijii=Z.Ta)(a,b,c,d,e,f,g);
D.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(D.dynCall_iiiiij=Z.Ua)(a,b,c,d,e,f,g);D.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,m)=>(D.dynCall_iiiiijj=Z.Va)(a,b,c,d,e,f,g,l,m);D.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,m,n)=>(D.dynCall_iiiiiijj=Z.Wa)(a,b,c,d,e,f,g,l,m,n);D.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=39200;D.___start_em_js=183072;D.___stop_em_js=184065;function Ze(a,b){var c=jb();try{P(a)(b)}catch(d){kb(c);if(d!==d+0)throw d;df(1,0)}}
function bf(a,b,c,d){var e=jb();try{P(a)(b,c,d)}catch(f){kb(e);if(f!==f+0)throw f;df(1,0)}}function $e(a,b,c){var d=jb();try{P(a)(b,c)}catch(e){kb(d);if(e!==e+0)throw e;df(1,0)}}function Ye(a,b,c,d){var e=jb();try{return P(a)(b,c,d)}catch(f){kb(e);if(f!==f+0)throw f;df(1,0)}}D.addRunDependency=Ua;D.removeRunDependency=Va;D.FS_createPath=Oc;D.FS_createLazyFile=Rc;D.FS_createDevice=Ma;D.wasmMemory=v;D.keepRuntimeAlive=()=>qb||0<M;D.ExitStatus=fb;D.FS_createPreloadedFile=nc;D.FS_createDataFile=mc;
D.FS_unlink=Jc;D.PThread=L;var ef;Ta=function ff(){ef||gf();ef||(Ta=ff)};
function gf(){function a(){if(!ef&&(ef=!0,D.calledRun=!0,!Ba)){Ka();la(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();Ia.unshift(b)}Qa(Ia)}}}if(!(0<Ra))if(F)la(D),Ka(),startWorker(D);else{if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)Fa.unshift(D.preRun.shift());Qa(Fa);0<Ra||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();gf();
if("object"==typeof window&&("undefined"==typeof F||!F)){var hf=()=>{var a=0,b=!1,c=m=>{var n=new XMLHttpRequest;n.open("POST","stdio.html",!1);n.send(m);try{window.close()}catch(q){}},d=m=>{var n=new XMLHttpRequest;++a;n.onreadystatechange=()=>{4==n.readyState&&0==--a&&b&&c("^exit^"+Ca)};n.open("POST","stdio.html",!0);n.send(m)};if(-1!=document.URL.search("localhost")||-1!=document.URL.search(":6931/")){var e=1,f=ya,g=E;Ha.unshift(()=>{0==a?c("^exit^"+Ca):b=!0});ya=m=>{d("^out^"+e++ +"^"+encodeURIComponent(m));
f(m)};E=m=>{d("^err^"+e++ +"^"+encodeURIComponent(m));g(m)};var l=()=>{try{d("^pageload^")}catch(m){setTimeout(l,50)}};l()}};"undefined"!=typeof document&&hf()};


  return readyPromise
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkCardWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], () => BlinkCardWasmSDK);
