
var BlinkCardWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkCardWasmSDK) {
  BlinkCardWasmSDK = BlinkCardWasmSDK || {};


function g(){p.buffer!=r&&aa(p.buffer);return ba}function y(){p.buffer!=r&&aa(p.buffer);return ca}function da(){p.buffer!=r&&aa(p.buffer);return ea}function z(){p.buffer!=r&&aa(p.buffer);return fa}function A(){p.buffer!=r&&aa(p.buffer);return ha}function C(){p.buffer!=r&&aa(p.buffer);return ia}function ja(){p.buffer!=r&&aa(p.buffer);return ka}var E;E||(E=typeof BlinkCardWasmSDK !== 'undefined' ? BlinkCardWasmSDK : {});var la,ma;E.ready=new Promise(function(a,b){la=a;ma=b});E.mc||(E.mc=0);E.mc++;
E.ENVIRONMENT_IS_PTHREAD||function(a){function b(m,q,n){var t=new XMLHttpRequest;t.open("GET",m,!0);t.responseType="arraybuffer";t.onprogress=function(v){var k=q;v.total&&(k=v.total);if(v.loaded){t.Yc?E.Db[m].loaded=v.loaded:(t.Yc=!0,E.Db||(E.Db={}),E.Db[m]={loaded:v.loaded,total:k});var u=k=v=0,w;for(w in E.Db){var B=E.Db[w];v+=B.total;k+=B.loaded;u++}v=Math.ceil(v*E.mc/u);E.setStatus&&E.setStatus("Downloading data... ("+k+"/"+v+")")}else!E.Db&&E.setStatus&&E.setStatus("Downloading data...")};t.onerror=
function(){throw Error("NetworkError for: "+m);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)n(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function q(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);
m.prototype.dd=v;v=a.files;for(var k=0;k<v.length;++k)m.prototype.xc[v[k].filename].onload();E.removeRunDependency("datafile_../../resources/advanced-threads/BlinkCardWasmSDK.data")}E.FS_createPath("/","microblink",!0,!0);m.prototype={xc:{},open:function(v,k){this.name=k;this.xc[k]=this;E.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.dd.subarray(this.start,this.end))},finish:function(v){E.FS_createDataFile(this.name,null,v,!0,!0,!0);E.removeRunDependency("fp "+
this.name);this.xc[this.name]=null}};for(var n=a.files,t=0;t<n.length;++t)(new m(n[t].start,n[t].end,n[t].audio||0)).open("GET",n[t].filename);E.addRunDependency("datafile_../../resources/advanced-threads/BlinkCardWasmSDK.data");E.Nc||(E.Nc={});E.Nc["../../resources/advanced-threads/BlinkCardWasmSDK.data"]={ce:!1};l?(q(l),l=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===
typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof E.locateFilePackage||E.locateFile||(E.locateFile=E.locateFilePackage,F("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=E.locateFile?E.locateFile("BlinkCardWasmSDK.data",""):"BlinkCardWasmSDK.data",f=a.remote_package_size,h=null,l=E.getPreloadedPackage?
E.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);E.calledRun?d():(E.preRun||(E.preRun=[]),E.preRun.push(d))}({files:[{filename:"/microblink/Model_349432d66ef2b216155673b634f7d5c47795bed35719b954f726b5f0856740f3.strop",start:0,end:52354},{filename:"/microblink/Model_f132d1bd7614b1274fafb8a41ec6c047b84b2a43654ae2da5ddd78a2765601c6.strop",start:52354,end:945434},{filename:"/microblink/Model_406f8d5d972cf76a9241b35abbe5758890353b9b7daa922f732c4151ff6a0d9c.strop",start:945434,
end:1236482},{filename:"/microblink/Model_b9263312a9b623d1a3b75b643ccdcbc36aae52c278d721443468147c50e44583.strop",start:1236482,end:1524690},{filename:"/microblink/card_templates.zzip",start:1524690,end:1735830},{filename:"/microblink/Model_1118d9d674e23996f70c6416b2bf5a6ce6ef24a6ad2c92f0ddd1e198e5f05305.strop",start:1735830,end:1756248},{filename:"/microblink/Model_830c13896f96c1cb6d5cad725f44e6aae470f8672d640d20b3272ed4bb839699.strop",start:1756248,end:2034522},{filename:"/microblink/Model_cc1fab8df49d9a21de6c7b76ccf0dac40b17fcfb7073cc520eca073cbf8e33e9.strop",
start:2034522,end:2038460}],remote_package_size:2038460,package_uuid:"e5bcfe84-cf89-4b07-b7c8-72f860a52b93"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},na;na=E.allowedThreads&&0<E.allowedThreads?E.allowedThreads-1:navigator.hardwareConcurrency-1;var oa=0,pa;0<na&&(E.threadWorkersReadyPromise=new Promise(function(a){pa=a}));E.preRun||(E.preRun=[]);
E.preRun.push(function(a){function b(){oa++;oa==na&&pa()}var c=a.PThread.rc;a.PThread.rc=function(d){c(d,b)}});var qa=Object.assign({},E),ra="./this.program",sa=(a,b)=>{throw b;},ta="object"==typeof window,ua="function"==typeof importScripts,va="object"==typeof process&&"object"==typeof process.Zd&&"string"==typeof process.Zd.node,G=E.ENVIRONMENT_IS_PTHREAD||!1,wa="";function xa(a){return E.locateFile?E.locateFile(a,wa):wa+a}var ya,za,Aa;
if(ta||ua)ua?wa=self.location.href:"undefined"!=typeof document&&document.currentScript&&(wa=document.currentScript.src),_scriptDir&&(wa=_scriptDir),wa=0!==wa.indexOf("blob:")?wa.substr(0,wa.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ya=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ua&&(Aa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),za=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Ba=E.print||console.log.bind(console),F=E.printErr||console.warn.bind(console);Object.assign(E,qa);qa=null;E.thisProgram&&(ra=E.thisProgram);E.quit&&(sa=E.quit);var Ca,Da=0,Ea;E.wasmBinary&&(Ea=E.wasmBinary);var noExitRuntime=E.noExitRuntime||!0;"object"!=typeof WebAssembly&&Fa("no native wasm support detected");var p,Ga,Ha=!1,Ia;
function Ja(a){var b=new TextDecoder(a);this.decode=c=>{c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ka="undefined"!=typeof TextDecoder?new Ja("utf8"):void 0;
function La(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function K(a,b){return a?La(y(),a,b):""}
function Ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function L(a,b,c){Ma(a,y(),b,c)}
function Na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Oa="undefined"!=typeof TextDecoder?new Ja("utf-16le"):void 0;function Pa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&z()[c];)++c;c<<=1;if(32<c-a&&Oa)return Oa.decode(y().subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function Qa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}function Ra(a){return 2*a.length}function Sa(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ta(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}function Ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Va(a){var b=Na(a)+1,c=Wa(b);c&&Ma(a,g(),c,b);return c}function Xa(a,b){g().set(a,b)}var r,ba,ca,ea,fa,ha,ia,Za,ka;G&&(r=E.buffer);
function aa(a){r=a;E.HEAP8=ba=new Int8Array(a);E.HEAP16=ea=new Int16Array(a);E.HEAP32=ha=new Int32Array(a);E.HEAPU8=ca=new Uint8Array(a);E.HEAPU16=fa=new Uint16Array(a);E.HEAPU32=ia=new Uint32Array(a);E.HEAPF32=Za=new Float32Array(a);E.HEAPF64=ka=new Float64Array(a)}var $a=E.INITIAL_MEMORY||209715200;
if(G)p=E.wasmMemory,r=E.buffer;else if(E.wasmMemory)p=E.wasmMemory;else if(p=new WebAssembly.Memory({initial:$a/65536,maximum:12800,shared:!0}),!(p.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),va&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");p&&(r=p.buffer);$a=r.byteLength;aa(r);var ab,bb=[],cb=[],db=[],eb=!1,fb=0;function gb(){return noExitRuntime||0<fb}
function hb(){G||(E.noFSInit||ib||(ib=!0,jb(),E.stdin=E.stdin,E.stdout=E.stdout,E.stderr=E.stderr,E.stdin?kb("/dev","stdin",E.stdin):lb("/dev/tty","/dev/stdin"),E.stdout?kb("/dev","stdout",null,E.stdout):lb("/dev/tty","/dev/stdout"),E.stderr?kb("/dev","stderr",null,E.stderr):lb("/dev/tty1","/dev/stderr"),mb("/dev/stdin",0),mb("/dev/stdout",1),mb("/dev/stderr",1)),nb=!1,ob(cb))}function pb(){var a=E.preRun.shift();bb.unshift(a)}var qb=0,rb=null,sb=null;
function tb(){qb++;E.monitorRunDependencies&&E.monitorRunDependencies(qb)}function ub(){qb--;E.monitorRunDependencies&&E.monitorRunDependencies(qb);if(0==qb&&(null!==rb&&(clearInterval(rb),rb=null),sb)){var a=sb;sb=null;a()}}E.preloadedImages={};E.preloadedAudios={};function Fa(a){if(G)postMessage({cmd:"onAbort",arg:a});else if(E.onAbort)E.onAbort(a);a="Aborted("+a+")";F(a);Ha=!0;Ia=1;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}
function vb(){return wb.startsWith("data:application/octet-stream;base64,")}var wb;wb="BlinkCardWasmSDK.wasm";vb()||(wb=xa(wb));function xb(){var a=wb;try{if(a==wb&&Ea)return new Uint8Array(Ea);if(Aa)return Aa(a);throw"both async and sync fetching of the wasm failed";}catch(b){Fa(b)}}
function yb(){return Ea||!ta&&!ua||"function"!=typeof fetch?Promise.resolve().then(function(){return xb()}):fetch(wb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+wb+"'";return a.arrayBuffer()}).catch(function(){return xb()})}
var M,zb,Ab={283549:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},283685:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},283901:function(a,b){a=K(a);b=K(b);throw Error(a+b);},284011:function(a,b){a=K(a);b=K(b);console.log(a+b)},284109:function(a){throw Error(K(a));},284152:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};
function ob(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(E);else{var c=b.de;"number"==typeof c?void 0===b.Kb?N(c)():N(c)(b.Kb):c(void 0===b.Kb?null:b.Kb)}}}function Bb(a){var b=Cb();a=a();Db(b);return a}function Eb(a){var b=O.wb[a];b&&(A()[a>>2]=0,O.Sc(b.worker))}function Fb(a){a instanceof Gb||"unwind"==a||sa(1,a)}
var O={Ab:[],Rb:[],hc:[],ud:function(){G&&O.wd()},he:function(){},wd:function(){O.receiveObjectTransfer=O.Id;O.threadInit=O.Vc;O.setExitStatus=O.Nd;noExitRuntime=!1},wb:{},Nd:function(a){Ia=a},Uc:function(){for(var a in O.wb){var b=O.wb[a];b&&b.worker&&O.Sc(b.worker)}for(a=0;a<O.Ab.length;++a)O.Ab[a].terminate();O.Ab=[]},Sc:function(a){O.Kd(function(){delete O.wb[a.Ib.yc];O.Ab.push(a);O.Rb.splice(O.Rb.indexOf(a),1);Hb(a.Ib.yc);a.Ib=void 0})},Kd:function(a){A()[Ib>>2]=0;try{a()}finally{A()[Ib>>2]=
1}},Id:function(){},Vc:function(){for(var a in O.hc)if(O.hc.hasOwnProperty(a))O.hc[a]()},rc:function(a,b){a.onmessage=c=>{c=c.data;var d=c.cmd;a.Ib&&(O.hd=a.Ib.yc);if(c.targetThread&&c.targetThread!=Jb()){var e=O.wb[c.oe];e?e.worker.postMessage(c,c.transferList):F('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===d)Kb();else if("spawnThread"===d)Lb(c);else if("cleanupThread"===d)Eb(c.thread);
else if("killThread"===d)c=c.thread,A()[c>>2]=0,d=O.wb[c],delete O.wb[c],d.worker.terminate(),Hb(c),O.Rb.splice(O.Rb.indexOf(d.worker),1),d.worker.Ib=void 0;else if("cancelThread"===d)O.wb[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.Qb&&(a.Qb(),delete a.Qb);else if("print"===d)Ba("Thread "+c.threadId+": "+c.text);else if("printErr"===d)F("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===
c.target)a.postMessage(c);else if("onAbort"===d){if(E.onAbort)E.onAbort(c.arg)}else F("worker sent an unknown command "+d);O.hd=void 0};a.onerror=c=>{F("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:E.mainScriptUrlOrBlob||_scriptDir,wasmMemory:p,wasmModule:Ga})},Zc:function(){var a=xa("BlinkCardWasmSDK.worker.js");O.Ab.push(new Worker(a))},od:function(){0==O.Ab.length&&(O.Zc(),O.rc(O.Ab[0]));return O.Ab.pop()}};
E.establishStackSpace=function(){var a=Jb(),b=A()[a+44>>2];a=A()[a+48>>2];Mb(b,b-a);Db(b)};function Nb(a){if(G)return P(1,0,a);try{Ob(a)}catch(b){Fb(b)}}var Pb=[];function N(a){var b=Pb[a];b||(a>=Pb.length&&(Pb.length=a+1),Pb[a]=b=ab.get(a));return b}E.invokeEntryPoint=function(a,b){return N(a)(b)};var Qb;Qb=G?()=>performance.now()-E.__performance_now_clock_drift:()=>performance.now();
function Lb(a){var b=O.od();if(!b)return 6;O.Rb.push(b);var c=O.wb[a.sc]={worker:b,yc:a.sc};b.Ib=c;var d={cmd:"run",start_routine:a.Sd,arg:a.Kb,threadInfoStruct:a.sc};b.Qb=()=>{d.time=performance.now();b.postMessage(d,a.Xd)};b.loaded&&(b.Qb(),delete b.Qb);return 0}function Rb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Q(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Rb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Sb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Tb(a){if("/"===a)return"/";a=Q(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ub(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){Fa("randomDevice")}}
function Vb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Rb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Wb=[];function Xb(a,b){Wb[a]={input:[],mb:[],Hb:b};Yb(a,Zb)}
var Zb={open:function(a){var b=Wb[a.node.Ob];if(!b)throw new R(43);a.kb=b;a.seekable=!1},close:function(a){a.kb.Hb.flush(a.kb)},flush:function(a){a.kb.Hb.flush(a.kb)},read:function(a,b,c,d){if(!a.kb||!a.kb.Hb.Jc)throw new R(60);for(var e=0,f=0;f<d;f++){try{var h=a.kb.Hb.Jc(a.kb)}catch(l){throw new R(29);}if(void 0===h&&0===e)throw new R(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.kb||!a.kb.Hb.tc)throw new R(60);try{for(var e=
0;e<d;e++)a.kb.Hb.tc(a.kb,b[c+e])}catch(f){throw new R(29);}d&&(a.node.timestamp=Date.now());return e}},ac={Jc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=$b(b,!0)}return a.input.shift()},tc:function(a,b){null===b||10===b?(Ba(La(a.mb,0)),a.mb=[]):0!=b&&a.mb.push(b)},flush:function(a){a.mb&&0<a.mb.length&&
(Ba(La(a.mb,0)),a.mb=[])}},bc={tc:function(a,b){null===b||10===b?(F(La(a.mb,0)),a.mb=[]):0!=b&&a.mb.push(b)},flush:function(a){a.mb&&0<a.mb.length&&(F(La(a.mb,0)),a.mb=[])}},S={vb:null,xb:function(){return S.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);S.vb||(S.vb={dir:{node:{ub:S.eb.ub,qb:S.eb.qb,Lb:S.eb.Lb,cc:S.eb.cc,Rc:S.eb.Rc,lc:S.eb.lc,Tc:S.eb.Tc,Qc:S.eb.Qc,fc:S.eb.fc},stream:{Cb:S.fb.Cb}},file:{node:{ub:S.eb.ub,qb:S.eb.qb},
stream:{Cb:S.fb.Cb,read:S.fb.read,write:S.fb.write,zc:S.fb.zc,dc:S.fb.dc,ec:S.fb.ec}},link:{node:{ub:S.eb.ub,qb:S.eb.qb,Pb:S.eb.Pb},stream:{}},Bc:{node:{ub:S.eb.ub,qb:S.eb.qb},stream:cc}});c=dc(a,b,c,d);16384===(c.mode&61440)?(c.eb=S.vb.dir.node,c.fb=S.vb.dir.stream,c.cb={}):32768===(c.mode&61440)?(c.eb=S.vb.file.node,c.fb=S.vb.file.stream,c.ib=0,c.cb=null):40960===(c.mode&61440)?(c.eb=S.vb.link.node,c.fb=S.vb.link.stream):8192===(c.mode&61440)&&(c.eb=S.vb.Bc.node,c.fb=S.vb.Bc.stream);c.timestamp=
Date.now();a&&(a.cb[b]=c,a.timestamp=c.timestamp);return c},ee:function(a){return a.cb?a.cb.subarray?a.cb.subarray(0,a.ib):new Uint8Array(a.cb):new Uint8Array(0)},Fc:function(a,b){var c=a.cb?a.cb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.cb,a.cb=new Uint8Array(b),0<a.ib&&a.cb.set(c.subarray(0,a.ib),0))},Jd:function(a,b){if(a.ib!=b)if(0==b)a.cb=null,a.ib=0;else{var c=a.cb;a.cb=new Uint8Array(b);c&&a.cb.set(c.subarray(0,Math.min(b,a.ib)));a.ib=b}},eb:{ub:function(a){var b=
{};b.jd=8192===(a.mode&61440)?a.id:1;b.oc=a.id;b.mode=a.mode;b.Ed=1;b.uid=0;b.sd=0;b.Ob=a.Ob;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.ib:40960===(a.mode&61440)?a.link.length:0;b.ad=new Date(a.timestamp);b.Dd=new Date(a.timestamp);b.gd=new Date(a.timestamp);b.bd=4096;b.cd=Math.ceil(b.size/b.bd);return b},qb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&S.Jd(a,b.size)},Lb:function(){throw ec[44];},cc:function(a,b,c,
d){return S.createNode(a,b,c,d)},Rc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=fc(b,c)}catch(f){}if(d)for(var e in d.cb)throw new R(55);}delete a.parent.cb[a.name];a.parent.timestamp=Date.now();a.name=c;b.cb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},lc:function(a,b){delete a.cb[b];a.timestamp=Date.now()},Tc:function(a,b){var c=fc(a,b),d;for(d in c.cb)throw new R(55);delete a.cb[b];a.timestamp=Date.now()},Qc:function(a){var b=[".",".."],c;for(c in a.cb)a.cb.hasOwnProperty(c)&&b.push(c);
return b},fc:function(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},Pb:function(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},fb:{read:function(a,b,c,d,e){var f=a.node.cb;if(e>=a.node.ib)return 0;a=Math.min(a.node.ib-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.cb||a.cb.subarray)){if(f)return a.cb=b.subarray(c,
c+d),a.ib=d;if(0===a.ib&&0===e)return a.cb=b.slice(c,c+d),a.ib=d;if(e+d<=a.ib)return a.cb.set(b.subarray(c,c+d),e),d}S.Fc(a,e+d);if(a.cb.subarray&&b.subarray)a.cb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.cb[e+f]=b[c+f];a.ib=Math.max(a.ib,e+d);return d},Cb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ib);if(0>b)throw new R(28);return b},zc:function(a,b,c){S.Fc(a.node,b+c);a.node.ib=Math.max(a.node.ib,b+c)},dc:function(a,b,c,d,e,f){if(0!==b)throw new R(28);
if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.cb;if(f&2||a.buffer!==r){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);(c=gc(65536,f))?y().fill(0,c,c+f):c=0;if(!c)throw new R(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{hb:c,$c:d}},ec:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R(43);if(e&2)return 0;S.fb.write(a,b,0,d,c,!1);return 0}}};
function hc(a,b,c){var d="al "+a;za(a,function(e){e||Fa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&ub(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&tb(d)}
var ic=null,jc={},kc=[],lc=1,mc=null,nb=!0,R=null,ec={},oc=(a,b={})=>{a=Vb("/",a);if(!a)return{path:"",node:null};b=Object.assign({Hc:!0,vc:0},b);if(8<b.vc)throw new R(32);a=Rb(a.split("/").filter(h=>!!h),!1);for(var c=ic,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=fc(c,a[e]);d=Q(d+"/"+a[e]);c.Mb&&(!f||f&&b.Hc)&&(c=c.Mb.root);if(!f||b.Zb)for(f=0;40960===(c.mode&61440);)if(c=nc(d),d=Vb(Sb(d),c),c=oc(d,{vc:b.vc+1}).node,40<f++)throw new R(32);}return{path:d,node:c}},pc=a=>
{for(var b;;){if(a===a.parent)return a=a.xb.Lc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},qc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mc.length},fc=(a,b)=>{var c;if(c=(c=rc(a,"x"))?c:a.eb.Lb?0:2)throw new R(c,a);for(c=mc[qc(a.id,b)];c;c=c.Gb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.eb.Lb(a,b)},dc=(a,b,c,d)=>{a=new sc(a,b,c,d);b=qc(a.parent.id,a.name);a.Gb=mc[b];return mc[b]=a},tc={r:0,"r+":2,w:577,"w+":578,
a:1089,"a+":1090},uc=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},rc=(a,b)=>{if(nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},vc=(a,b)=>{try{return fc(a,b),20}catch(c){}return rc(a,"wx")},wc=(a=0,b=4096)=>{for(;a<=b;a++)if(!kc[a])return a;throw new R(33);},yc=(a,b)=>{xc||(xc=function(){},xc.prototype={object:{get:function(){return this.node},set:function(c){this.node=c}}});a=Object.assign(new xc,
a);b=wc(b,void 0);a.zb=b;return kc[b]=a},cc={open:a=>{a.fb=jc[a.node.Ob].fb;a.fb.open&&a.fb.open(a)},Cb:()=>{throw new R(70);}},Yb=(a,b)=>{jc[a]={fb:b}},zc=(a,b)=>{var c="/"===b,d=!b;if(c&&ic)throw new R(10);if(!c&&!d){var e=oc(b,{Hc:!1});b=e.path;e=e.node;if(e.Mb)throw new R(10);if(16384!==(e.mode&61440))throw new R(54);}b={type:a,le:{},Lc:b,Cd:[]};a=a.xb(b);a.xb=b;b.root=a;c?ic=a:e&&(e.Mb=b,e.xb&&e.xb.Cd.push(b))},T=(a,b,c)=>{var d=oc(a,{parent:!0}).node;a=Tb(a);if(!a||"."===a||".."===a)throw new R(28);
var e=vc(d,a);if(e)throw new R(e);if(!d.eb.cc)throw new R(63);return d.eb.cc(d,a,b,c)},Ac=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return T(a,b|8192,c)},lb=(a,b)=>{if(!Vb(a))throw new R(44);var c=oc(b,{parent:!0}).node;if(!c)throw new R(44);b=Tb(b);var d=vc(c,b);if(d)throw new R(d);if(!c.eb.fc)throw new R(63);c.eb.fc(c,b,a)},Bc=a=>{var b=oc(a,{parent:!0}).node;if(!b)throw new R(44);var c=Tb(a);a=fc(b,c);a:{try{var d=fc(b,c)}catch(f){d=f.lb;break a}var e=rc(b,"wx");d=e?e:16384===(d.mode&61440)?
31:0}if(d)throw new R(d);if(!b.eb.lc)throw new R(63);if(a.Mb)throw new R(10);b.eb.lc(b,c);b=qc(a.parent.id,a.name);if(mc[b]===a)mc[b]=a.Gb;else for(b=mc[b];b;){if(b.Gb===a){b.Gb=a.Gb;break}b=b.Gb}},nc=a=>{a=oc(a).node;if(!a)throw new R(44);if(!a.eb.Pb)throw new R(28);return Vb(pc(a.parent),a.eb.Pb(a))},Cc=(a,b)=>{a=oc(a,{Zb:!b}).node;if(!a)throw new R(44);if(!a.eb.ub)throw new R(63);return a.eb.ub(a)},Dc=a=>Cc(a,!0),Ec=(a,b)=>{a="string"==typeof a?oc(a,{Zb:!0}).node:a;if(!a.eb.qb)throw new R(63);
a.eb.qb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},mb=(a,b,c,d)=>{if(""===a)throw new R(44);if("string"==typeof b){var e=tc[b];if("undefined"==typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=Q(a);try{f=oc(a,{Zb:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new R(20);}else f=T(a,c,0),e=!0;if(!f)throw new R(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new R(54);
if(!e&&(c=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==uc(b)||b&512)?31:rc(f,uc(b)):44))throw new R(c);if(b&512){c=f;c="string"==typeof c?oc(c,{Zb:!0}).node:c;if(!c.eb.qb)throw new R(63);if(16384===(c.mode&61440))throw new R(31);if(32768!==(c.mode&61440))throw new R(28);if(e=rc(c,"w"))throw new R(e);c.eb.qb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=yc({node:f,path:pc(f),flags:b,seekable:!0,position:0,fb:f.fb,Yd:[],error:!1},d);d.fb.open&&d.fb.open(d);!E.logReadFiles||b&1||(Fc||(Fc=
{}),a in Fc||(Fc[a]=1));return d},Gc=a=>{if(null===a.zb)throw new R(8);a.nc&&(a.nc=null);try{a.fb.close&&a.fb.close(a)}catch(b){throw b;}finally{kc[a.zb]=null}a.zb=null},Hc=(a,b,c)=>{if(null===a.zb)throw new R(8);if(!a.seekable||!a.fb.Cb)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.fb.Cb(a,b,c);a.Yd=[]},Ic=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new R(28);if(null===a.zb)throw new R(8);if(0===(a.flags&2097155))throw new R(8);if(16384===(a.node.mode&61440))throw new R(31);if(!a.fb.write)throw new R(28);
a.seekable&&a.flags&1024&&Hc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new R(70);b=a.fb.write(a,b,c,d,e,f);h||(a.position+=b);return b},jb=()=>{R||(R=function(a,b){this.node=b;this.Md=function(c){this.lb=c};this.Md(a);this.message="FS error"},R.prototype=Error(),R.prototype.constructor=R,[44].forEach(a=>{ec[a]=new R(a);ec[a].stack="<generic error, no stack>"}))},ib,Jc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Kc=(a,b)=>{a="string"==typeof a?a:pc(a);for(b=
b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Q(a+"/"+c);try{T(d,16895,0)}catch(e){}a=d}}return d},Lc=(a,b,c,d)=>{a=Q(("string"==typeof a?a:pc(a))+"/"+b);c=Jc(c,d);return T(a,(void 0!==c?c:438)&4095|32768,0)},Mc=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:pc(a),h=b?Q(a+"/"+b):a);a=Jc(d,e);h=T(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ec(h,a|146);b=mb(h,577);Ic(b,c,0,c.length,0,f);Gc(b);
Ec(h,a)}return h},kb=(a,b,c,d)=>{a=Q(("string"==typeof a?a:pc(a))+"/"+b);b=Jc(!!c,!!d);kb.Kc||(kb.Kc=64);var e=kb.Kc++<<8|0;Yb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,l,m)=>{for(var q=0,n=0;n<m;n++){try{var t=c()}catch(v){throw new R(29);}if(void 0===t&&0===q)throw new R(6);if(null===t||void 0===t)break;q++;h[l+n]=t}q&&(f.node.timestamp=Date.now());return q},write:(f,h,l,m)=>{for(var q=0;q<m;q++)try{d(h[l+q])}catch(n){throw new R(29);}m&&(f.node.timestamp=
Date.now());return q}});return Ac(a,b,e)},Nc=a=>{if(!(a.yd||a.zd||a.link||a.cb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ya)try{a.cb=$b(ya(a.url),!0),a.ib=a.cb.length}catch(b){throw new R(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Oc=(a,b,c,d,e)=>{function f(){this.qc=
!1;this.Yb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var t=n%this.Cc;return this.$b(n/this.Cc|0)[t]}};f.prototype.Ld=function(n){this.$b=n};f.prototype.Ac=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var t=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&
"gzip"===v;var u=1048576;k||(u=t);var w=this;w.Ld(B=>{var H=B*u,I=(B+1)*u-1;I=Math.min(I,t-1);if("undefined"==typeof w.Yb[B]){var x=w.Yb;if(H>I)throw Error("invalid range ("+H+", "+I+") or no bytes requested!");if(I>t-1)throw Error("only "+t+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);t!==u&&D.setRequestHeader("Range","bytes="+H+"-"+I);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);if(!(200<=
D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);H=void 0!==D.response?new Uint8Array(D.response||[]):$b(D.responseText||"",!0);x[B]=H}if("undefined"==typeof w.Yb[B])throw Error("doXHR failed!");return w.Yb[B]});if(n||!t)u=t=1,u=t=this.$b(0).length,Ba("LazyFiles on gzip forces download of the whole file when length is accessed");this.Xc=t;this.Wc=u;this.qc=!0};if("undefined"!=typeof XMLHttpRequest){if(!ua)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new f;Object.defineProperties(h,{length:{get:function(){this.qc||this.Ac();return this.Xc}},Cc:{get:function(){this.qc||this.Ac();return this.Wc}}});var l=void 0}else l=c,h=void 0;var m=Lc(a,b,d,e);h?m.cb=h:l&&(m.cb=null,m.url=l);Object.defineProperties(m,{ib:{get:function(){return this.cb.length}}});var q={};Object.keys(m.fb).forEach(n=>{var t=m.fb[n];q[n]=function(){Nc(m);return t.apply(null,arguments)}});q.read=(n,t,v,k,u)=>{Nc(m);n=n.node.cb;if(u>=n.length)return 0;k=Math.min(n.length-u,
k);if(n.slice)for(var w=0;w<k;w++)t[v+w]=n[u+w];else for(w=0;w<k;w++)t[v+w]=n.get(u+w);return k};m.fb=q;return m},Qc=(a,b,c,d,e,f,h,l,m,q)=>{function n(k){function u(w){q&&q();l||Mc(a,b,w,d,e,m);f&&f();ub(v)}Pc.ge(k,t,u,()=>{h&&h();ub(v)})||u(k)}var t=b?Vb(Q(a+"/"+b)):a,v="cp "+t;tb(v);"string"==typeof c?hc(c,k=>n(k),h):n(c)},V={},xc,Fc;
function Rc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Q(b)!==Q(pc(e.node)))return-54;throw e;}A()[c>>2]=d.jd;A()[c+4>>2]=0;A()[c+8>>2]=d.oc;A()[c+12>>2]=d.mode;A()[c+16>>2]=d.Ed;A()[c+20>>2]=d.uid;A()[c+24>>2]=d.sd;A()[c+28>>2]=d.Ob;A()[c+32>>2]=0;zb=[d.size>>>0,(M=d.size,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];A()[c+40>>2]=zb[0];A()[c+44>>2]=zb[1];A()[c+48>>2]=4096;A()[c+52>>2]=d.cd;A()[c+56>>2]=d.ad.getTime()/
1E3|0;A()[c+60>>2]=0;A()[c+64>>2]=d.Dd.getTime()/1E3|0;A()[c+68>>2]=0;A()[c+72>>2]=d.gd.getTime()/1E3|0;A()[c+76>>2]=0;zb=[d.oc>>>0,(M=d.oc,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];A()[c+80>>2]=zb[0];A()[c+84>>2]=zb[1];return 0}var Sc=void 0;function Tc(){Sc+=4;return A()[Sc-4>>2]}function Uc(a){a=kc[a];if(!a)throw new R(8);return a}
function Vc(a,b,c){if(G)return P(2,1,a,b,c);Sc=c;try{var d=Uc(a);switch(b){case 0:var e=Tc();return 0>e?-28:mb(d.path,d.flags,0,e).zb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Tc(),d.flags|=e,0;case 5:return e=Tc(),da()[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){if("undefined"==typeof V||!(f instanceof R))throw f;return-f.lb}}
function Wc(a,b){if(G)return P(3,1,a,b);try{var c=Uc(a);return Rc(Cc,c.path,b)}catch(d){if("undefined"==typeof V||!(d instanceof R))throw d;return-d.lb}}function Xc(a,b,c,d){if(G)return P(4,1,a,b,c,d);try{b=K(b);var e=d&256;d&=4096;var f=b;if("/"===f[0])b=f;else{if(-100===a)var h="/";else{var l=kc[a];if(!l)throw new R(8);h=l.path}if(0==f.length){if(!d)throw new R(44);b=h}else b=Q(h+"/"+f)}return Rc(e?Dc:Cc,b,c)}catch(m){if("undefined"==typeof V||!(m instanceof R))throw m;return-m.lb}}
function Yc(a,b,c){if(G)return P(5,1,a,b,c);Sc=c;try{var d=Uc(a);switch(b){case 21509:case 21505:return d.kb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.kb?0:-59;case 21519:if(!d.kb)return-59;var e=Tc();return A()[e>>2]=0;case 21520:return d.kb?-28:-59;case 21531:a=e=Tc();if(!d.fb.xd)throw new R(59);return d.fb.xd(d,b,a);case 21523:return d.kb?0:-59;case 21524:return d.kb?0:-59;default:Fa("bad ioctl syscall "+b)}}catch(f){if("undefined"==typeof V||!(f instanceof
R))throw f;return-f.lb}}function Zc(a,b,c){if(G)return P(7,1,a,b,c);Sc=c;try{var d=K(a),e=c?Tc():0;return mb(d,b,e).zb}catch(f){if("undefined"==typeof V||!(f instanceof R))throw f;return-f.lb}}function $c(a,b){if(G)return P(8,1,a,b);try{return a=K(a),Rc(Cc,a,b)}catch(c){if("undefined"==typeof V||!(c instanceof R))throw c;return-c.lb}}var ad={};function bd(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function cd(a){return this.fromWireType(C()[a>>2])}var dd={},ed={},fd={};
function gd(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function hd(a,b){a=gd(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function jd(a){var b=Error,c=hd(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var kd=void 0;function ld(a){throw new kd(a);}
function md(a,b,c){function d(l){l=c(l);l.length!==a.length&&ld("Mismatched type converter count");for(var m=0;m<a.length;++m)nd(a[m],l[m])}a.forEach(function(l){fd[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){ed.hasOwnProperty(l)?e[m]=ed[l]:(f.push(l),dd.hasOwnProperty(l)||(dd[l]=[]),dd[l].push(function(){e[m]=ed[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function od(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var pd=void 0;function W(a){for(var b="";y()[a];)b+=pd[y()[a++]];return b}var qd=void 0;function X(a){throw new qd(a);}
function nd(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||X('type "'+d+'" must have a positive integer typeid pointer');if(ed.hasOwnProperty(a)){if(c.td)return;X("Cannot register type '"+d+"' twice")}ed[a]=b;delete fd[a];dd.hasOwnProperty(a)&&(b=dd[a],delete dd[a],b.forEach(function(e){e()}))}function rd(a){X(a.bb.jb.gb.name+" instance already deleted")}var sd=!1;function td(){}
function ud(a){--a.count.value;0===a.count.value&&(a.ob?a.rb.yb(a.ob):a.jb.gb.yb(a.hb))}function vd(a,b,c){if(b===c)return a;if(void 0===c.sb)return null;a=vd(a,b,c.sb);return null===a?null:c.kd(a)}var wd={},xd=[];function yd(){for(;xd.length;){var a=xd.pop();a.bb.Eb=!1;a["delete"]()}}var zd=void 0,Ad={};function Bd(a,b){for(void 0===b&&X("ptr should not be undefined");a.sb;)b=a.Tb(b),a=a.sb;return Ad[b]}
function Cd(a,b){b.jb&&b.hb||ld("makeClassHandle requires ptr and ptrType");!!b.rb!==!!b.ob&&ld("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Dd(Object.create(a,{bb:{value:b}}))}function Dd(a){if("undefined"===typeof FinalizationRegistry)return Dd=b=>b,a;sd=new FinalizationRegistry(b=>{ud(b.bb)});Dd=b=>{var c=b.bb;c.ob&&sd.register(b,{bb:c},b);return b};td=b=>{sd.unregister(b)};return Dd(a)}function Ed(){}
function Fd(a,b,c){if(void 0===a[b].nb){var d=a[b];a[b]=function(){a[b].nb.hasOwnProperty(arguments.length)||X("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].nb+")!");return a[b].nb[arguments.length].apply(this,arguments)};a[b].nb=[];a[b].nb[d.Wb]=d}}
function Gd(a,b,c){E.hasOwnProperty(a)?((void 0===c||void 0!==E[a].nb&&void 0!==E[a].nb[c])&&X("Cannot register public name '"+a+"' twice"),Fd(E,a,a),E.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),E[a].nb[c]=b):(E[a]=b,void 0!==c&&(E[a].ke=c))}function Hd(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Fb=c;this.yb=d;this.sb=e;this.nd=f;this.Tb=h;this.kd=l;this.Gd=[]}
function Id(a,b,c){for(;b!==c;)b.Tb||X("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Tb(a),b=b.sb;return a}function Jd(a,b){if(null===b)return this.pc&&X("null is not a valid "+this.name),0;b.bb||X('Cannot pass "'+Kd(b)+'" as a '+this.name);b.bb.hb||X("Cannot pass deleted object as a pointer of type "+this.name);return Id(b.bb.hb,b.bb.jb.gb,this.gb)}
function Ld(a,b){if(null===b){this.pc&&X("null is not a valid "+this.name);if(this.bc){var c=this.uc();null!==a&&a.push(this.yb,c);return c}return 0}b.bb||X('Cannot pass "'+Kd(b)+'" as a '+this.name);b.bb.hb||X("Cannot pass deleted object as a pointer of type "+this.name);!this.ac&&b.bb.jb.ac&&X("Cannot convert argument of type "+(b.bb.rb?b.bb.rb.name:b.bb.jb.name)+" to parameter type "+this.name);c=Id(b.bb.hb,b.bb.jb.gb,this.gb);if(this.bc)switch(void 0===b.bb.ob&&X("Passing raw pointer to smart pointer is illegal"),
this.Rd){case 0:b.bb.rb===this?c=b.bb.ob:X("Cannot convert argument of type "+(b.bb.rb?b.bb.rb.name:b.bb.jb.name)+" to parameter type "+this.name);break;case 1:c=b.bb.ob;break;case 2:if(b.bb.rb===this)c=b.bb.ob;else{var d=b.clone();c=this.Hd(c,Md(function(){d["delete"]()}));null!==a&&a.push(this.yb,c)}break;default:X("Unsupporting sharing policy")}return c}
function Nd(a,b){if(null===b)return this.pc&&X("null is not a valid "+this.name),0;b.bb||X('Cannot pass "'+Kd(b)+'" as a '+this.name);b.bb.hb||X("Cannot pass deleted object as a pointer of type "+this.name);b.bb.jb.ac&&X("Cannot convert argument of type "+b.bb.jb.name+" to parameter type "+this.name);return Id(b.bb.hb,b.bb.jb.gb,this.gb)}
function Od(a,b,c,d){this.name=a;this.gb=b;this.pc=c;this.ac=d;this.bc=!1;this.yb=this.Hd=this.uc=this.Pc=this.Rd=this.Fd=void 0;void 0!==b.sb?this.toWireType=Ld:(this.toWireType=d?Jd:Nd,this.tb=null)}function Pd(a,b,c){E.hasOwnProperty(a)||ld("Replacing nonexistant public symbol");void 0!==E[a].nb&&void 0!==c?E[a].nb[c]=b:(E[a]=b,E[a].Wb=c)}
function Qd(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=E["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=N(b).apply(null,c);return d}}function Rd(a,b){a=W(a);var c=a.includes("j")?Qd(a,b):N(b);"function"!=typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var Sd=void 0;function Td(a){a=Ud(a);var b=W(a);Vd(a);return b}
function Wd(a,b){function c(f){e[f]||ed[f]||(fd[f]?fd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Sd(a+": "+d.map(Td).join([", "]));}function Xd(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function Yd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=hd(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Zd(a,b,c,d,e){var f=b.length;2>f&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].tb){l=!0;break}var m="void"!==b[0].name,q="",n="";for(c=0;c<f-2;++c)q+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+gd(a)+"("+q+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var t=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[X,d,e,bd,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",q.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].tb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",q.push(f+"_dtor"),d.push(b[c].tb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(a+"}\n");return Yd(q).apply(null,d)}var $d=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function ae(a){4<a&&0===--Y[a].wc&&(Y[a]=void 0,$d.push(a))}
function be(a){a||X("Cannot use deleted val. handle = "+a);return Y[a].value}function Md(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=$d.length?$d.pop():Y.length;Y[b]={wc:1,value:a};return b}}function Kd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ce(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;p.buffer!=r&&aa(p.buffer);return d.call(this,Za[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function de(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return y()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return z()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return C()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function ee(a,b){var c=ed[a];void 0===c&&X(b+" has unknown type "+Td(a));return c}var fe={};function ge(a){var b=fe[a];return void 0===b?W(a):b}var he=[];
function ie(){return"object"==typeof globalThis?globalThis:Function("return this")()}function je(a){var b=he.length;he.push(a);return b}function ke(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=ee(A()[(b>>2)+d],"parameter "+d);return c}var le=[],me={};
function ne(a,b,c,d,e,f,h,l){if(G)return P(9,1,a,b,c,d,e,f,h,l);try{var m=kc[e];if(!m)return-8;if(0!==(c&2)&&0===(d&2)&&2!==(m.flags&2097155))throw new R(2);if(1===(m.flags&2097155))throw new R(2);if(!m.fb.dc)throw new R(43);var q=m.fb.dc(m,a,b,f,c,d);var n=q.hb;A()[h>>2]=q.$c;return n}catch(t){if("undefined"==typeof V||!(t instanceof R))throw t;return-t.lb}}
function oe(a,b,c,d,e,f){if(G)return P(10,1,a,b,c,d,e,f);try{var h=kc[e];if(h&&c&2){var l=y().slice(a,a+b);h&&h.fb.ec&&h.fb.ec(h,l,f,b,d)}}catch(m){if("undefined"==typeof V||!(m instanceof R))throw m;return-m.lb}}
function pe(a,b,c){function d(q){return(q=q.toTimeString().match(/\(([A-Za-z ]+)\)$/))?q[1]:"GMT"}if(G)return P(11,1,a,b,c);var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset(),m=Math.max(e,l);A()[a>>2]=60*m;A()[b>>2]=Number(e!=l);a=d(f);b=d(h);a=Va(a);b=Va(b);l<e?(A()[c>>2]=a,A()[c+4>>2]=b):(A()[c>>2]=b,A()[c+4>>2]=a)}function qe(a,b,c){qe.ed||(qe.ed=!0,pe(a,b,c))}var re=[];
function P(a,b){var c=arguments.length-2,d=arguments;return Bb(function(){for(var e=se(8*c),f=e>>3,h=0;h<c;h++){var l=d[2+h];ja()[f+h]=l}return te(a,c,e,b)})}var ue=[];function ve(a,b,c,d){Bb(function(){var e=se(12),f=0;if(b){f=Na(b)+1;var h=Wa(f);L(b,h,f);f=h}A()[e>>2]=f;A()[e+4>>2]=c;A()[e+8>>2]=d;we(a,657457152,0,f,e)})}var xe=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function ye(a){a=2<a?K(a):a;return xe[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function ze(a,b,c){var d=ye(a);if(!d)return-4;d.Xb&&(A()[d.Xb>>2]=b,A()[d.Xb+4>>2]=c);if(d.Mc||!d.ae)d.Mc&&(d=d.Mc),a=!1,d.Vb&&d.Vb.Ub&&(a=d.Vb.Ub.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Vb.Ub.viewport(0,0,b,c);else return d.Xb?(d=A()[d.Xb+8>>2],a=a?K(a):"",ve(d,a,b,c),1):-4;return 0}
function Ae(a,b,c){return G?P(12,1,a,b,c):ze(a,b,c)}var Be=[];function Z(a,b){C()[a>>2]=b;C()[a+4>>2]=b/4294967296|0}function Ce(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)}var De;
function Ee(a,b,c,d,e){function f(D){var U=0,J=0;D&&(J=x.response?x.response.byteLength:0,U=Wa(J),y().set(new Uint8Array(x.response),U));C()[a+12>>2]=U;Z(a+16,J)}var h=C()[a+8>>2];if(h){var l=K(h),m=a+112,q=K(m);q||(q="GET");C();var n=C()[m+52>>2],t=C()[m+56>>2],v=!!C()[m+60>>2];C();var k=C()[m+68>>2],u=C()[m+72>>2],w=C()[m+76>>2],B=C()[m+80>>2];h=C()[m+84>>2];m=C()[m+88>>2];var H=!!(n&1),I=!!(n&2);n=!!(n&64);k=k?K(k):void 0;u=u?K(u):void 0;var x=new XMLHttpRequest;x.withCredentials=v;x.open(q,l,
!n,k,u);n||(x.timeout=t);x.qe=l;x.responseType="arraybuffer";B&&(l=K(B),x.overrideMimeType(l));if(w)for(;;){q=C()[w>>2];if(!q)break;l=C()[w+4>>2];if(!l)break;w+=8;q=K(q);l=K(l);x.setRequestHeader(q,l)}Be.push(x);w=Be.length;C()[a+0>>2]=w;h=h&&m?y().slice(h,h+m):null;x.onload=D=>{f(H&&!I);var U=x.response?x.response.byteLength:0;Z(a+24,0);U&&Z(a+32,U);z()[a+40>>1]=x.readyState;z()[a+42>>1]=x.status;x.statusText&&L(x.statusText,a+44,64);200<=x.status&&300>x.status?b&&b(a,x,D):c&&c(a,x,D)};x.onerror=
D=>{f(H);var U=x.status;Z(a+24,0);Z(a+32,x.response?x.response.byteLength:0);z()[a+40>>1]=x.readyState;z()[a+42>>1]=U;c&&c(a,x,D)};x.ontimeout=D=>{c&&c(a,x,D)};x.onprogress=D=>{var U=H&&I&&x.response?x.response.byteLength:0,J=0;H&&I&&(J=Wa(U),y().set(new Uint8Array(x.response),J));C()[a+12>>2]=J;Z(a+16,U);Z(a+24,D.loaded-U);Z(a+32,D.total);z()[a+40>>1]=x.readyState;3<=x.readyState&&0===x.status&&0<D.loaded&&(x.status=200);z()[a+42>>1]=x.status;x.statusText&&L(x.statusText,a+44,64);d&&d(a,x,D);J&&
Vd(J)};x.onreadystatechange=D=>{z()[a+40>>1]=x.readyState;2<=x.readyState&&(z()[a+42>>1]=x.status);e&&e(a,x,D)};try{x.send(h)}catch(D){c&&c(a,x,D)}}else c(a,0,"no url specified!")}function Fe(a,b){if(!eb&&!Ha)if(b)a();else try{if(a(),G&&!gb())try{G?Ge(Ia):Ob(Ia)}catch(c){Fb(c)}}catch(c){Fb(c)}}
function He(a,b,c,d){var e=De;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var h=K(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=()=>{z()[a+40>>1]=4;z()[a+42>>1]=200;L("OK",a+44,64);c(a,0,h)};l.onerror=m=>{z()[a+40>>1]=4;z()[a+42>>1]=413;L("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ie(a,b,c){var d=De;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Wa(l);y().set(new Uint8Array(h),m);C()[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);z()[a+40>>1]=4;z()[a+42>>1]=200;L("OK",a+44,64);b(a,0,h)}else z()[a+40>>1]=4,z()[a+42>>1]=404,L("Not Found",a+44,64),c(a,0,"no data")};f.onerror=h=>{z()[a+40>>1]=4;z()[a+42>>1]=
404;L("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Je(a,b,c){var d=De;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;C()[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);z()[a+40>>1]=4;z()[a+42>>1]=200;L("OK",a+44,64);b(a,0,h)};f.onerror=h=>{z()[a+40>>1]=4;z()[a+42>>1]=404;L("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Ke(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Le(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Me(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Ne(a,b){a.Ic||(a.Ic=a.getContext,a.getContext=function(d,e){e=a.Ic(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Oe(c,b):0}function Oe(a,b){var c=Wa(8);A()[c+4>>2]=Jb();var d={fe:c,attributes:b,version:b.Bd,Ub:a};a.canvas&&(a.canvas.Vb=d);("undefined"==typeof b.Ec||b.Ec)&&Pe(d);return c}
function Pe(a){a||(a=Qe);if(!a.vd){a.vd=!0;var b=a.Ub;Ke(b);Le(b);Me(b);b.be=b.getExtension("EXT_disjoint_timer_query");b.je=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Qe,Re=["default","low-power","high-performance"],Se={};
function Te(){if(!Ue){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ra||"./this.program"},b;for(b in Se)void 0===Se[b]?delete a[b]:a[b]=Se[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ue=c}return Ue}var Ue;
function Ve(a,b){if(G)return P(13,1,a,b);var c=0;Te().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function We(a,b){if(G)return P(14,1,a,b);var c=Te();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}function Xe(a){if(G)return P(15,1,a);try{var b=Uc(a);Gc(b);return 0}catch(c){if("undefined"==typeof V||!(c instanceof R))throw c;return c.lb}}
function Ye(a,b,c,d){if(G)return P(16,1,a,b,c,d);try{a:{for(var e=Uc(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,q=g(),n=h,t=l,v=void 0;if(0>t||0>v)throw new R(28);if(null===m.zb)throw new R(8);if(1===(m.flags&2097155))throw new R(8);if(16384===(m.node.mode&61440))throw new R(31);if(!m.fb.read)throw new R(28);var k="undefined"!=typeof v;if(!k)v=m.position;else if(!m.seekable)throw new R(70);var u=m.fb.read(m,q,n,t,v);k||(m.position+=u);var w=u;if(0>w){var B=-1;break a}a+=w;if(w<
l)break}B=a}A()[d>>2]=B;return 0}catch(H){if("undefined"==typeof V||!(H instanceof R))throw H;return H.lb}}
function Ze(a,b,c,d,e){if(G)return P(17,1,a,b,c,d,e);try{var f=Uc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Hc(f,a,d);zb=[f.position>>>0,(M=f.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];A()[e>>2]=zb[0];A()[e+4>>2]=zb[1];f.nc&&0===a&&0===d&&(f.nc=null);return 0}catch(h){if("undefined"==typeof V||!(h instanceof R))throw h;return h.lb}}
function $e(a,b,c,d){if(G)return P(18,1,a,b,c,d);try{a:{for(var e=Uc(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=Ic(e,g(),h,l,void 0);if(0>m){var q=-1;break a}a+=m}q=a}A()[d>>2]=q;return 0}catch(n){if("undefined"==typeof V||!(n instanceof R))throw n;return n.lb}}function af(a,b){af.Oc||(af.Oc=Ub());for(var c=0;c<b;c++)g()[a+c>>0]=af.Oc();return 0}function bf(a){return 0===a%4&&(0!==a%100||0===a%400)}function cf(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var df=[31,29,31,30,31,30,31,31,30,31,30,31],ef=[31,28,31,30,31,30,31,31,30,31,30,31];function ff(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(bf(a.getFullYear())?df:ef)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function gf(a,b,c,d){function e(k,u,w){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=w[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function w(H){return 0>H?-1:0<H?1:0}var B;0===(B=w(k.getFullYear()-u.getFullYear()))&&0===(B=w(k.getMonth()-u.getMonth()))&&(B=w(k.getDate()-u.getDate()));return B}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=ff(new Date(k.pb+1900,0,1),k.kc);var u=new Date(k.getFullYear()+1,0,4),w=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=h(w,k)?0>=h(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=A()[d+40>>2];d={Vd:A()[d>>2],Ud:A()[d+4>>2],ic:A()[d+8>>2],Sb:A()[d+12>>2],Jb:A()[d+16>>2],pb:A()[d+20>>2],jc:A()[d+24>>2],kc:A()[d+28>>2],pe:A()[d+
32>>2],Td:A()[d+36>>2],Wd:q?K(q):""};c=K(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in q)c=c.replace(new RegExp(n,"g"),q[n]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return t[k.jc].substring(0,3)},"%A":function(k){return t[k.jc]},"%b":function(k){return v[k.Jb].substring(0,3)},"%B":function(k){return v[k.Jb]},"%C":function(k){return f((k.pb+1900)/100|0,2)},"%d":function(k){return f(k.Sb,2)},"%e":function(k){return e(k.Sb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.ic,
2)},"%I":function(k){k=k.ic;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.Sb+cf(bf(k.pb+1900)?df:ef,k.Jb-1),3)},"%m":function(k){return f(k.Jb+1,2)},"%M":function(k){return f(k.Ud,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ic&&12>k.ic?"AM":"PM"},"%S":function(k){return f(k.Vd,2)},"%t":function(){return"\t"},"%u":function(k){return k.jc||7},"%U":function(k){var u=new Date(k.pb+1900,0,1),w=0===u.getDay()?u:ff(u,7-u.getDay());k=new Date(k.pb+1900,k.Jb,k.Sb);return 0>
h(w,k)?f(Math.ceil((31-w.getDate()+(cf(bf(k.getFullYear())?df:ef,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(w,u)?"01":"00"},"%V":function(k){var u=new Date(k.pb+1901,0,4),w=l(new Date(k.pb+1900,0,4));u=l(u);var B=ff(new Date(k.pb+1900,0,1),k.kc);return 0>h(B,w)?"53":0>=h(u,B)?"01":f(Math.ceil((w.getFullYear()<k.pb+1900?k.kc+32-w.getDate():k.kc+1-w.getDate())/7),2)},"%w":function(k){return k.jc},"%W":function(k){var u=new Date(k.pb,0,1),w=1===u.getDay()?u:ff(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.pb+1900,k.Jb,k.Sb);return 0>h(w,k)?f(Math.ceil((31-w.getDate()+(cf(bf(k.getFullYear())?df:ef,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(w,u)?"01":"00"},"%y":function(k){return(k.pb+1900).toString().substring(2)},"%Y":function(k){return k.pb+1900},"%z":function(k){k=k.Td;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Wd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(n in q)c.includes(n)&&(c=c.replace(new RegExp(n,
"g"),q[n](d)));c=c.replace(/\0\0/g,"%");n=$b(c,!1);if(n.length>b)return 0;Xa(n,a);return n.length-1}O.ud();function sc(a,b,c,d){a||(a=this);this.parent=a;this.xb=a.xb;this.Mb=null;this.id=lc++;this.name=b;this.mode=c;this.eb={};this.fb={};this.Ob=d}
Object.defineProperties(sc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},zd:{get:function(){return 16384===(this.mode&61440)}},yd:{get:function(){return 8192===(this.mode&61440)}}});jb();mc=Array(4096);zc(S,"/");T("/tmp",16895,0);T("/home",16895,0);T("/home/web_user",16895,0);
(()=>{T("/dev",16895,0);Yb(259,{read:()=>0,write:(b,c,d,e)=>e});Ac("/dev/null",259);Xb(1280,ac);Xb(1536,bc);Ac("/dev/tty",1280);Ac("/dev/tty1",1536);var a=Ub();kb("/dev","random",a);kb("/dev","urandom",a);T("/dev/shm",16895,0);T("/dev/shm/tmp",16895,0)})();
(()=>{T("/proc",16895,0);var a=T("/proc/self",16895,0);T("/proc/self/fd",16895,0);zc({xb:()=>{var b=dc(a,"fd",16895,73);b.eb={Lb:(c,d)=>{var e=kc[+d];if(!e)throw new R(8);c={parent:null,xb:{Lc:"fake"},eb:{Pb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Pc;E.FS_createPath=Kc;E.FS_createDataFile=Mc;E.FS_createPreloadedFile=Qc;E.FS_createLazyFile=Oc;E.FS_createDevice=kb;E.FS_unlink=Bc;kd=E.InternalError=jd("InternalError");for(var hf=Array(256),jf=0;256>jf;++jf)hf[jf]=String.fromCharCode(jf);
pd=hf;qd=E.BindingError=jd("BindingError");Ed.prototype.isAliasOf=function(a){if(!(this instanceof Ed&&a instanceof Ed))return!1;var b=this.bb.jb.gb,c=this.bb.hb,d=a.bb.jb.gb;for(a=a.bb.hb;b.sb;)c=b.Tb(c),b=b.sb;for(;d.sb;)a=d.Tb(a),d=d.sb;return b===d&&c===a};
Ed.prototype.clone=function(){this.bb.hb||rd(this);if(this.bb.Nb)return this.bb.count.value+=1,this;var a=Dd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.bb;a=a(c.call(b,d,{bb:{value:{count:e.count,Eb:e.Eb,Nb:e.Nb,hb:e.hb,jb:e.jb,ob:e.ob,rb:e.rb}}}));a.bb.count.value+=1;a.bb.Eb=!1;return a};Ed.prototype["delete"]=function(){this.bb.hb||rd(this);this.bb.Eb&&!this.bb.Nb&&X("Object already scheduled for deletion");td(this);ud(this.bb);this.bb.Nb||(this.bb.ob=void 0,this.bb.hb=void 0)};
Ed.prototype.isDeleted=function(){return!this.bb.hb};Ed.prototype.deleteLater=function(){this.bb.hb||rd(this);this.bb.Eb&&!this.bb.Nb&&X("Object already scheduled for deletion");xd.push(this);1===xd.length&&zd&&zd(yd);this.bb.Eb=!0;return this};E.getInheritedInstanceCount=function(){return Object.keys(Ad).length};E.getLiveInheritedInstances=function(){var a=[],b;for(b in Ad)Ad.hasOwnProperty(b)&&a.push(Ad[b]);return a};E.flushPendingDeletes=yd;E.setDelayFunction=function(a){zd=a;xd.length&&zd&&zd(yd)};
Od.prototype.pd=function(a){this.Pc&&(a=this.Pc(a));return a};Od.prototype.Dc=function(a){this.yb&&this.yb(a)};Od.prototype.argPackAdvance=8;Od.prototype.readValueFromPointer=cd;Od.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Od.prototype.fromWireType=function(a){function b(){return this.bc?Cd(this.gb.Fb,{jb:this.Fd,hb:c,rb:this,ob:a}):Cd(this.gb.Fb,{jb:this,hb:a})}var c=this.pd(a);if(!c)return this.Dc(a),null;var d=Bd(this.gb,c);if(void 0!==d){if(0===d.bb.count.value)return d.bb.hb=c,d.bb.ob=a,d.clone();d=d.clone();this.Dc(a);return d}d=this.gb.nd(c);d=wd[d];if(!d)return b.call(this);d=this.ac?d.fd:d.pointerType;var e=vd(c,this.gb,d.gb);return null===e?b.call(this):this.bc?Cd(d.gb.Fb,{jb:d,hb:e,rb:this,ob:a}):Cd(d.gb.Fb,
{jb:d,hb:e})};Sd=E.UnboundTypeError=jd("UnboundTypeError");E.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};E.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};G||(Ce(a=>{De=a;ub("library_fetch_init")},()=>{De=!1;ub("library_fetch_init")}),"undefined"!=typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||tb("library_fetch_init"));
var kf=[null,Nb,Vc,Wc,Xc,Yc,function(a,b){if(G)return P(6,1,a,b);try{return a=K(a),Rc(Dc,a,b)}catch(c){if("undefined"==typeof V||!(c instanceof R))throw c;return-c.lb}},Zc,$c,ne,oe,pe,Ae,Ve,We,Xe,Ye,Ze,$e];function $b(a,b){var c=Array(Na(a)+1);a=Ma(a,c,0,c.length);b&&(c.length=a);return c}
var sf={aa:function(a){lf(a,!ua,1,!ta);O.Vc()},D:function(a){G?postMessage({cmd:"cleanupThread",thread:a}):Eb(a)},E:function(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(G&&0===e.length)return mf(687865856,a,b,c,d);a={Sd:c,sc:a,Kb:d,Xd:e};return G?(a.$d="spawnThread",postMessage(a,e),0):Lb(a)},H:Vc,ga:Wc,ea:Xc,ha:Yc,I:Zc,fa:$c,g:function(a){var b=ad[a];delete ad[a];var c=b.uc,d=b.yb,
e=b.Gc,f=e.map(function(h){return h.rd}).concat(e.map(function(h){return h.Pd}));md([a],f,function(h){var l={};e.forEach(function(m,q){var n=h[q],t=m.$b,v=m.qd,k=h[q+e.length],u=m.Od,w=m.Qd;l[m.md]={read:function(B){return n.fromWireType(t(v,B))},write:function(B,H){var I=[];u(w,B,k.toWireType(I,H));bd(I)}}});return[{name:b.name,fromWireType:function(m){var q={},n;for(n in l)q[n]=l[n].read(m);d(m);return q},toWireType:function(m,q){for(var n in l)if(!(n in q))throw new TypeError('Missing field:  "'+
n+'"');var t=c();for(n in l)l[n].write(t,q[n]);null!==m&&m.push(d,t);return t},argPackAdvance:8,readValueFromPointer:cd,tb:d}]})},N:function(){},oa:function(a,b,c,d,e){var f=od(c);b=W(b);nd(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=da();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},tb:null})},s:function(a,
b,c,d,e,f,h,l,m,q,n,t,v){n=W(n);f=Rd(e,f);l&&(l=Rd(h,l));q&&(q=Rd(m,q));v=Rd(t,v);var k=gd(n);Gd(k,function(){Wd("Cannot construct "+n+" due to unbound types",[d])});md([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var w=u.gb;var B=w.Fb}else B=Ed.prototype;u=hd(k,function(){if(Object.getPrototypeOf(this)!==H)throw new qd("Use 'new' to construct "+n);if(void 0===I.Bb)throw new qd(n+" has no accessible constructor");var D=I.Bb[arguments.length];if(void 0===D)throw new qd("Tried to invoke ctor of "+n+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(I.Bb).toString()+") parameters instead!");return D.apply(this,arguments)});var H=Object.create(B,{constructor:{value:u}});u.prototype=H;var I=new Hd(n,u,H,v,w,f,l,q);w=new Od(n,I,!0,!1);B=new Od(n+"*",I,!1,!1);var x=new Od(n+" const*",I,!1,!0);wd[a]={pointerType:B,fd:x};Pd(k,u);return[w,B,x]})},z:function(a,b,c,d,e,f){0<b||Fa(void 0);var h=Xd(b,c);e=Rd(d,e);md([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.gb.Bb&&(l.gb.Bb=[]);if(void 0!==
l.gb.Bb[b-1])throw new qd("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.gb.Bb[b-1]=()=>{Wd("Cannot construct "+l.name+" due to unbound types",h)};md([],h,function(q){q.splice(1,0,null);l.gb.Bb[b-1]=Zd(m,q,null,e,f);return[]});return[]})},l:function(a,b,c,d,e,f,h,l){var m=Xd(c,d);b=W(b);f=Rd(e,f);md([],[a],function(q){function n(){Wd("Cannot call "+
t+" due to unbound types",m)}q=q[0];var t=q.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&q.gb.Gd.push(b);var v=q.gb.Fb,k=v[b];void 0===k||void 0===k.nb&&k.className!==q.name&&k.Wb===c-2?(n.Wb=c-2,n.className=q.name,v[b]=n):(Fd(v,b,t),v[b].nb[c-2]=n);md([],m,function(u){u=Zd(t,u,q,f,h);void 0===v[b].nb?(u.Wb=c-2,v[b]=u):v[b].nb[c-2]=u;return[]});return[]})},na:function(a,b){b=W(b);nd(a,{name:b,fromWireType:function(c){var d=be(c);ae(c);return d},toWireType:function(c,d){return Md(d)},
argPackAdvance:8,readValueFromPointer:cd,tb:null})},J:function(a,b,c){c=od(c);b=W(b);nd(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:ce(b,c),tb:null})},y:function(a,b,c,d,e,f){var h=Xd(b,c);a=W(a);e=Rd(d,e);Gd(a,function(){Wd("Cannot call "+a+" due to unbound types",h)},b-1);md([],h,function(l){Pd(a,Zd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},h:function(a,b,c,d,e){b=W(b);-1===e&&(e=4294967295);e=od(c);var f=
l=>l;if(0===d){var h=32-8*c;f=l=>l<<h>>>h}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};nd(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:de(b,e,0!==d),tb:null})},c:function(a,b,c){function d(f){f>>=2;var h=C();return new e(r,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=W(c);nd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{td:!0})},K:function(a,
b){b=W(b);var c="std::string"===b;nd(a,{name:b,fromWireType:function(d){var e=C()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==y()[l]){f=K(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(y()[d+4+h]);m=m.join("")}Vd(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||
X("Cannot pass non-string to std::string");var h=(c&&f?()=>Na(e):()=>e.length)(),l=Wa(4+h+1);C()[l>>2]=h;if(c&&f)L(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(Vd(l),X("String has UTF-16 code units that do not fit in 8 bits"));y()[l+4+f]=m}else for(f=0;f<h;++f)y()[l+4+f]=e[f];null!==d&&d.push(Vd,l);return l},argPackAdvance:8,readValueFromPointer:cd,tb:function(d){Vd(d)}})},v:function(a,b,c){c=W(c);if(2===b){var d=Pa;var e=Qa;var f=Ra;var h=()=>z();var l=1}else 4===b&&(d=Sa,
e=Ta,f=Ua,h=()=>C(),l=2);nd(a,{name:c,fromWireType:function(m){for(var q=C()[m>>2],n=h(),t,v=m+4,k=0;k<=q;++k){var u=m+4+k*b;if(k==q||0==n[u>>l])v=d(v,u-v),void 0===t?t=v:(t+=String.fromCharCode(0),t+=v),v=u+b}Vd(m);return t},toWireType:function(m,q){"string"!=typeof q&&X("Cannot pass non-string to C++ string type "+c);var n=f(q),t=Wa(4+n+b);C()[t>>2]=n>>l;e(q,t+4,n+b);null!==m&&m.push(Vd,t);return t},argPackAdvance:8,readValueFromPointer:cd,tb:function(m){Vd(m)}})},f:function(a,b,c,d,e,f){ad[a]=
{name:W(b),uc:Rd(c,d),yb:Rd(e,f),Gc:[]}},b:function(a,b,c,d,e,f,h,l,m,q){ad[a].Gc.push({md:W(b),rd:c,$b:Rd(d,e),qd:f,Pd:h,Od:Rd(l,m),Qd:q})},pa:function(a,b){b=W(b);nd(a,{Ad:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},W:function(){return 2097152},qa:function(a){delete Be[a-1]},ba:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.wb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},
R:function(){throw Infinity;},j:function(a,b,c){a=be(a);b=ee(b,"emval::as");var d=[],e=Md(d);A()[c>>2]=e;return b.toWireType(d,a)},q:function(a,b,c,d){a=he[a];b=be(b);c=ge(c);a(b,c,null,d)},A:ae,wa:function(a){if(0===a)return Md(ie());a=ge(a);return Md(ie()[a])},p:function(a,b){var c=ke(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(n){return n.name}).join("_")+"$";var e=le[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(c[1+
l]);var m="return function "+gd("methodCaller_"+b)+"(handle, name, destructors, args) {\n",q=0;for(l=0;l<a-1;++l)m+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(q?"+"+q:"")+");\n",q+=c[l+1].argPackAdvance;m+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)c[l+1].deleteObject&&(m+="    argType"+l+".deleteObject(arg"+l+");\n");d.Ad||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+"};\n");a=Yd(e).apply(null,f);e=je(a);return le[b]=e},k:function(a,b){a=be(a);
b=be(b);return Md(a[b])},S:function(a){4<a&&(Y[a].wc+=1)},x:function(a,b,c,d){a=be(a);var e=me[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType",
"Module","valueToHandle",h+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(ee,E,Md);me[b]=e}return e(a,c,d)},ta:function(){return Md([])},ya:function(a){return Md(ge(a))},va:function(){return Md({})},xa:function(a){var b=be(a);bd(b);ae(a)},r:function(a,b,c){a=be(a);b=be(b);c=be(c);a[b]=c},n:function(a,b){a=ee(a,"_emval_take_value");a=a.readValueFromPointer(b);return Md(a)},ja:function(a,b){a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+
8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a},ka:function(a){var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>
2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();return b.getTime()/
1E3|0},X:ne,Y:oe,la:qe,i:function(){Fa("")},za:function(){var a=E.allowedThreads;return a?a:navigator.hardwareConcurrency},w:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Qb();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0},o:function(a,b,c){re.length=0;var d;for(c>>=2;d=y()[b++];)(d=105>d)&&c&1&&c++,re.push(d?ja()[c++>>1]:A()[c]),++c;return Ab[a].apply(null,re)},C:function(){ua||(Ca||(Ca={}),Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},m:Qb,sa:function(){return"undefined"!=typeof SharedArrayBuffer},ia:function(a,b,c){y().copyWithin(a,b,b+c)},Z:function(a,b,c){ue.length=b;c>>=3;for(var d=0;d<b;d++)ue[d]=ja()[c+d];return(0>a?Ab[-a-1]:kf[a]).apply(null,
ue)},V:function(a){var b=y().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,838860800,d+(65536-d%65536)%65536);a:{try{p.grow(e-r.byteLength+65535>>>16);aa(p.buffer);var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},_:function(a,b,c){return ye(a)?ze(a,b,c):Ae(a,b,c)},ra:function(a,b,c,d,e){fb+=1;var f=a+112,h=K(f),l=C()[f+36>>2],m=C()[f+40>>2],q=C()[f+44>>2],n=C()[f+48>>2],t=C()[f+52>>
2],v=!!(t&4),k=!!(t&32),u=!!(t&16),w=!!(t&64),B=J=>{--fb;Fe(()=>{l?N(l)(J):b&&b(J)},w)},H=J=>{Fe(()=>{q?N(q)(J):d&&d(J)},w)},I=J=>{--fb;Fe(()=>{m?N(m)(J):c&&c(J)},w)},x=J=>{Fe(()=>{n?N(n)(J):e&&e(J)},w)};t=J=>{Ee(J,B,I,H,x)};var D=(J,qf)=>{He(J,qf.response,Ya=>{--fb;Fe(()=>{l?N(l)(Ya):b&&b(Ya)},w)},Ya=>{--fb;Fe(()=>{l?N(l)(Ya):b&&b(Ya)},w)})},U=J=>{Ee(J,D,I,H,x)};if("EM_IDB_STORE"===h)h=C()[f+84>>2],He(a,y().slice(h,h+C()[f+88>>2]),B,I);else if("EM_IDB_DELETE"===h)Je(a,B,I);else if(u){if(k)return 0;
Ee(a,v?D:B,I,H,x)}else Ie(a,B,k?I:v?U:t);return a},ma:function(){throw"unwind";},$:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:Re[c],failIfMajorPerformanceCaveat:!!A()[b+7],Bd:A()[b+8],ie:A()[b+9],Ec:A()[b+10],ld:A()[b+11],me:A()[b+12],ne:A()[b+13]};a=ye(a);return!a||b.ld?0:Ne(a,b)},ca:Ve,da:We,t:function(a){Ob(a)},u:Xe,G:Ye,M:Ze,F:$e,e:function(){return Da},
ua:function(){var a=self.navigator.userAgent,b=Na(a)+1,c=Wa(b);L(a,c,b);return c},T:af,O:nf,B:of,P:pf,Q:rf,a:p||E.wasmMemory,d:function(a){Da=a},L:gf,U:function(a,b,c,d){return gf(a,b,c,d)}};
(function(){function a(e,f){E.asm=e.exports;O.hc.push(E.asm.Ea);ab=E.asm.La;cb.unshift(E.asm.Aa);Ga=f;G||ub("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return yb().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);Fa(f)})}var d={a:sf};G||tb("wasm-instantiate");if(E.instantiateWasm)try{return E.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return Ea||"function"!=typeof WebAssembly.instantiateStreaming||vb()||"function"!=typeof fetch?c(b):fetch(wb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();E.___wasm_call_ctors=function(){return(E.___wasm_call_ctors=E.asm.Aa).apply(null,arguments)};
var Vd=E._free=function(){return(Vd=E._free=E.asm.Ba).apply(null,arguments)},Wa=E._malloc=function(){return(Wa=E._malloc=E.asm.Ca).apply(null,arguments)},Jb=E._pthread_self=function(){return(Jb=E._pthread_self=E.asm.Da).apply(null,arguments)};E._emscripten_tls_init=function(){return(E._emscripten_tls_init=E.asm.Ea).apply(null,arguments)};
var gc=E._emscripten_builtin_memalign=function(){return(gc=E._emscripten_builtin_memalign=E.asm.Fa).apply(null,arguments)},Ud=E.___getTypeName=function(){return(Ud=E.___getTypeName=E.asm.Ga).apply(null,arguments)};E.___embind_register_native_and_builtin_types=function(){return(E.___embind_register_native_and_builtin_types=E.asm.Ha).apply(null,arguments)};E.__emscripten_thread_crashed=function(){return(E.__emscripten_thread_crashed=E.asm.Ia).apply(null,arguments)};
var Kb=E._emscripten_main_thread_process_queued_calls=function(){return(Kb=E._emscripten_main_thread_process_queued_calls=E.asm.Ja).apply(null,arguments)},lf=E.__emscripten_thread_init=function(){return(lf=E.__emscripten_thread_init=E.asm.Ka).apply(null,arguments)};E._emscripten_current_thread_process_queued_calls=function(){return(E._emscripten_current_thread_process_queued_calls=E.asm.Ma).apply(null,arguments)};
var mf=E._emscripten_sync_run_in_main_thread_4=function(){return(mf=E._emscripten_sync_run_in_main_thread_4=E.asm.Na).apply(null,arguments)},te=E._emscripten_run_in_main_runtime_thread_js=function(){return(te=E._emscripten_run_in_main_runtime_thread_js=E.asm.Oa).apply(null,arguments)},we=E._emscripten_dispatch_to_thread_=function(){return(we=E._emscripten_dispatch_to_thread_=E.asm.Pa).apply(null,arguments)},Hb=E.__emscripten_thread_free_data=function(){return(Hb=E.__emscripten_thread_free_data=E.asm.Qa).apply(null,
arguments)},Ge=E.__emscripten_thread_exit=function(){return(Ge=E.__emscripten_thread_exit=E.asm.Ra).apply(null,arguments)},tf=E._setThrew=function(){return(tf=E._setThrew=E.asm.Sa).apply(null,arguments)},Mb=E._emscripten_stack_set_limits=function(){return(Mb=E._emscripten_stack_set_limits=E.asm.Ta).apply(null,arguments)},Cb=E.stackSave=function(){return(Cb=E.stackSave=E.asm.Ua).apply(null,arguments)},Db=E.stackRestore=function(){return(Db=E.stackRestore=E.asm.Va).apply(null,arguments)},se=E.stackAlloc=
function(){return(se=E.stackAlloc=E.asm.Wa).apply(null,arguments)};E.dynCall_ji=function(){return(E.dynCall_ji=E.asm.Xa).apply(null,arguments)};E.dynCall_jiji=function(){return(E.dynCall_jiji=E.asm.Ya).apply(null,arguments)};E.dynCall_viijii=function(){return(E.dynCall_viijii=E.asm.Za).apply(null,arguments)};E.dynCall_iiiiij=function(){return(E.dynCall_iiiiij=E.asm._a).apply(null,arguments)};E.dynCall_iiiiijj=function(){return(E.dynCall_iiiiijj=E.asm.$a).apply(null,arguments)};
E.dynCall_iiiiiijj=function(){return(E.dynCall_iiiiiijj=E.asm.ab).apply(null,arguments)};var Ib=E.__emscripten_allow_main_runtime_queued_calls=282756;function of(a,b){var c=Cb();try{N(a)(b)}catch(d){Db(c);if(d!==d+0)throw d;tf(1,0)}}function rf(a,b,c,d){var e=Cb();try{N(a)(b,c,d)}catch(f){Db(e);if(f!==f+0)throw f;tf(1,0)}}function pf(a,b,c){var d=Cb();try{N(a)(b,c)}catch(e){Db(d);if(e!==e+0)throw e;tf(1,0)}}
function nf(a,b,c,d){var e=Cb();try{return N(a)(b,c,d)}catch(f){Db(e);if(f!==f+0)throw f;tf(1,0)}}E.addRunDependency=tb;E.removeRunDependency=ub;E.FS_createPath=Kc;E.FS_createDataFile=Mc;E.FS_createPreloadedFile=Qc;E.FS_createLazyFile=Oc;E.FS_createDevice=kb;E.FS_unlink=Bc;E.keepRuntimeAlive=gb;E.PThread=O;E.PThread=O;E.wasmMemory=p;E.ExitStatus=Gb;var uf;function Gb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}sb=function vf(){uf||wf();uf||(sb=vf)};
function wf(){function a(){if(!uf&&(uf=!0,E.calledRun=!0,!Ha)){hb();la(E);if(E.onRuntimeInitialized)E.onRuntimeInitialized();if(!G){if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;){var b=E.postRun.shift();db.unshift(b)}ob(db)}}}if(!(0<qb))if(G)la(E),hb(),postMessage({cmd:"loaded"});else{if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)pb();ob(bb);0<qb||(E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){E.setStatus("")},
1);a()},1)):a())}}E.run=wf;function Ob(a){Ia=a;if(G)throw Nb(a),"unwind";gb()||G||(O.Uc(),eb=!0);Ia=a;if(!gb()){O.Uc();if(E.onExit)E.onExit(a);Ha=!0}sa(a,new Gb(a))}if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.pop()();wf();


  return BlinkCardWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkCardWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkCardWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkCardWasmSDK"] = BlinkCardWasmSDK;
