
var BlinkCardWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkCardWasmSDK) {
  BlinkCardWasmSDK = BlinkCardWasmSDK || {};


function g(){n.buffer!=t&&aa(n.buffer);return ca}function x(){n.buffer!=t&&aa(n.buffer);return da}function ea(){n.buffer!=t&&aa(n.buffer);return fa}function y(){n.buffer!=t&&aa(n.buffer);return ha}function A(){n.buffer!=t&&aa(n.buffer);return ia}function C(){n.buffer!=t&&aa(n.buffer);return ja}function ka(){n.buffer!=t&&aa(n.buffer);return la}var E;E||(E=typeof BlinkCardWasmSDK !== 'undefined' ? BlinkCardWasmSDK : {});var ma,na;E.ready=new Promise(function(a,b){ma=a;na=b});E.Qc||(E.Qc=0);E.Qc++;
(function(a){function b(m,q,p){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(u){var k=q;u.total&&(k=u.total);if(u.loaded){r.Cd?E.cc[m].loaded=u.loaded:(r.Cd=!0,E.cc||(E.cc={}),E.cc[m]={loaded:u.loaded,total:k});var v=k=u=0,z;for(z in E.cc){var B=E.cc[z];u+=B.total;k+=B.loaded;v++}u=Math.ceil(u*E.Qc/v);E.setStatus&&E.setStatus("Downloading data... ("+k+"/"+u+")")}else!E.cc&&E.setStatus&&E.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(u,k,v){this.start=u;this.end=k;this.audio=v}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);m.prototype.Hd=u;u=a.files;for(var k=
0;k<u.length;++k)m.prototype.ad[u[k].filename].onload();E.removeRunDependency("datafile_../../resources/advanced-threads/BlinkCardWasmSDK.data")}E.FS_createPath("/","microblink",!0,!0);m.prototype={ad:{},open:function(u,k){this.name=k;this.ad[k]=this;E.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Hd.subarray(this.start,this.end))},finish:function(u){E.FS_createDataFile(this.name,null,u,!0,!0,!0);E.removeRunDependency("fp "+this.name);this.ad[this.name]=null}};
for(var p=a.files,r=0;r<p.length;++r)(new m(p[r].start,p[r].end,p[r].audio)).open("GET",p[r].filename);E.addRunDependency("datafile_../../resources/advanced-threads/BlinkCardWasmSDK.data");E.td||(E.td={});E.td["../../resources/advanced-threads/BlinkCardWasmSDK.data"]={Ue:!1};l?(q(l),l=null):h=q}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof E.locateFilePackage||E.locateFile||(E.locateFile=E.locateFilePackage,F("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=E.locateFile?E.locateFile("BlinkCardWasmSDK.data",""):"BlinkCardWasmSDK.data",f=a.remote_package_size,h=null,l=E.getPreloadedPackage?E.getPreloadedPackage(e,
f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);E.calledRun?d():(E.preRun||(E.preRun=[]),E.preRun.push(d))})({files:[{filename:"/microblink/BlinkCard_Detector_general_6.0.0.strop",start:0,end:288976,audio:0},{filename:"/microblink/BlinkCard_EmbossedClassifier_general_6.1.0.strop",start:288976,end:341650,audio:0},{filename:"/microblink/BlinkCard_BlurClassifier_general_6.0.0.strop",start:341650,end:346068,audio:0},{filename:"/microblink/BlinkCard_RotationClassifier_general_6.0.0.strop",start:346068,
end:363542,audio:0},{filename:"/microblink/BlinkCard_RotationClassifier_general_6.2.0.strop",start:363542,end:384472,audio:0},{filename:"/microblink/BlinkCard_Classifier_general_6.1.0.strop",start:384472,end:469466,audio:0},{filename:"/microblink/BlinkCard_WordDetector_general_6.1.0.strop",start:469466,end:1363122,audio:0},{filename:"/microblink/BlinkCard_Ocr_general_6.4.0.strop",start:1363122,end:1654522,audio:0},{filename:"/microblink/templates.zzip",start:1654522,end:1789957,audio:0}],remote_package_size:1789957,
package_uuid:"85c651fc-3cf7-44f8-aea4-12554c1437c0"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},oa;oa=E.allowedThreads&&0<E.allowedThreads?E.allowedThreads-1:navigator.hardwareConcurrency-1;var pa=0,ra;0<oa&&(E.threadWorkersReadyPromise=new Promise(function(a){ra=a}));E.preRun||(E.preRun=[]);E.preRun.push(function(a){function b(){pa++;pa==oa&&ra()}var c=a.PThread.Wc;a.PThread.Wc=function(d){c(d,b)}});var sa={},ta;
for(ta in E)E.hasOwnProperty(ta)&&(sa[ta]=E[ta]);var ua="./this.program";function va(a,b){throw b;}var wa=!1,xa=!1,ya=!1;wa="object"===typeof window;xa="function"===typeof importScripts;ya="object"===typeof process&&"object"===typeof process.Ne&&"string"===typeof process.Ne.node;var G=E.ENVIRONMENT_IS_PTHREAD||!1;G&&(t=E.buffer);var za="";function Aa(a){return E.locateFile?E.locateFile(a,za):za+a}var Ba,Ca;
if(wa||xa)xa?za=self.location.href:"undefined"!==typeof document&&document.currentScript&&(za=document.currentScript.src),_scriptDir&&(za=_scriptDir),za=0!==za.indexOf("blob:")?za.substr(0,za.lastIndexOf("/")+1):"",Ba=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},xa&&(Ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var Da=E.print||console.log.bind(console),F=E.printErr||console.warn.bind(console);for(ta in sa)sa.hasOwnProperty(ta)&&(E[ta]=sa[ta]);sa=null;E.thisProgram&&(ua=E.thisProgram);E.quit&&(va=E.quit);var Ea,Fa=0,Ga;E.wasmBinary&&(Ga=E.wasmBinary);var noExitRuntime=E.noExitRuntime||!0;"object"!==typeof WebAssembly&&H("no native wasm support detected");var n,Ha,Ia=!1,Ja;function Ka(a,b){a||H("Assertion failed: "+b)}
function La(a,b,c){c=b+c;for(var d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function K(a,b){return a?La(x(),a,b):""}
function Ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Na(a,b,c){Ma(a,x(),b,c)}
function Oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Pa(a,b){for(var c="",d=0;!(d>=b/2);++d){var e=ea()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Qa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);ea()[b>>1]=f;b+=2}ea()[b>>1]=0;return b-d}
function Ra(a){return 2*a.length}function Sa(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ta(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Va(a){var b=Oa(a)+1,c=L(b);c&&Ma(a,g(),c,b);return c}function Wa(a,b){g().set(a,b)}var t,ca,da,fa,ha,ia,ja,Xa,la;function aa(a){t=a;E.HEAP8=ca=new Int8Array(a);E.HEAP16=fa=new Int16Array(a);E.HEAP32=ia=new Int32Array(a);E.HEAPU8=da=new Uint8Array(a);E.HEAPU16=ha=new Uint16Array(a);E.HEAPU32=ja=new Uint32Array(a);E.HEAPF32=Xa=new Float32Array(a);E.HEAPF64=la=new Float64Array(a)}
var Ya=E.INITIAL_MEMORY||209715200;
if(G)n=E.wasmMemory,t=E.buffer;else if(E.wasmMemory)n=E.wasmMemory;else if(n=new WebAssembly.Memory({initial:Ya/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ya&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
n&&(t=n.buffer);Ya=t.byteLength;aa(t);var M,Za=[],$a=[],ab=[],bb=[];function cb(){G||(E.noFSInit||db||(db=!0,eb(),E.stdin=E.stdin,E.stdout=E.stdout,E.stderr=E.stderr,E.stdin?fb("/dev","stdin",E.stdin):gb("/dev/tty","/dev/stdin"),E.stdout?fb("/dev","stdout",null,E.stdout):gb("/dev/tty","/dev/stdout"),E.stderr?fb("/dev","stderr",null,E.stderr):gb("/dev/tty1","/dev/stderr"),hb("/dev/stdin",0),hb("/dev/stdout",1),hb("/dev/stderr",1)),ib($a))}function jb(){var a=E.preRun.shift();Za.unshift(a)}
var kb=0,lb=null,mb=null;function nb(){Ka(!G,"addRunDependency cannot be used in a pthread worker");kb++;E.monitorRunDependencies&&E.monitorRunDependencies(kb)}function ob(){kb--;E.monitorRunDependencies&&E.monitorRunDependencies(kb);if(0==kb&&(null!==lb&&(clearInterval(lb),lb=null),mb)){var a=mb;mb=null;a()}}E.preloadedImages={};E.preloadedAudios={};
function H(a){if(E.onAbort)E.onAbort(a);G&&console.error("Pthread aborting at "+Error().stack);a+="";F(a);Ia=!0;Ja=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");na(a);throw a;}function pb(){var a=qb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var qb="BlinkCardWasmSDK.wasm";pb()||(qb=Aa(qb));
function rb(){var a=qb;try{if(a==qb&&Ga)return new Uint8Array(Ga);if(Ca)return Ca(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}function sb(){return Ga||!wa&&!xa||"function"!==typeof fetch?Promise.resolve().then(function(){return rb()}):fetch(qb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+qb+"'";return a.arrayBuffer()}).catch(function(){return rb()})}
var N,tb,vb={139378:function(a,b){a=K(a);b=K(b);throw Error(a+b);},139488:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},139704:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},139840:function(a,b){a=K(a);b=K(b);console.log(a+b)},139938:function(a){throw Error(K(a));},139981:function(){throw"Canceled!";},139999:function(a,b){setTimeout(function(){ub(a,b)},0)},140078:function(){throw Error("Unable to perform that operation while recognizer is in use!");
}};function ib(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(E);else{var c=b.Ve;"number"===typeof c?void 0===b.lc?M.get(c)():M.get(c)(b.lc):c(void 0===b.lc?null:b.lc)}}}
function wb(a,b){if(0>=a||a>g().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),xb>>2),d=0;if(c==a&&Atomics.compareExchange(A(),xb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}E._emscripten_futex_wake=wb;
function yb(a){if(G)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=O.Ub[a];b&&(A()[a+12>>2]=0,O.Gc(b.worker))}
var O={Zb:[],Yb:[],bd:[],Ye:function(){},Yd:function(){for(var a=L(228),b=0;57>b;++b)C()[a/4+b]=0;A()[a+12>>2]=a;b=a+152;A()[b>>2]=b;var c=L(512);for(b=0;128>b;++b)C()[c/4+b]=0;Atomics.store(C(),a+100>>2,c);Atomics.store(C(),a+40>>2,a);zb(a,!xa,1);Ab(a)},Zd:function(){O.receiveObjectTransfer=O.ne;O.threadInit=O.Ge;O.threadCancel=O.Fe;O.threadExit=O.zd;O.setExitStatus=O.te},Ub:{},Jc:[],pe:function(){for(;0<O.Jc.length;)O.Jc.pop()();G&&Bb()&&Cb()},yd:function(a,b){Atomics.store(C(),a+56>>2,1);Atomics.store(C(),
a+60>>2,0);O.pe();Atomics.store(C(),a+4>>2,b);Atomics.store(C(),a+0>>2,1);wb(a+0,2147483647);zb(0,0,0)},te:function(a){Ja=a},zd:function(a){var b=Bb();b&&(O.yd(b,a),G&&postMessage({cmd:"exit"}))},Fe:function(){O.yd(Bb(),-1);postMessage({cmd:"cancelDone"})},Ee:function(){for(var a in O.Ub){var b=O.Ub[a];b&&b.worker&&O.Gc(b.worker)}O.Ub={};for(a=0;a<O.Zb.length;++a){var c=O.Zb[a];c.terminate()}O.Zb=[];for(a=0;a<O.Yb.length;++a)c=O.Yb[a],b=c.Nb,O.Rc(b),c.terminate();O.Yb=[]},Rc:function(a){if(a){if(a.Vb){var b=
A()[a.Vb+100>>2];A()[a.Vb+100>>2]=0;P(b);P(a.Vb)}a.Vb=0;a.Pc&&a.bc&&P(a.bc);a.bc=0;a.worker&&(a.worker.Nb=null)}},Gc:function(a){O.qe(function(){delete O.Ub[a.Nb.Vb];O.Zb.push(a);O.Yb.splice(O.Yb.indexOf(a),1);O.Rc(a.Nb);a.Nb=void 0})},qe:function(a){A()[Db>>2]=0;try{a()}finally{A()[Db>>2]=1}},ne:function(){},Ge:function(){for(var a in O.bd)O.bd[a]()},Wc:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.Nb&&(O.Ld=a.Nb.Vb);if(d.targetThread&&d.targetThread!=Bb()){var f=O.Ub[d.ef];f?f.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Eb();else if("spawnThread"===e)Fb(c.data);else if("cleanupThread"===e)yb(d.thread);else if("killThread"===e){c=d.thread;if(G)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";A()[c+12>>2]=0;c=O.Ub[c];c.worker.terminate();
O.Rc(c);O.Yb.splice(O.Yb.indexOf(c.worker),1);c.worker.Nb=void 0}else if("cancelThread"===e){c=d.thread;if(G)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";O.Ub[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===e)a.loaded=!0,b&&b(a),a.qc&&(a.qc(),delete a.qc);else if("print"===e)Da("Thread "+d.threadId+": "+d.text);else if("printErr"===e)F("Thread "+d.threadId+": "+d.text);else if("alert"===
e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===e)a.Nb&&Atomics.load(C(),a.Nb.Vb+64>>2)&&O.Gc(a);else if("exitProcess"===e)try{Gb(d.returnCode)}catch(h){if(h instanceof Hb)return;throw h;}else"cancelDone"===e?O.Gc(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):F("worker sent an unknown command "+e));O.Ld=void 0};a.onerror=function(c){F("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:E.mainScriptUrlOrBlob||
_scriptDir,wasmMemory:n,wasmModule:Ha})},Dd:function(){var a=Aa("BlinkCardWasmSDK.worker.js");O.Zb.push(new Worker(a))},Rd:function(){0==O.Zb.length&&(O.Dd(),O.Wc(O.Zb[0]));return O.Zb.pop()},Pe:function(a){for(a=performance.now()+a;performance.now()<a;);}};E.establishStackSpace=function(a,b){Ib(a,b);Q(a)};E.invokeEntryPoint=function(a,b){return M.get(a)(b)};var Jb=0;function Kb(){return noExitRuntime||0<Jb}E.keepRuntimeAlive=Kb;var Lb;
Lb=G?function(){return performance.now()-E.__performance_now_clock_drift}:function(){return performance.now()};function Mb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Lb();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0}function Nb(a,b){O.Jc.push(function(){M.get(a)(b)})}
function Ob(a){this.Cb=a-16;this.ye=function(b){A()[this.Cb+8>>2]=b};this.ve=function(b){A()[this.Cb+0>>2]=b};this.we=function(){A()[this.Cb+4>>2]=0};this.ue=function(){var b=0;g()[this.Cb+12>>0]=b};this.xe=function(){var b=0;g()[this.Cb+13>>0]=b};this.pd=function(b,c){this.ye(b);this.ve(c);this.we();this.ue();this.xe()}}var Pb=0;
function Qb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(G)return R(2,1);if(!Qb.Id){Qb.Id=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);A()[Rb()>>2]=60*f;A()[Sb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Va(c);d=Va(d);e<b?(A()[Tb()>>2]=c,A()[Tb()+4>>2]=d):(A()[Tb()>>2]=d,A()[Tb()+4>>2]=c)}}
function Ub(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Vb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ub(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Wb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Xb(a){if("/"===a)return"/";a=Vb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Yb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){H("randomDevice")}}
function Zb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ub(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var $b=[];function ac(a,b){$b[a]={input:[],Ib:[],ic:b};bc(a,cc)}
var cc={open:function(a){var b=$b[a.node.oc];if(!b)throw new S(43);a.Fb=b;a.seekable=!1},close:function(a){a.Fb.ic.flush(a.Fb)},flush:function(a){a.Fb.ic.flush(a.Fb)},read:function(a,b,c,d){if(!a.Fb||!a.Fb.ic.od)throw new S(60);for(var e=0,f=0;f<d;f++){try{var h=a.Fb.ic.od(a.Fb)}catch(l){throw new S(29);}if(void 0===h&&0===e)throw new S(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Fb||!a.Fb.ic.Xc)throw new S(60);try{for(var e=
0;e<d;e++)a.Fb.ic.Xc(a.Fb,b[c+e])}catch(f){throw new S(29);}d&&(a.node.timestamp=Date.now());return e}},ec={od:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=dc(b,!0)}return a.input.shift()},Xc:function(a,b){null===b||10===b?(Da(La(a.Ib,0)),a.Ib=[]):0!=b&&a.Ib.push(b)},flush:function(a){a.Ib&&0<a.Ib.length&&
(Da(La(a.Ib,0)),a.Ib=[])}},fc={Xc:function(a,b){null===b||10===b?(F(La(a.Ib,0)),a.Ib=[]):0!=b&&a.Ib.push(b)},flush:function(a){a.Ib&&0<a.Ib.length&&(F(La(a.Ib,0)),a.Ib=[])}},T={Tb:null,Wb:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.Tb||(T.Tb={dir:{node:{Sb:T.zb.Sb,Lb:T.zb.Lb,mc:T.zb.mc,Cc:T.zb.Cc,xd:T.zb.xd,Nc:T.zb.Nc,Hc:T.zb.Hc,wd:T.zb.wd,Ic:T.zb.Ic},stream:{ac:T.Bb.ac}},file:{node:{Sb:T.zb.Sb,Lb:T.zb.Lb},
stream:{ac:T.Bb.ac,read:T.Bb.read,write:T.Bb.write,cd:T.Bb.cd,Dc:T.Bb.Dc,Ec:T.Bb.Ec}},link:{node:{Sb:T.zb.Sb,Lb:T.zb.Lb,pc:T.zb.pc},stream:{}},ed:{node:{Sb:T.zb.Sb,Lb:T.zb.Lb},stream:gc}});c=hc(a,b,c,d);ic(c.mode)?(c.zb=T.Tb.dir.node,c.Bb=T.Tb.dir.stream,c.Ab={}):32768===(c.mode&61440)?(c.zb=T.Tb.file.node,c.Bb=T.Tb.file.stream,c.Eb=0,c.Ab=null):40960===(c.mode&61440)?(c.zb=T.Tb.link.node,c.Bb=T.Tb.link.stream):8192===(c.mode&61440)&&(c.zb=T.Tb.ed.node,c.Bb=T.Tb.ed.stream);c.timestamp=Date.now();
a&&(a.Ab[b]=c,a.timestamp=c.timestamp);return c},We:function(a){return a.Ab?a.Ab.subarray?a.Ab.subarray(0,a.Eb):new Uint8Array(a.Ab):new Uint8Array(0)},kd:function(a,b){var c=a.Ab?a.Ab.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ab,a.Ab=new Uint8Array(b),0<a.Eb&&a.Ab.set(c.subarray(0,a.Eb),0))},oe:function(a,b){if(a.Eb!=b)if(0==b)a.Ab=null,a.Eb=0;else{var c=a.Ab;a.Ab=new Uint8Array(b);c&&a.Ab.set(c.subarray(0,Math.min(b,a.Eb)));a.Eb=b}},zb:{Sb:function(a){var b=
{};b.Md=8192===(a.mode&61440)?a.id:1;b.Tc=a.id;b.mode=a.mode;b.ie=1;b.uid=0;b.Vd=0;b.oc=a.oc;b.size=ic(a.mode)?4096:32768===(a.mode&61440)?a.Eb:40960===(a.mode&61440)?a.link.length:0;b.Ed=new Date(a.timestamp);b.he=new Date(a.timestamp);b.Kd=new Date(a.timestamp);b.Fd=4096;b.Gd=Math.ceil(b.size/b.Fd);return b},Lb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.oe(a,b.size)},mc:function(){throw jc[44];},Cc:function(a,b,c,d){return T.createNode(a,
b,c,d)},xd:function(a,b,c){if(ic(a.mode)){try{var d=kc(b,c)}catch(f){}if(d)for(var e in d.Ab)throw new S(55);}delete a.parent.Ab[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ab[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Nc:function(a,b){delete a.Ab[b];a.timestamp=Date.now()},Hc:function(a,b){var c=kc(a,b),d;for(d in c.Ab)throw new S(55);delete a.Ab[b];a.timestamp=Date.now()},wd:function(a){var b=[".",".."],c;for(c in a.Ab)a.Ab.hasOwnProperty(c)&&b.push(c);return b},Ic:function(a,b,c){a=T.createNode(a,
b,41471,0);a.link=c;return a},pc:function(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},Bb:{read:function(a,b,c,d,e){var f=a.node.Ab;if(e>=a.node.Eb)return 0;a=Math.min(a.node.Eb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ab||a.Ab.subarray)){if(f)return a.Ab=b.subarray(c,c+d),a.Eb=d;if(0===a.Eb&&0===e)return a.Ab=
b.slice(c,c+d),a.Eb=d;if(e+d<=a.Eb)return a.Ab.set(b.subarray(c,c+d),e),d}T.kd(a,e+d);if(a.Ab.subarray&&b.subarray)a.Ab.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ab[e+f]=b[c+f];a.Eb=Math.max(a.Eb,e+d);return d},ac:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Eb);if(0>b)throw new S(28);return b},cd:function(a,b,c){T.kd(a.node,b+c);a.node.Eb=Math.max(a.node.Eb,b+c)},Dc:function(a,b,c,d,e,f){if(0!==b)throw new S(28);if(32768!==(a.node.mode&61440))throw new S(43);
a=a.node.Ab;if(f&2||a.buffer!==t){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=L(f);c<f;)g()[b+c++]=0;c=b;if(!c)throw new S(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{Cb:c,Oc:d}},Ec:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);if(e&2)return 0;T.Bb.write(a,b,0,d,c,!1);return 0}}},lc=null,mc={},nc=[],oc=1,pc=null,qc=!0,rc={},S=null,jc={};
function sc(a,b){a=Zb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={md:!0,Zc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Zc)throw new S(32);a=Ub(a.split("/").filter(function(h){return!!h}),!1);var e=lc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=kc(e,a[d]);c=Vb(c+"/"+a[d]);e.fc&&(!f||f&&b.md)&&(e=e.fc.root);if(!f||b.yc)for(f=0;40960===(e.mode&61440);)if(e=tc(c),c=Zb(Wb(c),e),e=sc(c,{Zc:b.Zc}).node,40<f++)throw new S(32);}return{path:c,node:e}}
function uc(a){for(var b;;){if(a===a.parent)return a=a.Wb.rd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function vc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pc.length}function wc(a){var b=vc(a.parent.id,a.name);if(pc[b]===a)pc[b]=a.hc;else for(b=pc[b];b;){if(b.hc===a){b.hc=a.hc;break}b=b.hc}}
function kc(a,b){var c;if(c=(c=xc(a,"x"))?c:a.zb.mc?0:2)throw new S(c,a);for(c=pc[vc(a.id,b)];c;c=c.hc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.zb.mc(a,b)}function hc(a,b,c,d){a=new yc(a,b,c,d);b=vc(a.parent.id,a.name);a.hc=pc[b];return pc[b]=a}function ic(a){return 16384===(a&61440)}var zc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function xc(a,b){if(qc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Bc(a,b){try{return kc(a,b),20}catch(c){}return xc(a,"wx")}function Cc(a,b,c){try{var d=kc(a,b)}catch(e){return e.Hb}if(a=xc(a,"wx"))return a;if(c){if(!ic(d.mode))return 54;if(d===d.parent||"/"===uc(d))return 10}else if(ic(d.mode))return 31;return 0}
function Dc(a){var b=4096;for(a=a||0;a<=b;a++)if(!nc[a])return a;throw new S(33);}function Ec(a,b){Fc||(Fc=function(){},Fc.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Fc,d;for(d in a)c[d]=a[d];a=c;b=Dc(b);a.Rb=b;return nc[b]=a}var gc={open:function(a){a.Bb=mc[a.node.oc].Bb;a.Bb.open&&a.Bb.open(a)},ac:function(){throw new S(70);}};function bc(a,b){mc[a]={Bb:b}}
function Gc(a,b){var c="/"===b,d=!b;if(c&&lc)throw new S(10);if(!c&&!d){var e=sc(b,{md:!1});b=e.path;e=e.node;if(e.fc)throw new S(10);if(!ic(e.mode))throw new S(54);}b={type:a,bf:{},rd:b,ge:[]};a=a.Wb(b);a.Wb=b;b.root=a;c?lc=a:e&&(e.fc=b,e.Wb&&e.Wb.ge.push(b))}function Hc(a,b,c){var d=sc(a,{parent:!0}).node;a=Xb(a);if(!a||"."===a||".."===a)throw new S(28);var e=Bc(d,a);if(e)throw new S(e);if(!d.zb.Cc)throw new S(63);return d.zb.Cc(d,a,b,c)}function Ic(a){return Hc(a,16895,0)}
function Jc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Hc(a,b|8192,c)}function gb(a,b){if(!Zb(a))throw new S(44);var c=sc(b,{parent:!0}).node;if(!c)throw new S(44);b=Xb(b);var d=Bc(c,b);if(d)throw new S(d);if(!c.zb.Ic)throw new S(63);c.zb.Ic(c,b,a)}
function Kc(a){var b=sc(a,{parent:!0}).node,c=Xb(a),d=kc(b,c),e=Cc(b,c,!1);if(e)throw new S(e);if(!b.zb.Nc)throw new S(63);if(d.fc)throw new S(10);try{rc.willDeletePath&&rc.willDeletePath(a)}catch(f){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.zb.Nc(b,c);wc(d);try{if(rc.onDeletePath)rc.onDeletePath(a)}catch(f){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function tc(a){a=sc(a).node;if(!a)throw new S(44);if(!a.zb.pc)throw new S(28);return Zb(uc(a.parent),a.zb.pc(a))}function Lc(a,b){a="string"===typeof a?sc(a,{yc:!0}).node:a;if(!a.zb.Lb)throw new S(63);a.zb.Lb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function hb(a,b,c,d){if(""===a)throw new S(44);if("string"===typeof b){var e=zc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Vb(a);try{f=sc(a,{yc:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new S(20);}else f=Hc(a,c,0),e=!0;if(!f)throw new S(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!ic(f.mode))throw new S(54);if(!e&&(c=f?40960===(f.mode&61440)?32:ic(f.mode)&&
("r"!==Ac(b)||b&512)?31:xc(f,Ac(b)):44))throw new S(c);if(b&512){c=f;c="string"===typeof c?sc(c,{yc:!0}).node:c;if(!c.zb.Lb)throw new S(63);if(ic(c.mode))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(e=xc(c,"w"))throw new S(e);c.zb.Lb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Ec({node:f,path:uc(f),flags:b,seekable:!0,position:0,Bb:f.Bb,Me:[],error:!1},d);d.Bb.open&&d.Bb.open(d);!E.logReadFiles||b&1||(Mc||(Mc={}),a in Mc||(Mc[a]=1,F("FS.trackingDelegate error on read file: "+a)));
try{rc.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),rc.onOpenFile(a,f))}catch(h){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Nc(a){if(null===a.Rb)throw new S(8);a.Sc&&(a.Sc=null);try{a.Bb.close&&a.Bb.close(a)}catch(b){throw b;}finally{nc[a.Rb]=null}a.Rb=null}function Oc(a,b,c){if(null===a.Rb)throw new S(8);if(!a.seekable||!a.Bb.ac)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.Bb.ac(a,b,c);a.Me=[]}
function Pc(a,b,c,d,e,f){if(0>d||0>e)throw new S(28);if(null===a.Rb)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(ic(a.node.mode))throw new S(31);if(!a.Bb.write)throw new S(28);a.seekable&&a.flags&1024&&Oc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new S(70);b=a.Bb.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&rc.onWriteToFile)rc.onWriteToFile(a.path)}catch(l){F("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function eb(){S||(S=function(a,b){this.node=b;this.se=function(c){this.Hb=c};this.se(a);this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(function(a){jc[a]=new S(a);jc[a].stack="<generic error, no stack>"}))}var db;function Qc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Rc(a,b){a="string"===typeof a?a:uc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Vb(a+"/"+c);try{Ic(d)}catch(e){}a=d}}return d}
function Sc(a,b,c,d){a=Vb(("string"===typeof a?a:uc(a))+"/"+b);c=Qc(c,d);return Hc(a,(void 0!==c?c:438)&4095|32768,0)}function Tc(a,b,c,d,e,f){a=b?Vb(("string"===typeof a?a:uc(a))+"/"+b):a;d=Qc(d,e);e=Hc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Lc(e,d|146);a=hb(e,577);Pc(a,c,0,c.length,0,f);Nc(a);Lc(e,d)}return e}
function fb(a,b,c,d){a=Vb(("string"===typeof a?a:uc(a))+"/"+b);b=Qc(!!c,!!d);fb.qd||(fb.qd=64);var e=fb.qd++<<8|0;bc(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var q=0,p=0;p<m;p++){try{var r=c()}catch(u){throw new S(29);}if(void 0===r&&0===q)throw new S(6);if(null===r||void 0===r)break;q++;h[l+p]=r}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,l,m){for(var q=0;q<m;q++)try{d(h[l+q])}catch(p){throw new S(29);}m&&
(f.node.timestamp=Date.now());return q}});return Jc(a,b,e)}function Uc(a){if(!(a.ae||a.be||a.link||a.Ab)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(Ba)try{a.Ab=dc(Ba(a.url),!0),a.Eb=a.Ab.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Vc(a,b,c,d,e){function f(){this.Vc=!1;this.xc=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.fd;return this.zc(p/this.fd|0)[r]}};f.prototype.re=function(p){this.zc=p};f.prototype.dd=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),u,k=(u=p.getResponseHeader("Accept-Ranges"))&&"bytes"===u;p=
(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;k||(v=r);var z=this;z.re(function(B){var I=B*v,J=(B+1)*v-1;J=Math.min(J,r-1);if("undefined"===typeof z.xc[B]){var qa=z.xc;if(I>J)throw Error("invalid range ("+I+", "+J+") or no bytes requested!");if(J>r-1)throw Error("only "+r+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);r!==v&&w.setRequestHeader("Range","bytes="+I+"-"+J);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);I=void 0!==w.response?new Uint8Array(w.response||[]):dc(w.responseText||"",!0);qa[B]=I}if("undefined"===typeof z.xc[B])throw Error("doXHR failed!");return z.xc[B]});if(p||!r)v=r=1,v=r=this.zc(0).length,Da("LazyFiles on gzip forces download of the whole file when length is accessed");this.Bd=r;this.Ad=v;this.Vc=!0};if("undefined"!==
typeof XMLHttpRequest){if(!xa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Vc||this.dd();return this.Bd}},fd:{get:function(){this.Vc||this.dd();return this.Ad}}});var l=void 0}else l=c,h=void 0;var m=Sc(a,b,d,e);h?m.Ab=h:l&&(m.Ab=null,m.url=l);Object.defineProperties(m,{Eb:{get:function(){return this.Ab.length}}});var q={};Object.keys(m.Bb).forEach(function(p){var r=
m.Bb[p];q[p]=function(){Uc(m);return r.apply(null,arguments)}});q.read=function(p,r,u,k,v){Uc(m);p=p.node.Ab;if(v>=p.length)return 0;k=Math.min(p.length-v,k);if(p.slice)for(var z=0;z<k;z++)r[u+z]=p[v+z];else for(z=0;z<k;z++)r[u+z]=p.get(v+z);return k};m.Bb=q;return m}
function Wc(a,b,c,d,e,f,h,l,m,q){function p(k){function v(B){q&&q();l||Tc(a,b,B,d,e,m);f&&f();ob(u)}var z=!1;E.preloadPlugins.forEach(function(B){!z&&B.canHandle(r)&&(B.handle(k,r,v,function(){h&&h();ob(u)}),z=!0)});z||v(k)}Xc.pd();var r=b?Zb(Vb(a+"/"+b)):a,u="cp "+r;nb(u);"string"==typeof c?Xc.Oe(c,function(k){p(k)},h):p(c)}var U={},Fc,Mc,Yc={};
function Zc(a,b){try{var c=sc(a,{yc:!0}).node;if(!c)throw new S(44);if(!c.zb.Sb)throw new S(63);var d=c.zb.Sb(c)}catch(e){if(e&&e.node&&Vb(a)!==Vb(uc(e.node)))return-54;throw e;}A()[b>>2]=d.Md;A()[b+4>>2]=0;A()[b+8>>2]=d.Tc;A()[b+12>>2]=d.mode;A()[b+16>>2]=d.ie;A()[b+20>>2]=d.uid;A()[b+24>>2]=d.Vd;A()[b+28>>2]=d.oc;A()[b+32>>2]=0;tb=[d.size>>>0,(N=d.size,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[b+40>>2]=tb[0];A()[b+
44>>2]=tb[1];A()[b+48>>2]=4096;A()[b+52>>2]=d.Gd;A()[b+56>>2]=d.Ed.getTime()/1E3|0;A()[b+60>>2]=0;A()[b+64>>2]=d.he.getTime()/1E3|0;A()[b+68>>2]=0;A()[b+72>>2]=d.Kd.getTime()/1E3|0;A()[b+76>>2]=0;tb=[d.Tc>>>0,(N=d.Tc,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[b+80>>2]=tb[0];A()[b+84>>2]=tb[1];return 0}var $c=void 0;function ad(){$c+=4;return A()[$c-4>>2]}function bd(a){a=nc[a];if(!a)throw new S(8);return a}
function cd(a,b,c){if(G)return R(3,1,a,b,c);$c=c;try{var d=bd(a);switch(b){case 0:var e=ad();return 0>e?-28:hb(d.path,d.flags,0,e).Rb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ad(),d.flags|=e,0;case 12:return e=ad(),ea()[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof U&&f instanceof S||H(f),-f.Hb}}
function dd(a,b){if(G)return R(4,1,a,b);try{var c=bd(a);return Zc(c.path,b)}catch(d){return"undefined"!==typeof U&&d instanceof S||H(d),-d.Hb}}
function ed(a,b,c){if(G)return R(5,1,a,b,c);$c=c;try{var d=bd(a);switch(b){case 21509:case 21505:return d.Fb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Fb?0:-59;case 21519:if(!d.Fb)return-59;var e=ad();return A()[e>>2]=0;case 21520:return d.Fb?-28:-59;case 21531:a=e=ad();if(!d.Bb.$d)throw new S(59);return d.Bb.$d(d,b,a);case 21523:return d.Fb?0:-59;case 21524:return d.Fb?0:-59;default:H("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof U&&f instanceof
S||H(f),-f.Hb}}
function fd(a,b,c,d,e,f){if(G)return R(6,1,a,b,c,d,e,f);try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=gd(16384,b);if(!m){l=-48;break a}hd(m,0,b);h=!0}else{var q=nc[e];if(!q){l=-8;break a}var p=f;if(0!==(c&2)&&0===(d&2)&&2!==(q.flags&2097155))throw new S(2);if(1===(q.flags&2097155))throw new S(2);if(!q.Bb.Dc)throw new S(43);var r=q.Bb.Dc(q,a,b,p,c,d);m=r.Cb;h=r.Oc}Yc[m]={fe:m,de:b,Oc:h,Rb:e,ke:c,flags:d,offset:f};l=m}}return l}catch(u){return"undefined"!==typeof U&&
u instanceof S||H(u),-u.Hb}}function id(a,b){if(G)return R(7,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=Yc[a];if(d&&b===d.de){var e=nc[d.Rb];if(e&&d.ke&2){var f=d.flags,h=d.offset,l=x().slice(a,a+b);e&&e.Bb.Ec&&e.Bb.Ec(e,l,h,b,f)}Yc[a]=null;d.Oc&&P(d.fe)}c=0}return c}catch(m){return"undefined"!==typeof U&&m instanceof S||H(m),-m.Hb}}
function jd(a,b,c){if(G)return R(8,1,a,b,c);$c=c;try{var d=K(a),e=c?ad():0;return hb(d,b,e).Rb}catch(f){return"undefined"!==typeof U&&f instanceof S||H(f),-f.Hb}}
function kd(a){if(G)return R(9,1,a);try{a=K(a);var b=sc(a,{parent:!0}).node,c=Xb(a),d=kc(b,c),e=Cc(b,c,!0);if(e)throw new S(e);if(!b.zb.Hc)throw new S(63);if(d.fc)throw new S(10);try{rc.willDeletePath&&rc.willDeletePath(a)}catch(f){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.zb.Hc(b,c);wc(d);try{if(rc.onDeletePath)rc.onDeletePath(a)}catch(f){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==
typeof U&&f instanceof S||H(f),-f.Hb}}function ld(a,b){if(G)return R(10,1,a,b);try{return a=K(a),Zc(a,b)}catch(c){return"undefined"!==typeof U&&c instanceof S||H(c),-c.Hb}}function md(a){if(G)return R(11,1,a);try{return a=K(a),Kc(a),0}catch(b){return"undefined"!==typeof U&&b instanceof S||H(b),-b.Hb}}var nd={};function od(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function pd(a){return this.fromWireType(C()[a>>2])}var qd={},rd={},sd={};
function td(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ud(a,b){a=td(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function vd(a){var b=Error,c=ud(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var wd=void 0;function xd(a){throw new wd(a);}
function yd(a,b,c){function d(l){l=c(l);l.length!==a.length&&xd("Mismatched type converter count");for(var m=0;m<a.length;++m)zd(a[m],l[m])}a.forEach(function(l){sd[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){rd.hasOwnProperty(l)?e[m]=rd[l]:(f.push(l),qd.hasOwnProperty(l)||(qd[l]=[]),qd[l].push(function(){e[m]=rd[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function Ad(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Bd=void 0;function V(a){for(var b="";x()[a];)b+=Bd[x()[a++]];return b}var Cd=void 0;function X(a){throw new Cd(a);}
function zd(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||X('type "'+d+'" must have a positive integer typeid pointer');if(rd.hasOwnProperty(a)){if(c.Wd)return;X("Cannot register type '"+d+"' twice")}rd[a]=b;delete sd[a];qd.hasOwnProperty(a)&&(b=qd[a],delete qd[a],b.forEach(function(e){e()}))}function Dd(a){X(a.yb.Gb.Db.name+" instance already deleted")}var Ed=!1;function Fd(){}
function Gd(a){--a.count.value;0===a.count.value&&(a.Mb?a.Ob.Xb(a.Mb):a.Gb.Db.Xb(a.Cb))}function Hd(a){if("undefined"===typeof FinalizationGroup)return Hd=function(b){return b},a;Ed=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Cb?Gd(c):console.warn("object already deleted: "+c.Cb)});Hd=function(b){Ed.register(b,b.yb,b.yb);return b};Fd=function(b){Ed.unregister(b.yb)};return Hd(a)}var Id=void 0,Jd=[];
function Kd(){for(;Jd.length;){var a=Jd.pop();a.yb.dc=!1;a["delete"]()}}function Ld(){}var Md={};function Nd(a,b,c){if(void 0===a[b].Jb){var d=a[b];a[b]=function(){a[b].Jb.hasOwnProperty(arguments.length)||X("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Jb+")!");return a[b].Jb[arguments.length].apply(this,arguments)};a[b].Jb=[];a[b].Jb[d.vc]=d}}
function Od(a,b,c){E.hasOwnProperty(a)?((void 0===c||void 0!==E[a].Jb&&void 0!==E[a].Jb[c])&&X("Cannot register public name '"+a+"' twice"),Nd(E,a,a),E.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),E[a].Jb[c]=b):(E[a]=b,void 0!==c&&(E[a].af=c))}function Pd(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.ec=c;this.Xb=d;this.Pb=e;this.Qd=f;this.sc=h;this.Nd=l;this.le=[]}
function Qd(a,b,c){for(;b!==c;)b.sc||X("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.sc(a),b=b.Pb;return a}function Rd(a,b){if(null===b)return this.Uc&&X("null is not a valid "+this.name),0;b.yb||X('Cannot pass "'+Sd(b)+'" as a '+this.name);b.yb.Cb||X("Cannot pass deleted object as a pointer of type "+this.name);return Qd(b.yb.Cb,b.yb.Gb.Db,this.Db)}
function Td(a,b){if(null===b){this.Uc&&X("null is not a valid "+this.name);if(this.Bc){var c=this.Yc();null!==a&&a.push(this.Xb,c);return c}return 0}b.yb||X('Cannot pass "'+Sd(b)+'" as a '+this.name);b.yb.Cb||X("Cannot pass deleted object as a pointer of type "+this.name);!this.Ac&&b.yb.Gb.Ac&&X("Cannot convert argument of type "+(b.yb.Ob?b.yb.Ob.name:b.yb.Gb.name)+" to parameter type "+this.name);c=Qd(b.yb.Cb,b.yb.Gb.Db,this.Db);if(this.Bc)switch(void 0===b.yb.Mb&&X("Passing raw pointer to smart pointer is illegal"),
this.Ce){case 0:b.yb.Ob===this?c=b.yb.Mb:X("Cannot convert argument of type "+(b.yb.Ob?b.yb.Ob.name:b.yb.Gb.name)+" to parameter type "+this.name);break;case 1:c=b.yb.Mb;break;case 2:if(b.yb.Ob===this)c=b.yb.Mb;else{var d=b.clone();c=this.me(c,Ud(function(){d["delete"]()}));null!==a&&a.push(this.Xb,c)}break;default:X("Unsupporting sharing policy")}return c}
function Vd(a,b){if(null===b)return this.Uc&&X("null is not a valid "+this.name),0;b.yb||X('Cannot pass "'+Sd(b)+'" as a '+this.name);b.yb.Cb||X("Cannot pass deleted object as a pointer of type "+this.name);b.yb.Gb.Ac&&X("Cannot convert argument of type "+b.yb.Gb.name+" to parameter type "+this.name);return Qd(b.yb.Cb,b.yb.Gb.Db,this.Db)}function Wd(a,b,c){if(b===c)return a;if(void 0===c.Pb)return null;a=Wd(a,b,c.Pb);return null===a?null:c.Nd(a)}var Xd={};
function Yd(a,b){for(void 0===b&&X("ptr should not be undefined");a.Pb;)b=a.sc(b),a=a.Pb;return Xd[b]}function Zd(a,b){b.Gb&&b.Cb||xd("makeClassHandle requires ptr and ptrType");!!b.Ob!==!!b.Mb&&xd("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Hd(Object.create(a,{yb:{value:b}}))}
function $d(a,b,c,d){this.name=a;this.Db=b;this.Uc=c;this.Ac=d;this.Bc=!1;this.Xb=this.me=this.Yc=this.vd=this.Ce=this.je=void 0;void 0!==b.Pb?this.toWireType=Td:(this.toWireType=d?Rd:Vd,this.Qb=null)}function ae(a,b,c){E.hasOwnProperty(a)||xd("Replacing nonexistant public symbol");void 0!==E[a].Jb&&void 0!==c?E[a].Jb[c]=b:(E[a]=b,E[a].vc=c)}
function be(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=E["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=M.get(b).apply(null,c);return d}}function ce(a,b){a=V(a);var c=-1!=a.indexOf("j")?be(a,b):M.get(b);"function"!==typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var de=void 0;function ee(a){a=fe(a);var b=V(a);P(a);return b}
function ge(a,b){function c(f){e[f]||rd[f]||(sd[f]?sd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new de(a+": "+d.map(ee).join([", "]));}function he(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function ie(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ud(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function je(a,b,c,d,e){var f=b.length;2>f&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Qb){l=!0;break}var m="void"!==b[0].name,q="",p="";for(c=0;c<f-2;++c)q+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+td(a)+"("+q+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[X,d,e,od,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",q.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Qb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",q.push(f+"_dtor"),d.push(b[c].Qb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(a+"}\n");return ie(q).apply(null,d)}var ke=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function le(a){4<a&&0===--Y[a].$c&&(Y[a]=void 0,ke.push(a))}
function Ud(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ke.length?ke.pop():Y.length;Y[b]={$c:1,value:a};return b}}function Sd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function me(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;n.buffer!=t&&aa(n.buffer);return d.call(this,Xa[c>>2])};case 3:return function(c){return this.fromWireType(ka()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ne(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return x()[d]};case 1:return c?function(d){return ea()[d>>1]}:function(d){return y()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return C()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function oe(a){a||X("Cannot use deleted val. handle = "+a);return Y[a].value}function pe(a,b){var c=rd[a];void 0===c&&X(b+" has unknown type "+ee(a));return c}var qe={};
function re(a){var b=qe[a];return void 0===b?V(a):b}var se=[];function te(){return"object"===typeof globalThis?globalThis:Function("return this")()}function ue(a){var b=se.length;se.push(a);return b}function ve(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=pe(A()[(b>>2)+d],"parameter "+d);return c}var we={},xe=[];
function ye(){xa||(Ea||(Ea={}),Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function ze(a,b,c){if(0>=a||a>g().length||a&1)return-28;if(wa){if(Atomics.load(A(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(A(),xb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(A(),xb>>2,0),-73;d=Atomics.exchange(A(),xb>>2,0);if(0==d)break;Eb();if(Atomics.load(A(),a>>2)!=b)return-6;Atomics.exchange(A(),xb>>2,a)}return 0}a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function R(a,b){for(var c=arguments.length-2,d=Z(),e=Ae(8*c),f=e>>3,h=0;h<c;h++){var l=arguments[2+h];ka()[f+h]=l}c=Be(a,c,e,b);Q(d);return c}var Ce=[],De=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Ee(a){a=2<a?K(a):a;return De[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Fe(a,b,c){var d=Ee(a);if(!d)return-4;d.wc&&(A()[d.wc>>2]=b,A()[d.wc+4>>2]=c);if(d.sd||!d.Re)d.sd&&(d=d.sd),a=!1,d.uc&&d.uc.tc&&(a=d.uc.tc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.uc.tc.viewport(0,0,b,c);else{if(d.wc){d=A()[d.wc+8>>2];a=a?K(a):"";var e=Z(),f=Ae(12),h=0;if(a){h=Oa(a)+1;var l=L(h);Na(a,l,h);h=l}A()[f>>2]=h;A()[f+4>>2]=b;A()[f+8>>2]=c;Ge(0,d,657457152,0,h,f);Q(e);return 1}return-4}return 0}
function He(a,b,c){return G?R(12,1,a,b,c):Fe(a,b,c)}var Ie=[];function Je(a,b){C()[a>>2]=b;C()[a+4>>2]=b/4294967296|0}function Ke(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var Le;
function Me(a,b,c,d,e){function f(D){var ba=0,W=0;D&&(W=w.response?w.response.byteLength:0,ba=L(W),x().set(new Uint8Array(w.response),ba));C()[a+12>>2]=ba;Je(a+16,W)}var h=C()[a+8>>2];if(h){var l=K(h),m=a+112,q=K(m);q||(q="GET");C();var p=C()[m+52>>2],r=C()[m+56>>2],u=!!C()[m+60>>2];C();var k=C()[m+68>>2],v=C()[m+72>>2],z=C()[m+76>>2],B=C()[m+80>>2];h=C()[m+84>>2];m=C()[m+88>>2];var I=!!(p&1),J=!!(p&2);p=!!(p&64);k=k?K(k):void 0;v=v?K(v):void 0;var qa=B?K(B):void 0,w=new XMLHttpRequest;w.withCredentials=
u;w.open(q,l,!p,k,v);p||(w.timeout=r);w.gf=l;w.responseType="arraybuffer";B&&w.overrideMimeType(qa);if(z)for(;;){q=C()[z>>2];if(!q)break;l=C()[z+4>>2];if(!l)break;z+=8;q=K(q);l=K(l);w.setRequestHeader(q,l)}Ie.push(w);z=Ie.length;C()[a+0>>2]=z;h=h&&m?x().slice(h,h+m):null;w.onload=function(D){f(I&&!J);var ba=w.response?w.response.byteLength:0;Je(a+24,0);ba&&Je(a+32,ba);y()[a+40>>1]=w.readyState;y()[a+42>>1]=w.status;w.statusText&&Na(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,D):c&&
c(a,w,D)};w.onerror=function(D){f(I);var ba=w.status;Je(a+24,0);Je(a+32,w.response?w.response.byteLength:0);y()[a+40>>1]=w.readyState;y()[a+42>>1]=ba;c&&c(a,w,D)};w.ontimeout=function(D){c&&c(a,w,D)};w.onprogress=function(D){var ba=I&&J&&w.response?w.response.byteLength:0,W=0;I&&J&&(W=L(ba),x().set(new Uint8Array(w.response),W));C()[a+12>>2]=W;Je(a+16,ba);Je(a+24,D.loaded-ba);Je(a+32,D.total);y()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<D.loaded&&(w.status=200);y()[a+42>>1]=w.status;
w.statusText&&Na(w.statusText,a+44,64);d&&d(a,w,D);W&&P(W)};w.onreadystatechange=function(D){y()[a+40>>1]=w.readyState;2<=w.readyState&&(y()[a+42>>1]=w.status);e&&e(a,w,D)};try{w.send(h)}catch(D){c&&c(a,w,D)}}else c(a,0,"no url specified!")}
function Ne(a){try{a()}catch(b){if(b instanceof Hb)return;if("unwind"!==b)throw b&&"object"===typeof b&&b.stack&&F("exception thrown: "+[b,b.stack]),b;}if(G&&!Kb())try{if(G)throw a=Ja,G?O.zd(a):Gb(a),ya&&process.Te(a),"unwind";Gb(Ja)}catch(b){if(!(b instanceof Hb))throw b;}}
function Oe(a,b,c,d){var e=Le;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var h=K(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){y()[a+40>>1]=4;y()[a+42>>1]=200;Na("OK",a+44,64);c(a,0,h)};l.onerror=function(m){y()[a+40>>1]=4;y()[a+42>>1]=413;Na("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Pe(a,b,c){var d=Le;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=L(l);x().set(new Uint8Array(h),m);C()[a+12>>2]=m;Je(a+16,l);Je(a+24,0);Je(a+32,l);y()[a+40>>1]=4;y()[a+42>>1]=200;Na("OK",a+44,64);b(a,0,h)}else y()[a+40>>1]=4,y()[a+42>>1]=404,Na("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){y()[a+
40>>1]=4;y()[a+42>>1]=404;Na("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Qe(a,b,c){var d=Le;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;C()[a+12>>2]=0;Je(a+16,0);Je(a+24,0);Je(a+32,0);y()[a+40>>1]=4;y()[a+42>>1]=200;Na("OK",a+44,64);b(a,0,h)};f.onerror=function(h){y()[a+40>>1]=4;y()[a+42>>1]=404;Na("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Re(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Se(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Te(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Ue(a,b){a.nd||(a.nd=a.getContext,a.getContext=function(d,e){e=a.nd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ve(c,b):0}function Ve(a,b){var c=L(8);A()[c+4>>2]=Bb();var d={Xe:c,attributes:b,version:b.ee,tc:a};a.canvas&&(a.canvas.uc=d);("undefined"===typeof b.jd||b.jd)&&We(d);return c}
function We(a){a||(a=Xe);if(!a.Xd){a.Xd=!0;var b=a.tc;Re(b);Se(b);Te(b);b.Se=b.getExtension("EXT_disjoint_timer_query");b.$e=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Xe,Ye=["default","low-power","high-performance"],Ze={};
function $e(){if(!af){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ua||"./this.program"},b;for(b in Ze)a[b]=Ze[b];var c=[];for(b in a)c.push(b+"="+a[b]);af=c}return af}var af;
function bf(a,b){if(G)return R(13,1,a,b);try{var c=0;$e().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof U&&d instanceof S||H(d),d.Hb}}function cf(a,b){if(G)return R(14,1,a,b);try{var c=$e();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof S||H(e),e.Hb}}
function df(a){if(G)return R(15,1,a);try{var b=bd(a);Nc(b);return 0}catch(c){return"undefined"!==typeof U&&c instanceof S||H(c),c.Hb}}function ef(a,b){if(G)return R(16,1,a,b);try{var c=bd(a),d=c.Fb?2:ic(c.mode)?3:40960===(c.mode&61440)?7:4;g()[b>>0]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof S||H(e),e.Hb}}
function ff(a,b,c,d){if(G)return R(17,1,a,b,c,d);try{a:{for(var e=bd(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,q=g(),p=h,r=l,u=void 0;if(0>r||0>u)throw new S(28);if(null===m.Rb)throw new S(8);if(1===(m.flags&2097155))throw new S(8);if(ic(m.node.mode))throw new S(31);if(!m.Bb.read)throw new S(28);var k="undefined"!==typeof u;if(!k)u=m.position;else if(!m.seekable)throw new S(70);var v=m.Bb.read(m,q,p,r,u);k||(m.position+=v);var z=v;if(0>z){var B=-1;break a}a+=z;if(z<l)break}B=a}A()[d>>
2]=B;return 0}catch(I){return"undefined"!==typeof U&&I instanceof S||H(I),I.Hb}}
function gf(a,b,c,d,e){if(G)return R(18,1,a,b,c,d,e);try{var f=bd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Oc(f,a,d);tb=[f.position>>>0,(N=f.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[e>>2]=tb[0];A()[e+4>>2]=tb[1];f.Sc&&0===a&&0===d&&(f.Sc=null);return 0}catch(h){return"undefined"!==typeof U&&h instanceof S||H(h),h.Hb}}
function hf(a,b,c,d){if(G)return R(19,1,a,b,c,d);try{a:{for(var e=bd(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=Pc(e,g(),h,l,void 0);if(0>m){var q=-1;break a}a+=m}q=a}A()[d>>2]=q;return 0}catch(p){return"undefined"!==typeof U&&p instanceof S||H(p),p.Hb}}function jf(a,b){jf.ud||(jf.ud=Yb());for(var c=0;c<b;c++)g()[a+c>>0]=jf.ud();return 0}
function Fb(a){if(G)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=O.Rd();if(!b)return 6;if(void 0!==b.Nb)throw"Internal error!";if(!a.Fc)throw"Internal error, no pthread ptr!";O.Yb.push(b);for(var c=L(512),d=0;128>d;++d)A()[c+4*d>>2]=0;var e=a.bc+a.jc;d=O.Ub[a.Fc]={worker:b,bc:a.bc,jc:a.jc,Pc:a.Pc,Vb:a.Fc};var f=d.Vb>>2;Atomics.store(C(),f+16,a.hd);Atomics.store(C(),f+25,c);Atomics.store(C(),f+10,d.Vb);Atomics.store(C(),f+20,a.jc);Atomics.store(C(),
f+19,e);Atomics.store(C(),f+26,a.jc);Atomics.store(C(),f+28,e);Atomics.store(C(),f+29,a.hd);c=kf()+40;Atomics.store(C(),f+43,c);b.Nb=d;var h={cmd:"run",start_routine:a.De,arg:a.lc,threadInfoStruct:a.Fc,stackBase:a.bc,stackSize:a.jc};b.qc=function(){h.time=performance.now();b.postMessage(h,a.Le)};b.loaded&&(b.qc(),delete b.qc);return 0}
function lf(a,b){if(!a)return F("pthread_join attempted on a null thread pointer!"),71;if(G&&Bb()==a)return F("PThread "+a+" is attempting to join to itself!"),16;if(!G&&mf()==a)return F("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+12>>2]!==a)return F("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(C(),a+64>>2))return F("Attempted to join thread "+a+", which was already detached!"),28;for(ye();;){var c=
Atomics.load(C(),a+0>>2);if(1==c)return c=Atomics.load(C(),a+4>>2),b&&(A()[b>>2]=c),Atomics.store(C(),a+64>>2,1),G?postMessage({cmd:"cleanupThread",thread:a}):yb(a),0;if(G){var d=Bb();if(d&&!Atomics.load(C(),d+56>>2)&&2==Atomics.load(C(),d+0>>2))throw"Canceled!";}G||Eb();ze(a+0,c,G?100:1)}}function nf(a){return 0===a%4&&(0!==a%100||0===a%400)}function of(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var pf=[31,29,31,30,31,30,31,31,30,31,30,31],qf=[31,28,31,30,31,30,31,31,30,31,30,31];
function rf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(nf(a.getFullYear())?pf:qf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function sf(a,b,c,d){function e(k,v,z){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=z[0]+k;return k}function f(k,v){return e(k,v,"0")}function h(k,v){function z(I){return 0>I?-1:0<I?1:0}var B;0===(B=z(k.getFullYear()-v.getFullYear()))&&0===(B=z(k.getMonth()-v.getMonth()))&&(B=z(k.getDate()-v.getDate()));return B}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=rf(new Date(k.Kb+1900,0,1),k.Mc);var v=new Date(k.getFullYear()+1,0,4),z=l(new Date(k.getFullYear(),0,4));v=l(v);return 0>=h(z,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=A()[d+40>>2];d={Je:A()[d>>2],Ie:A()[d+4>>2],Kc:A()[d+8>>2],rc:A()[d+12>>2],kc:A()[d+16>>2],Kb:A()[d+20>>2],Lc:A()[d+24>>2],Mc:A()[d+28>>2],ff:A()[d+
32>>2],He:A()[d+36>>2],Ke:q?K(q):""};c=K(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in q)c=c.replace(new RegExp(p,"g"),q[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return r[k.Lc].substring(0,3)},"%A":function(k){return r[k.Lc]},"%b":function(k){return u[k.kc].substring(0,3)},"%B":function(k){return u[k.kc]},"%C":function(k){return f((k.Kb+1900)/100|0,2)},"%d":function(k){return f(k.rc,2)},"%e":function(k){return e(k.rc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Kc,
2)},"%I":function(k){k=k.Kc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.rc+of(nf(k.Kb+1900)?pf:qf,k.kc-1),3)},"%m":function(k){return f(k.kc+1,2)},"%M":function(k){return f(k.Ie,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Kc&&12>k.Kc?"AM":"PM"},"%S":function(k){return f(k.Je,2)},"%t":function(){return"\t"},"%u":function(k){return k.Lc||7},"%U":function(k){var v=new Date(k.Kb+1900,0,1),z=0===v.getDay()?v:rf(v,7-v.getDay());k=new Date(k.Kb+1900,k.kc,k.rc);return 0>
h(z,k)?f(Math.ceil((31-z.getDate()+(of(nf(k.getFullYear())?pf:qf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,v)?"01":"00"},"%V":function(k){var v=new Date(k.Kb+1901,0,4),z=l(new Date(k.Kb+1900,0,4));v=l(v);var B=rf(new Date(k.Kb+1900,0,1),k.Mc);return 0>h(B,z)?"53":0>=h(v,B)?"01":f(Math.ceil((z.getFullYear()<k.Kb+1900?k.Mc+32-z.getDate():k.Mc+1-z.getDate())/7),2)},"%w":function(k){return k.Lc},"%W":function(k){var v=new Date(k.Kb,0,1),z=1===v.getDay()?v:rf(v,0===v.getDay()?1:7-v.getDay()+1);k=
new Date(k.Kb+1900,k.kc,k.rc);return 0>h(z,k)?f(Math.ceil((31-z.getDate()+(of(nf(k.getFullYear())?pf:qf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,v)?"01":"00"},"%y":function(k){return(k.Kb+1900).toString().substring(2)},"%Y":function(k){return k.Kb+1900},"%z":function(k){k=k.He;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Ke},"%%":function(){return"%"}};for(p in q)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),q[p](d)));p=
dc(c,!1);if(p.length>b)return 0;Wa(p,a);return p.length-1}function yc(a,b,c,d){a||(a=this);this.parent=a;this.Wb=a.Wb;this.fc=null;this.id=oc++;this.name=b;this.mode=c;this.zb={};this.Bb={};this.oc=d}
Object.defineProperties(yc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},be:{get:function(){return ic(this.mode)}},ae:{get:function(){return 8192===(this.mode&61440)}}});eb();pc=Array(4096);Gc(T,"/");Ic("/tmp");Ic("/home");Ic("/home/web_user");
(function(){Ic("/dev");bc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Jc("/dev/null",259);ac(1280,ec);ac(1536,fc);Jc("/dev/tty",1280);Jc("/dev/tty1",1536);var a=Yb();fb("/dev","random",a);fb("/dev","urandom",a);Ic("/dev/shm");Ic("/dev/shm/tmp")})();
(function(){Ic("/proc");var a=Ic("/proc/self");Ic("/proc/self/fd");Gc({Wb:function(){var b=hc(a,"fd",16895,73);b.zb={mc:function(c,d){var e=nc[+d];if(!e)throw new S(8);c={parent:null,Wb:{rd:"fake"},zb:{pc:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Xc;E.FS_createPath=Rc;E.FS_createDataFile=Tc;E.FS_createPreloadedFile=Wc;E.FS_createLazyFile=Vc;E.FS_createDevice=fb;E.FS_unlink=Kc;wd=E.InternalError=vd("InternalError");
for(var tf=Array(256),uf=0;256>uf;++uf)tf[uf]=String.fromCharCode(uf);Bd=tf;Cd=E.BindingError=vd("BindingError");Ld.prototype.isAliasOf=function(a){if(!(this instanceof Ld&&a instanceof Ld))return!1;var b=this.yb.Gb.Db,c=this.yb.Cb,d=a.yb.Gb.Db;for(a=a.yb.Cb;b.Pb;)c=b.sc(c),b=b.Pb;for(;d.Pb;)a=d.sc(a),d=d.Pb;return b===d&&c===a};
Ld.prototype.clone=function(){this.yb.Cb||Dd(this);if(this.yb.nc)return this.yb.count.value+=1,this;var a=Hd,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.yb;a=a(c.call(b,d,{yb:{value:{count:e.count,dc:e.dc,nc:e.nc,Cb:e.Cb,Gb:e.Gb,Mb:e.Mb,Ob:e.Ob}}}));a.yb.count.value+=1;a.yb.dc=!1;return a};Ld.prototype["delete"]=function(){this.yb.Cb||Dd(this);this.yb.dc&&!this.yb.nc&&X("Object already scheduled for deletion");Fd(this);Gd(this.yb);this.yb.nc||(this.yb.Mb=void 0,this.yb.Cb=void 0)};
Ld.prototype.isDeleted=function(){return!this.yb.Cb};Ld.prototype.deleteLater=function(){this.yb.Cb||Dd(this);this.yb.dc&&!this.yb.nc&&X("Object already scheduled for deletion");Jd.push(this);1===Jd.length&&Id&&Id(Kd);this.yb.dc=!0;return this};$d.prototype.Sd=function(a){this.vd&&(a=this.vd(a));return a};$d.prototype.gd=function(a){this.Xb&&this.Xb(a)};$d.prototype.argPackAdvance=8;$d.prototype.readValueFromPointer=pd;$d.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
$d.prototype.fromWireType=function(a){function b(){return this.Bc?Zd(this.Db.ec,{Gb:this.je,Cb:c,Ob:this,Mb:a}):Zd(this.Db.ec,{Gb:this,Cb:a})}var c=this.Sd(a);if(!c)return this.gd(a),null;var d=Yd(this.Db,c);if(void 0!==d){if(0===d.yb.count.value)return d.yb.Cb=c,d.yb.Mb=a,d.clone();d=d.clone();this.gd(a);return d}d=this.Db.Qd(c);d=Md[d];if(!d)return b.call(this);d=this.Ac?d.Jd:d.pointerType;var e=Wd(c,this.Db,d.Db);return null===e?b.call(this):this.Bc?Zd(d.Db.ec,{Gb:d,Cb:e,Ob:this,Mb:a}):Zd(d.Db.ec,
{Gb:d,Cb:e})};E.getInheritedInstanceCount=function(){return Object.keys(Xd).length};E.getLiveInheritedInstances=function(){var a=[],b;for(b in Xd)Xd.hasOwnProperty(b)&&a.push(Xd[b]);return a};E.flushPendingDeletes=Kd;E.setDelayFunction=function(a){Id=a;Jd.length&&Id&&Id(Kd)};de=E.UnboundTypeError=vd("UnboundTypeError");E.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};E.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
G||(Ke(function(a){Le=a;ob("library_fetch_init")},function(){Le=!1;ob("library_fetch_init")}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||nb("library_fetch_init"));var vf=[null,function(a,b){if(G)return R(1,1,a,b)},Qb,cd,dd,ed,fd,id,jd,kd,ld,md,He,bf,cf,df,ef,ff,gf,hf];function dc(a,b){var c=Array(Oa(a)+1);a=Ma(a,c,0,c.length);b&&(c.length=a);return c}
var Jf={n:function(a,b,c,d){H("Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,d?K(d):"unknown function"])},va:function(a,b){return Mb(a,b)},F:function(a){return L(a+16)+16},Ia:function(a,b){return Nb(a,b)},E:function(a,b,c){(new Ob(a)).pd(b,c);Pb++;throw a;},ua:function(a,b){Qb();a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();
var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a;a=A()[Tb()+(a?4:0)>>2];A()[b+40>>2]=a;return b},W:cd,za:dd,xa:ed,Ca:fd,Ba:function(){return 0},Aa:id,C:jd,wa:kd,ya:ld,T:md,j:function(a){var b=nd[a];delete nd[a];var c=b.Yc,d=b.Xb,e=b.ld,f=e.map(function(h){return h.Ud}).concat(e.map(function(h){return h.Ae}));
yd([a],f,function(h){var l={};e.forEach(function(m,q){var p=h[q],r=m.zc,u=m.Td,k=h[q+e.length],v=m.ze,z=m.Be;l[m.Pd]={read:function(B){return p.fromWireType(r(u,B))},write:function(B,I){var J=[];v(z,B,k.toWireType(J,I));od(J)}}});return[{name:b.name,fromWireType:function(m){var q={},p;for(p in l)q[p]=l[p].read(m);d(m);return q},toWireType:function(m,q){for(var p in l)if(!(p in q))throw new TypeError('Missing field:  "'+p+'"');var r=c();for(p in l)l[p].write(r,q[p]);null!==m&&m.push(d,r);return r},
argPackAdvance:8,readValueFromPointer:pd,Qb:d}]})},Ea:function(a,b,c,d,e){var f=Ad(c);b=V(b);zd(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=ea();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},Qb:null})},B:function(a,b,c,d,e,f,h,l,m,q,p,r,u){p=V(p);f=ce(e,f);l&&(l=ce(h,l));q&&(q=ce(m,q));u=ce(r,u);var k=td(p);
Od(k,function(){ge("Cannot construct "+p+" due to unbound types",[d])});yd([a,b,c],d?[d]:[],function(v){v=v[0];if(d){var z=v.Db;var B=z.ec}else B=Ld.prototype;v=ud(k,function(){if(Object.getPrototypeOf(this)!==I)throw new Cd("Use 'new' to construct "+p);if(void 0===J.$b)throw new Cd(p+" has no accessible constructor");var w=J.$b[arguments.length];if(void 0===w)throw new Cd("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.$b).toString()+
") parameters instead!");return w.apply(this,arguments)});var I=Object.create(B,{constructor:{value:v}});v.prototype=I;var J=new Pd(p,v,I,u,z,f,l,q);z=new $d(p,J,!0,!1);B=new $d(p+"*",J,!1,!1);var qa=new $d(p+" const*",J,!1,!0);Md[a]={pointerType:B,Jd:qa};ae(k,v);return[z,B,qa]})},J:function(a,b,c,d,e,f){Ka(0<b);var h=he(b,c);e=ce(d,e);var l=[f],m=[];yd([],[a],function(q){q=q[0];var p="constructor "+q.name;void 0===q.Db.$b&&(q.Db.$b=[]);if(void 0!==q.Db.$b[b-1])throw new Cd("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+q.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");q.Db.$b[b-1]=function(){ge("Cannot construct "+q.name+" due to unbound types",h)};yd([],h,function(r){q.Db.$b[b-1]=function(){arguments.length!==b-1&&X(p+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var u=1;u<b;++u)l[u]=r[u].toWireType(m,arguments[u-1]);u=e.apply(null,l);od(m);return r[0].fromWireType(u)};return[]});return[]})},
s:function(a,b,c,d,e,f,h,l){var m=he(c,d);b=V(b);f=ce(e,f);yd([],[a],function(q){function p(){ge("Cannot call "+r+" due to unbound types",m)}q=q[0];var r=q.name+"."+b;l&&q.Db.le.push(b);var u=q.Db.ec,k=u[b];void 0===k||void 0===k.Jb&&k.className!==q.name&&k.vc===c-2?(p.vc=c-2,p.className=q.name,u[b]=p):(Nd(u,b,r),u[b].Jb[c-2]=p);yd([],m,function(v){v=je(r,v,q,f,h);void 0===u[b].Jb?(v.vc=c-2,u[b]=v):u[b].Jb[c-2]=v;return[]});return[]})},Da:function(a,b){b=V(b);zd(a,{name:b,fromWireType:function(c){var d=
Y[c].value;le(c);return d},toWireType:function(c,d){return Ud(d)},argPackAdvance:8,readValueFromPointer:pd,Qb:null})},X:function(a,b,c){c=Ad(c);b=V(b);zd(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Sd(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:me(b,c),Qb:null})},I:function(a,b,c,d,e,f){var h=he(b,c);a=V(a);e=ce(d,e);Od(a,function(){ge("Cannot call "+a+" due to unbound types",
h)},b-1);yd([],h,function(l){ae(a,je(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},l:function(a,b,c,d,e){function f(q){return q}b=V(b);-1===e&&(e=4294967295);var h=Ad(c);if(0===d){var l=32-8*c;f=function(q){return q<<l>>>l}}var m=-1!=b.indexOf("unsigned");zd(a,{name:b,fromWireType:f,toWireType:function(q,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Sd(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+Sd(p)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+d+", "+e+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:ne(b,h,0!==d),Qb:null})},k:function(a,b,c){function d(f){f>>=2;var h=C();return new e(t,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);zd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Wd:!0})},Y:function(a,b){b=V(b);var c="std::string"===b;zd(a,{name:b,fromWireType:function(d){var e=C()[d>>
2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==x()[l]){f=K(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(x()[d+4+h]);m=m.join("")}P(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||X("Cannot pass non-string to std::string");var h=(c&&f?function(){return Oa(e)}:
function(){return e.length})(),l=L(4+h+1);C()[l>>2]=h;if(c&&f)Na(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(P(l),X("String has UTF-16 code units that do not fit in 8 bits"));x()[l+4+f]=m}else for(f=0;f<h;++f)x()[l+4+f]=e[f];null!==d&&d.push(P,l);return l},argPackAdvance:8,readValueFromPointer:pd,Qb:function(d){P(d)}})},D:function(a,b,c){c=V(c);if(2===b){var d=Pa;var e=Qa;var f=Ra;var h=function(){return y()};var l=1}else 4===b&&(d=Sa,e=Ta,f=Ua,h=function(){return C()},l=2);
zd(a,{name:c,fromWireType:function(m){for(var q=C()[m>>2],p=h(),r,u=m+4,k=0;k<=q;++k){var v=m+4+k*b;if(k==q||0==p[v>>l])u=d(u,v-u),void 0===r?r=u:(r+=String.fromCharCode(0),r+=u),u=v+b}P(m);return r},toWireType:function(m,q){"string"!==typeof q&&X("Cannot pass non-string to C++ string type "+c);var p=f(q),r=L(4+p+b);C()[r>>2]=p>>l;e(q,r+4,p+b);null!==m&&m.push(P,r);return r},argPackAdvance:8,readValueFromPointer:pd,Qb:function(m){P(m)}})},i:function(a,b,c,d,e,f){nd[a]={name:V(b),Yc:ce(c,d),Xb:ce(e,
f),ld:[]}},e:function(a,b,c,d,e,f,h,l,m,q){nd[a].ld.push({Pd:V(b),Ud:c,zc:ce(d,e),Td:f,Ae:h,ze:ce(l,m),Be:q})},Fa:function(a,b){b=V(b);zd(a,{ce:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},Ga:function(a){delete Ie[a-1]},na:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.Ub[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},v:function(a,
b,c){a=oe(a);b=pe(b,"emval::as");var d=[],e=Ud(d);A()[c>>2]=e;return b.toWireType(d,a)},y:function(a,b,c,d){a=se[a];b=oe(b);c=re(c);a(b,c,null,d)},O:le,Oa:function(a){if(0===a)return Ud(te());a=re(a);return Ud(te()[a])},x:function(a,b){b=ve(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(q){return q.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+td("methodCaller_"+d)+"(handle, name, destructors, args) {\n";
var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.ce||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=ie(e).apply(null,f);return ue(a)},Ra:function(a){a=re(a);return Ud(E[a])},r:function(a,b){a=oe(a);b=oe(b);return Ud(a[b])},ga:function(a){4<a&&(Y[a].$c+=1)},
H:function(a,b,c,d){a=oe(a);var e=we[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+
e+");\nreturn __emval_register(obj);\n}\n")))(pe,E,Ud);we[b]=e}return e(a,c,d)},Ma:function(){return Ud([])},Qa:function(a){return Ud(re(a))},Na:function(){return Ud({})},Pa:function(a){od(Y[a].value);le(a)},p:function(a,b,c){a=oe(a);b=oe(b);c=oe(c);a[b]=c},u:function(a,b){a=pe(a,"_emval_take_value");a=a.readValueFromPointer(b);return Ud(a)},q:function(){H()},L:function(){var a=E.allowedThreads;return a?a:navigator.hardwareConcurrency},Q:Mb,o:function(a,b,c){xe.length=0;var d;for(c>>=2;d=x()[b++];)(d=
105>d)&&c&1&&c++,xe.push(d?ka()[c++>>1]:A()[c]),++c;return vb[a].apply(null,xe)},qa:ye,S:function(){},w:ze,t:wb,z:Lb,K:function(){return"undefined"!==typeof SharedArrayBuffer},d:function(a,b){wf(a,b||1);throw"longjmp";},fa:function(a,b,c){x().copyWithin(a,b,b+c)},ka:function(a,b,c){Ce.length=b;c>>=3;for(var d=0;d<b;d++)Ce[d]=ka()[c+d];return(0>a?vb[-a-1]:vf[a]).apply(null,Ce)},ha:function(a){var b=x().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-t.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},la:function(a,b,c){return Ee(a)?Fe(a,b,c):He(a,b,c)},R:function(){},Ha:function(a,b,c,d,e){function f(D){Me(D,h,q,p,m)}function h(D,ba){Oe(D,ba.response,function(W){--Jb;Ne(function(){v?M.get(v)(W):b&&b(W)})},function(W){--Jb;Ne(function(){v?M.get(v)(W):b&&b(W)})})}function l(D){Me(D,r,q,p,m)}function m(D){Ne(function(){I?
M.get(I)(D):e&&e(D)})}function q(D){--Jb;Ne(function(){z?M.get(z)(D):c&&c(D)})}function p(D){Ne(function(){B?M.get(B)(D):d&&d(D)})}function r(D){--Jb;Ne(function(){v?M.get(v)(D):b&&b(D)})}Jb+=1;var u=a+112,k=K(u),v=C()[u+36>>2],z=C()[u+40>>2],B=C()[u+44>>2],I=C()[u+48>>2],J=C()[u+52>>2],qa=!!(J&4),w=!!(J&32);J=!!(J&16);if("EM_IDB_STORE"===k)k=C()[u+84>>2],Oe(a,x().slice(k,k+C()[u+88>>2]),r,q);else if("EM_IDB_DELETE"===k)Qe(a,r,q);else if(J){if(w)return 0;Me(a,qa?h:r,q,p,m)}else Pe(a,r,w?q:qa?f:l);
return a},ma:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:Ye[c],failIfMajorPerformanceCaveat:!!A()[b+7],ee:A()[b+8],Ze:A()[b+9],jd:A()[b+10],Od:A()[b+11],cf:A()[b+12],df:A()[b+13]};a=Ee(a);return!a||b.Od?0:Ue(a,b)},sa:bf,ta:cf,G:function(a){Gb(a)},A:df,ra:ef,V:ff,$:gf,U:hf,b:function(){return Fa|0},Ka:function(){var a=self.navigator.userAgent,b=Oa(a)+1,
c=L(b);Na(a,c,b);return c},ia:jf,ea:function(){O.Yd()},M:xf,h:yf,m:zf,N:Af,da:Bf,f:Cf,g:Df,P:Ef,ca:Ff,ba:Gf,aa:Hf,a:n||E.wasmMemory,La:function(a){Qb();var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+
6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},oa:function(a){var b=O.Jc.pop();a&&b()},pa:Nb,Z:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return F("pthread_create called with a null thread pointer!"),
28;var e=[];if(G&&0===e.length)return If(687865856,a,b,c,d);var f=0,h=0;if(b&&-1!=b){var l=A()[b>>2];l+=81920;f=A()[b+8>>2];h=0!==A()[b+12>>2]}else l=2097152;(b=0==f)?f=gd(16,l):(f-=l,Ka(0<f));for(var m=L(228),q=0;57>q;++q)C()[(m>>2)+q]=0;A()[a>>2]=m;A()[m+12>>2]=m;a=m+152;A()[a>>2]=a;c={bc:f,jc:l,Pc:b,hd:h,De:c,Fc:m,lc:d,Le:e};return G?(c.Qe="spawnThread",postMessage(c,e),0):Fb(c)},Ja:function(a,b){return lf(a,b)},c:function(a){Fa=a|0},_:sf,ja:function(a,b,c,d){return sf(a,b,c,d)}};
(function(){function a(e,f){E.asm=e.exports;M=E.asm.Xa;$a.unshift(E.asm.Sa);O.bd.push(E.asm.Wa);Ha=f;G||ob("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return sb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);H(f)})}var d={a:Jf};G||nb("wasm-instantiate");if(E.instantiateWasm)try{return E.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Ga||
"function"!==typeof WebAssembly.instantiateStreaming||pb()||"function"!==typeof fetch?c(b):fetch(qb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(na);return{}})();E.___wasm_call_ctors=function(){return(E.___wasm_call_ctors=E.asm.Sa).apply(null,arguments)};
var P=E._free=function(){return(P=E._free=E.asm.Ta).apply(null,arguments)},L=E._malloc=function(){return(L=E._malloc=E.asm.Ua).apply(null,arguments)},Bb=E._pthread_self=function(){return(Bb=E._pthread_self=E.asm.Va).apply(null,arguments)};E._emscripten_tls_init=function(){return(E._emscripten_tls_init=E.asm.Wa).apply(null,arguments)};var fe=E.___getTypeName=function(){return(fe=E.___getTypeName=E.asm.Ya).apply(null,arguments)};
E.___embind_register_native_and_builtin_types=function(){return(E.___embind_register_native_and_builtin_types=E.asm.Za).apply(null,arguments)};
var kf=E._emscripten_get_global_libc=function(){return(kf=E._emscripten_get_global_libc=E.asm._a).apply(null,arguments)},hd=E._memset=function(){return(hd=E._memset=E.asm.$a).apply(null,arguments)},Tb=E.__get_tzname=function(){return(Tb=E.__get_tzname=E.asm.ab).apply(null,arguments)},Sb=E.__get_daylight=function(){return(Sb=E.__get_daylight=E.asm.bb).apply(null,arguments)},Rb=E.__get_timezone=function(){return(Rb=E.__get_timezone=E.asm.cb).apply(null,arguments)},mf=E._emscripten_main_browser_thread_id=
function(){return(mf=E._emscripten_main_browser_thread_id=E.asm.db).apply(null,arguments)},Cb=E.___pthread_tsd_run_dtors=function(){return(Cb=E.___pthread_tsd_run_dtors=E.asm.eb).apply(null,arguments)},Eb=E._emscripten_main_thread_process_queued_calls=function(){return(Eb=E._emscripten_main_thread_process_queued_calls=E.asm.fb).apply(null,arguments)};E._emscripten_current_thread_process_queued_calls=function(){return(E._emscripten_current_thread_process_queued_calls=E.asm.gb).apply(null,arguments)};
var Ab=E._emscripten_register_main_browser_thread_id=function(){return(Ab=E._emscripten_register_main_browser_thread_id=E.asm.hb).apply(null,arguments)},ub=E.__emscripten_do_dispatch_to_thread=function(){return(ub=E.__emscripten_do_dispatch_to_thread=E.asm.ib).apply(null,arguments)},If=E._emscripten_sync_run_in_main_thread_4=function(){return(If=E._emscripten_sync_run_in_main_thread_4=E.asm.jb).apply(null,arguments)},Be=E._emscripten_run_in_main_runtime_thread_js=function(){return(Be=E._emscripten_run_in_main_runtime_thread_js=
E.asm.kb).apply(null,arguments)},Ge=E.__emscripten_call_on_thread=function(){return(Ge=E.__emscripten_call_on_thread=E.asm.lb).apply(null,arguments)},zb=E.__emscripten_thread_init=function(){return(zb=E.__emscripten_thread_init=E.asm.mb).apply(null,arguments)},Z=E.stackSave=function(){return(Z=E.stackSave=E.asm.nb).apply(null,arguments)},Q=E.stackRestore=function(){return(Q=E.stackRestore=E.asm.ob).apply(null,arguments)},Ae=E.stackAlloc=function(){return(Ae=E.stackAlloc=E.asm.pb).apply(null,arguments)},
Ib=E._emscripten_stack_set_limits=function(){return(Ib=E._emscripten_stack_set_limits=E.asm.qb).apply(null,arguments)},wf=E._setThrew=function(){return(wf=E._setThrew=E.asm.rb).apply(null,arguments)},gd=E._memalign=function(){return(gd=E._memalign=E.asm.sb).apply(null,arguments)};E.dynCall_jiji=function(){return(E.dynCall_jiji=E.asm.tb).apply(null,arguments)};E.dynCall_viijii=function(){return(E.dynCall_viijii=E.asm.ub).apply(null,arguments)};
E.dynCall_iiiiiijj=function(){return(E.dynCall_iiiiiijj=E.asm.vb).apply(null,arguments)};E.dynCall_iiiiij=function(){return(E.dynCall_iiiiij=E.asm.wb).apply(null,arguments)};E.dynCall_iiiiijj=function(){return(E.dynCall_iiiiijj=E.asm.xb).apply(null,arguments)};var Db=E.__emscripten_allow_main_runtime_queued_calls=138852,xb=E.__emscripten_main_thread_futex=726936;function Cf(a,b){var c=Z();try{M.get(a)(b)}catch(d){Q(c);if(d!==d+0&&"longjmp"!==d)throw d;wf(1,0)}}
function yf(a,b){var c=Z();try{return M.get(a)(b)}catch(d){Q(c);if(d!==d+0&&"longjmp"!==d)throw d;wf(1,0)}}function Df(a,b,c){var d=Z();try{M.get(a)(b,c)}catch(e){Q(d);if(e!==e+0&&"longjmp"!==e)throw e;wf(1,0)}}function zf(a,b,c){var d=Z();try{return M.get(a)(b,c)}catch(e){Q(d);if(e!==e+0&&"longjmp"!==e)throw e;wf(1,0)}}function Ef(a,b,c,d){var e=Z();try{M.get(a)(b,c,d)}catch(f){Q(e);if(f!==f+0&&"longjmp"!==f)throw f;wf(1,0)}}
function Bf(a,b,c,d,e){var f=Z();try{return M.get(a)(b,c,d,e)}catch(h){Q(f);if(h!==h+0&&"longjmp"!==h)throw h;wf(1,0)}}function Af(a,b,c,d){var e=Z();try{return M.get(a)(b,c,d)}catch(f){Q(e);if(f!==f+0&&"longjmp"!==f)throw f;wf(1,0)}}function Ff(a,b,c,d,e){var f=Z();try{M.get(a)(b,c,d,e)}catch(h){Q(f);if(h!==h+0&&"longjmp"!==h)throw h;wf(1,0)}}function xf(a){var b=Z();try{return M.get(a)()}catch(c){Q(b);if(c!==c+0&&"longjmp"!==c)throw c;wf(1,0)}}
function Gf(a,b,c,d,e,f,h){var l=Z();try{M.get(a)(b,c,d,e,f,h)}catch(m){Q(l);if(m!==m+0&&"longjmp"!==m)throw m;wf(1,0)}}function Hf(a,b,c,d,e,f,h,l,m,q){var p=Z();try{M.get(a)(b,c,d,e,f,h,l,m,q)}catch(r){Q(p);if(r!==r+0&&"longjmp"!==r)throw r;wf(1,0)}}E.addRunDependency=nb;E.removeRunDependency=ob;E.FS_createPath=Rc;E.FS_createDataFile=Tc;E.FS_createPreloadedFile=Wc;E.FS_createLazyFile=Vc;E.FS_createDevice=fb;E.FS_unlink=Kc;E.PThread=O;E.PThread=O;E.wasmMemory=n;E.ExitStatus=Hb;var Kf;
function Hb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}mb=function Lf(){Kf||Mf();Kf||(mb=Lf)};
function Mf(){function a(){if(!Kf&&(Kf=!0,E.calledRun=!0,!Ia)){cb();G||(qc=!1,ib(ab));ma(E);if(E.onRuntimeInitialized)E.onRuntimeInitialized();if(!G){if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;){var b=E.postRun.shift();bb.unshift(b)}ib(bb)}}}if(!(0<kb))if(G)ma(E),cb(),postMessage({cmd:"loaded"});else{if(!G){if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)jb();ib(Za)}0<kb||(E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){E.setStatus("")},
1);a()},1)):a())}}E.run=Mf;function Gb(a){Ja=a;if(G)throw postMessage({cmd:"exitProcess",returnCode:a}),new Hb(a);if(!Kb()){O.Ee();if(E.onExit)E.onExit(a);Ia=!0}va(a,new Hb(a))}if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.pop()();G&&(noExitRuntime=!1,O.Zd());Mf();


  return BlinkCardWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkCardWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkCardWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkCardWasmSDK"] = BlinkCardWasmSDK;
