
var BlinkCardWasmSDK = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkCardWasmSDK = {})  {

/*

 Copyright 2019 The Emscripten Authors
 SPDX-License-Identifier: MIT

 Copyright 2013 The Emscripten Authors
 SPDX-License-Identifier: MIT

 This file gets implicatly injected as a `--post-js` file when
 emcc is run with `--emrun`
*/
var g;g||(g=typeof BlinkCardWasmSDK !== 'undefined' ? BlinkCardWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.Hb||(g.Hb=0);g.Hb++;
g.ENVIRONMENT_IS_PTHREAD||g.$ww||function(a){function b(m,n,r){var p=new XMLHttpRequest;p.open("GET",m,!0);p.responseType="arraybuffer";p.onprogress=function(q){var k=n;q.total&&(k=q.total);if(q.loaded){p.mc?g.hb[m].loaded=q.loaded:(p.mc=!0,g.hb||(g.hb={}),g.hb[m]={loaded:q.loaded,total:k});var t=k=q=0,x;for(x in g.hb){var z=g.hb[x];q+=z.total;k+=z.loaded;t++}q=Math.ceil(q*g.Hb/t);g.setStatus&&g.setStatus("Downloading data... ("+k+"/"+q+")")}else!g.hb&&g.setStatus&&g.setStatus("Downloading data...")};
p.onerror=function(){throw Error("NetworkError for: "+m);};p.onload=function(){if(200==p.status||304==p.status||206==p.status||0==p.status&&p.response)r(p.response);else throw Error(p.statusText+" : "+p.responseURL);};p.send(null)}function c(m){console.error("package error:",m)}function d(){function m(q,k,t){this.start=q;this.end=k;this.audio=t}function n(q){if(!q)throw"Loading data file failed."+Error().stack;if(q.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
q=new Uint8Array(q);m.prototype.qc=q;q=a.files;for(var k=0;k<q.length;++k)m.prototype.Qb[q[k].filename].onload();g.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E0/sdk-blinkcard-in-browser/resources/advanced/BlinkCardWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={Qb:{},open:function(q,k){this.name=k;this.Qb[k]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.qc.subarray(this.start,this.end))},finish:function(q){g.FS_createDataFile(this.name,
null,q,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.Qb[this.name]=null}};for(var r=a.files,p=0;p<r.length;++p)(new m(r[p].start,r[p].end,r[p].audio||0)).open("GET",r[p].filename);g.addRunDependency("datafile_/opt/jenkins/jenkinsData/E0/sdk-blinkcard-in-browser/resources/advanced/BlinkCardWasmSDK.data");g.dc||(g.dc={});g.dc["/opt/jenkins/jenkinsData/E0/sdk-blinkcard-in-browser/resources/advanced/BlinkCardWasmSDK.data"]={ed:!1};l?(n(l),l=null):h=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,u("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkCardWasmSDK.data",
""):"BlinkCardWasmSDK.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/microblink/Model_1118d9d674e23996f70c6416b2bf5a6ce6ef24a6ad2c92f0ddd1e198e5f05305.strop",start:0,end:20418},{filename:"/microblink/Model_349432d66ef2b216155673b634f7d5c47795bed35719b954f726b5f0856740f3.strop",start:20418,end:72804},{filename:"/microblink/Model_3b11c3ffacbbf390b932fb9a7024f1a0016f66281ea8c790f8b5903374ad89c2.strop",
start:72804,end:361584},{filename:"/microblink/Model_47a2b4fe3503a673b9119db53c50711a9f9ae9b3ada515a534fdbd8013623d43.strop",start:361584,end:727840},{filename:"/microblink/Model_830c13896f96c1cb6d5cad725f44e6aae470f8672d640d20b3272ed4bb839699.strop",start:727840,end:1006114},{filename:"/microblink/Model_9f6734be0f5c1e4f3c6c621f4a72db8241feaf7c8705dc68a9cc07a7b634ee85.strop",start:1006114,end:1103684},{filename:"/microblink/Model_b9263312a9b623d1a3b75b643ccdcbc36aae52c278d721443468147c50e44583.strop",
start:1103684,end:1391892},{filename:"/microblink/Model_cc1fab8df49d9a21de6c7b76ccf0dac40b17fcfb7073cc520eca073cbf8e33e9.strop",start:1391892,end:1395830},{filename:"/microblink/Model_eb41c55c618d8cb10ed79e1d8c051e1ec0d513e13812aec06da6844111cf8b3f.strop",start:1395830,end:1454072},{filename:"/microblink/Model_ee471cb6e7b68287281f761c2b05221043b9b059c6cea9132523ab2981f9a7ca.strop",start:1454072,end:3878584},{filename:"/microblink/Model_f132d1bd7614b1274fafb8a41ec6c047b84b2a43654ae2da5ddd78a2765601c6.strop",
start:3878584,end:4771700},{filename:"/microblink/Model_face34941a89e9b0e84fc8a0268e766ce845507e1bd924a6bed8825d75c5d243.strop",start:4771700,end:4829878}],remote_package_size:4829878});g.onAbort=function(a){u("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){u("Stacktrace: "+b.stack)}};
if("object"==typeof window){g.arguments=window.location.search.substr(1).trim().split("&");for(let a=0;a<g.arguments.length;++a)g.arguments[a]=decodeURI(g.arguments[a]);g.arguments[0]||(g.arguments=[])}var ca=Object.assign({},g),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="",ja,ka,la;
if(fa||ha)ha?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),_scriptDir&&(ia=_scriptDir),ia=0!==ia.indexOf("blob:")?ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=g.print||console.log.bind(console),u=g.printErr||console.warn.bind(console);Object.assign(g,ca);ca=null;g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);var na;g.wasmBinary&&(na=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!1;"object"!=typeof WebAssembly&&oa("no native wasm support detected");
var pa,qa=!1,ra,sa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function v(a,b){return a?ta(w,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var C,w,va,D,E,I,wa,xa;function ya(){var a=pa.buffer;g.HEAP8=C=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=D=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=wa=new Float32Array(a);g.HEAPF64=xa=new Float64Array(a)}var za,Aa=[],Ba=[],Ca=[],Da=[],Ea=!1,Fa=0;
function Ga(){var a=g.preRun.shift();Aa.unshift(a)}var Ha=0,Ia=null,Ja=null;function Ka(){Ha++;g.monitorRunDependencies&&g.monitorRunDependencies(Ha)}function La(){Ha--;g.monitorRunDependencies&&g.monitorRunDependencies(Ha);if(0==Ha&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja)){var a=Ja;Ja=null;a()}}function oa(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";u(a);qa=!0;ra=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
function Ma(a){return a.startsWith("data:application/octet-stream;base64,")}var Na;Na="BlinkCardWasmSDK.wasm";if(!Ma(Na)){var Oa=Na;Na=g.locateFile?g.locateFile(Oa,ia):ia+Oa}function Pa(a){try{if(a==Na&&na)return new Uint8Array(na);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){oa(b)}}
function Qa(a){return na||!fa&&!ha||"function"!=typeof fetch?Promise.resolve().then(function(){return Pa(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Pa(a)})}function Ta(a,b,c){return Qa(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){u("failed to asynchronously prepare wasm: "+d);oa(d)})}
function Ua(a,b){var c=Na;return na||"function"!=typeof WebAssembly.instantiateStreaming||Ma(c)||"function"!=typeof fetch?Ta(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){u("wasm streaming compile failed: "+e);u("falling back to ArrayBuffer instantiation");return Ta(c,a,b)})})}
var J,K,Va={186357:a=>{a=v(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},186493:(a,b,c,d)=>{a=v(a);b=v(b);c=v(c);d=v(d);throw Error(a+b+c+d);},186709:(a,b)=>{a=v(a);b=v(b);throw Error(a+b);},186819:a=>{throw Error(v(a));},186862:()=>{throw Error("Unable to perform that operation while recognizer is in use!");}};function Wa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Xa(a){for(;0<a.length;)a.shift()(g)}function Ya(a){this.Ka=a-24;this.Vc=function(b){I[this.Ka+4>>2]=b};this.Sc=function(b){I[this.Ka+8>>2]=b};this.Tc=function(){E[this.Ka>>2]=0};this.Rc=function(){C[this.Ka+12>>0]=0};this.Uc=function(){C[this.Ka+13>>0]=0};this.Dc=function(b,c){this.Qc();this.Vc(b);this.Sc(c);this.Tc();this.Rc();this.Uc()};this.Qc=function(){I[this.Ka+16>>2]=0}}
var Za=0,$a=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$a(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ab=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},bb=
a=>{if("/"===a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function cb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>oa("randomDevice")}
function db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$a(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function eb(a,b){var c=Array(ua(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}var fb=[];function gb(a,b){fb[a]={input:[],Oa:[],lb:b};hb(a,ib)}
var ib={open:function(a){var b=fb[a.node.qb];if(!b)throw new M(43);a.Sa=b;a.seekable=!1},close:function(a){a.Sa.lb.wb(a.Sa)},wb:function(a){a.Sa.lb.wb(a.Sa)},read:function(a,b,c,d){if(!a.Sa||!a.Sa.lb.ac)throw new M(60);for(var e=0,f=0;f<d;f++){try{var h=a.Sa.lb.ac(a.Sa)}catch(l){throw new M(29);}if(void 0===h&&0===e)throw new M(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Sa||!a.Sa.lb.Mb)throw new M(60);try{for(var e=0;e<d;e++)a.Sa.lb.Mb(a.Sa,
b[c+e])}catch(f){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},jb={ac:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=eb(b,!0)}return a.input.shift()},Mb:function(a,b){null===b||10===b?(ma(ta(a.Oa,0)),a.Oa=[]):0!=b&&a.Oa.push(b)},wb:function(a){a.Oa&&0<a.Oa.length&&(ma(ta(a.Oa,0)),a.Oa=[])}},
kb={Mb:function(a,b){null===b||10===b?(u(ta(a.Oa,0)),a.Oa=[]):0!=b&&a.Oa.push(b)},wb:function(a){a.Oa&&0<a.Oa.length&&(u(ta(a.Oa,0)),a.Oa=[])}};function lb(a){a=65536*Math.ceil(a/65536);var b=mb(65536,a);b?(w.fill(0,b,b+a),a=b):a=0;return a}
var O={Ya:null,$a:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);O.Ya||(O.Ya={dir:{node:{Xa:O.Ia.Xa,Ra:O.Ia.Ra,mb:O.Ia.mb,Ab:O.Ia.Ab,ic:O.Ia.ic,Gb:O.Ia.Gb,jc:O.Ia.jc,hc:O.Ia.hc,Db:O.Ia.Db},stream:{eb:O.Ja.eb}},file:{node:{Xa:O.Ia.Xa,Ra:O.Ia.Ra},stream:{eb:O.Ja.eb,read:O.Ja.read,write:O.Ja.write,Sb:O.Ja.Sb,nb:O.Ja.nb,Bb:O.Ja.Bb}},link:{node:{Xa:O.Ia.Xa,Ra:O.Ia.Ra,rb:O.Ia.rb},stream:{}},Vb:{node:{Xa:O.Ia.Xa,Ra:O.Ia.Ra},
stream:nb}});c=ob(a,b,c,d);16384===(c.mode&61440)?(c.Ia=O.Ya.dir.node,c.Ja=O.Ya.dir.stream,c.Ha={}):32768===(c.mode&61440)?(c.Ia=O.Ya.file.node,c.Ja=O.Ya.file.stream,c.Ma=0,c.Ha=null):40960===(c.mode&61440)?(c.Ia=O.Ya.link.node,c.Ja=O.Ya.link.stream):8192===(c.mode&61440)&&(c.Ia=O.Ya.Vb.node,c.Ja=O.Ya.Vb.stream);c.timestamp=Date.now();a&&(a.Ha[b]=c,a.timestamp=c.timestamp);return c},fd:function(a){return a.Ha?a.Ha.subarray?a.Ha.subarray(0,a.Ma):new Uint8Array(a.Ha):new Uint8Array(0)},Yb:function(a,
b){var c=a.Ha?a.Ha.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ha,a.Ha=new Uint8Array(b),0<a.Ma&&a.Ha.set(c.subarray(0,a.Ma),0))},Nc:function(a,b){if(a.Ma!=b)if(0==b)a.Ha=null,a.Ma=0;else{var c=a.Ha;a.Ha=new Uint8Array(b);c&&a.Ha.set(c.subarray(0,Math.min(b,a.Ma)));a.Ma=b}},Ia:{Xa:function(a){var b={};b.uc=8192===(a.mode&61440)?a.id:1;b.Jb=a.id;b.mode=a.mode;b.Jc=1;b.uid=0;b.Bc=0;b.qb=a.qb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.Ma:40960===
(a.mode&61440)?a.link.length:0;b.nc=new Date(a.timestamp);b.Ic=new Date(a.timestamp);b.sc=new Date(a.timestamp);b.oc=4096;b.pc=Math.ceil(b.size/b.oc);return b},Ra:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Nc(a,b.size)},mb:function(){throw pb[44];},Ab:function(a,b,c,d){return O.createNode(a,b,c,d)},ic:function(a,b,c){if(16384===(a.mode&61440)){try{var d=qb(b,c)}catch(f){}if(d)for(var e in d.Ha)throw new M(55);}delete a.parent.Ha[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Ha[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Gb:function(a,b){delete a.Ha[b];a.timestamp=Date.now()},jc:function(a,b){var c=qb(a,b),d;for(d in c.Ha)throw new M(55);delete a.Ha[b];a.timestamp=Date.now()},hc:function(a){var b=[".",".."],c;for(c in a.Ha)a.Ha.hasOwnProperty(c)&&b.push(c);return b},Db:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},rb:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},Ja:{read:function(a,
b,c,d,e){var f=a.node.Ha;if(e>=a.node.Ma)return 0;a=Math.min(a.node.Ma-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===C.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ha||a.Ha.subarray)){if(f)return a.Ha=b.subarray(c,c+d),a.Ma=d;if(0===a.Ma&&0===e)return a.Ha=b.slice(c,c+d),a.Ma=d;if(e+d<=a.Ma)return a.Ha.set(b.subarray(c,c+d),e),d}O.Yb(a,e+d);if(a.Ha.subarray&&b.subarray)a.Ha.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.Ha[e+f]=b[c+f];a.Ma=Math.max(a.Ma,e+d);return d},eb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ma);if(0>b)throw new M(28);return b},Sb:function(a,b,c){O.Yb(a.node,b+c);a.node.Ma=Math.max(a.node.Ma,b+c)},nb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.Ha;if(e&2||a.buffer!==C.buffer){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=lb(b);if(!b)throw new M(48);
C.set(a,b)}else c=!1,b=a.byteOffset;return{Ka:b,Tb:c}},Bb:function(a,b,c,d){O.Ja.write(a,b,0,d,c,!1);return 0}}};function rb(a,b,c){var d="al "+a;ka(a,e=>{e||oa('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&La(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ka(d)}
var sb=null,tb={},ub=[],vb=1,wb=null,xb=!0,M=null,pb={},P=(a,b={})=>{a=db(a);if(!a)return{path:"",node:null};b=Object.assign({$b:!0,Ob:0},b);if(8<b.Ob)throw new M(32);a=a.split("/").filter(h=>!!h);for(var c=sb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=qb(c,a[e]);d=L(d+"/"+a[e]);c.ob&&(!f||f&&b.$b)&&(c=c.ob.root);if(!f||b.vb)for(f=0;40960===(c.mode&61440);)if(c=yb(d),d=db(ab(d),c),c=P(d,{Ob:b.Ob+1}).node,40<f++)throw new M(32);}return{path:d,node:c}},zb=a=>{for(var b;;){if(a===
a.parent)return a=a.$a.cc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ab=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%wb.length},qb=(a,b)=>{var c;if(c=(c=Bb(a,"x"))?c:a.Ia.mb?0:2)throw new M(c,a);for(c=wb[Ab(a.id,b)];c;c=c.kb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ia.mb(a,b)},ob=(a,b,c,d)=>{a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.kb=wb[b];return wb[b]=a},Db={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Eb=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Bb=(a,b)=>{if(xb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Fb=(a,b)=>{try{return qb(a,b),20}catch(c){}return Bb(a,"wx")},Gb=()=>{for(var a=0;4096>=a;a++)if(!ub[a])return a;throw new M(33);},Ib=a=>{Hb||(Hb=function(){this.Cb={}},Hb.prototype={},Object.defineProperties(Hb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=
c}},flags:{get:function(){return this.Cb.flags},set:function(c){this.Cb.flags=c}},position:{get:function(){return this.Cb.position},set:function(c){this.Cb.position=c}}}));a=Object.assign(new Hb,a);var b=Gb();a.cb=b;return ub[b]=a},nb={open:a=>{a.Ja=tb[a.node.qb].Ja;a.Ja.open&&a.Ja.open(a)},eb:()=>{throw new M(70);}},hb=(a,b)=>{tb[a]={Ja:b}},Jb=(a,b)=>{var c="/"===b,d=!b;if(c&&sb)throw new M(10);if(!c&&!d){var e=P(b,{$b:!1});b=e.path;e=e.node;if(e.ob)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);
}b={type:a,jd:{},cc:b,Hc:[]};a=a.$a(b);a.$a=b;b.root=a;c?sb=a:e&&(e.ob=b,e.$a&&e.$a.Hc.push(b))},Q=(a,b,c)=>{var d=P(a,{parent:!0}).node;a=bb(a);if(!a||"."===a||".."===a)throw new M(28);var e=Fb(d,a);if(e)throw new M(e);if(!d.Ia.Ab)throw new M(63);return d.Ia.Ab(d,a,b,c)},Kb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return Q(a,b|8192,c)},Lb=(a,b)=>{if(!db(a))throw new M(44);var c=P(b,{parent:!0}).node;if(!c)throw new M(44);b=bb(b);var d=Fb(c,b);if(d)throw new M(d);if(!c.Ia.Db)throw new M(63);c.Ia.Db(c,
b,a)},Mb=a=>{var b=P(a,{parent:!0}).node;if(!b)throw new M(44);var c=bb(a);a=qb(b,c);a:{try{var d=qb(b,c)}catch(f){d=f.Ta;break a}var e=Bb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new M(d);if(!b.Ia.Gb)throw new M(63);if(a.ob)throw new M(10);b.Ia.Gb(b,c);b=Ab(a.parent.id,a.name);if(wb[b]===a)wb[b]=a.kb;else for(b=wb[b];b;){if(b.kb===a){b.kb=a.kb;break}b=b.kb}},yb=a=>{a=P(a).node;if(!a)throw new M(44);if(!a.Ia.rb)throw new M(28);return db(zb(a.parent),a.Ia.rb(a))},Nb=(a,b)=>{a=P(a,{vb:!b}).node;
if(!a)throw new M(44);if(!a.Ia.Xa)throw new M(63);return a.Ia.Xa(a)},Ob=a=>Nb(a,!0),Pb=(a,b)=>{a="string"==typeof a?P(a,{vb:!0}).node:a;if(!a.Ia.Ra)throw new M(63);a.Ia.Ra(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Rb=(a,b,c)=>{if(""===a)throw new M(44);if("string"==typeof b){var d=Db[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=L(a);try{e=P(a,{vb:!(b&131072)}).node}catch(f){}}d=
!1;if(b&64)if(e){if(b&128)throw new M(20);}else e=Q(a,c,0),d=!0;if(!e)throw new M(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new M(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Eb(b)||b&512)?31:Bb(e,Eb(b)):44))throw new M(c);if(b&512&&!d){c=e;c="string"==typeof c?P(c,{vb:!0}).node:c;if(!c.Ia.Ra)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(d=Bb(c,"w"))throw new M(d);c.Ia.Ra(c,{size:0,
timestamp:Date.now()})}b&=-131713;e=Ib({node:e,path:zb(e),flags:b,seekable:!0,position:0,Ja:e.Ja,dd:[],error:!1});e.Ja.open&&e.Ja.open(e);!g.logReadFiles||b&1||(Qb||(Qb={}),a in Qb||(Qb[a]=1));return e},Sb=a=>{if(null===a.cb)throw new M(8);a.Ib&&(a.Ib=null);try{a.Ja.close&&a.Ja.close(a)}catch(b){throw b;}finally{ub[a.cb]=null}a.cb=null},Tb=(a,b,c)=>{if(null===a.cb)throw new M(8);if(!a.seekable||!a.Ja.eb)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.Ja.eb(a,b,c);a.dd=[]},Ub=(a,b,
c,d,e,f)=>{if(0>d||0>e)throw new M(28);if(null===a.cb)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.Ja.write)throw new M(28);a.seekable&&a.flags&1024&&Tb(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new M(70);b=a.Ja.write(a,b,c,d,e,f);h||(a.position+=b);return b},Vb=()=>{M||(M=function(a,b){this.name="ErrnoError";this.node=b;this.Pc=function(c){this.Ta=c};this.Pc(a);this.message="FS error"},M.prototype=
Error(),M.prototype.constructor=M,[44].forEach(a=>{pb[a]=new M(a);pb[a].stack="<generic error, no stack>"}))},Wb,Xb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Yb=(a,b)=>{a="string"==typeof a?a:zb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a+"/"+c);try{Q(d,16895,0)}catch(e){}a=d}}return d},Zb=(a,b,c,d)=>{a=L(("string"==typeof a?a:zb(a))+"/"+b);c=Xb(c,d);return Q(a,(void 0!==c?c:438)&4095|32768,0)},$b=(a,b,c,d,e,f)=>{var h=b;a&&(a="string"==typeof a?a:zb(a),h=b?L(a+
"/"+b):a);a=Xb(d,e);h=Q(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Pb(h,a|146);b=Rb(h,577);Ub(b,c,0,c.length,0,f);Sb(b);Pb(h,a)}return h},R=(a,b,c,d)=>{a=L(("string"==typeof a?a:zb(a))+"/"+b);b=Xb(!!c,!!d);R.bc||(R.bc=64);var e=R.bc++<<8|0;hb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,h,l,m)=>{for(var n=0,r=0;r<m;r++){try{var p=c()}catch(q){throw new M(29);}if(void 0===
p&&0===n)throw new M(6);if(null===p||void 0===p)break;n++;h[l+r]=p}n&&(f.node.timestamp=Date.now());return n},write:(f,h,l,m)=>{for(var n=0;n<m;n++)try{d(h[l+n])}catch(r){throw new M(29);}m&&(f.node.timestamp=Date.now());return n}});return Kb(a,b,e)},ac=a=>{if(!(a.Ec||a.Fc||a.link||a.Ha)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(ja)try{a.Ha=eb(ja(a.url),!0),a.Ma=a.Ha.length}catch(b){throw new M(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},bc=(a,b,c,d,e)=>{function f(){this.Lb=!1;this.ub=[]}function h(p,q,k,t,x){p=p.node.Ha;if(x>=p.length)return 0;t=Math.min(p.length-x,t);if(p.slice)for(var z=0;z<t;z++)q[k+z]=p[x+z];else for(z=0;z<t;z++)q[k+z]=p.get(x+z);return t}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var q=p%this.Wb;return this.xb(p/this.Wb|0)[q]}};f.prototype.Oc=function(p){this.xb=
p};f.prototype.Ub=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),k,t=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var x=1048576;t||(x=q);var z=this;z.Oc(F=>{var G=F*x,y=(F+1)*x-1;y=Math.min(y,q-1);if("undefined"==typeof z.ub[F]){var N=z.ub;if(G>y)throw Error("invalid range ("+
G+", "+y+") or no bytes requested!");if(y>q-1)throw Error("only "+q+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);q!==x&&B.setRequestHeader("Range","bytes="+G+"-"+y);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);G=void 0!==B.response?new Uint8Array(B.response||[]):eb(B.responseText||"",
!0);N[F]=G}if("undefined"==typeof z.ub[F])throw Error("doXHR failed!");return z.ub[F]});if(p||!q)x=q=1,x=q=this.xb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.lc=q;this.kc=x;this.Lb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.Lb||this.Ub();return this.lc}},
Wb:{get:function(){this.Lb||this.Ub();return this.kc}}});var m=void 0}else m=c,l=void 0;var n=Zb(a,b,d,e);l?n.Ha=l:m&&(n.Ha=null,n.url=m);Object.defineProperties(n,{Ma:{get:function(){return this.Ha.length}}});var r={};Object.keys(n.Ja).forEach(p=>{var q=n.Ja[p];r[p]=function(){ac(n);return q.apply(null,arguments)}});r.read=(p,q,k,t,x)=>{ac(n);return h(p,q,k,t,x)};r.nb=(p,q,k)=>{ac(n);var t=lb(q);if(!t)throw new M(48);h(p,C,t,q,k);return{Ka:t,Tb:!0}};n.Ja=r;return n},dc=(a,b,c,d,e,f,h,l,m,n)=>{function r(k){function t(x){n&&
n();l||$b(a,b,x,d,e,m);f&&f();La(q)}cc.gd(k,p,t,()=>{h&&h();La(q)})||t(k)}var p=b?db(L(a+"/"+b)):a,q="cp "+p;Ka(q);"string"==typeof c?rb(c,k=>r(k),h):r(c)},ec={},Hb,Qb;function fc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":gc(a).path;if(0==b.length){if(!c)throw new M(44);return a}return L(a+"/"+b)}
function hc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&L(b)!==L(zb(f.node)))return-54;throw f;}E[c>>2]=d.uc;E[c+8>>2]=d.Jb;E[c+12>>2]=d.mode;I[c+16>>2]=d.Jc;E[c+20>>2]=d.uid;E[c+24>>2]=d.Bc;E[c+28>>2]=d.qb;K=[d.size>>>0,(J=d.size,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+40>>2]=K[0];E[c+44>>2]=K[1];E[c+48>>2]=4096;E[c+52>>2]=d.pc;a=d.nc.getTime();b=d.Ic.getTime();var e=d.sc.getTime();K=[Math.floor(a/1E3)>>>0,(J=
Math.floor(a/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+56>>2]=K[0];E[c+60>>2]=K[1];I[c+64>>2]=a%1E3*1E3;K=[Math.floor(b/1E3)>>>0,(J=Math.floor(b/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+72>>2]=K[0];E[c+76>>2]=K[1];I[c+80>>2]=b%1E3*1E3;K=[Math.floor(e/1E3)>>>0,(J=Math.floor(e/1E3),1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+88>>2]=K[0];E[c+92>>2]=K[1];I[c+96>>2]=e%1E3*1E3;K=[d.Jb>>>0,(J=d.Jb,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[c+104>>2]=K[0];E[c+108>>2]=K[1];return 0}var ic=void 0;function gc(a){a=ub[a];if(!a)throw new M(8);return a}var jc={};function kc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function lc(a){return this.fromWireType(E[a>>2])}var mc={},nc={},oc={};function pc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function qc(a,b){a=pc(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function rc(a){var b=Error,c=qc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var sc=void 0;function tc(a){throw new sc(a);}
function uc(a,b,c){function d(l){l=c(l);l.length!==a.length&&tc("Mismatched type converter count");for(var m=0;m<a.length;++m)vc(a[m],l[m])}a.forEach(function(l){oc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach((l,m)=>{nc.hasOwnProperty(l)?e[m]=nc[l]:(f.push(l),mc.hasOwnProperty(l)||(mc[l]=[]),mc[l].push(()=>{e[m]=nc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function wc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var xc=void 0;function S(a){for(var b="";w[a];)b+=xc[w[a++]];return b}var yc=void 0;function T(a){throw new yc(a);}
function vc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(nc.hasOwnProperty(a)){if(c.Cc)return;T("Cannot register type '"+d+"' twice")}nc[a]=b;delete oc[a];mc.hasOwnProperty(a)&&(b=mc[a],delete mc[a],b.forEach(e=>e()))}function zc(a){T(a.Aa.Na.La.name+" instance already deleted")}var Ac=!1;function Bc(){}
function Cc(a){--a.count.value;0===a.count.value&&(a.Qa?a.Ua.ab(a.Qa):a.Na.La.ab(a.Ka))}function Dc(a,b,c){if(b===c)return a;if(void 0===c.Va)return null;a=Dc(a,b,c.Va);return null===a?null:c.vc(a)}var Ec={},Fc=[];function Gc(){for(;Fc.length;){var a=Fc.pop();a.Aa.ib=!1;a["delete"]()}}var Hc=void 0,Ic={};function Jc(a,b){for(void 0===b&&T("ptr should not be undefined");a.Va;)b=a.sb(b),a=a.Va;return Ic[b]}
function Kc(a,b){b.Na&&b.Ka||tc("makeClassHandle requires ptr and ptrType");!!b.Ua!==!!b.Qa&&tc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Lc(Object.create(a,{Aa:{value:b}}))}function Lc(a){if("undefined"===typeof FinalizationRegistry)return Lc=b=>b,a;Ac=new FinalizationRegistry(b=>{Cc(b.Aa)});Lc=b=>{var c=b.Aa;c.Qa&&Ac.register(b,{Aa:c},b);return b};Bc=b=>{Ac.unregister(b)};return Lc(a)}function Mc(){}
function Nc(a,b,c){if(void 0===a[b].Pa){var d=a[b];a[b]=function(){a[b].Pa.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Pa+")!");return a[b].Pa[arguments.length].apply(this,arguments)};a[b].Pa=[];a[b].Pa[d.tb]=d}}
function Oc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Pa&&void 0!==g[a].Pa[c])&&T("Cannot register public name '"+a+"' twice"),Nc(g,a,a),g.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Pa[c]=b):(g[a]=b,void 0!==c&&(g[a].hd=c))}function Pc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.jb=c;this.ab=d;this.Va=e;this.xc=f;this.sb=h;this.vc=l;this.Lc=[]}
function Qc(a,b,c){for(;b!==c;)b.sb||T("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.sb(a),b=b.Va;return a}function Rc(a,b){if(null===b)return this.Kb&&T("null is not a valid "+this.name),0;b.Aa||T('Cannot pass "'+Sc(b)+'" as a '+this.name);b.Aa.Ka||T("Cannot pass deleted object as a pointer of type "+this.name);return Qc(b.Aa.Ka,b.Aa.Na.La,this.La)}
function Tc(a,b){if(null===b){this.Kb&&T("null is not a valid "+this.name);if(this.zb){var c=this.Nb();null!==a&&a.push(this.ab,c);return c}return 0}b.Aa||T('Cannot pass "'+Sc(b)+'" as a '+this.name);b.Aa.Ka||T("Cannot pass deleted object as a pointer of type "+this.name);!this.yb&&b.Aa.Na.yb&&T("Cannot convert argument of type "+(b.Aa.Ua?b.Aa.Ua.name:b.Aa.Na.name)+" to parameter type "+this.name);c=Qc(b.Aa.Ka,b.Aa.Na.La,this.La);if(this.zb)switch(void 0===b.Aa.Qa&&T("Passing raw pointer to smart pointer is illegal"),
this.Zc){case 0:b.Aa.Ua===this?c=b.Aa.Qa:T("Cannot convert argument of type "+(b.Aa.Ua?b.Aa.Ua.name:b.Aa.Na.name)+" to parameter type "+this.name);break;case 1:c=b.Aa.Qa;break;case 2:if(b.Aa.Ua===this)c=b.Aa.Qa;else{var d=b.clone();c=this.Mc(c,U(function(){d["delete"]()}));null!==a&&a.push(this.ab,c)}break;default:T("Unsupporting sharing policy")}return c}
function Uc(a,b){if(null===b)return this.Kb&&T("null is not a valid "+this.name),0;b.Aa||T('Cannot pass "'+Sc(b)+'" as a '+this.name);b.Aa.Ka||T("Cannot pass deleted object as a pointer of type "+this.name);b.Aa.Na.yb&&T("Cannot convert argument of type "+b.Aa.Na.name+" to parameter type "+this.name);return Qc(b.Aa.Ka,b.Aa.Na.La,this.La)}
function Vc(a,b,c,d){this.name=a;this.La=b;this.Kb=c;this.yb=d;this.zb=!1;this.ab=this.Mc=this.Nb=this.fc=this.Zc=this.Kc=void 0;void 0!==b.Va?this.toWireType=Tc:(this.toWireType=d?Rc:Uc,this.Wa=null)}function Wc(a,b,c){g.hasOwnProperty(a)||tc("Replacing nonexistant public symbol");void 0!==g[a].Pa&&void 0!==c?g[a].Pa[c]=b:(g[a]=b,g[a].tb=c)}var Xc=[];function V(a){var b=Xc[a];b||(a>=Xc.length&&(Xc.length=a+1),Xc[a]=b=za.get(a));return b}
function Yc(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=V(b).apply(null,c);return d}}function W(a,b){a=S(a);var c=a.includes("j")?Yc(a,b):V(b);"function"!=typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var Zc=void 0;function $c(a){a=ad(a);var b=S(a);bd(a);return b}
function cd(a,b){function c(f){e[f]||nc[f]||(oc[f]?oc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Zc(a+": "+d.map($c).join([", "]));}function dd(a,b){for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c}
function ed(a,b,c,d,e){var f=b.length;2>f&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Wa){l=!0;break}var m="void"!==b[0].name,n=f-2,r=Array(n),p=[],q=[];return function(){arguments.length!==n&&T("function "+a+" called with "+arguments.length+" arguments, expected "+n+" args!");q.length=0;p.length=h?2:1;p[0]=e;if(h){var k=b[1].toWireType(q,this);p[1]=k}for(var t=0;t<n;++t)r[t]=
b[t+2].toWireType(q,arguments[t]),p.push(r[t]);t=d.apply(null,p);if(l)kc(q);else for(var x=h?1:2;x<b.length;x++){var z=1===x?k:r[x-2];null!==b[x].Wa&&b[x].Wa(z)}k=m?b[0].fromWireType(t):void 0;return k}}var fd=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function gd(a){4<a&&0===--Y[a].Pb&&(Y[a]=void 0,fd.push(a))}
var hd=a=>{a||T("Cannot use deleted val. handle = "+a);return Y[a].value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=fd.length?fd.pop():Y.length;Y[b]={Pb:1,value:a};return b}};function Sc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function jd(a,b){switch(b){case 2:return function(c){return this.fromWireType(wa[c>>2])};case 3:return function(c){return this.fromWireType(xa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function kd(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return w[d]};case 1:return c?function(d){return va[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var ld="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function md(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&ld)return ld.decode(w.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=va[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function nd(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)va[b>>1]=a.charCodeAt(e),b+=2;va[b>>1]=0;return b-d}function od(a){return 2*a.length}
function pd(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function qd(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function rd(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function sd(a,b){var c=nc[a];void 0===c&&T(b+" has unknown type "+$c(a));return c}var td={};function ud(a){var b=td[a];return void 0===b?S(a):b}var vd=[];
function wd(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function xd(a){var b=vd.length;vd.push(a);return b}function yd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=sd(I[b+4*d>>2],"parameter "+d);return c}var zd=[];function Ad(a){var b=Array(a+1);return function(c,d,e){b[0]=c;for(var f=0;f<a;++f){var h=sd(I[d+4*f>>2],"parameter "+f);b[f+1]=h.readValueFromPointer(e);e+=h.argPackAdvance}c=new (c.bind.apply(c,b));return U(c)}}var Bd={};function Cd(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Dd=[0,31,60,91,121,152,182,213,244,274,305,335],Ed=[0,31,59,90,120,151,181,212,243,273,304,334];function Fd(a){return(Cd(a.getFullYear())?Dd:Ed)[a.getMonth()]+a.getDate()-1}function Gd(a){var b=ua(a)+1,c=Hd(b);c&&A(a,C,c,b);return c}var Id=[],Jd={};function Z(a,b){I[a>>2]=b;I[a+4>>2]=b/4294967296|0}var Kd;
function Ld(a,b,c,d,e){function f(){var B=0,X=0;y.response&&F&&0===I[a+12>>2]&&(X=y.response.byteLength);0<X&&(B=Hd(X),w.set(new Uint8Array(y.response),B));I[a+12>>2]=B;Z(a+16,X);Z(a+24,0);(B=y.response?y.response.byteLength:0)&&Z(a+32,B);D[a+40>>1]=y.readyState;D[a+42>>1]=y.status;y.statusText&&A(y.statusText,w,a+44,64)}var h=I[a+8>>2];if(h){var l=v(h),m=a+112,n=v(m);n||(n="GET");var r=I[m+52>>2],p=I[m+56>>2],q=!!I[m+60>>2],k=I[m+68>>2],t=I[m+72>>2];h=I[m+76>>2];var x=I[m+80>>2],z=I[m+84>>2];m=I[m+
88>>2];var F=!!(r&1),G=!!(r&2);r=!!(r&64);k=k?v(k):void 0;t=t?v(t):void 0;var y=new XMLHttpRequest;y.withCredentials=q;y.open(n,l,!r,k,t);r||(y.timeout=p);y.ld=l;y.responseType="arraybuffer";x&&(l=v(x),y.overrideMimeType(l));if(h)for(;;){n=I[h>>2];if(!n)break;l=I[h+4>>2];if(!l)break;h+=8;n=v(n);l=v(l);y.setRequestHeader(n,l)}var N=I[a+0>>2];Jd[N]=y;h=z&&m?w.slice(z,z+m):null;y.onload=B=>{N in Jd&&(f(),200<=y.status&&300>y.status?b&&b(a,y,B):c&&c(a,y,B))};y.onerror=B=>{N in Jd&&(f(),c&&c(a,y,B))};
y.ontimeout=B=>{N in Jd&&c&&c(a,y,B)};y.onprogress=B=>{if(N in Jd){var X=F&&G&&y.response?y.response.byteLength:0,H=0;0<X&&F&&G&&(H=Hd(X),w.set(new Uint8Array(y.response),H));I[a+12>>2]=H;Z(a+16,X);Z(a+24,B.loaded-X);Z(a+32,B.total);D[a+40>>1]=y.readyState;3<=y.readyState&&0===y.status&&0<B.loaded&&(y.status=200);D[a+42>>1]=y.status;y.statusText&&A(y.statusText,w,a+44,64);d&&d(a,y,B);H&&bd(H)}};y.onreadystatechange=B=>{N in Jd?(D[a+40>>1]=y.readyState,2<=y.readyState&&(D[a+42>>1]=y.status),e&&e(a,
y,B)):--Fa};try{y.send(h)}catch(B){c&&c(a,y,B)}}else c(a,0,"no url specified!")}function Md(a){a instanceof Wa||"unwind"==a||ea(1,a)}function Nd(a){ra=a;if(!(noExitRuntime||0<Fa)){Od();Xa(Ca);Wb=!1;Pd(0);for(var b=0;b<ub.length;b++){var c=ub[b];c&&Sb(c)}Ea=!0}ra=a;if(!(noExitRuntime||0<Fa)){if(g.onExit)g.onExit(a);qa=!0}ea(a,new Wa(a))}
function Qd(a,b,c,d){var e=Kd;if(e){var f=I[a+112+64>>2];f||(f=I[a+8>>2]);var h=v(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=()=>{D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);c(a,0,h)};l.onerror=m=>{D[a+40>>1]=4;D[a+42>>1]=413;A("Payload Too Large",w,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Rd(a,b,c){var d=Kd;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=v(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=h=>{if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Hd(l);w.set(new Uint8Array(h),m);I[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);b(a,0,h)}else D[a+40>>1]=4,D[a+42>>1]=404,A("Not Found",w,a+44,64),c(a,0,"no data")};f.onerror=h=>{D[a+40>>1]=4;D[a+42>>1]=404;A("Not Found",
w,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Sd(a,b,c){var d=Kd;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=v(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=h=>{h=h.target.result;I[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);D[a+40>>1]=4;D[a+42>>1]=200;A("OK",w,a+44,64);b(a,0,h)};f.onerror=h=>{D[a+40>>1]=4;D[a+42>>1]=404;A("Not Found",w,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Td={};
function Ud(){if(!Vd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Td)void 0===Td[b]?delete a[b]:a[b]=Td[b];var c=[];for(b in a)c.push(b+"="+a[b]);Vd=c}return Vd}var Vd;function Wd(a,b){Wd.ec||(Wd.ec=cb());for(var c=0;c<b;c++)C[a+c>>0]=Wd.ec();return 0}
var Xd=[31,29,31,30,31,30,31,31,30,31,30,31],Yd=[31,28,31,30,31,30,31,31,30,31,30,31];
function Zd(a,b,c,d){function e(k,t,x){for(k="number"==typeof k?k.toString():k||"";k.length<t;)k=x[0]+k;return k}function f(k,t){return e(k,t,"0")}function h(k,t){function x(F){return 0>F?-1:0<F?1:0}var z;0===(z=x(k.getFullYear()-t.getFullYear()))&&0===(z=x(k.getMonth()-t.getMonth()))&&(z=x(k.getDate()-t.getDate()));return z}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var t=k.fb;for(k=new Date((new Date(k.gb+1900,0,1)).getTime());0<t;){var x=k.getMonth(),z=(Cd(k.getFullYear())?Xd:Yd)[x];if(t>z-k.getDate())t-=z-k.getDate()+1,k.setDate(1),11>x?k.setMonth(x+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+t);break}}x=new Date(k.getFullYear()+1,0,4);t=l(new Date(k.getFullYear(),
0,4));x=l(x);return 0>=h(t,k)?0>=h(x,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=E[d+40>>2];d={bd:E[d>>2],ad:E[d+4>>2],Eb:E[d+8>>2],Rb:E[d+12>>2],Fb:E[d+16>>2],gb:E[d+20>>2],Za:E[d+24>>2],fb:E[d+28>>2],kd:E[d+32>>2],$c:E[d+36>>2],cd:n?v(n):""};c=v(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),q="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return p[k.Za].substring(0,3)},"%A":function(k){return p[k.Za]},"%b":function(k){return q[k.Fb].substring(0,3)},"%B":function(k){return q[k.Fb]},
"%C":function(k){return f((k.gb+1900)/100|0,2)},"%d":function(k){return f(k.Rb,2)},"%e":function(k){return e(k.Rb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Eb,2)},"%I":function(k){k=k.Eb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var t=0,x=0;x<=k.Fb-1;t+=(Cd(k.gb+1900)?Xd:Yd)[x++]);return f(k.Rb+t,3)},"%m":function(k){return f(k.Fb+1,2)},"%M":function(k){return f(k.ad,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=
k.Eb&&12>k.Eb?"AM":"PM"},"%S":function(k){return f(k.bd,2)},"%t":function(){return"\t"},"%u":function(k){return k.Za||7},"%U":function(k){return f(Math.floor((k.fb+7-k.Za)/7),2)},"%V":function(k){var t=Math.floor((k.fb+7-(k.Za+6)%7)/7);2>=(k.Za+371-k.fb-2)%7&&t++;if(t)53==t&&(x=(k.Za+371-k.fb)%7,4==x||3==x&&Cd(k.gb)||(t=1));else{t=52;var x=(k.Za+7-k.fb-1)%7;(4==x||5==x&&Cd(k.gb%400-1))&&t++}return f(t,2)},"%w":function(k){return k.Za},"%W":function(k){return f(Math.floor((k.fb+7-(k.Za+6)%7)/7),2)},
"%y":function(k){return(k.gb+1900).toString().substring(2)},"%Y":function(k){return k.gb+1900},"%z":function(k){k=k.$c;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.cd},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(r in n)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),n[r](d)));c=c.replace(/\0\0/g,"%");r=eb(c,!1);if(r.length>b)return 0;C.set(r,a);return r.length-1}
function Cb(a,b,c,d){a||(a=this);this.parent=a;this.$a=a.$a;this.ob=null;this.id=vb++;this.name=b;this.mode=c;this.Ia={};this.Ja={};this.qb=d}Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Fc:{get:function(){return 16384===(this.mode&61440)}},Ec:{get:function(){return 8192===(this.mode&61440)}}});Vb();
wb=Array(4096);Jb(O,"/");Q("/tmp",16895,0);Q("/home",16895,0);Q("/home/web_user",16895,0);(()=>{Q("/dev",16895,0);hb(259,{read:()=>0,write:(b,c,d,e)=>e});Kb("/dev/null",259);gb(1280,jb);gb(1536,kb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);var a=cb();R("/dev","random",a);R("/dev","urandom",a);Q("/dev/shm",16895,0);Q("/dev/shm/tmp",16895,0)})();
(()=>{Q("/proc",16895,0);var a=Q("/proc/self",16895,0);Q("/proc/self/fd",16895,0);Jb({$a:()=>{var b=ob(a,"fd",16895,73);b.Ia={mb:(c,d)=>{var e=ub[+d];if(!e)throw new M(8);c={parent:null,$a:{cc:"fake"},Ia:{rb:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var cc;g.FS_createPath=Yb;g.FS_createDataFile=$b;g.FS_createPreloadedFile=dc;g.FS_unlink=Mb;g.FS_createLazyFile=bc;g.FS_createDevice=R;sc=g.InternalError=rc("InternalError");for(var $d=Array(256),ae=0;256>ae;++ae)$d[ae]=String.fromCharCode(ae);
xc=$d;yc=g.BindingError=rc("BindingError");Mc.prototype.isAliasOf=function(a){if(!(this instanceof Mc&&a instanceof Mc))return!1;var b=this.Aa.Na.La,c=this.Aa.Ka,d=a.Aa.Na.La;for(a=a.Aa.Ka;b.Va;)c=b.sb(c),b=b.Va;for(;d.Va;)a=d.sb(a),d=d.Va;return b===d&&c===a};
Mc.prototype.clone=function(){this.Aa.Ka||zc(this);if(this.Aa.pb)return this.Aa.count.value+=1,this;var a=Lc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Aa;a=a(c.call(b,d,{Aa:{value:{count:e.count,ib:e.ib,pb:e.pb,Ka:e.Ka,Na:e.Na,Qa:e.Qa,Ua:e.Ua}}}));a.Aa.count.value+=1;a.Aa.ib=!1;return a};Mc.prototype["delete"]=function(){this.Aa.Ka||zc(this);this.Aa.ib&&!this.Aa.pb&&T("Object already scheduled for deletion");Bc(this);Cc(this.Aa);this.Aa.pb||(this.Aa.Qa=void 0,this.Aa.Ka=void 0)};
Mc.prototype.isDeleted=function(){return!this.Aa.Ka};Mc.prototype.deleteLater=function(){this.Aa.Ka||zc(this);this.Aa.ib&&!this.Aa.pb&&T("Object already scheduled for deletion");Fc.push(this);1===Fc.length&&Hc&&Hc(Gc);this.Aa.ib=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(Ic).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Ic)Ic.hasOwnProperty(b)&&a.push(Ic[b]);return a};g.flushPendingDeletes=Gc;g.setDelayFunction=function(a){Hc=a;Fc.length&&Hc&&Hc(Gc)};
Vc.prototype.yc=function(a){this.fc&&(a=this.fc(a));return a};Vc.prototype.Xb=function(a){this.ab&&this.ab(a)};Vc.prototype.argPackAdvance=8;Vc.prototype.readValueFromPointer=lc;Vc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Vc.prototype.fromWireType=function(a){function b(){return this.zb?Kc(this.La.jb,{Na:this.Kc,Ka:c,Ua:this,Qa:a}):Kc(this.La.jb,{Na:this,Ka:a})}var c=this.yc(a);if(!c)return this.Xb(a),null;var d=Jc(this.La,c);if(void 0!==d){if(0===d.Aa.count.value)return d.Aa.Ka=c,d.Aa.Qa=a,d.clone();d=d.clone();this.Xb(a);return d}d=this.La.xc(c);d=Ec[d];if(!d)return b.call(this);d=this.yb?d.rc:d.pointerType;var e=Dc(c,this.La,d.La);return null===e?b.call(this):this.zb?Kc(d.La.jb,{Na:d,Ka:e,Ua:this,Qa:a}):Kc(d.La.jb,
{Na:d,Ka:e})};Zc=g.UnboundTypeError=rc("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Ka("library_fetch_init");
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=d=>b(d)})(a=>{Kd=a;La("library_fetch_init")},()=>{Kd=!1;La("library_fetch_init")});
var fe={la:function(a,b,c){(new Ya(a)).Dc(b,c);Za++;throw a;},X:function(a,b){try{var c=gc(a);return hc(Nb,c.path,b)}catch(d){if("undefined"==typeof ec||"ErrnoError"!==d.name)throw d;return-d.Ta}},V:function(a,b,c,d){try{b=v(b);var e=d&256;b=fc(a,b,d&4096);return hc(e?Ob:Nb,b,c)}catch(f){if("undefined"==typeof ec||"ErrnoError"!==f.name)throw f;return-f.Ta}},Y:function(a,b,c,d){ic=d;try{b=v(b);b=fc(a,b);if(d){ic+=4;var e=E[ic-4>>2]}else e=0;return Rb(b,c,e).cb}catch(f){if("undefined"==typeof ec||"ErrnoError"!==
f.name)throw f;return-f.Ta}},W:function(a,b){try{return a=v(a),hc(Nb,a,b)}catch(c){if("undefined"==typeof ec||"ErrnoError"!==c.name)throw c;return-c.Ta}},f:function(a){var b=jc[a];delete jc[a];var c=b.Nb,d=b.ab,e=b.Zb,f=e.map(h=>h.Ac).concat(e.map(h=>h.Xc));uc([a],f,h=>{var l={};e.forEach((m,n)=>{var r=h[n],p=m.xb,q=m.zc,k=h[n+e.length],t=m.Wc,x=m.Yc;l[m.wc]={read:z=>r.fromWireType(p(q,z)),write:(z,F)=>{var G=[];t(x,z,k.toWireType(G,F));kc(G)}}});return[{name:b.name,fromWireType:function(m){var n=
{},r;for(r in l)n[r]=l[r].read(m);d(m);return n},toWireType:function(m,n){for(var r in l)if(!(r in n))throw new TypeError('Missing field:  "'+r+'"');var p=c();for(r in l)l[r].write(p,n[r]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:lc,Wa:d}]})},I:function(){},ea:function(a,b,c,d,e){var f=wc(c);b=S(b);vc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=C;else if(2===c)l=va;
else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},Wa:null})},s:function(a,b,c,d,e,f,h,l,m,n,r,p,q){r=S(r);f=W(e,f);l&&(l=W(h,l));n&&(n=W(m,n));q=W(p,q);var k=pc(r);Oc(k,function(){cd("Cannot construct "+r+" due to unbound types",[d])});uc([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var x=t.La;var z=x.jb}else z=Mc.prototype;t=qc(k,function(){if(Object.getPrototypeOf(this)!==F)throw new yc("Use 'new' to construct "+r);if(void 0===G.bb)throw new yc(r+
" has no accessible constructor");var N=G.bb[arguments.length];if(void 0===N)throw new yc("Tried to invoke ctor of "+r+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(G.bb).toString()+") parameters instead!");return N.apply(this,arguments)});var F=Object.create(z,{constructor:{value:t}});t.prototype=F;var G=new Pc(r,t,F,q,x,f,l,n);x=new Vc(r,G,!0,!1);z=new Vc(r+"*",G,!1,!1);var y=new Vc(r+" const*",G,!1,!0);Ec[a]={pointerType:z,rc:y};Wc(k,t);return[x,z,y]})},z:function(a,
b,c,d,e,f){0<b||oa();var h=dd(b,c);e=W(d,e);uc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.La.bb&&(l.La.bb=[]);if(void 0!==l.La.bb[b-1])throw new yc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.La.bb[b-1]=()=>{cd("Cannot construct "+l.name+" due to unbound types",h)};uc([],h,function(n){n.splice(1,0,null);l.La.bb[b-
1]=ed(m,n,null,e,f);return[]});return[]})},h:function(a,b,c,d,e,f,h,l){var m=dd(c,d);b=S(b);f=W(e,f);uc([],[a],function(n){function r(){cd("Cannot call "+p+" due to unbound types",m)}n=n[0];var p=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.La.Lc.push(b);var q=n.La.jb,k=q[b];void 0===k||void 0===k.Pa&&k.className!==n.name&&k.tb===c-2?(r.tb=c-2,r.className=n.name,q[b]=r):(Nc(q,b,p),q[b].Pa[c-2]=r);uc([],m,function(t){t=ed(p,t,n,f,h);void 0===q[b].Pa?(t.tb=c-2,q[b]=t):q[b].Pa[c-
2]=t;return[]});return[]})},da:function(a,b){b=S(b);vc(a,{name:b,fromWireType:function(c){var d=hd(c);gd(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:lc,Wa:null})},F:function(a,b,c){c=wc(c);b=S(b);vc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:jd(b,c),Wa:null})},w:function(a,b,c,d,e,f){var h=dd(b,c);a=S(a);e=W(d,e);Oc(a,function(){cd("Cannot call "+a+" due to unbound types",h)},b-
1);uc([],h,function(l){Wc(a,ed(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},g:function(a,b,c,d,e){b=S(b);-1===e&&(e=4294967295);e=wc(c);var f=l=>l;if(0===d){var h=32-8*c;f=l=>l<<h>>>h}c=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};vc(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:kd(b,e,0!==d),Wa:null})},d:function(a,b,c){function d(f){f>>=2;var h=I;return new e(h.buffer,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,
Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);vc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Cc:!0})},G:function(a,b){b=S(b);var c="std::string"===b;vc(a,{name:b,fromWireType:function(d){var e=I[d>>2],f=d+4;if(c)for(var h=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==w[m]){h=v(h,m-h);if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(w[f+l]);n=n.join("")}bd(d);return n},toWireType:function(d,e){e instanceof
ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||T("Cannot pass non-string to std::string");var h=c&&f?ua(e):e.length;var l=Hd(4+h+1),m=l+4;I[l>>2]=h;if(c&&f)A(e,w,m,h+1);else if(f)for(f=0;f<h;++f){var n=e.charCodeAt(f);255<n&&(bd(m),T("String has UTF-16 code units that do not fit in 8 bits"));w[m+f]=n}else for(f=0;f<h;++f)w[m+f]=e[f];null!==d&&d.push(bd,l);return l},argPackAdvance:8,readValueFromPointer:lc,
Wa:function(d){bd(d)}})},v:function(a,b,c){c=S(c);if(2===b){var d=md;var e=nd;var f=od;var h=()=>D;var l=1}else 4===b&&(d=pd,e=qd,f=rd,h=()=>I,l=2);vc(a,{name:c,fromWireType:function(m){for(var n=I[m>>2],r=h(),p,q=m+4,k=0;k<=n;++k){var t=m+4+k*b;if(k==n||0==r[t>>l])q=d(q,t-q),void 0===p?p=q:(p+=String.fromCharCode(0),p+=q),q=t+b}bd(m);return p},toWireType:function(m,n){"string"!=typeof n&&T("Cannot pass non-string to C++ string type "+c);var r=f(n),p=Hd(4+r+b);I[p>>2]=r>>l;e(n,p+4,r+b);null!==m&&
m.push(bd,p);return p},argPackAdvance:8,readValueFromPointer:lc,Wa:function(m){bd(m)}})},e:function(a,b,c,d,e,f){jc[a]={name:S(b),Nb:W(c,d),ab:W(e,f),Zb:[]}},c:function(a,b,c,d,e,f,h,l,m,n){jc[a].Zb.push({wc:S(b),Ac:c,xb:W(d,e),zc:f,Xc:h,Wc:W(l,m),Yc:n})},fa:function(a,b){b=S(b);vc(a,{Gc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ga:function(a){var b=Jd[a];b&&(delete Jd[a],0<b.readyState&&4>b.readyState&&b.abort())},_:function(){return!0},M:function(){throw Infinity;
},k:function(a,b,c){a=hd(a);b=sd(b,"emval::as");var d=[],e=U(d);I[c>>2]=e;return b.toWireType(d,a)},o:function(a,b,c,d){a=vd[a];b=hd(b);c=ud(c);a(b,c,null,d)},b:gd,p:function(a){if(0===a)return U(wd());a=ud(a);return U(wd()[a])},n:function(a,b){var c=yd(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(h){return h.name}).join("_")+"$";var e=zd[b];if(void 0!==e)return e;var f=Array(a-1);e=xd((h,l,m,n)=>{for(var r=0,p=0;p<a-1;++p)f[p]=c[p+1].readValueFromPointer(n+r),r+=c[p+1].argPackAdvance;h=h[l].apply(h,
f);for(p=0;p<a-1;++p)c[p+1].tc&&c[p+1].tc(f[p]);if(!d.Gc)return d.toWireType(m,h)});return zd[b]=e},y:function(a,b){a=hd(a);b=hd(b);return U(a[b])},t:function(a){4<a&&(Y[a].Pb+=1)},r:function(a,b,c,d){a=hd(a);var e=Bd[b];e||(e=Ad(b),Bd[b]=e);return e(a,c,d)},A:function(){return U([])},m:function(a){return U(ud(a))},x:function(){return U({})},j:function(a){var b=hd(a);kc(b);gd(a)},l:function(a,b,c){a=hd(a);b=hd(b);c=hd(c);a[b]=c},i:function(a,b){a=sd(a,"_emval_take_value");a=a.readValueFromPointer(b);
return U(a)},aa:function(a,b){a=new Date(1E3*(I[a>>2]+4294967296*E[a+4>>2]));E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();E[b+28>>2]=Fd(a)|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},ba:function(a){var b=new Date(E[a+
20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(f,e);0>c?E[a+32>>2]=Number(e!=f&&h==d):0<c!=(h==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=Fd(b)|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();E[a+20>>2]=
b.getYear();return b.getTime()/1E3|0},R:function(a,b,c,d,e,f,h){try{var l=gc(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new M(2);if(1===(l.flags&2097155))throw new M(2);if(!l.Ja.nb)throw new M(43);var m=l.Ja.nb(l,a,e,b,c);var n=m.Ka;E[f>>2]=m.Tb;I[h>>2]=n;return 0}catch(r){if("undefined"==typeof ec||"ErrnoError"!==r.name)throw r;return-r.Ta}},S:function(a,b,c,d,e,f){try{var h=gc(e);if(c&2){if(32768!==(h.node.mode&61440))throw new M(43);d&2||h.Ja.Bb&&h.Ja.Bb(h,w.slice(a,a+b),f,b,d)}}catch(l){if("undefined"==
typeof ec||"ErrnoError"!==l.name)throw l;return-l.Ta}},ca:function(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset();I[a>>2]=60*Math.max(e,l);E[b>>2]=Number(e!=l);a=d(f);b=d(h);a=Gd(a);b=Gd(b);l<e?(I[c>>2]=a,I[c+4>>2]=b):(I[c>>2]=b,I[c+4>>2]=a)},a:function(){oa("")},q:function(a,b,c){Id.length=0;var d;for(c>>=2;d=w[b++];)c+=105!=d&c,Id.push(105==
d?E[c]:xa[c++>>1]),++c;return Va[a].apply(null,Id)},$:function(){return Date.now()},Q:function(){return 2147483648},u:()=>performance.now(),ia:function(){return!ha},Z:function(a,b,c){w.copyWithin(a,b,b+c)},P:function(a){var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=Math,e=d.min;var f=Math.max(a,b+2097152/c);f+=(65536-f%65536)%65536;a:{var h=pa.buffer;try{pa.grow(e.call(d,2147483648,f)-h.byteLength+65535>>>16);ya();var l=1;break a}catch(m){}l=void 0}if(l)return!0}return!1},
ha:function(a,b,c,d,e){function f(H){if(z)H();else if(!Ea&&!qa)try{if(H(),!(noExitRuntime||0<Fa))try{Nd(ra)}catch(Ra){Md(Ra)}}catch(Ra){Md(Ra)}}Fa+=1;var h=a+112,l=v(h),m=I[h+36>>2],n=I[h+40>>2],r=I[h+44>>2],p=I[h+48>>2],q=I[h+52>>2],k=!!(q&4),t=!!(q&32),x=!!(q&16),z=!!(q&64),F=H=>{--Fa;f(()=>{m?V(m)(H):b&&b(H)})},G=H=>{f(()=>{r?V(r)(H):d&&d(H)})},y=H=>{--Fa;f(()=>{n?V(n)(H):c&&c(H)})},N=H=>{f(()=>{p?V(p)(H):e&&e(H)})};q=H=>{Ld(H,F,y,G,N)};var B=(H,Ra)=>{Qd(H,Ra.response,Sa=>{--Fa;f(()=>{m?V(m)(Sa):
b&&b(Sa)})},Sa=>{--Fa;f(()=>{m?V(m)(Sa):b&&b(Sa)})})},X=H=>{Ld(H,B,y,G,N)};if("EM_IDB_STORE"===l)l=I[h+84>>2],Qd(a,w.slice(l,l+I[h+88>>2]),F,y);else if("EM_IDB_DELETE"===l)Sd(a,F,y);else if(x){if(t)return 0;Ld(a,k?B:F,y,G,N)}else Rd(a,F,t?y:k?X:q);return a},T:function(a,b){var c=0;Ud().forEach(function(d,e){var f=b+c;e=I[a+4*e>>2]=f;for(f=0;f<d.length;++f)C[e++>>0]=d.charCodeAt(f);C[e>>0]=0;c+=d.length+1});return 0},U:function(a,b){var c=Ud();I[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+
1});I[b>>2]=d;return 0},ma:Nd,E:function(a){try{var b=gc(a);Sb(b);return 0}catch(c){if("undefined"==typeof ec||"ErrnoError"!==c.name)throw c;return c.Ta}},D:function(a,b,c,d){try{a:{var e=gc(a);a=b;for(var f,h=b=0;h<c;h++){var l=I[a>>2],m=I[a+4>>2];a+=8;var n=e,r=l,p=m,q=f,k=C;if(0>p||0>q)throw new M(28);if(null===n.cb)throw new M(8);if(1===(n.flags&2097155))throw new M(8);if(16384===(n.node.mode&61440))throw new M(31);if(!n.Ja.read)throw new M(28);var t="undefined"!=typeof q;if(!t)q=n.position;else if(!n.seekable)throw new M(70);
var x=n.Ja.read(n,k,r,p,q);t||(n.position+=x);var z=x;if(0>z){var F=-1;break a}b+=z;if(z<m)break;"undefined"!==typeof f&&(f+=z)}F=b}I[d>>2]=F;return 0}catch(G){if("undefined"==typeof ec||"ErrnoError"!==G.name)throw G;return G.Ta}},H:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=gc(a);Tb(f,b,d);K=[f.position>>>0,(J=f.position,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>
0:0)];E[e>>2]=K[0];E[e+4>>2]=K[1];f.Ib&&0===b&&0===d&&(f.Ib=null);return 0}catch(h){if("undefined"==typeof ec||"ErrnoError"!==h.name)throw h;return h.Ta}},C:function(a,b,c,d){try{a:{var e=gc(a);a=b;for(var f,h=b=0;h<c;h++){var l=I[a>>2],m=I[a+4>>2];a+=8;var n=Ub(e,C,l,m,f);if(0>n){var r=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}r=b}I[d>>2]=r;return 0}catch(p){if("undefined"==typeof ec||"ErrnoError"!==p.name)throw p;return p.Ta}},ja:function(){var a=stackTrace(),b=ua(a)+1,c=Hd(b);A(a,w,c,b);return c},
N:Wd,J:be,B:ce,K:de,L:ee,ka:Zd,O:function(a,b,c,d){return Zd(a,b,c,d)}};(function(){function a(c){c=c.exports;g.asm=c;pa=g.asm.na;ya();za=g.asm.ra;Ba.unshift(g.asm.oa);La("wasm-instantiate");return c}var b={a:fe};Ka("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){u("Module.instantiateWasm callback failed with error: "+c),ba(c)}Ua(b,function(c){a(c.instance)}).catch(ba);return{}})();function bd(){return(bd=g.asm.pa).apply(null,arguments)}
function Hd(){return(Hd=g.asm.qa).apply(null,arguments)}var Pd=g._fflush=function(){return(Pd=g._fflush=g.asm.sa).apply(null,arguments)},ad=g.___getTypeName=function(){return(ad=g.___getTypeName=g.asm.ta).apply(null,arguments)};g.__embind_initialize_bindings=function(){return(g.__embind_initialize_bindings=g.asm.ua).apply(null,arguments)};function Od(){return(Od=g.asm.va).apply(null,arguments)}function mb(){return(mb=g.asm.wa).apply(null,arguments)}
function ge(){return(ge=g.asm.xa).apply(null,arguments)}function he(){return(he=g.asm.ya).apply(null,arguments)}function ie(){return(ie=g.asm.za).apply(null,arguments)}g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Ba).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ca).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Da).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ea).apply(null,arguments)};
g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Fa).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Ga).apply(null,arguments)};g.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=1024;g.___start_em_js=185484;g.___stop_em_js=186357;function ce(a,b){var c=he();try{V(a)(b)}catch(d){ie(c);if(d!==d+0)throw d;ge(1,0)}}function ee(a,b,c,d){var e=he();try{V(a)(b,c,d)}catch(f){ie(e);if(f!==f+0)throw f;ge(1,0)}}
function de(a,b,c){var d=he();try{V(a)(b,c)}catch(e){ie(d);if(e!==e+0)throw e;ge(1,0)}}function be(a,b,c,d){var e=he();try{return V(a)(b,c,d)}catch(f){ie(e);if(f!==f+0)throw f;ge(1,0)}}g.addRunDependency=Ka;g.removeRunDependency=La;g.FS_createPath=Yb;g.FS_createDataFile=$b;g.FS_createPreloadedFile=dc;g.FS_createLazyFile=bc;g.FS_createDevice=R;g.FS_unlink=Mb;var je;Ja=function ke(){je||le();je||(Ja=ke)};
function le(){function a(){if(!je&&(je=!0,g.calledRun=!0,!qa)){g.noFSInit||Wb||(Wb=!0,Vb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?R("/dev","stdin",g.stdin):Lb("/dev/tty","/dev/stdin"),g.stdout?R("/dev","stdout",null,g.stdout):Lb("/dev/tty","/dev/stdout"),g.stderr?R("/dev","stderr",null,g.stderr):Lb("/dev/tty1","/dev/stderr"),Rb("/dev/stdin",0),Rb("/dev/stdout",1),Rb("/dev/stderr",1));xb=!1;Xa(Ba);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Da.unshift(b)}Xa(Da)}}if(!(0<Ha)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ga();Xa(Aa);0<Ha||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();le();
if("object"==typeof window&&("undefined"==typeof ENVIRONMENT_IS_PTHREAD||!ENVIRONMENT_IS_PTHREAD)){var me=()=>{var a=0,b=!1,c=m=>{var n=new XMLHttpRequest;n.open("POST","stdio.html",!1);n.send(m);try{window.close()}catch(r){}},d=m=>{var n=new XMLHttpRequest;++a;n.onreadystatechange=()=>{4==n.readyState&&0==--a&&b&&c("^exit^"+ra)};n.open("POST","stdio.html",!0);n.send(m)};if(-1!=document.URL.search("localhost")||-1!=document.URL.search(":6931/")){var e=1,f=ma,h=u;Ca.unshift(()=>{0==a?c("^exit^"+ra):
b=!0});ma=m=>{d("^out^"+e++ +"^"+encodeURIComponent(m));f(m)};u=m=>{d("^err^"+e++ +"^"+encodeURIComponent(m));h(m)};var l=()=>{try{d("^pageload^")}catch(m){setTimeout(l,50)}};l()}};"undefined"!=typeof document&&me()};


  return BlinkCardWasmSDK.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkCardWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkCardWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkCardWasmSDK"] = BlinkCardWasmSDK;
