
var BlinkCardWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkCardWasmSDK) {
  BlinkCardWasmSDK = BlinkCardWasmSDK || {};


var g;g||(g=typeof BlinkCardWasmSDK !== 'undefined' ? BlinkCardWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.Ib||(g.Ib=0);g.Ib++;
(function(a){function b(m,p,n){var q=new XMLHttpRequest;q.open("GET",m,!0);q.responseType="arraybuffer";q.onprogress=function(v){var k=p;v.total&&(k=v.total);if(v.loaded){q.lc?g.fb[m].loaded=v.loaded:(q.lc=!0,g.fb||(g.fb={}),g.fb[m]={loaded:v.loaded,total:k});var u=k=v=0,x;for(x in g.fb){var y=g.fb[x];v+=y.total;k+=y.loaded;u++}v=Math.ceil(v*g.Ib/u);g.setStatus&&g.setStatus("Downloading data... ("+k+"/"+v+")")}else!g.fb&&g.setStatus&&g.setStatus("Downloading data...")};q.onerror=function(){throw Error("NetworkError for: "+
m);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)n(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function p(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);m.prototype.pc=v;v=a.files;for(var k=
0;k<v.length;++k)m.prototype.Rb[v[k].filename].onload();g.removeRunDependency("datafile_../../resources/advanced/BlinkCardWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={Rb:{},open:function(v,k){this.name=k;this.Rb[k]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.pc.subarray(this.start,this.end))},finish:function(v){g.FS_createDataFile(this.name,null,v,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.Rb[this.name]=null}};for(var n=
a.files,q=0;q<n.length;++q)(new m(n[q].start,n[q].end,n[q].audio||0)).open("GET",n[q].filename);g.addRunDependency("datafile_../../resources/advanced/BlinkCardWasmSDK.data");g.cc||(g.cc={});g.cc["../../resources/advanced/BlinkCardWasmSDK.data"]={$c:!1};l?(p(l),l=null):h=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,r("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkCardWasmSDK.data",""):"BlinkCardWasmSDK.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?
d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/microblink/Model_9ddda5959c7694e413899b6723956d42f8c89f80c1f673879440684bbb3b8dad.strop",start:0,end:288208},{filename:"/microblink/Model_349432d66ef2b216155673b634f7d5c47795bed35719b954f726b5f0856740f3.strop",start:288208,end:340562},{filename:"/microblink/Model_cc1fab8df49d9a21de6c7b76ccf0dac40b17fcfb7073cc520eca073cbf8e33e9.strop",start:340562,end:344500},{filename:"/microblink/Model_9dc0335b6b55322b592e8be0b7e57216af00e3badcf78a69aea2543e5ff2c0e3.strop",
start:344500,end:361398},{filename:"/microblink/Model_f1bfb0da115c7d247dd44b6082e53cddf830058e3cf1ef88161e77a42584fb31.strop",start:361398,end:381816},{filename:"/microblink/Model_d41e83baa5b06261e15e7baefad0bc6a145491b58130921d410d658e6d9c70bf.strop",start:381816,end:466522},{filename:"/microblink/Model_e10bce9a414a7da1191868196799db37f21a56d11e9619e8db91127cd1881238.strop",start:466522,end:1359602},{filename:"/microblink/Model_406f8d5d972cf76a9241b35abbe5758890353b9b7daa922f732c4151ff6a0d9c.strop",
start:1359602,end:1650650},{filename:"/microblink/templates.zzip",start:1650650,end:1786085}],remote_package_size:1786085,package_uuid:"7f0eea07-7994-45b9-b627-3198c251b530"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in g)g.hasOwnProperty(da)&&(ca[da]=g[da]);var ea="./this.program";function ha(a,b){throw b;}var ia="object"===typeof window,ja="function"===typeof importScripts,ka="",la,ma,na;
if(ia||ja)ja?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),_scriptDir&&(ka=_scriptDir),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ja&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=g.print||console.log.bind(console),r=g.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(g[da]=ca[da]);ca=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(ha=g.quit);var pa=0,qa;g.wasmBinary&&(qa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&t("no native wasm support detected");
var ra,sa=!1,ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?ua(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&C[c];)++c;c<<=1;if(32<c-a&&wa)return wa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ya[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ea(a){var b=va(a)+1,c=Fa(b);c&&B(a,F,c,b);return c}var Ga,F,A,ya,C,E,I,Ha,Ia;
function Ja(){var a=ra.buffer;Ga=a;g.HEAP8=F=new Int8Array(a);g.HEAP16=ya=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=C=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=Ha=new Float32Array(a);g.HEAPF64=Ia=new Float64Array(a)}var L,Ka=[],La=[],Ma=[];function Na(){var a=g.preRun.shift();Ka.unshift(a)}var Oa=0,Pa=null,Qa=null;function Ra(){Oa++;g.monitorRunDependencies&&g.monitorRunDependencies(Oa)}
function Sa(){Oa--;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);if(0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa)){var a=Qa;Qa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function t(a){if(g.onAbort)g.onAbort(a);a+="";r(a);sa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ua(){return Va.startsWith("data:application/octet-stream;base64,")}var Va;Va="BlinkCardWasmSDK.wasm";
if(!Ua()){var Wa=Va;Va=g.locateFile?g.locateFile(Wa,ka):ka+Wa}function Xa(){var a=Va;try{if(a==Va&&qa)return new Uint8Array(qa);if(na)return na(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}function Ya(){return qa||!ia&&!ja||"function"!==typeof fetch?Promise.resolve().then(function(){return Xa()}):fetch(Va,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Va+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}
var M,Za,$a={206105:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},206241:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},206457:function(a,b){a=z(a);b=z(b);throw Error(a+b);},206567:function(a,b){a=z(a);b=z(b);console.log(a+b)},206665:function(a){throw Error(z(a));},206708:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};
function ab(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ad;"number"===typeof c?void 0===b.Hb?L.get(c)():L.get(c)(b.Hb):c(void 0===b.Hb?null:b.Hb)}}}
function bb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);E[cb()>>2]=60*f;E[db()>>2]=Number(b!=e);c=a(c);d=a(d);c=Ea(c);d=Ea(d);e<b?(E[eb()>>2]=c,E[eb()+4>>2]=d):(E[eb()>>2]=d,E[eb()+4>>2]=c)}var fb;
function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function N(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";a=N(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){t("randomDevice")}}
function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var lb=[];function mb(a,b){lb[a]={input:[],Pa:[],jb:b};nb(a,ob)}
var ob={open:function(a){var b=lb[a.node.ob];if(!b)throw new O(43);a.Na=b;a.seekable=!1},close:function(a){a.Na.jb.flush(a.Na)},flush:function(a){a.Na.jb.flush(a.Na)},read:function(a,b,c,d){if(!a.Na||!a.Na.jb.$b)throw new O(60);for(var e=0,f=0;f<d;f++){try{var h=a.Na.jb.$b(a.Na)}catch(l){throw new O(29);}if(void 0===h&&0===e)throw new O(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Na||!a.Na.jb.Nb)throw new O(60);try{for(var e=
0;e<d;e++)a.Na.jb.Nb(a.Na,b[c+e])}catch(f){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},qb={$b:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=pb(b,!0)}return a.input.shift()},Nb:function(a,b){null===b||10===b?(oa(ua(a.Pa,0)),a.Pa=[]):0!=b&&a.Pa.push(b)},flush:function(a){a.Pa&&0<a.Pa.length&&
(oa(ua(a.Pa,0)),a.Pa=[])}},rb={Nb:function(a,b){null===b||10===b?(r(ua(a.Pa,0)),a.Pa=[]):0!=b&&a.Pa.push(b)},flush:function(a){a.Pa&&0<a.Pa.length&&(r(ua(a.Pa,0)),a.Pa=[])}};function sb(a){a=65536*Math.ceil(a/65536);var b=tb(65536,a);if(!b)return 0;A.fill(0,b,b+a);return b}
var P={Za:null,ab:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.Za||(P.Za={dir:{node:{Ya:P.Ia.Ya,Ta:P.Ia.Ta,lb:P.Ia.lb,yb:P.Ia.yb,hc:P.Ia.hc,Fb:P.Ia.Fb,ic:P.Ia.ic,fc:P.Ia.fc,Bb:P.Ia.Bb},stream:{eb:P.Ja.eb}},file:{node:{Ya:P.Ia.Ya,Ta:P.Ia.Ta},stream:{eb:P.Ja.eb,read:P.Ja.read,write:P.Ja.write,Sb:P.Ja.Sb,zb:P.Ja.zb,Ab:P.Ja.Ab}},link:{node:{Ya:P.Ia.Ya,Ta:P.Ia.Ta,pb:P.Ia.pb},stream:{}},Ub:{node:{Ya:P.Ia.Ya,Ta:P.Ia.Ta},
stream:ub}});c=vb(a,b,c,d);Q(c.mode)?(c.Ia=P.Za.dir.node,c.Ja=P.Za.dir.stream,c.Ha={}):32768===(c.mode&61440)?(c.Ia=P.Za.file.node,c.Ja=P.Za.file.stream,c.Ma=0,c.Ha=null):40960===(c.mode&61440)?(c.Ia=P.Za.link.node,c.Ja=P.Za.link.stream):8192===(c.mode&61440)&&(c.Ia=P.Za.Ub.node,c.Ja=P.Za.Ub.stream);c.timestamp=Date.now();a&&(a.Ha[b]=c,a.timestamp=c.timestamp);return c},bd:function(a){return a.Ha?a.Ha.subarray?a.Ha.subarray(0,a.Ma):new Uint8Array(a.Ha):new Uint8Array(0)},Xb:function(a,b){var c=a.Ha?
a.Ha.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ha,a.Ha=new Uint8Array(b),0<a.Ma&&a.Ha.set(c.subarray(0,a.Ma),0))},Oc:function(a,b){if(a.Ma!=b)if(0==b)a.Ha=null,a.Ma=0;else{var c=a.Ha;a.Ha=new Uint8Array(b);c&&a.Ha.set(c.subarray(0,Math.min(b,a.Ma)));a.Ma=b}},Ia:{Ya:function(a){var b={};b.sc=8192===(a.mode&61440)?a.id:1;b.Kb=a.id;b.mode=a.mode;b.Jc=1;b.uid=0;b.zc=0;b.ob=a.ob;b.size=Q(a.mode)?4096:32768===(a.mode&61440)?a.Ma:40960===(a.mode&61440)?a.link.length:
0;b.mc=new Date(a.timestamp);b.Ic=new Date(a.timestamp);b.rc=new Date(a.timestamp);b.nc=4096;b.oc=Math.ceil(b.size/b.nc);return b},Ta:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Oc(a,b.size)},lb:function(){throw wb[44];},yb:function(a,b,c,d){return P.createNode(a,b,c,d)},hc:function(a,b,c){if(Q(a.mode)){try{var d=xb(b,c)}catch(f){}if(d)for(var e in d.Ha)throw new O(55);}delete a.parent.Ha[a.name];a.parent.timestamp=Date.now();a.name=
c;b.Ha[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Fb:function(a,b){delete a.Ha[b];a.timestamp=Date.now()},ic:function(a,b){var c=xb(a,b),d;for(d in c.Ha)throw new O(55);delete a.Ha[b];a.timestamp=Date.now()},fc:function(a){var b=[".",".."],c;for(c in a.Ha)a.Ha.hasOwnProperty(c)&&b.push(c);return b},Bb:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},pb:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},Ja:{read:function(a,b,c,d,e){var f=a.node.Ha;if(e>=a.node.Ma)return 0;
a=Math.min(a.node.Ma-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===F.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ha||a.Ha.subarray)){if(f)return a.Ha=b.subarray(c,c+d),a.Ma=d;if(0===a.Ma&&0===e)return a.Ha=b.slice(c,c+d),a.Ma=d;if(e+d<=a.Ma)return a.Ha.set(b.subarray(c,c+d),e),d}P.Xb(a,e+d);if(a.Ha.subarray&&b.subarray)a.Ha.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ha[e+
f]=b[c+f];a.Ma=Math.max(a.Ma,e+d);return d},eb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ma);if(0>b)throw new O(28);return b},Sb:function(a,b,c){P.Xb(a.node,b+c);a.node.Ma=Math.max(a.node.Ma,b+c)},zb:function(a,b,c,d,e,f){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.Ha;if(f&2||a.buffer!==Ga){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=sb(c);if(!c)throw new O(48);F.set(a,
c)}else d=!1,c=a.byteOffset;return{La:c,Gb:d}},Ab:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.Ja.write(a,b,0,d,c,!1);return 0}}};function yb(a,b,c){var d="al "+a;ma(a,function(e){e||t('Assertion failed: Loading data file "'+(a+'" failed (no arrayBuffer).'));b(new Uint8Array(e));d&&Sa(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ra(d)}var zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,Fb={},O=null,wb={};
function R(a,b){a=kb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Zb:!0,Pb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Pb)throw new O(32);a=gb(a.split("/").filter(function(h){return!!h}),!1);var e=zb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=xb(e,a[d]);c=N(c+"/"+a[d]);e.mb&&(!f||f&&b.Zb)&&(e=e.mb.root);if(!f||b.ub)for(f=0;40960===(e.mode&61440);)if(e=Gb(c),c=kb(hb(c),e),e=R(c,{Pb:b.Pb}).node,40<f++)throw new O(32);}return{path:c,node:e}}
function Hb(a){for(var b;;){if(a===a.parent)return a=a.ab.bc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ib(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function xb(a,b){var c;if(c=(c=Jb(a,"x"))?c:a.Ia.lb?0:2)throw new O(c,a);for(c=Db[Ib(a.id,b)];c;c=c.ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ia.lb(a,b)}
function vb(a,b,c,d){a=new Kb(a,b,c,d);b=Ib(a.parent.id,a.name);a.ib=Db[b];return Db[b]=a}function Q(a){return 16384===(a&61440)}var Lb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Jb(a,b){if(Eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Nb(a,b){try{return xb(a,b),20}catch(c){}return Jb(a,"wx")}
function Ob(){var a=4096;for(var b=0;b<=a;b++)if(!Bb[b])return b;throw new O(33);}function Pb(a){Qb||(Qb=function(){},Qb.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new Qb,c;for(c in a)b[c]=a[c];a=b;b=Ob();a.$a=b;return Bb[b]=a}var ub={open:function(a){a.Ja=Ab[a.node.ob].Ja;a.Ja.open&&a.Ja.open(a)},eb:function(){throw new O(70);}};function nb(a,b){Ab[a]={Ja:b}}
function Rb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new O(10);if(!c&&!d){var e=R(b,{Zb:!1});b=e.path;e=e.node;if(e.mb)throw new O(10);if(!Q(e.mode))throw new O(54);}b={type:a,ed:{},bc:b,Hc:[]};a=a.ab(b);a.ab=b;b.root=a;c?zb=a:e&&(e.mb=b,e.ab&&e.ab.Hc.push(b))}function Sb(a,b,c){var d=R(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new O(28);var e=Nb(d,a);if(e)throw new O(e);if(!d.Ia.yb)throw new O(63);return d.Ia.yb(d,a,b,c)}function Tb(a){return Sb(a,16895,0)}
function Ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Sb(a,b|8192,c)}function Vb(a,b){if(!kb(a))throw new O(44);var c=R(b,{parent:!0}).node;if(!c)throw new O(44);b=ib(b);var d=Nb(c,b);if(d)throw new O(d);if(!c.Ia.Bb)throw new O(63);c.Ia.Bb(c,b,a)}
function Wb(a){var b=R(a,{parent:!0}).node,c=ib(a),d=xb(b,c);a:{try{var e=xb(b,c)}catch(h){e=h.Sa;break a}var f=Jb(b,"wx");e=f?f:Q(e.mode)?31:0}if(e)throw new O(e);if(!b.Ia.Fb)throw new O(63);if(d.mb)throw new O(10);try{Fb.willDeletePath&&Fb.willDeletePath(a)}catch(h){r("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Ia.Fb(b,c);b=Ib(d.parent.id,d.name);if(Db[b]===d)Db[b]=d.ib;else for(b=Db[b];b;){if(b.ib===d){b.ib=d.ib;break}b=b.ib}try{if(Fb.onDeletePath)Fb.onDeletePath(a)}catch(h){r("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Gb(a){a=R(a).node;if(!a)throw new O(44);if(!a.Ia.pb)throw new O(28);return kb(Hb(a.parent),a.Ia.pb(a))}function Xb(a,b){a="string"===typeof a?R(a,{ub:!0}).node:a;if(!a.Ia.Ta)throw new O(63);a.Ia.Ta(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Yb(a,b,c){if(""===a)throw new O(44);if("string"===typeof b){var d=Lb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=N(a);try{e=R(a,{ub:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new O(20);}else e=Sb(a,c,0),d=!0;if(!e)throw new O(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!Q(e.mode))throw new O(54);if(!d&&(c=e?40960===(e.mode&61440)?32:Q(e.mode)&&
("r"!==Mb(b)||b&512)?31:Jb(e,Mb(b)):44))throw new O(c);if(b&512){c=e;c="string"===typeof c?R(c,{ub:!0}).node:c;if(!c.Ia.Ta)throw new O(63);if(Q(c.mode))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(d=Jb(c,"w"))throw new O(d);c.Ia.Ta(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Pb({node:e,path:Hb(e),flags:b,seekable:!0,position:0,Ja:e.Ja,Zc:[],error:!1});e.Ja.open&&e.Ja.open(e);!g.logReadFiles||b&1||(Zb||(Zb={}),a in Zb||(Zb[a]=1,r("FS.trackingDelegate error on read file: "+a)));try{Fb.onOpenFile&&
(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),Fb.onOpenFile(a,c))}catch(f){r("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}return e}function $b(a){if(null===a.$a)throw new O(8);a.Jb&&(a.Jb=null);try{a.Ja.close&&a.Ja.close(a)}catch(b){throw b;}finally{Bb[a.$a]=null}a.$a=null}function ac(a,b,c){if(null===a.$a)throw new O(8);if(!a.seekable||!a.Ja.eb)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.Ja.eb(a,b,c);a.Zc=[]}
function bc(a,b,c,d,e,f){if(0>d||0>e)throw new O(28);if(null===a.$a)throw new O(8);if(0===(a.flags&2097155))throw new O(8);if(Q(a.node.mode))throw new O(31);if(!a.Ja.write)throw new O(28);a.seekable&&a.flags&1024&&ac(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new O(70);b=a.Ja.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&Fb.onWriteToFile)Fb.onWriteToFile(a.path)}catch(l){r("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function cc(){O||(O=function(a,b){this.node=b;this.Qc=function(c){this.Sa=c};this.Qc(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){wb[a]=new O(a);wb[a].stack="<generic error, no stack>"}))}var dc;function ec(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function fc(a,b){a="string"===typeof a?a:Hb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=N(a+"/"+c);try{Tb(d)}catch(e){}a=d}}return d}
function gc(a,b,c,d){a=N(("string"===typeof a?a:Hb(a))+"/"+b);c=ec(c,d);return Sb(a,(void 0!==c?c:438)&4095|32768,0)}function hc(a,b,c,d,e,f){a=b?N(("string"===typeof a?a:Hb(a))+"/"+b):a;d=ec(d,e);e=Sb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Xb(e,d|146);a=Yb(e,577);bc(a,c,0,c.length,0,f);$b(a);Xb(e,d)}return e}
function ic(a,b,c,d){a=N(("string"===typeof a?a:Hb(a))+"/"+b);b=ec(!!c,!!d);ic.ac||(ic.ac=64);var e=ic.ac++<<8|0;nb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var p=0,n=0;n<m;n++){try{var q=c()}catch(v){throw new O(29);}if(void 0===q&&0===p)throw new O(6);if(null===q||void 0===q)break;p++;h[l+n]=q}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,l,m){for(var p=0;p<m;p++)try{d(h[l+p])}catch(n){throw new O(29);}m&&
(f.node.timestamp=Date.now());return p}});return Ub(a,b,e)}function jc(a){if(!(a.Cc||a.Dc||a.link||a.Ha)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.Ha=pb(la(a.url),!0),a.Ma=a.Ha.length}catch(b){throw new O(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function kc(a,b,c,d,e){function f(){this.Mb=!1;this.tb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.Vb;return this.vb(n/this.Vb|0)[q]}};f.prototype.Pc=function(n){this.vb=n};f.prototype.Tb=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=
(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;k||(u=q);var x=this;x.Pc(function(y){var H=y*u,G=(y+1)*u-1;G=Math.min(G,q-1);if("undefined"===typeof x.tb[y]){var fa=x.tb;if(H>G)throw Error("invalid range ("+H+", "+G+") or no bytes requested!");if(G>q-1)throw Error("only "+q+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);q!==u&&w.setRequestHeader("Range","bytes="+H+"-"+G);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);H=void 0!==w.response?new Uint8Array(w.response||[]):pb(w.responseText||"",!0);fa[y]=H}if("undefined"===typeof x.tb[y])throw Error("doXHR failed!");return x.tb[y]});if(n||!q)u=q=1,u=q=this.vb(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.kc=q;this.jc=u;this.Mb=!0};if("undefined"!==
typeof XMLHttpRequest){if(!ja)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Mb||this.Tb();return this.kc}},Vb:{get:function(){this.Mb||this.Tb();return this.jc}}});var l=void 0}else l=c,h=void 0;var m=gc(a,b,d,e);h?m.Ha=h:l&&(m.Ha=null,m.url=l);Object.defineProperties(m,{Ma:{get:function(){return this.Ha.length}}});var p={};Object.keys(m.Ja).forEach(function(n){var q=
m.Ja[n];p[n]=function(){jc(m);return q.apply(null,arguments)}});p.read=function(n,q,v,k,u){jc(m);n=n.node.Ha;if(u>=n.length)return 0;k=Math.min(n.length-u,k);if(n.slice)for(var x=0;x<k;x++)q[v+x]=n[u+x];else for(x=0;x<k;x++)q[v+x]=n.get(u+x);return k};m.Ja=p;return m}
function lc(a,b,c,d,e,f,h,l,m,p){function n(k){function u(y){p&&p();l||hc(a,b,y,d,e,m);f&&f();Sa(v)}var x=!1;g.preloadPlugins.forEach(function(y){!x&&y.canHandle(q)&&(y.handle(k,q,u,function(){h&&h();Sa(v)}),x=!0)});x||u(k)}mc.cd();var q=b?kb(N(a+"/"+b)):a,v="cp "+q;Ra(v);"string"==typeof c?yb(c,function(k){n(k)},h):n(c)}var S={},Qb,Zb,nc={};
function oc(a,b){try{var c=R(a,{ub:!0}).node;if(!c)throw new O(44);if(!c.Ia.Ya)throw new O(63);var d=c.Ia.Ya(c)}catch(e){if(e&&e.node&&N(a)!==N(Hb(e.node)))return-54;throw e;}E[b>>2]=d.sc;E[b+4>>2]=0;E[b+8>>2]=d.Kb;E[b+12>>2]=d.mode;E[b+16>>2]=d.Jc;E[b+20>>2]=d.uid;E[b+24>>2]=d.zc;E[b+28>>2]=d.ob;E[b+32>>2]=0;Za=[d.size>>>0,(M=d.size,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[b+40>>2]=Za[0];E[b+44>>2]=Za[1];E[b+48>>
2]=4096;E[b+52>>2]=d.oc;E[b+56>>2]=d.mc.getTime()/1E3|0;E[b+60>>2]=0;E[b+64>>2]=d.Ic.getTime()/1E3|0;E[b+68>>2]=0;E[b+72>>2]=d.rc.getTime()/1E3|0;E[b+76>>2]=0;Za=[d.Kb>>>0,(M=d.Kb,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[b+80>>2]=Za[0];E[b+84>>2]=Za[1];return 0}var pc=void 0;function qc(){pc+=4;return E[pc-4>>2]}function rc(a){a=Bb[a];if(!a)throw new O(8);return a}var sc={};
function tc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function uc(a){return this.fromWireType(I[a>>2])}var vc={},wc={},xc={};function yc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function zc(a,b){a=yc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ac(a){var b=Error,c=zc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Bc=void 0;function Cc(a){throw new Bc(a);}
function Dc(a,b,c){function d(l){l=c(l);l.length!==a.length&&Cc("Mismatched type converter count");for(var m=0;m<a.length;++m)Ec(a[m],l[m])}a.forEach(function(l){xc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){wc.hasOwnProperty(l)?e[m]=wc[l]:(f.push(l),vc.hasOwnProperty(l)||(vc[l]=[]),vc[l].push(function(){e[m]=wc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function Fc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Gc=void 0;function T(a){for(var b="";A[a];)b+=Gc[A[a++]];return b}var Hc=void 0;function U(a){throw new Hc(a);}
function Ec(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(wc.hasOwnProperty(a)){if(c.Ac)return;U("Cannot register type '"+d+"' twice")}wc[a]=b;delete xc[a];vc.hasOwnProperty(a)&&(b=vc[a],delete vc[a],b.forEach(function(e){e()}))}function Ic(a){U(a.Ga.Oa.Ka.name+" instance already deleted")}var Jc=!1;function Kc(){}
function Lc(a){--a.count.value;0===a.count.value&&(a.Ua?a.Va.bb(a.Ua):a.Oa.Ka.bb(a.La))}function Mc(a){if("undefined"===typeof FinalizationGroup)return Mc=function(b){return b},a;Jc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.La?Lc(c):console.warn("object already deleted: "+c.La)});Mc=function(b){Jc.register(b,b.Ga,b.Ga);return b};Kc=function(b){Jc.unregister(b.Ga)};return Mc(a)}var Nc=void 0,Oc=[];
function Pc(){for(;Oc.length;){var a=Oc.pop();a.Ga.gb=!1;a["delete"]()}}function Qc(){}var Rc={};function Sc(a,b,c){if(void 0===a[b].Qa){var d=a[b];a[b]=function(){a[b].Qa.hasOwnProperty(arguments.length)||U("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Qa+")!");return a[b].Qa[arguments.length].apply(this,arguments)};a[b].Qa=[];a[b].Qa[d.sb]=d}}
function Tc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Qa&&void 0!==g[a].Qa[c])&&U("Cannot register public name '"+a+"' twice"),Sc(g,a,a),g.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Qa[c]=b):(g[a]=b,void 0!==c&&(g[a].dd=c))}function Uc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.hb=c;this.bb=d;this.Wa=e;this.vc=f;this.rb=h;this.tc=l;this.Mc=[]}
function Vc(a,b,c){for(;b!==c;)b.rb||U("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.rb(a),b=b.Wa;return a}function Wc(a,b){if(null===b)return this.Lb&&U("null is not a valid "+this.name),0;b.Ga||U('Cannot pass "'+Xc(b)+'" as a '+this.name);b.Ga.La||U("Cannot pass deleted object as a pointer of type "+this.name);return Vc(b.Ga.La,b.Ga.Oa.Ka,this.Ka)}
function Yc(a,b){if(null===b){this.Lb&&U("null is not a valid "+this.name);if(this.xb){var c=this.Ob();null!==a&&a.push(this.bb,c);return c}return 0}b.Ga||U('Cannot pass "'+Xc(b)+'" as a '+this.name);b.Ga.La||U("Cannot pass deleted object as a pointer of type "+this.name);!this.wb&&b.Ga.Oa.wb&&U("Cannot convert argument of type "+(b.Ga.Va?b.Ga.Va.name:b.Ga.Oa.name)+" to parameter type "+this.name);c=Vc(b.Ga.La,b.Ga.Oa.Ka,this.Ka);if(this.xb)switch(void 0===b.Ga.Ua&&U("Passing raw pointer to smart pointer is illegal"),
this.Uc){case 0:b.Ga.Va===this?c=b.Ga.Ua:U("Cannot convert argument of type "+(b.Ga.Va?b.Ga.Va.name:b.Ga.Oa.name)+" to parameter type "+this.name);break;case 1:c=b.Ga.Ua;break;case 2:if(b.Ga.Va===this)c=b.Ga.Ua;else{var d=b.clone();c=this.Nc(c,V(function(){d["delete"]()}));null!==a&&a.push(this.bb,c)}break;default:U("Unsupporting sharing policy")}return c}
function Zc(a,b){if(null===b)return this.Lb&&U("null is not a valid "+this.name),0;b.Ga||U('Cannot pass "'+Xc(b)+'" as a '+this.name);b.Ga.La||U("Cannot pass deleted object as a pointer of type "+this.name);b.Ga.Oa.wb&&U("Cannot convert argument of type "+b.Ga.Oa.name+" to parameter type "+this.name);return Vc(b.Ga.La,b.Ga.Oa.Ka,this.Ka)}function $c(a,b,c){if(b===c)return a;if(void 0===c.Wa)return null;a=$c(a,b,c.Wa);return null===a?null:c.tc(a)}var ad={};
function bd(a,b){for(void 0===b&&U("ptr should not be undefined");a.Wa;)b=a.rb(b),a=a.Wa;return ad[b]}function cd(a,b){b.Oa&&b.La||Cc("makeClassHandle requires ptr and ptrType");!!b.Va!==!!b.Ua&&Cc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Mc(Object.create(a,{Ga:{value:b}}))}
function dd(a,b,c,d){this.name=a;this.Ka=b;this.Lb=c;this.wb=d;this.xb=!1;this.bb=this.Nc=this.Ob=this.ec=this.Uc=this.Kc=void 0;void 0!==b.Wa?this.toWireType=Yc:(this.toWireType=d?Wc:Zc,this.Xa=null)}function ed(a,b,c){g.hasOwnProperty(a)||Cc("Replacing nonexistant public symbol");void 0!==g[a].Qa&&void 0!==c?g[a].Qa[c]=b:(g[a]=b,g[a].sb=c)}
function fd(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=L.get(b).apply(null,c);return d}}function W(a,b){a=T(a);var c=a.includes("j")?fd(a,b):L.get(b);"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var gd=void 0;function hd(a){a=jd(a);var b=T(a);X(a);return b}
function kd(a,b){function c(f){e[f]||wc[f]||(xc[f]?xc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new gd(a+": "+d.map(hd).join([", "]));}function ld(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function md(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=zc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function nd(a,b,c,d,e){var f=b.length;2>f&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Xa){l=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+yc(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var q=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[U,d,e,tc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+q+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+q+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Xa&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].Xa));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return md(p).apply(null,d)}var od=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function pd(a){4<a&&0===--Y[a].Qb&&(Y[a]=void 0,od.push(a))}
function V(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=od.length?od.pop():Y.length;Y[b]={Qb:1,value:a};return b}}function Xc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function qd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ha[c>>2])};case 3:return function(c){return this.fromWireType(Ia[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function rd(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return A[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return C[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function sd(a){a||U("Cannot use deleted val. handle = "+a);return Y[a].value}function td(a,b){var c=wc[a];void 0===c&&U(b+" has unknown type "+hd(a));return c}var ud={};
function vd(a){var b=ud[a];return void 0===b?T(a):b}var wd=[];function xd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function yd(a){var b=wd.length;wd.push(a);return b}function zd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=td(E[(b>>2)+d],"parameter "+d);return c}var Ad={},Bd;Bd=function(){return performance.now()};var Cd=[],Dd=[];function Z(a,b){I[a>>2]=b;I[a+4>>2]=b/4294967296|0}var Ed;
function Fd(a,b,c,d,e){function f(J){var K=0,D=0;J&&(D=w.response?w.response.byteLength:0,K=Fa(D),A.set(new Uint8Array(w.response),K));I[a+12>>2]=K;Z(a+16,D)}var h=I[a+8>>2];if(h){var l=z(h),m=a+112,p=z(m);p||(p="GET");var n=I[m+52>>2],q=I[m+56>>2],v=!!I[m+60>>2],k=I[m+68>>2],u=I[m+72>>2];h=I[m+76>>2];var x=I[m+80>>2],y=I[m+84>>2];m=I[m+88>>2];var H=!!(n&1),G=!!(n&2);n=!!(n&64);k=k?z(k):void 0;u=u?z(u):void 0;var fa=x?z(x):void 0,w=new XMLHttpRequest;w.withCredentials=v;w.open(p,l,!n,k,u);n||(w.timeout=
q);w.gd=l;w.responseType="arraybuffer";x&&w.overrideMimeType(fa);if(h)for(;;){p=I[h>>2];if(!p)break;l=I[h+4>>2];if(!l)break;h+=8;p=z(p);l=z(l);w.setRequestHeader(p,l)}Dd.push(w);I[a+0>>2]=Dd.length;h=y&&m?A.slice(y,y+m):null;w.onload=function(J){f(H&&!G);var K=w.response?w.response.byteLength:0;Z(a+24,0);K&&Z(a+32,K);C[a+40>>1]=w.readyState;C[a+42>>1]=w.status;w.statusText&&B(w.statusText,A,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,J):c&&c(a,w,J)};w.onerror=function(J){f(H);var K=w.status;Z(a+
24,0);Z(a+32,w.response?w.response.byteLength:0);C[a+40>>1]=w.readyState;C[a+42>>1]=K;c&&c(a,w,J)};w.ontimeout=function(J){c&&c(a,w,J)};w.onprogress=function(J){var K=H&&G&&w.response?w.response.byteLength:0,D=0;H&&G&&(D=Fa(K),A.set(new Uint8Array(w.response),D));I[a+12>>2]=D;Z(a+16,K);Z(a+24,J.loaded-K);Z(a+32,J.total);C[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<J.loaded&&(w.status=200);C[a+42>>1]=w.status;w.statusText&&B(w.statusText,A,a+44,64);d&&d(a,w,J);D&&X(D)};w.onreadystatechange=
function(J){C[a+40>>1]=w.readyState;2<=w.readyState&&(C[a+42>>1]=w.status);e&&e(a,w,J)};try{w.send(h)}catch(J){c&&c(a,w,J)}}else c(a,0,"no url specified!")}function Gd(a,b){if(!sa)if(b)a();else try{a()}catch(c){if(a=c,!(a instanceof Hd||"unwind"===a))throw a&&"object"===typeof a&&a.stack&&r("exception thrown: "+[a,a.stack]),a;}}
function Id(a,b,c,d){var e=Ed;if(e){var f=I[a+112+64>>2];f||(f=I[a+8>>2]);var h=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);c(a,0,h)};l.onerror=function(m){C[a+40>>1]=4;C[a+42>>1]=413;B("Payload Too Large",A,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Jd(a,b,c){var d=Ed;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Fa(l);A.set(new Uint8Array(h),m);I[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)}else C[a+40>>1]=4,C[a+42>>1]=404,B("Not Found",A,a+44,64),c(a,0,"no data")};f.onerror=function(h){C[a+40>>1]=4;C[a+42>>1]=404;
B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Kd(a,b,c){var d=Ed;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;I[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)};f.onerror=function(h){C[a+40>>1]=4;C[a+42>>1]=404;B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Ld={};
function Md(){if(!Nd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ld)void 0===Ld[b]?delete a[b]:a[b]=Ld[b];var c=[];for(b in a)c.push(b+"="+a[b]);Nd=c}return Nd}var Nd;function Od(a,b){Od.dc||(Od.dc=jb());for(var c=0;c<b;c++)F[a+c>>0]=Od.dc();return 0}function Pd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Qd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Rd=[31,29,31,30,31,30,31,31,30,31,30,31],Sd=[31,28,31,30,31,30,31,31,30,31,30,31];function Td(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Pd(a.getFullYear())?Rd:Sd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ud(a,b,c,d){function e(k,u,x){for(k="number"===typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(H){return 0>H?-1:0<H?1:0}var y;0===(y=x(k.getFullYear()-u.getFullYear()))&&0===(y=x(k.getMonth()-u.getMonth()))&&(y=x(k.getDate()-u.getDate()));return y}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=Td(new Date(k.Ra+1900,0,1),k.Eb);var u=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=h(x,k)?0>=h(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=E[d+40>>2];d={Xc:E[d>>2],Wc:E[d+4>>2],Cb:E[d+8>>2],qb:E[d+12>>2],kb:E[d+16>>2],Ra:E[d+20>>2],Db:E[d+24>>2],Eb:E[d+28>>2],fd:E[d+32>>2],Vc:E[d+
36>>2],Yc:p?z(p):""};c=z(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return q[k.Db].substring(0,3)},"%A":function(k){return q[k.Db]},"%b":function(k){return v[k.kb].substring(0,3)},"%B":function(k){return v[k.kb]},"%C":function(k){return f((k.Ra+1900)/100|0,2)},"%d":function(k){return f(k.qb,2)},"%e":function(k){return e(k.qb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Cb,
2)},"%I":function(k){k=k.Cb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.qb+Qd(Pd(k.Ra+1900)?Rd:Sd,k.kb-1),3)},"%m":function(k){return f(k.kb+1,2)},"%M":function(k){return f(k.Wc,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Cb&&12>k.Cb?"AM":"PM"},"%S":function(k){return f(k.Xc,2)},"%t":function(){return"\t"},"%u":function(k){return k.Db||7},"%U":function(k){var u=new Date(k.Ra+1900,0,1),x=0===u.getDay()?u:Td(u,7-u.getDay());k=new Date(k.Ra+1900,k.kb,k.qb);return 0>
h(x,k)?f(Math.ceil((31-x.getDate()+(Qd(Pd(k.getFullYear())?Rd:Sd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%V":function(k){var u=new Date(k.Ra+1901,0,4),x=l(new Date(k.Ra+1900,0,4));u=l(u);var y=Td(new Date(k.Ra+1900,0,1),k.Eb);return 0>h(y,x)?"53":0>=h(u,y)?"01":f(Math.ceil((x.getFullYear()<k.Ra+1900?k.Eb+32-x.getDate():k.Eb+1-x.getDate())/7),2)},"%w":function(k){return k.Db},"%W":function(k){var u=new Date(k.Ra,0,1),x=1===u.getDay()?u:Td(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.Ra+1900,k.kb,k.qb);return 0>h(x,k)?f(Math.ceil((31-x.getDate()+(Qd(Pd(k.getFullYear())?Rd:Sd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%y":function(k){return(k.Ra+1900).toString().substring(2)},"%Y":function(k){return k.Ra+1900},"%z":function(k){k=k.Vc;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Yc},"%%":function(){return"%"}};for(n in p)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));n=pb(c,
!1);if(n.length>b)return 0;F.set(n,a);return n.length-1}function Kb(a,b,c,d){a||(a=this);this.parent=a;this.ab=a.ab;this.mb=null;this.id=Cb++;this.name=b;this.mode=c;this.Ia={};this.Ja={};this.ob=d}
Object.defineProperties(Kb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Dc:{get:function(){return Q(this.mode)}},Cc:{get:function(){return 8192===(this.mode&61440)}}});cc();Db=Array(4096);Rb(P,"/");Tb("/tmp");Tb("/home");Tb("/home/web_user");
(function(){Tb("/dev");nb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Ub("/dev/null",259);mb(1280,qb);mb(1536,rb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);var a=jb();ic("/dev","random",a);ic("/dev","urandom",a);Tb("/dev/shm");Tb("/dev/shm/tmp")})();
(function(){Tb("/proc");var a=Tb("/proc/self");Tb("/proc/self/fd");Rb({ab:function(){var b=vb(a,"fd",16895,73);b.Ia={lb:function(c,d){var e=Bb[+d];if(!e)throw new O(8);c={parent:null,ab:{bc:"fake"},Ia:{pb:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var mc;g.FS_createPath=fc;g.FS_createDataFile=hc;g.FS_createPreloadedFile=lc;g.FS_createLazyFile=kc;g.FS_createDevice=ic;g.FS_unlink=Wb;Bc=g.InternalError=Ac("InternalError");
for(var Vd=Array(256),Wd=0;256>Wd;++Wd)Vd[Wd]=String.fromCharCode(Wd);Gc=Vd;Hc=g.BindingError=Ac("BindingError");Qc.prototype.isAliasOf=function(a){if(!(this instanceof Qc&&a instanceof Qc))return!1;var b=this.Ga.Oa.Ka,c=this.Ga.La,d=a.Ga.Oa.Ka;for(a=a.Ga.La;b.Wa;)c=b.rb(c),b=b.Wa;for(;d.Wa;)a=d.rb(a),d=d.Wa;return b===d&&c===a};
Qc.prototype.clone=function(){this.Ga.La||Ic(this);if(this.Ga.nb)return this.Ga.count.value+=1,this;var a=Mc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ga;a=a(c.call(b,d,{Ga:{value:{count:e.count,gb:e.gb,nb:e.nb,La:e.La,Oa:e.Oa,Ua:e.Ua,Va:e.Va}}}));a.Ga.count.value+=1;a.Ga.gb=!1;return a};Qc.prototype["delete"]=function(){this.Ga.La||Ic(this);this.Ga.gb&&!this.Ga.nb&&U("Object already scheduled for deletion");Kc(this);Lc(this.Ga);this.Ga.nb||(this.Ga.Ua=void 0,this.Ga.La=void 0)};
Qc.prototype.isDeleted=function(){return!this.Ga.La};Qc.prototype.deleteLater=function(){this.Ga.La||Ic(this);this.Ga.gb&&!this.Ga.nb&&U("Object already scheduled for deletion");Oc.push(this);1===Oc.length&&Nc&&Nc(Pc);this.Ga.gb=!0;return this};dd.prototype.wc=function(a){this.ec&&(a=this.ec(a));return a};dd.prototype.Wb=function(a){this.bb&&this.bb(a)};dd.prototype.argPackAdvance=8;dd.prototype.readValueFromPointer=uc;dd.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
dd.prototype.fromWireType=function(a){function b(){return this.xb?cd(this.Ka.hb,{Oa:this.Kc,La:c,Va:this,Ua:a}):cd(this.Ka.hb,{Oa:this,La:a})}var c=this.wc(a);if(!c)return this.Wb(a),null;var d=bd(this.Ka,c);if(void 0!==d){if(0===d.Ga.count.value)return d.Ga.La=c,d.Ga.Ua=a,d.clone();d=d.clone();this.Wb(a);return d}d=this.Ka.vc(c);d=Rc[d];if(!d)return b.call(this);d=this.wb?d.qc:d.pointerType;var e=$c(c,this.Ka,d.Ka);return null===e?b.call(this):this.xb?cd(d.Ka.hb,{Oa:d,La:e,Va:this,Ua:a}):cd(d.Ka.hb,
{Oa:d,La:e})};g.getInheritedInstanceCount=function(){return Object.keys(ad).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in ad)ad.hasOwnProperty(b)&&a.push(ad[b]);return a};g.flushPendingDeletes=Pc;g.setDelayFunction=function(a){Nc=a;Oc.length&&Nc&&Nc(Pc)};gd=g.UnboundTypeError=Ac("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){Ed=a;Sa("library_fetch_init")},function(){Ed=!1;Sa("library_fetch_init")});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Ra("library_fetch_init");
function pb(a,b){var c=Array(va(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var $d={S:function(a,b){fb||(fb=!0,bb());a=new Date(1E3*E[a>>2]);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);E[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;E[b+32>>2]=a;
a=E[eb()+(a?4:0)>>2];E[b+40>>2]=a;return b},W:function(a,b){try{var c=rc(a);return oc(c.path,b)}catch(d){return"undefined"!==typeof S&&d instanceof O||t(d),-d.Sa}},U:function(a,b,c){pc=c;try{var d=rc(a);switch(b){case 21509:case 21505:return d.Na?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Na?0:-59;case 21519:if(!d.Na)return-59;var e=qc();return E[e>>2]=0;case 21520:return d.Na?-28:-59;case 21531:a=e=qc();if(!d.Ja.Bc)throw new O(59);return d.Ja.Bc(d,b,a);case 21523:return d.Na?
0:-59;case 21524:return d.Na?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof S&&f instanceof O||t(f),-f.Sa}},Z:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var m=sb(b);if(!m){l=-48;break a}h=!0}else{var p=Bb[e];if(!p){l=-8;break a}var n=f;if(0!==(c&2)&&0===(d&2)&&2!==(p.flags&2097155))throw new O(2);if(1===(p.flags&2097155))throw new O(2);if(!p.Ja.zb)throw new O(43);var q=p.Ja.zb(p,a,b,n,c,d);m=q.La;h=q.Gb}nc[m]=
{Gc:m,Fc:b,Gb:h,$a:e,Lc:c,flags:d,offset:f};l=m}}return l}catch(v){return"undefined"!==typeof S&&v instanceof O||t(v),-v.Sa}},Y:function(){return 0},X:function(a,b){try{var c=nc[a];if(0!==b&&c){if(b===c.Fc){var d=Bb[c.$a];d&&c.Lc&2&&d&&d.Ja.Ab&&d.Ja.Ab(d,A.slice(a,a+b),c.offset,b,c.flags);nc[a]=null;c.Gb&&X(c.Gc)}var e=0}else e=-28;return e}catch(f){return"undefined"!==typeof S&&f instanceof O||t(f),-f.Sa}},C:function(a,b,c){pc=c;try{var d=z(a),e=c?qc():0;return Yb(d,b,e).$a}catch(f){return"undefined"!==
typeof S&&f instanceof O||t(f),-f.Sa}},V:function(a,b){try{return a=z(a),oc(a,b)}catch(c){return"undefined"!==typeof S&&c instanceof O||t(c),-c.Sa}},f:function(a){var b=sc[a];delete sc[a];var c=b.Ob,d=b.bb,e=b.Yb,f=e.map(function(h){return h.yc}).concat(e.map(function(h){return h.Sc}));Dc([a],f,function(h){var l={};e.forEach(function(m,p){var n=h[p],q=m.vb,v=m.xc,k=h[p+e.length],u=m.Rc,x=m.Tc;l[m.uc]={read:function(y){return n.fromWireType(q(v,y))},write:function(y,H){var G=[];u(x,y,k.toWireType(G,
H));tc(G)}}});return[{name:b.name,fromWireType:function(m){var p={},n;for(n in l)p[n]=l[n].read(m);d(m);return p},toWireType:function(m,p){for(var n in l)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in l)l[n].write(q,p[n]);null!==m&&m.push(d,q);return q},argPackAdvance:8,readValueFromPointer:uc,Xa:d}]})},H:function(){},ca:function(a,b,c,d,e){var f=Fc(c);b=T(b);Ec(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===
c)var l=F;else if(2===c)l=ya;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},Xa:null})},q:function(a,b,c,d,e,f,h,l,m,p,n,q,v){n=T(n);f=W(e,f);l&&(l=W(h,l));p&&(p=W(m,p));v=W(q,v);var k=yc(n);Tc(k,function(){kd("Cannot construct "+n+" due to unbound types",[d])});Dc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.Ka;var y=x.hb}else y=Qc.prototype;u=zc(k,function(){if(Object.getPrototypeOf(this)!==H)throw new Hc("Use 'new' to construct "+
n);if(void 0===G.cb)throw new Hc(n+" has no accessible constructor");var w=G.cb[arguments.length];if(void 0===w)throw new Hc("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(G.cb).toString()+") parameters instead!");return w.apply(this,arguments)});var H=Object.create(y,{constructor:{value:u}});u.prototype=H;var G=new Uc(n,u,H,v,x,f,l,p);x=new dd(n,G,!0,!1);y=new dd(n+"*",G,!1,!1);var fa=new dd(n+" const*",G,!1,!0);Rc[a]={pointerType:y,
qc:fa};ed(k,u);return[x,y,fa]})},r:function(a,b,c,d,e,f){0<b||t("Assertion failed: undefined");var h=ld(b,c);e=W(d,e);Dc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.Ka.cb&&(l.Ka.cb=[]);if(void 0!==l.Ka.cb[b-1])throw new Hc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.Ka.cb[b-1]=function(){kd("Cannot construct "+
l.name+" due to unbound types",h)};Dc([],h,function(p){p.splice(1,0,null);l.Ka.cb[b-1]=nd(m,p,null,e,f);return[]});return[]})},k:function(a,b,c,d,e,f,h,l){var m=ld(c,d);b=T(b);f=W(e,f);Dc([],[a],function(p){function n(){kd("Cannot call "+q+" due to unbound types",m)}p=p[0];var q=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.Ka.Mc.push(b);var v=p.Ka.hb,k=v[b];void 0===k||void 0===k.Qa&&k.className!==p.name&&k.sb===c-2?(n.sb=c-2,n.className=p.name,v[b]=n):(Sc(v,b,q),v[b].Qa[c-2]=
n);Dc([],m,function(u){u=nd(q,u,p,f,h);void 0===v[b].Qa?(u.sb=c-2,v[b]=u):v[b].Qa[c-2]=u;return[]});return[]})},ba:function(a,b){b=T(b);Ec(a,{name:b,fromWireType:function(c){var d=Y[c].value;pd(c);return d},toWireType:function(c,d){return V(d)},argPackAdvance:8,readValueFromPointer:uc,Xa:null})},D:function(a,b,c){c=Fc(c);b=T(b);Ec(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Xc(e)+'" to '+
this.name);return e},argPackAdvance:8,readValueFromPointer:qd(b,c),Xa:null})},w:function(a,b,c,d,e,f){var h=ld(b,c);a=T(a);e=W(d,e);Tc(a,function(){kd("Cannot call "+a+" due to unbound types",h)},b-1);Dc([],h,function(l){ed(a,nd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},g:function(a,b,c,d,e){function f(p){return p}b=T(b);-1===e&&(e=4294967295);var h=Fc(c);if(0===d){var l=32-8*c;f=function(p){return p<<l>>>l}}var m=b.includes("unsigned");Ec(a,{name:b,fromWireType:f,toWireType:function(p,
n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Xc(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+Xc(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:rd(b,h,0!==d),Xa:null})},e:function(a,b,c){function d(f){f>>=2;var h=I;return new e(Ga,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=T(c);Ec(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Ac:!0})},E:function(a,b){b=T(b);var c="std::string"===b;Ec(a,{name:b,fromWireType:function(d){var e=I[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==A[l]){f=z(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(A[d+4+h]);m=m.join("")}X(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&
(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var h=(c&&f?function(){return va(e)}:function(){return e.length})(),l=Fa(4+h+1);I[l>>2]=h;if(c&&f)B(e,A,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(X(l),U("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=m}else for(f=0;f<h;++f)A[l+4+f]=e[f];null!==d&&d.push(X,l);return l},argPackAdvance:8,
readValueFromPointer:uc,Xa:function(d){X(d)}})},t:function(a,b,c){c=T(c);if(2===b){var d=xa;var e=za;var f=Aa;var h=function(){return C};var l=1}else 4===b&&(d=Ba,e=Ca,f=Da,h=function(){return I},l=2);Ec(a,{name:c,fromWireType:function(m){for(var p=I[m>>2],n=h(),q,v=m+4,k=0;k<=p;++k){var u=m+4+k*b;if(k==p||0==n[u>>l])v=d(v,u-v),void 0===q?q=v:(q+=String.fromCharCode(0),q+=v),v=u+b}X(m);return q},toWireType:function(m,p){"string"!==typeof p&&U("Cannot pass non-string to C++ string type "+c);var n=
f(p),q=Fa(4+n+b);I[q>>2]=n>>l;e(p,q+4,n+b);null!==m&&m.push(X,q);return q},argPackAdvance:8,readValueFromPointer:uc,Xa:function(m){X(m)}})},d:function(a,b,c,d,e,f){sc[a]={name:T(b),Ob:W(c,d),bb:W(e,f),Yb:[]}},a:function(a,b,c,d,e,f,h,l,m,p){sc[a].Yb.push({uc:T(b),yc:c,vb:W(d,e),xc:f,Sc:h,Rc:W(l,m),Tc:p})},da:function(a,b){b=T(b);Ec(a,{Ec:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},_:function(a){delete Dd[a-1]},K:function(){throw"longjmp";},i:function(a,b,c){a=sd(a);
b=td(b,"emval::as");var d=[],e=V(d);E[c>>2]=e;return b.toWireType(d,a)},o:function(a,b,c,d){a=wd[a];b=sd(b);c=vd(c);a(b,c,null,d)},x:pd,ia:function(a){if(0===a)return V(xd());a=vd(a);return V(xd()[a])},n:function(a,b){b=zd(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+yc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=
0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Ec||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=md(e).apply(null,f);return yd(a)},ga:function(a){a=vd(a);return V(g[a])},j:function(a,b){a=sd(a);b=sd(b);return V(a[b])},J:function(a){4<a&&(Y[a].Qb+=1)},v:function(a,
b,c,d){a=sd(a);var e=Ad[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(td,
g,V);Ad[b]=e}return e(a,c,d)},fa:function(){return V([])},ka:function(a){return V(vd(a))},ha:function(){return V({})},ja:function(a){tc(Y[a].value);pd(a)},h:function(a,b,c){a=sd(a);b=sd(b);c=sd(c);a[b]=c},m:function(a,b){a=td(a,"_emval_take_value");a=a.readValueFromPointer(b);return V(a)},l:function(){t()},A:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Bd();else return-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},p:function(a,b,c){Cd.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&
c&1&&c++,Cd.push(d?Ia[c++>>1]:E[c]),++c;return $a[a].apply(null,Cd)},aa:function(){return!ja},L:function(a,b,c){A.copyWithin(a,b,b+c)},M:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ra.grow(Math.min(2147483648,d)-Ga.byteLength+65535>>>16);Ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},$:function(a,b,c,d,e){function f(D){Fd(D,h,p,n,m)}function h(D,be){Id(D,
be.response,function(Ta){Gd(function(){u?L.get(u)(Ta):b&&b(Ta)},K)},function(Ta){Gd(function(){u?L.get(u)(Ta):b&&b(Ta)},K)})}function l(D){Fd(D,q,p,n,m)}function m(D){Gd(function(){H?L.get(H)(D):e&&e(D)},K)}function p(D){Gd(function(){x?L.get(x)(D):c&&c(D)},K)}function n(D){Gd(function(){y?L.get(y)(D):d&&d(D)},K)}function q(D){Gd(function(){u?L.get(u)(D):b&&b(D)},K)}var v=a+112,k=z(v),u=I[v+36>>2],x=I[v+40>>2],y=I[v+44>>2],H=I[v+48>>2],G=I[v+52>>2],fa=!!(G&4),w=!!(G&32),J=!!(G&16),K=!!(G&64);if("EM_IDB_STORE"===
k)k=I[v+84>>2],Id(a,A.slice(k,k+I[v+88>>2]),q,p);else if("EM_IDB_DELETE"===k)Kd(a,q,p);else if(J){if(w)return 0;Fd(a,fa?h:q,p,n,m)}else Jd(a,q,w?p:fa?f:l);return a},Q:function(a,b){var c=0;Md().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)F[e++>>0]=d.charCodeAt(f);F[e>>0]=0;c+=d.length+1});return 0},R:function(a,b){var c=Md();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},u:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);sa=!0}ha(a,
new Hd(a))},s:function(a){try{var b=rc(a);$b(b);return 0}catch(c){return"undefined"!==typeof S&&c instanceof O||t(c),c.Sa}},P:function(a,b){try{var c=rc(a);F[b>>0]=c.Na?2:Q(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof S&&d instanceof O||t(d),d.Sa}},B:function(a,b,c,d){try{a:{for(var e=rc(a),f=a=0;f<c;f++){var h=E[b+(8*f+4)>>2],l=e,m=E[b+8*f>>2],p=h,n=void 0,q=F;if(0>p||0>n)throw new O(28);if(null===l.$a)throw new O(8);if(1===(l.flags&2097155))throw new O(8);if(Q(l.node.mode))throw new O(31);
if(!l.Ja.read)throw new O(28);var v="undefined"!==typeof n;if(!v)n=l.position;else if(!l.seekable)throw new O(70);var k=l.Ja.read(l,q,m,p,n);v||(l.position+=k);var u=k;if(0>u){var x=-1;break a}a+=u;if(u<h)break}x=a}E[d>>2]=x;return 0}catch(y){return"undefined"!==typeof S&&y instanceof O||t(y),y.Sa}},G:function(a,b,c,d,e){try{var f=rc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ac(f,a,d);Za=[f.position>>>0,(M=f.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[e>>2]=Za[0];E[e+4>>2]=Za[1];f.Jb&&0===a&&0===d&&(f.Jb=null);return 0}catch(h){return"undefined"!==typeof S&&h instanceof O||t(h),h.Sa}},T:function(a,b,c,d){try{a:{for(var e=rc(a),f=a=0;f<c;f++){var h=bc(e,F,E[b+8*f>>2],E[b+(8*f+4)>>2],void 0);if(0>h){var l=-1;break a}a+=h}l=a}E[d>>2]=l;return 0}catch(m){return"undefined"!==typeof S&&m instanceof O||t(m),m.Sa}},c:function(){return pa},la:function(){var a=self.navigator.userAgent,
b=va(a)+1,c=Fa(b);B(a,A,c,b);return c},N:Od,I:Xd,z:Yd,y:Zd,ea:function(a){fb||(fb=!0,bb());var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?E[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=(b.getTime()-e.getTime())/
864E5|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},b:function(a){pa=a},F:Ud,O:function(a,b,c,d){return Ud(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ra=g.asm.ma;Ja();L=g.asm.za;La.unshift(g.asm.na);Sa("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){r("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:$d};Ra("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return qa||
"function"!==typeof WebAssembly.instantiateStreaming||Ua()||"function"!==typeof fetch?c(b):fetch(Va,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){r("wasm streaming compile failed: "+f);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.na).apply(null,arguments)};
var X=g._free=function(){return(X=g._free=g.asm.oa).apply(null,arguments)},Fa=g._malloc=function(){return(Fa=g._malloc=g.asm.pa).apply(null,arguments)},jd=g.___getTypeName=function(){return(jd=g.___getTypeName=g.asm.qa).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.ra).apply(null,arguments)};
var eb=g.__get_tzname=function(){return(eb=g.__get_tzname=g.asm.sa).apply(null,arguments)},db=g.__get_daylight=function(){return(db=g.__get_daylight=g.asm.ta).apply(null,arguments)},cb=g.__get_timezone=function(){return(cb=g.__get_timezone=g.asm.ua).apply(null,arguments)},ae=g.stackSave=function(){return(ae=g.stackSave=g.asm.va).apply(null,arguments)},ce=g.stackRestore=function(){return(ce=g.stackRestore=g.asm.wa).apply(null,arguments)},de=g._setThrew=function(){return(de=g._setThrew=g.asm.xa).apply(null,
arguments)},tb=g._memalign=function(){return(tb=g._memalign=g.asm.ya).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Aa).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Ba).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ca).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Da).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Ea).apply(null,arguments)};
g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Fa).apply(null,arguments)};function Yd(a,b){var c=ae();try{L.get(a)(b)}catch(d){ce(c);if(d!==d+0&&"longjmp"!==d)throw d;de(1,0)}}function Zd(a,b,c){var d=ae();try{L.get(a)(b,c)}catch(e){ce(d);if(e!==e+0&&"longjmp"!==e)throw e;de(1,0)}}function Xd(a,b,c,d){var e=ae();try{return L.get(a)(b,c,d)}catch(f){ce(e);if(f!==f+0&&"longjmp"!==f)throw f;de(1,0)}}g.addRunDependency=Ra;g.removeRunDependency=Sa;g.FS_createPath=fc;g.FS_createDataFile=hc;
g.FS_createPreloadedFile=lc;g.FS_createLazyFile=kc;g.FS_createDevice=ic;g.FS_unlink=Wb;var ee;function Hd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function fe(){ee||ge();ee||(Qa=fe)};
function ge(){function a(){if(!ee&&(ee=!0,g.calledRun=!0,!sa)){g.noFSInit||dc||(dc=!0,cc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?ic("/dev","stdin",g.stdin):Vb("/dev/tty","/dev/stdin"),g.stdout?ic("/dev","stdout",null,g.stdout):Vb("/dev/tty","/dev/stdout"),g.stderr?ic("/dev","stderr",null,g.stderr):Vb("/dev/tty1","/dev/stderr"),Yb("/dev/stdin",0),Yb("/dev/stdout",1),Yb("/dev/stderr",1));Eb=!1;ab(La);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ma.unshift(b)}ab(Ma)}}if(!(0<Oa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Na();ab(Ka);0<Oa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=ge;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ge();


  return BlinkCardWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkCardWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkCardWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkCardWasmSDK"] = BlinkCardWasmSDK;
