var BlinkCardWasmSDK=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var m=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope;m.expectedDataFileDownloads??(m.expectedDataFileDownloads=0);m.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(k,t,n){m.dataFileDownloads??(m.dataFileDownloads={});fetch(k).catch(p=>Promise.reject(Error(`Network Error: ${k}`,{cause:p}))).then(p=>{if(!p.ok)return Promise.reject(Error(`${p.status}: ${p.url}`));if(!p.body&&p.arrayBuffer)return p.arrayBuffer().then(n);const x=p.body.getReader(),q=()=>x.read().then(F).catch(H=>Promise.reject(Error(`Unexpected error while handling : ${p.url} ${H}`,
{cause:H}))),u=[],z=Number(p.headers.get("Content-Length")??t);let I=0;const F=({done:H,value:v})=>{if(H){var G=new Uint8Array(u.map(C=>C.length).reduce((C,da)=>C+da,0));H=0;for(var E of u)G.set(E,H),H+=E.length;n(G.buffer)}else{u.push(v);I+=v.length;m.dataFileDownloads[k]={loaded:I,total:z};H=E=0;for(G of Object.values(m.dataFileDownloads))E+=G.loaded,H+=G.total;m.setStatus?.(`Downloading data... (${E}/${H})`);return q()}};m.setStatus?.("Downloading data...");return q()})}function d(k){console.error("package error:",
k)}function e(k){function t(q,u,z){this.start=q;this.end=u;this.audio=z}function n(q){if(!q)throw"Loading data file failed."+Error().stack;if(q.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;q=new Uint8Array(q);t.prototype.Wb=q;q=b.files;for(var u=0;u<q.length;++u)t.prototype.Fb[q[u].filename].onload();k.removeRunDependency("datafile_/opt/jenkins/jenkinsData/E3/sdk-blinkcard-in-browser/resources/basic/BlinkCardWasmSDK.data")}k.FS_createPath("/","microblink",
!0,!0);t.prototype={Fb:{},open:function(q,u){this.name=u;this.Fb[u]=this;k.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.Wb.subarray(this.start,this.end))},finish:function(q){k.FS_createDataFile(this.name,null,q,!0,!0,!0);k.removeRunDependency(`fp ${this.name}`);this.Fb[this.name]=null}};for(var p=b.files,x=0;x<p.length;++x)(new t(p[x].start,p[x].end,p[x].audio||0)).open("GET",p[x].filename);k.addRunDependency("datafile_/opt/jenkins/jenkinsData/E3/sdk-blinkcard-in-browser/resources/basic/BlinkCardWasmSDK.data");
k.preloadResults??(k.preloadResults={});k.preloadResults["/opt/jenkins/jenkinsData/E3/sdk-blinkcard-in-browser/resources/basic/BlinkCardWasmSDK.data"]={Gc:!1};l?(n(l),l=null):h=n}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=m.locateFile?m.locateFile("BlinkCardWasmSDK.data",
""):"BlinkCardWasmSDK.data",g=b.remote_package_size,h=null,l=m.getPreloadedPackage?m.getPreloadedPackage(f,g):null;l||c(f,g,k=>{h?(h(k),h=null):l=k},d);m.calledRun?e(m):(m.preRun??(m.preRun=[])).push(e)}({files:[{filename:"/microblink/Model_07c7ab860e77ec2e92bb822f6d62424b8595a5beb4340f6b2f7f6a4cffa5d050.strop",start:0,end:103198},{filename:"/microblink/Model_1118d9d674e23996f70c6416b2bf5a6ce6ef24a6ad2c92f0ddd1e198e5f05305.strop",start:103198,end:122300},{filename:"/microblink/Model_2880751121560047e6dc571bc8ff4683aeb863886f7c0789234594ceb1e23577.strop",
start:122300,end:126035},{filename:"/microblink/Model_349432d66ef2b216155673b634f7d5c47795bed35719b954f726b5f0856740f3.strop",start:126035,end:174352},{filename:"/microblink/Model_36d8e94f4cb46097bd6b7385f2aa91fcdee1a5fefeec59e56d1b9e82c94b00a7.strop",start:174352,end:518808},{filename:"/microblink/Model_3b11c3ffacbbf390b932fb9a7024f1a0016f66281ea8c790f8b5903374ad89c2.strop",start:518808,end:787529},{filename:"/microblink/Model_4336af7999b059ac75281d0d71b60dd55b33c2b22c2b2c8e2b9ab56fe6ad720d.strop",
start:787529,end:1114397},{filename:"/microblink/Model_473ac5f5e256623c0a6b282698c1f1b033b9fb5359e6aa142e9fb4a4022afe4e.strop",start:1114397,end:1120846},{filename:"/microblink/Model_5065f3a3bc1c2fece482ee66e9275fc198b9be239547e08b6086c59f347ca72f.strop",start:1120846,end:3376001},{filename:"/microblink/Model_673fc1384d1f4e156f3744a22ac3c8216d52c6a6e58940b87e9c950fcaf1517d.strop",start:3376001,end:4800308},{filename:"/microblink/Model_830c13896f96c1cb6d5cad725f44e6aae470f8672d640d20b3272ed4bb839699.strop",
start:4800308,end:5057331},{filename:"/microblink/Model_8326c5065a6d8451d6d004db73babf4a4a9f502c68643a14934cc098d04bf44f.strop",start:5057331,end:5445025},{filename:"/microblink/Model_8c7727da554fd257fa758787ca3d0f517b47f6c5ba791792f516da7dd210fde8.strop",start:5445025,end:6471880},{filename:"/microblink/Model_93607315418f2c5d3abec06d0b2a81e69abeb1b8d0506ed6373d7d74bd5e4b05.strop",start:6471880,end:7716871},{filename:"/microblink/Model_9f6734be0f5c1e4f3c6c621f4a72db8241feaf7c8705dc68a9cc07a7b634ee85.strop",
start:7716871,end:7800507},{filename:"/microblink/Model_a1516add883f909ebecf9b565238086f8f31bbb3e7fb2113258e3ae7c659555e.strop",start:7800507,end:8096309},{filename:"/microblink/Model_a9623413eba53db7d5cd23301e49b37d71d77290b0b2bc2efa9cbe69cb7e2b2e.strop",start:8096309,end:11757244},{filename:"/microblink/Model_abb3e9795585a24a9bbd1dd41ec97daa2e1d7d42087aacd981411fd8b26bf493.strop",start:11757244,end:12089400},{filename:"/microblink/Model_b452fd3cd4037080cfcb4c423dba5bc58c8ceafc28427fdf9c5778fb353f088e.strop",
start:12089400,end:12095896},{filename:"/microblink/Model_b9263312a9b623d1a3b75b643ccdcbc36aae52c278d721443468147c50e44583.strop",start:12095896,end:12364170},{filename:"/microblink/Model_cc1fab8df49d9a21de6c7b76ccf0dac40b17fcfb7073cc520eca073cbf8e33e9.strop",start:12364170,end:12367901},{filename:"/microblink/Model_e946dc0b1d15d7dd6ab8b936593bd77a07a9d8a5fa7a803e531713a6f5d2eab6.strop",start:12367901,end:13397754},{filename:"/microblink/Model_f132d1bd7614b1274fafb8a41ec6c047b84b2a43654ae2da5ddd78a2765601c6.strop",
start:13397754,end:14232579},{filename:"/microblink/Model_f2874f5766b779c063dbe30467979163497dc4b29c43bab23d70c798ee32993a.strop",start:14232579,end:14307981},{filename:"/microblink/Model_f479233a81ecef2708f6217ed1e29dfe437522e0cf34bd4d9ef6c39266afa9ab.strop",start:14307981,end:14433102},{filename:"/microblink/Model_f531088a1f65a31d6ba039e09446fe24c18360080fec3792308ac01514803620.strop",start:14433102,end:15096155},{filename:"/microblink/Model_faf688599c7e261a2a7404730f69ed029115bb0d3e7a3657731d88e701720efe.strop",
start:15096155,end:15111828},{filename:"/microblink/Model_fc22f7553e3e85531eb79ef6db1474302664508cc7ae4ff0d950447b20f2f8ee.strop",start:15111828,end:15184526}],remote_package_size:15184526})})();m.onAbort=function(a){r("Aborted with message: "+a);try{throw new WebAssembly.RuntimeError(a);}catch(b){r("Stacktrace: "+b.stack)}};var ca="./this.program";ba&&(_scriptName=self.location.href);var ea="",fa,ha;
if(aa||ba){try{ea=(new URL(".",_scriptName)).href}catch{}ba&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ia=console.log.bind(console),r=console.error.bind(console),ja,ka=!1,la,ma,na,oa,w,y,A,pa,B,D,qa,ra,sa,ta,ua=!1;
function va(){var a=oa.buffer;w=new Int8Array(a);A=new Int16Array(a);y=new Uint8Array(a);pa=new Uint16Array(a);B=new Int32Array(a);D=new Uint32Array(a);qa=new Float32Array(a);ra=new Float64Array(a);sa=new BigInt64Array(a);ta=new BigUint64Array(a)}var wa=0,xa=null;function ya(){wa++;m.monitorRunDependencies?.(wa)}function za(){wa--;m.monitorRunDependencies?.(wa);if(0==wa&&xa){var a=xa;xa=null;a()}}
function Aa(a){m.onAbort?.(a);a="Aborted("+a+")";r(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");na?.(a);throw a;}var Ba;async function Ca(a){if(!ja)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==Ba&&ja)a=new Uint8Array(ja);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Da(a,b){try{var c=await Ca(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),Aa(d)}}async function Ea(a){var b=Ba;if(!ja&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return Da(b,a)}
class Fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ga=a=>{for(;0<a.length;)a.shift()(m)},Ha=[],Ia=[],Ka=()=>{var a=m.preRun.shift();Ia.push(a)},La=!0,Ma=[],Na,J=a=>{var b=Ma[a];b||(Ma[a]=b=Na.get(a));return b},K=()=>{var a=B[+Oa>>2];Oa+=4;return a},Pa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Qa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Pa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");
return(b?"/":"")+a},Ra=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Sa=()=>a=>crypto.getRandomValues(a),Ta=a=>{(Ta=Sa())(a)},Ua=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Pa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":
"")+b||"."},Va="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Wa=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},L=(a,b=0,c,d)=>{c=Wa(a,b,c,d);if(16<c-b&&a.buffer&&Va)return Va.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Xa=[],Ya=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},M=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|
g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Za=a=>{var b=Array(Ya(a)+1);a=M(a,b,0,b.length);b.length=a;return b},$a=[];function ab(a,b){$a[a]={input:[],output:[],Ta:b};bb(a,cb)}
var cb={open(a){var b=$a[a.node.pb];if(!b)throw new N(43);a.Aa=b;a.seekable=!1},close(a){a.Aa.Ta.kb(a.Aa)},kb(a){a.Aa.Ta.kb(a.Aa)},read(a,b,c,d){if(!a.Aa||!a.Aa.Ta.Pb)throw new N(60);for(var e=0,f=0;f<d;f++){try{var g=a.Aa.Ta.Pb(a.Aa)}catch(h){throw new N(29);}if(void 0===g&&0===e)throw new N(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Xa=Date.now());return e},write(a,b,c,d){if(!a.Aa||!a.Aa.Ta.Cb)throw new N(60);try{for(var e=0;e<d;e++)a.Aa.Ta.Cb(a.Aa,b[c+e])}catch(f){throw new N(29);
}d&&(a.node.Ma=a.node.Ia=Date.now());return e}},db={Pb(){a:{if(!Xa.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Xa=Za(a)}a=Xa.shift()}return a},Cb(a,b){null===b||10===b?(ia(L(a.output)),a.output=[]):0!=b&&a.output.push(b)},kb(a){0<a.output?.length&&(ia(L(a.output)),a.output=[])},fc(){return{Ac:25856,Cc:5,zc:191,Bc:35387,yc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0]}},hc(){return 0},ic(){return[24,80]}},eb={Cb(a,b){null===b||10===b?(r(L(a.output)),a.output=[]):0!=b&&a.output.push(b)},kb(a){0<a.output?.length&&(r(L(a.output)),a.output=[])}},gb=a=>{a=65536*Math.ceil(a/65536);var b=fb(65536,a);b&&y.fill(0,b,b+a);return b},O={Oa:null,Sa(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.Oa||(O.Oa={dir:{node:{Va:O.xa.Va,Ra:O.xa.Ra,eb:O.xa.eb,nb:O.xa.nb,Tb:O.xa.Tb,tb:O.xa.tb,Ub:O.xa.Ub,Eb:O.xa.Eb,
sb:O.xa.sb},stream:{Na:O.wa.Na}},file:{node:{Va:O.xa.Va,Ra:O.xa.Ra},stream:{Na:O.wa.Na,read:O.wa.read,write:O.wa.write,Bb:O.wa.Bb,ob:O.wa.ob}},link:{node:{Va:O.xa.Va,Ra:O.xa.Ra,hb:O.xa.hb},stream:{}},Kb:{node:{Va:O.xa.Va,Ra:O.xa.Ra},stream:hb}});c=ib(a,b,c,d);P(c.mode)?(c.xa=O.Oa.dir.node,c.wa=O.Oa.dir.stream,c.va={}):32768===(c.mode&61440)?(c.xa=O.Oa.file.node,c.wa=O.Oa.file.stream,c.Ca=0,c.va=null):40960===(c.mode&61440)?(c.xa=O.Oa.link.node,c.wa=O.Oa.link.stream):8192===(c.mode&61440)&&(c.xa=O.Oa.Kb.node,
c.wa=O.Oa.Kb.stream);c.Xa=c.Ma=c.Ia=Date.now();a&&(a.va[b]=c,a.Xa=a.Ma=a.Ia=c.Xa);return c},Hc(a){return a.va?a.va.subarray?a.va.subarray(0,a.Ca):new Uint8Array(a.va):new Uint8Array(0)},xa:{Va(a){var b={};b.Dc=8192===(a.mode&61440)?a.id:1;b.Kc=a.id;b.mode=a.mode;b.Lc=1;b.uid=0;b.Ic=0;b.pb=a.pb;b.size=P(a.mode)?4096:32768===(a.mode&61440)?a.Ca:40960===(a.mode&61440)?a.link.length:0;b.Xa=new Date(a.Xa);b.Ma=new Date(a.Ma);b.Ia=new Date(a.Ia);b.Vb=4096;b.xc=Math.ceil(b.size/b.Vb);return b},Ra(a,b){for(var c of["mode",
"atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Ca!=b&&(0==b?(a.va=null,a.Ca=0):(c=a.va,a.va=new Uint8Array(b),c&&a.va.set(c.subarray(0,Math.min(b,a.Ca))),a.Ca=b)))},eb(){O.vb||(O.vb=new N(44),O.vb.stack="<generic error, no stack>");throw O.vb;},nb(a,b,c,d){return O.createNode(a,b,c,d)},Tb(a,b,c){try{var d=jb(b,c)}catch(f){}if(d){if(P(a.mode))for(var e in d.va)throw new N(55);kb(d)}delete a.parent.va[a.name];b.va[c]=a;a.name=c;b.Ia=b.Ma=a.parent.Ia=a.parent.Ma=Date.now()},
tb(a,b){delete a.va[b];a.Ia=a.Ma=Date.now()},Ub(a,b){var c=jb(a,b),d;for(d in c.va)throw new N(55);delete a.va[b];a.Ia=a.Ma=Date.now()},Eb(a){return[".","..",...Object.keys(a.va)]},sb(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},hb(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},wa:{read(a,b,c,d,e){var f=a.node.va;if(e>=a.node.Ca)return 0;a=Math.min(a.node.Ca-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===
w.buffer&&(f=!1);if(!d)return 0;a=a.node;a.Ma=a.Ia=Date.now();if(b.subarray&&(!a.va||a.va.subarray)){if(f)return a.va=b.subarray(c,c+d),a.Ca=d;if(0===a.Ca&&0===e)return a.va=b.slice(c,c+d),a.Ca=d;if(e+d<=a.Ca)return a.va.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.va?a.va.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.va,a.va=new Uint8Array(f),0<a.Ca&&a.va.set(g.subarray(0,a.Ca),0));if(a.va.subarray&&b.subarray)a.va.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.va[e+
f]=b[c+f];a.Ca=Math.max(a.Ca,e+d);return d},Na(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ca);if(0>b)throw new N(28);return b},Bb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.va;if(e&2||!a||a.buffer!==w.buffer){d=!0;e=gb(b);if(!e)throw new N(48);if(a){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);w.set(a,e)}}else d=!1,e=a.byteOffset;return{za:e,Wa:d}},ob(a,b,c,d){O.wa.write(a,b,0,d,c,!1);return 0}}},lb=
async a=>{a=await fa(a);return new Uint8Array(a)},mb=[],nb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Jc();var e=!1;mb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},ob=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},pb=null,qb={},rb=[],sb=1,tb=null,ub=!1,vb=!0,wb={},N=class{name="ErrnoError";constructor(a){this.Ja=a}},xb=class{rb={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.rb.flags}set flags(a){this.rb.flags=a}get position(){return this.rb.position}set position(a){this.rb.position=
a}},yb=class{xa={};wa={};qb=365;ub=146;fb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Sa=a.Sa;this.id=sb++;this.name=b;this.mode=c;this.pb=d;this.Xa=this.Ma=this.Ia=Date.now()}get read(){return(this.mode&this.qb)===this.qb}set read(a){a?this.mode|=this.qb:this.mode&=~this.qb}get write(){return(this.mode&this.ub)===this.ub}set write(a){a?this.mode|=this.ub:this.mode&=~this.ub}get kc(){return P(this.mode)}get jc(){return 8192===(this.mode&61440)}};
function zb(a,b={}){if(!a)throw new N(44);b.xb??(b.xb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=pb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ra(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Qa(e+"/"+a[f]);try{d=jb(d,a[f])}catch(h){if(44===h?.Ja&&g&&b.nc)return{path:e};throw h;}!d.fb||g&&!b.xb||(d=d.fb.root);if(40960===(d.mode&61440)&&(!g||b.wb)){if(!d.xa.hb)throw new N(52);
d=d.xa.hb(d);"/"===d.charAt(0)||(d=Ra(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new N(32);}function Ab(a){for(var b;;){if(a===a.parent)return a=a.Sa.Rb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Bb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%tb.length}
function kb(a){var b=Bb(a.parent.id,a.name);if(tb[b]===a)tb[b]=a.$a;else for(b=tb[b];b;){if(b.$a===a){b.$a=a.$a;break}b=b.$a}}function jb(a,b){var c=P(a.mode)?(c=Cb(a,"x"))?c:a.xa.eb?0:2:54;if(c)throw new N(c);for(c=tb[Bb(a.id,b)];c;c=c.$a){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.xa.eb(a,b)}function ib(a,b,c,d){a=new yb(a,b,c,d);b=Bb(a.parent.id,a.name);a.$a=tb[b];return tb[b]=a}function P(a){return 16384===(a&61440)}
function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cb(a,b){if(vb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Eb(a,b){if(!P(a.mode))return 54;try{return jb(a,b),20}catch(c){}return Cb(a,"wx")}function Q(a){a=rb[a];if(!a)throw new N(8);return a}
function Fb(a,b=-1){a=Object.assign(new xb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!rb[b])break a;throw new N(33);}a.Ua=b;return rb[b]=a}function Gb(a,b=-1){a=Fb(a,b);a.wa?.Fc?.(a);return a}function Hb(a,b){var c=null?.wa.Ra,d=c?null:a;c??=a.xa.Ra;if(!c)throw new N(63);c(d,b)}var hb={open(a){a.wa=qb[a.node.pb].wa;a.wa.open?.(a)},Na(){throw new N(70);}};function bb(a,b){qb[a]={wa:b}}
function Ib(a,b){var c="/"===b;if(c&&pb)throw new N(10);if(!c&&b){var d=zb(b,{xb:!1});b=d.path;d=d.node;if(d.fb)throw new N(10);if(!P(d.mode))throw new N(54);}b={type:a,Mc:{},Rb:b,mc:[]};a=a.Sa(b);a.Sa=b;b.root=a;c?pb=a:d&&(d.fb=b,d.Sa&&d.Sa.mc.push(b))}function Jb(a,b,c){var d=zb(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new N(28);if("."===a||".."===a)throw new N(20);var e=Eb(d,a);if(e)throw new N(e);if(!d.xa.nb)throw new N(63);return d.xa.nb(d,a,b,c)}
function Kb(a,b=438){return Jb(a,b&4095|32768,0)}function R(a){return Jb(a,16895,0)}function Lb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Jb(a,b|8192,c)}function Mb(a,b){if(!Ua(a))throw new N(44);var c=zb(b,{parent:!0}).node;if(!c)throw new N(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Eb(c,b);if(d)throw new N(d);if(!c.xa.sb)throw new N(63);c.xa.sb(c,b,a)}
function Nb(a){var b=zb(a,{parent:!0}).node;if(!b)throw new N(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=jb(b,a);a:{try{var d=jb(b,a)}catch(f){d=f.Ja;break a}var e=Cb(b,"wx");d=e?e:P(d.mode)?31:0}if(d)throw new N(d);if(!b.xa.tb)throw new N(63);if(c.fb)throw new N(10);b.xa.tb(b,a);kb(c)}function Ob(a,b){a="string"==typeof a?zb(a,{wb:!0}).node:a;Hb(a,{mode:b&4095|a.mode&-4096,Ia:Date.now(),Ec:void 0})}
function Pb(a,b,c=438){if(""===a)throw new N(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=zb(a,{wb:!(b&131072),nc:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new N(20);}else{if(e)throw new N(31);d=Jb(a,c|511,0);f=!0}if(!d)throw new N(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!P(d.mode))throw new N(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:P(d.mode)&&("r"!==Db(b)||b&576)?31:Cb(d,Db(b)):44))throw new N(e);if(b&512&&!f){e=d;e="string"==typeof e?zb(e,{wb:!0}).node:e;if(P(e.mode))throw new N(31);if(32768!==(e.mode&61440))throw new N(28);var g=Cb(e,"w");if(g)throw new N(g);Hb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Fb({node:d,path:Ab(d),flags:b,seekable:!0,position:0,wa:d.wa,wc:[],error:!1});e.wa.open&&e.wa.open(e);f&&Ob(d,c&511);!m.logReadFiles||b&1||a in wb||(wb[a]=1);return e}
function Qb(a){if(null===a.Ua)throw new N(8);a.yb&&(a.yb=null);try{a.wa.close&&a.wa.close(a)}catch(b){throw b;}finally{rb[a.Ua]=null}a.Ua=null}function Rb(a,b,c){if(null===a.Ua)throw new N(8);if(!a.seekable||!a.wa.Na)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.wa.Na(a,b,c);a.wc=[]}
function Sb(a,b,c,d,e,f){if(0>d||0>e)throw new N(28);if(null===a.Ua)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(P(a.node.mode))throw new N(31);if(!a.wa.write)throw new N(28);a.seekable&&a.flags&1024&&Rb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new N(70);b=a.wa.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Tb(a,b){a="string"==typeof a?a:Ab(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Qa(a+"/"+c);try{R(d)}catch(e){if(20!=e.Ja)throw e;}a=d}}return d}function Ub(a,b,c,d){a=Qa(("string"==typeof a?a:Ab(a))+"/"+b);return Kb(a,ob(c,d))}
function Vb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Ab(a),g=b?Qa(a+"/"+b):a);a=ob(d,e);g=Kb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ob(g,a|146);b=Pb(g,577);Sb(b,c,0,c.length,0,f);Qb(b);Ob(g,a)}}
function Wb(a,b,c,d){a=Qa(("string"==typeof a?a:Ab(a))+"/"+b);b=ob(!!c,!!d);Wb.Qb??(Wb.Qb=64);var e=Wb.Qb++<<8|0;bb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,l){for(var k=0,t=0;t<l;t++){try{var n=c()}catch(p){throw new N(29);}if(void 0===n&&0===k)throw new N(6);if(null===n||void 0===n)break;k++;g[h+t]=n}k&&(f.node.Xa=Date.now());return k},write(f,g,h,l){for(var k=0;k<l;k++)try{d(g[h+k])}catch(t){throw new N(29);}l&&(f.node.Ma=f.node.Ia=Date.now());return k}});return Lb(a,
b,e)}function Xb(a){if(!(a.jc||a.kc||a.link||a.va)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.va=ha(a.url),a.Ca=a.va.length}catch(b){throw new N(29);}}}
function Yb(a,b,c,d,e){function f(n,p,x,q,u){n=n.node.va;if(u>=n.length)return 0;q=Math.min(n.length-u,q);if(n.slice)for(var z=0;z<q;z++)p[x+z]=n[u+z];else for(z=0;z<q;z++)p[x+z]=n.get(u+z);return q}class g{Ab=!1;jb=[];cb=void 0;Ib=0;Hb=0;get(n){if(!(n>this.length-1||0>n)){var p=n%this.Lb;return this.cb(n/this.Lb|0)[p]}}rc(n){this.cb=n}Jb(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);
var p=Number(n.getResponseHeader("Content-length")),x,q=(x=n.getResponseHeader("Accept-Ranges"))&&"bytes"===x;n=(x=n.getResponseHeader("Content-Encoding"))&&"gzip"===x;var u=1048576;q||(u=p);var z=this;z.rc(I=>{var F=I*u,H=(I+1)*u-1;H=Math.min(H,p-1);if("undefined"==typeof z.jb[I]){var v=z.jb;if(F>H)throw Error("invalid range ("+F+", "+H+") or no bytes requested!");if(H>p-1)throw Error("only "+p+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",c,!1);p!==u&&G.setRequestHeader("Range",
"bytes="+F+"-"+H);G.responseType="arraybuffer";G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);F=void 0!==G.response?new Uint8Array(G.response||[]):Za(G.responseText||"");v[I]=F}if("undefined"==typeof z.jb[I])throw Error("doXHR failed!");return z.jb[I]});if(n||!p)u=p=1,u=p=this.cb(0).length,ia("LazyFiles on gzip forces download of the whole file when length is accessed");
this.Ib=p;this.Hb=u;this.Ab=!0}get length(){this.Ab||this.Jb();return this.Ib}get Lb(){this.Ab||this.Jb();return this.Hb}}if("undefined"!=typeof XMLHttpRequest){if(!ba)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var l=void 0}else l=c,h=void 0;var k=Ub(a,b,d,e);h?k.va=h:l&&(k.va=null,k.url=l);Object.defineProperties(k,{Ca:{get:function(){return this.va.length}}});var t={};Object.keys(k.wa).forEach(n=>{var p=
k.wa[n];t[n]=(...x)=>{Xb(k);return p(...x)}});t.read=(n,p,x,q,u)=>{Xb(k);return f(n,p,x,q,u)};t.Bb=(n,p,x)=>{Xb(k);var q=gb(p);if(!q)throw new N(48);f(n,w,q,p,x);return{za:q,Wa:!0}};k.wa=t;return k}var Zb={},$b=(a,b,c)=>a?L(y,a,b,c):"",Oa=void 0,ac={},bc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function cc(a){return this.Da(D[a>>2])}
var dc={},ec={},fc={},gc=class extends Error{constructor(a){super(a);this.name="InternalError"}},hc=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new gc("Mismatched type converter count");for(var l=0;l<a.length;++l)S(a[l],h[l])}a.forEach(h=>fc[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,l)=>{ec.hasOwnProperty(h)?e[l]=ec[h]:(f.push(h),dc.hasOwnProperty(h)||(dc[h]=[]),dc[h].push(()=>{e[l]=ec[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},T=a=>{for(var b="";;){var c=y[a++];if(!c)return b;
b+=String.fromCharCode(c)}},U=class extends Error{constructor(a){super(a);this.name="BindingError"}};function ic(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(ec.hasOwnProperty(a)){if(c.dc)return;throw new U(`Cannot register type '${d}' twice`);}ec[a]=b;delete fc[a];dc.hasOwnProperty(a)&&(b=dc[a],delete dc[a],b.forEach(e=>e()))}function S(a,b,c={}){return ic(a,b,c)}
var jc=(a,b,c)=>{switch(b){case 1:return c?d=>w[d]:d=>y[d];case 2:return c?d=>A[d>>1]:d=>pa[d>>1];case 4:return c?d=>B[d>>2]:d=>D[d>>2];case 8:return c?d=>sa[d>>3]:d=>ta[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},kc=a=>{throw new U(a.ua.Ba.ya.name+" instance already deleted");},lc=!1,mc=()=>{},nc=a=>{if("undefined"===typeof FinalizationRegistry)return nc=b=>b,a;lc=new FinalizationRegistry(b=>{b=b.ua;--b.count.value;0===b.count.value&&(b.Fa?b.Ka.Pa(b.Fa):b.Ba.ya.Pa(b.za))});
nc=b=>{var c=b.ua;c.Fa&&lc.register(b,{ua:c},b);return b};mc=b=>{lc.unregister(b)};return nc(a)},oc=[];function pc(){}
var qc=(a,b)=>Object.defineProperty(b,"name",{value:a}),rc={},sc=(a,b,c)=>{if(void 0===a[b].Ea){var d=a[b];a[b]=function(...e){if(!a[b].Ea.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Ea})!`);return a[b].Ea[e.length].apply(this,e)};a[b].Ea=[];a[b].Ea[d.ab]=d}},tc=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].Ea&&void 0!==m[a].Ea[c])throw new U(`Cannot register public name '${a}' twice`);sc(m,
a,a);if(m[a].Ea.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);m[a].Ea[c]=b}else m[a]=b,m[a].ab=c},uc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function vc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Za=c;this.Pa=d;this.Ha=e;this.$b=f;this.ib=g;this.Yb=h;this.pc=[]}
var wc=(a,b,c)=>{for(;b!==c;){if(!b.ib)throw new U(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ib(a);b=b.Ha}return a},xc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function yc(a,b){if(null===b){if(this.zb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.ua)throw new U(`Cannot pass "${xc(b)}" as a ${this.name}`);if(!b.ua.za)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return wc(b.ua.za,b.ua.Ba.ya,this.ya)}
function zc(a,b){if(null===b){if(this.zb)throw new U(`null is not a valid ${this.name}`);if(this.mb){var c=this.Db();null!==a&&a.push(this.Pa,c);return c}return 0}if(!b||!b.ua)throw new U(`Cannot pass "${xc(b)}" as a ${this.name}`);if(!b.ua.za)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.lb&&b.ua.Ba.lb)throw new U(`Cannot convert argument of type ${b.ua.Ka?b.ua.Ka.name:b.ua.Ba.name} to parameter type ${this.name}`);c=wc(b.ua.za,b.ua.Ba.ya,this.ya);if(this.mb){if(void 0===
b.ua.Fa)throw new U("Passing raw pointer to smart pointer is illegal");switch(this.vc){case 0:if(b.ua.Ka===this)c=b.ua.Fa;else throw new U(`Cannot convert argument of type ${b.ua.Ka?b.ua.Ka.name:b.ua.Ba.name} to parameter type ${this.name}`);break;case 1:c=b.ua.Fa;break;case 2:if(b.ua.Ka===this)c=b.ua.Fa;else{var d=b.clone();c=this.qc(c,V(()=>d["delete"]()));null!==a&&a.push(this.Pa,c)}break;default:throw new U("Unsupporting sharing policy");}}return c}
function Ac(a,b){if(null===b){if(this.zb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.ua)throw new U(`Cannot pass "${xc(b)}" as a ${this.name}`);if(!b.ua.za)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ua.Ba.lb)throw new U(`Cannot convert argument of type ${b.ua.Ba.name} to parameter type ${this.name}`);return wc(b.ua.za,b.ua.Ba.ya,this.ya)}
var Bc=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ha)return null;a=Bc(a,b,c.Ha);return null===a?null:c.Yb(a)},Cc={},Dc=(a,b)=>{if(void 0===b)throw new U("ptr should not be undefined");for(;a.Ha;)b=a.ib(b),a=a.Ha;return Cc[b]},Ec=(a,b)=>{if(!b.Ba||!b.za)throw new gc("makeClassHandle requires ptr and ptrType");if(!!b.Ka!==!!b.Fa)throw new gc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return nc(Object.create(a,{ua:{value:b,writable:!0}}))};
function Fc(a,b,c,d,e,f,g,h,l,k,t){this.name=a;this.ya=b;this.zb=c;this.lb=d;this.mb=e;this.oc=f;this.vc=g;this.Sb=h;this.Db=l;this.qc=k;this.Pa=t;e||void 0!==b.Ha?this.Ga=zc:(this.Ga=d?yc:Ac,this.La=null)}var Gc=(a,b,c)=>{if(!m.hasOwnProperty(a))throw new gc("Replacing nonexistent public symbol");void 0!==m[a].Ea&&void 0!==c?m[a].Ea[c]=b:(m[a]=b,m[a].ab=c)},W=(a,b)=>{a=T(a);var c=J(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};
class Hc extends Error{}var Kc=a=>{a=Ic(a);var b=T(a);Jc(a);return b},Lc=(a,b)=>{function c(f){e[f]||ec[f]||(fc[f]?fc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Hc(`${a}: `+d.map(Kc).join([", "]));},Mc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c};function Nc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].La)return!0;return!1}
function Oc(a,b,c,d,e){var f=b.length;if(2>f)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,h=Nc(b),l=!b[0].lc,k=f-2,t=Array(k),n=[],p=[];return qc(a,function(...x){p.length=0;n.length=g?2:1;n[0]=e;if(g){var q=b[1].Ga(p,this);n[1]=q}for(var u=0;u<k;++u)t[u]=b[u+2].Ga(p,x[u]),n.push(t[u]);x=d(...n);if(h)bc(p);else for(u=g?1:2;u<b.length;u++){var z=1===u?q:t[u-2];null!==b[u].La&&b[u].La(z)}q=l?b[0].Da(x):void 0;return q})}
var Pc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Qc=[],Rc=[0,1,,1,null,1,!0,1,!1,1],Sc=a=>{9<a&&0===--Rc[a+1]&&(Rc[a]=void 0,Qc.push(a))},X=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return Rc[a]},V=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Qc.pop()||Rc.length;Rc[b]=a;Rc[b+1]=1;return b}},Tc={name:"emscripten::val",Da:a=>{var b=X(a);Sc(a);return b},Ga:(a,b)=>V(b),Qa:cc,La:null},Uc=(a,b)=>{switch(b){case 4:return function(c){return this.Da(qa[c>>
2])};case 8:return function(c){return this.Da(ra[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Vc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Wc=(a,b,c)=>{a>>=1;b=Wa(pa,a,b/2,c);if(16<b-a&&Vc)return Vc.decode(pa.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(pa[a]);return c},Xc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},Yc=a=>2*a.length,
Zc=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=D[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},$c=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},ad=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},bd=0,cd=[],dd=a=>{var b=cd.length;cd.push(a);return b},ed=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=D[b+4*d>>2],g=ec[f];
if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Kc(f)}`,new U(a);c[e]=g}return c},fd={},gd=a=>{var b=fd[a];return void 0===b?T(a):b},hd=a=>0===a%4&&(0!==a%100||0===a%400),jd=[0,31,60,91,121,152,182,213,244,274,305,335],kd=[0,31,59,90,120,151,181,212,243,273,304,334],ld={},md=a=>{if(!(a instanceof Fa||"unwind"==a))throw a;},nd=a=>{la=a;La||0<bd||(m.onExit?.(a),ka=!0);throw new Fa(a);},od=a=>{if(!ka)try{if(a(),!(La||0<bd))try{la=a=la,nd(a)}catch(b){md(b)}}catch(b){md(b)}},pd=[];
function qd(a){var b=Y,c=b.Ob.pop()||b.Wa.length;b.Wa[c]=a;return c}class rd{Wa=[void 0];Ob=[];get(a){return this.Wa[a]}has(a){return void 0!==this.Wa[a]}}var Y,sd;
function td(a,b,c,d,e){function f(){var E=0,C=0;v.response&&I&&0===D[a+12>>2]&&(C=v.response.byteLength);0<C&&(E=ud(C),y.set(new Uint8Array(v.response),E));D[a+12>>2]=E;Z(a+16,C);Z(a+24,0);(E=v.response?v.response.byteLength:0)&&Z(a+32,E);A[a+40>>1]=v.readyState;A[a+42>>1]=v.status;v.statusText&&M(v.statusText,y,a+44,64);H&&(E=vd(v.responseURL),D[a+200>>2]=E)}var g=D[a+8>>2];if(g){var h=g?L(y,g):"",l=a+108,k=$b(l+0);k||="GET";var t=D[l+56>>2],n=D[l+68>>2],p=D[l+72>>2];g=D[l+76>>2];var x=D[l+80>>2],
q=D[l+84>>2],u=D[l+88>>2],z=D[l+52>>2],I=!!(z&1),F=!!(z&2),H=!!(z&64);n=n?n?L(y,n):"":void 0;p=p?p?L(y,p):"":void 0;var v=new XMLHttpRequest;v.withCredentials=!!y[l+60];v.open(k,h,!H,n,p);H||(v.timeout=t);v.Oc=h;v.responseType="arraybuffer";x&&(h=x?L(y,x):"",v.overrideMimeType(h));if(g)for(;;){l=D[g>>2];if(!l)break;h=D[g+4>>2];if(!h)break;g+=8;l=l?L(y,l):"";h=h?L(y,h):"";v.setRequestHeader(l,h)}var G=qd(v);D[a>>2]=G;g=q&&u?y.slice(q,q+u):null;v.onload=E=>{Y.has(G)&&(f(),200<=v.status&&300>v.status?
b?.(a,v,E):c?.(a,v,E))};v.onerror=E=>{Y.has(G)&&(f(),c?.(a,v,E))};v.ontimeout=E=>{Y.has(G)&&c?.(a,v,E)};v.onprogress=E=>{if(Y.has(G)){var C=I&&F&&v.response?v.response.byteLength:0,da=0;0<C&&I&&F&&(da=ud(C),y.set(new Uint8Array(v.response),da));D[a+12>>2]=da;Z(a+16,C);Z(a+24,E.loaded-C);Z(a+32,E.total);A[a+40>>1]=v.readyState;3<=v.readyState&&0===v.status&&0<E.loaded&&(v.status=200);A[a+42>>1]=v.status;v.statusText&&M(v.statusText,y,a+44,64);d?.(a,v,E);Jc(da)}};v.onreadystatechange=E=>{if(Y.has(G)){A[a+
40>>1]=v.readyState;2<=v.readyState&&(A[a+42>>1]=v.status);if(!H&&2===v.readyState&&0<v.responseURL.length){var C=vd(v.responseURL);D[a+200>>2]=C}e?.(a,v,E)}};try{v.send(g)}catch(E){c?.(a,v,E)}}else c(a,0,"no url specified!")}var Z=(a,b)=>{D[a>>2]=b;D[a+4>>2]=(b-D[a>>2])/4294967296},vd=a=>{var b=Ya(a)+1,c=ud(b);c&&M(a,y,c,b);return c};
function wd(a,b,c,d){var e=sd;if(e){var f=D[a+108+64>>2];f||=D[a+8>>2];var g=f?L(y,f):"";try{var h=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);h.onsuccess=()=>{A[a+40>>1]=4;A[a+42>>1]=200;M("OK",y,a+44,64);c(a,0,g)};h.onerror=l=>{A[a+40>>1]=4;A[a+42>>1]=413;M("Payload Too Large",y,a+44,64);d(a,0,l)}}catch(l){d(a,0,l)}}else d(a,0,"IndexedDB not available!")}
function xd(a,b,c){var d=sd;if(d){var e=D[a+108+64>>2];e||=D[a+8>>2];e=e?L(y,e):"";try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var h=g.byteLength||g.length,l=ud(h);y.set(new Uint8Array(g),l);D[a+12>>2]=l;Z(a+16,h);Z(a+24,0);Z(a+32,h);A[a+40>>1]=4;A[a+42>>1]=200;M("OK",y,a+44,64);b(a,0,g)}else A[a+40>>1]=4,A[a+42>>1]=404,M("Not Found",y,a+44,64),c(a,0,"no data")};f.onerror=g=>{A[a+40>>1]=4;A[a+42>>1]=404;M("Not Found",
y,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function yd(a,b,c){var d=sd;if(d){var e=D[a+108+64>>2];e||=D[a+8>>2];e=e?L(y,e):"";try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;D[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);A[a+40>>1]=4;A[a+42>>1]=200;M("OK",y,a+44,64);b(a,0,g)};f.onerror=g=>{A[a+40>>1]=4;A[a+42>>1]=404;M("Not Found",y,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var zd={},Bd=()=>{if(!Ad){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in zd)void 0===zd[b]?delete a[b]:a[b]=zd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ad=c}return Ad},Ad;tb=Array(4096);Ib(O,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");bb(259,{read:()=>0,write:(d,e,f,g)=>g,Na:()=>0});Lb("/dev/null",259);ab(1280,db);ab(1536,eb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ta(a),b=a.byteLength);return a[--b]};Wb("/dev","random",c);Wb("/dev","urandom",c);R("/dev/shm");R("/dev/shm/tmp")})();
(function(){R("/proc");var a=R("/proc/self");R("/proc/self/fd");Ib({Sa(){var b=ib(a,"fd",16895,73);b.wa={Na:O.wa.Na};b.xa={eb(c,d){c=+d;var e=Q(c);c={parent:null,Sa:{Rb:"fake"},xa:{hb:()=>e.path},id:c+1};return c.parent=c},Eb(){return Array.from(rb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();
(()=>{let a=pc.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof pc&&c instanceof pc))return!1;var d=this.ua.Ba.ya,e=this.ua.za;c.ua=c.ua;var f=c.ua.Ba.ya;for(c=c.ua.za;d.Ha;)e=d.ib(e),d=d.Ha;for(;f.Ha;)c=f.ib(c),f=f.Ha;return d===f&&e===c},clone:function(){this.ua.za||kc(this);if(this.ua.gb)return this.ua.count.value+=1,this;var c=nc,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.ua;c=c(e.call(d,f,{ua:{value:{count:g.count,bb:g.bb,gb:g.gb,za:g.za,Ba:g.Ba,Fa:g.Fa,Ka:g.Ka}}}));
c.ua.count.value+=1;c.ua.bb=!1;return c},["delete"](){this.ua.za||kc(this);if(this.ua.bb&&!this.ua.gb)throw new U("Object already scheduled for deletion");mc(this);var c=this.ua;--c.count.value;0===c.count.value&&(c.Fa?c.Ka.Pa(c.Fa):c.Ba.ya.Pa(c.za));this.ua.gb||(this.ua.Fa=void 0,this.ua.za=void 0)},isDeleted:function(){return!this.ua.za},deleteLater:function(){this.ua.za||kc(this);if(this.ua.bb&&!this.ua.gb)throw new U("Object already scheduled for deletion");oc.push(this);this.ua.bb=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Fc.prototype,{ac(a){this.Sb&&(a=this.Sb(a));return a},Mb(a){this.Pa?.(a)},Qa:cc,Da:function(a){function b(){return this.mb?Ec(this.ya.Za,{Ba:this.oc,za:c,Ka:this,Fa:a}):Ec(this.ya.Za,{Ba:this,za:a})}var c=this.ac(a);if(!c)return this.Mb(a),null;var d=Dc(this.ya,c);if(void 0!==d){if(0===d.ua.count.value)return d.ua.za=c,d.ua.Fa=a,d.clone();d=d.clone();this.Mb(a);return d}d=this.ya.$b(c);d=rc[d];if(!d)return b.call(this);d=this.lb?d.Xb:d.pointerType;var e=Bc(c,this.ya,d.ya);return null===
e?b.call(this):this.mb?Ec(d.ya.Za,{Ba:d,za:e,Ka:this,Fa:a}):Ec(d.ya.Za,{Ba:d,za:e})}});Y=new rd;ya("library_fetch_init");(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})(a=>{sd=a;za("library_fetch_init")},()=>{sd=!1;za("library_fetch_init")});m.noExitRuntime&&(La=m.noExitRuntime);
m.preloadPlugins&&(mb=m.preloadPlugins);m.print&&(ia=m.print);m.printErr&&(r=m.printErr);m.wasmBinary&&(ja=m.wasmBinary);m.thisProgram&&(ca=m.thisProgram);m.addRunDependency=ya;m.removeRunDependency=za;m.FS_createPreloadedFile=(a,b,c,d,e,f,g,h,l,k)=>{function t(x){function q(u){k?.();h||Vb(a,b,u,d,e,l);f?.();za(p)}nb(x,n,q,()=>{g?.();za(p)})||q(x)}var n=b?Ua(Qa(a+"/"+b)):a,p=`cp ${n}`;ya(p);"string"==typeof c?lb(c).then(t,g):t(c)};m.FS_unlink=(...a)=>Nb(...a);m.FS_createPath=(...a)=>Tb(...a);
m.FS_createDevice=(...a)=>Wb(...a);m.FS_createDataFile=(...a)=>Vb(...a);m.FS_createLazyFile=(...a)=>Yb(...a);
var Cd={183306:a=>{a=a?L(y,a):"";throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},183442:(a,b,c,d)=>{a=a?L(y,a):"";b=b?L(y,b):"";c=c?L(y,c):"";d=d?L(y,d):"";throw Error(a+b+c+d);},183658:(a,b)=>{a=a?L(y,a):"";b=b?L(y,b):"";throw Error(a+b);},183768:a=>{throw Error(a?L(y,a):"");},183811:()=>{throw Error("Unable to perform that operation while recognizer is in use!");}},Ic,Jc,ud,fb,Dd,Ed,Fd,Gd;m.__ZN2MB2NN28LinearDefragmentingAllocator10Allocation4nullE=1024;
var Ld={E:(a,b)=>J(a)(b),u:function(a,b,c){Oa=c;try{var d=Q(a);switch(b){case 0:var e=K();if(0>e)break;for(;rb[e];)e++;return Gb(d,e).Ua;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=K(),d.flags|=e,0;case 12:return e=K(),A[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Zb||"ErrnoError"!==f.name)throw f;return-f.Ja}},V:function(a,b,c){Oa=c;try{var d=Q(a);switch(b){case 21509:return d.Aa?0:-59;case 21505:if(!d.Aa)return-59;if(d.Aa.Ta.fc){a=[3,28,127,21,
4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=K();B[e>>2]=25856;B[e+4>>2]=5;B[e+8>>2]=191;B[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Aa?0:-59;case 21506:case 21507:case 21508:if(!d.Aa)return-59;if(d.Aa.Ta.hc)for(e=K(),a=[],f=0;32>f;f++)a.push(w[e+f+17]);return 0;case 21519:if(!d.Aa)return-59;e=K();return B[e>>2]=0;case 21520:return d.Aa?-28:-59;case 21537:case 21531:e=K();if(!d.wa.ec)throw new N(59);return d.wa.ec(d,
b,e);case 21523:if(!d.Aa)return-59;d.Aa.Ta.ic&&(f=[24,80],e=K(),A[e>>1]=f[0],A[e+2>>1]=f[1]);return 0;case 21524:return d.Aa?0:-59;case 21515:return d.Aa?0:-59;default:return-28}}catch(g){if("undefined"==typeof Zb||"ErrnoError"!==g.name)throw g;return-g.Ja}},v:function(a,b,c,d){Oa=d;try{b=b?L(y,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Q(a).path;if(0==e.length)throw new N(44);b=f+"/"+e}var g=d?K():0;return Pb(b,c,g).Ua}catch(h){if("undefined"==typeof Zb||"ErrnoError"!==h.name)throw h;
return-h.Ja}},W:()=>Aa(""),f:a=>{var b=ac[a];delete ac[a];var c=b.Db,d=b.Pa,e=b.Nb,f=e.map(g=>g.cc).concat(e.map(g=>g.tc));hc([a],f,g=>{var h={};e.forEach((l,k)=>{var t=g[k],n=l.cb,p=l.bc,x=g[k+e.length],q=l.sc,u=l.uc;h[l.Zb]={read:z=>t.Da(n(p,z)),write:(z,I)=>{var F=[];q(u,z,x.Ga(F,I));bc(F)},optional:g[k].optional}});return[{name:b.name,Da:l=>{var k={},t;for(t in h)k[t]=h[t].read(l);d(l);return k},Ga:(l,k)=>{for(var t in h)if(!(t in k||h[t].optional))throw new TypeError(`Missing field: "${t}"`);
var n=c();for(t in h)h[t].write(n,k[t]);null!==l&&l.push(d,n);return n},Qa:cc,La:d}]})},y:(a,b,c,d,e)=>{b=T(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}S(a,{name:b,Da:f,Ga:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},Qa:jc(b,c,!d),La:null})},ha:(a,b,c,d)=>{b=T(b);S(a,{name:b,Da:function(e){return!!e},Ga:function(e,f){return f?c:d},Qa:function(e){return this.Da(y[e])},La:null})},j:(a,b,c,d,e,f,g,h,l,k,t,n,p)=>{t=T(t);f=W(e,f);h&&=W(g,h);k&&=W(l,k);p=W(n,p);var x=
uc(t);tc(x,function(){Lc(`Cannot construct ${t} due to unbound types`,[d])});hc([a,b,c],d?[d]:[],q=>{q=q[0];if(d){var u=q.ya;var z=u.Za}else z=pc.prototype;q=qc(t,function(...v){if(Object.getPrototypeOf(this)!==I)throw new U(`Use 'new' to construct ${t}`);if(void 0===F.Ya)throw new U(`${t} has no accessible constructor`);var G=F.Ya[v.length];if(void 0===G)throw new U(`Tried to invoke ctor of ${t} with invalid number of parameters (${v.length}) - expected (${Object.keys(F.Ya).toString()}) parameters instead!`);
return G.apply(this,v)});var I=Object.create(z,{constructor:{value:q}});q.prototype=I;var F=new vc(t,q,I,p,u,f,h,k);if(F.Ha){var H;(H=F.Ha).Gb??(H.Gb=[]);F.Ha.Gb.push(F)}u=new Fc(t,F,!0,!1,!1);H=new Fc(t+"*",F,!1,!1,!1);z=new Fc(t+" const*",F,!1,!0,!1);rc[a]={pointerType:H,Xb:z};Gc(x,q);return[u,H,z]})},o:(a,b,c,d,e,f)=>{var g=Mc(b,c);e=W(d,e);hc([],[a],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.ya.Ya&&(h.ya.Ya=[]);if(void 0!==h.ya.Ya[b-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.ya.Ya[b-1]=()=>{Lc(`Cannot construct ${h.name} due to unbound types`,g)};hc([],g,k=>{k.splice(1,0,null);h.ya.Ya[b-1]=Oc(l,k,null,e,f);return[]});return[]})},g:(a,b,c,d,e,f,g,h)=>{var l=Mc(c,d);b=T(b);b=Pc(b);f=W(e,f);hc([],[a],k=>{function t(){Lc(`Cannot call ${n} due to unbound types`,l)}k=k[0];var n=`${k.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&k.ya.pc.push(b);
var p=k.ya.Za,x=p[b];void 0===x||void 0===x.Ea&&x.className!==k.name&&x.ab===c-2?(t.ab=c-2,t.className=k.name,p[b]=t):(sc(p,b,n),p[b].Ea[c-2]=t);hc([],l,q=>{q=Oc(n,q,k,f,g);void 0===p[b].Ea?(q.ab=c-2,p[b]=q):p[b].Ea[c-2]=q;return[]});return[]})},fa:a=>S(a,Tc),x:(a,b,c)=>{b=T(b);S(a,{name:b,Da:d=>d,Ga:(d,e)=>e,Qa:Uc(b,c),La:null})},q:(a,b,c,d,e,f)=>{var g=Mc(b,c);a=T(a);a=Pc(a);e=W(d,e);tc(a,function(){Lc(`Cannot call ${a} due to unbound types`,g)},b-1);hc([],g,h=>{Gc(a,Oc(a,[h[0],null].concat(h.slice(1)),
null,e,f),b-1);return[]})},h:(a,b,c,d,e)=>{b=T(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}S(a,{name:b,Da:f,Ga:(h,l)=>l,Qa:jc(b,c,0!==d),La:null})},d:(a,b,c)=>{function d(f){return new e(w.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=T(c);S(a,{name:c,Da:d,Qa:d},{dc:!0})},ga:(a,b)=>{b=T(b);S(a,{name:b,Da(c){var d=$b(c+4,D[c>>2],!0);Jc(c);return d},Ga(c,d){d instanceof ArrayBuffer&&
(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var f=e?Ya(d):d.length;var g=ud(4+f+1),h=g+4;D[g>>2]=f;e?M(d,y,h,f+1):y.set(d,h);null!==c&&c.push(Jc,g);return g},Qa:cc,La(c){Jc(c)}})},p:(a,b,c)=>{c=T(c);if(2===b){var d=Wc;var e=Xc;var f=Yc}else d=Zc,e=$c,f=ad;S(a,{name:c,Da:g=>{var h=d(g+4,D[g>>2]*b,!0);Jc(g);return h},Ga:(g,h)=>{if("string"!=typeof h)throw new U(`Cannot pass non-string to C++ string type ${c}`);
var l=f(h),k=ud(4+l+b);D[k>>2]=l/b;e(h,k+4,l+b);null!==g&&g.push(Jc,k);return k},Qa:cc,La(g){Jc(g)}})},e:(a,b,c,d,e,f)=>{ac[a]={name:T(b),Db:W(c,d),Pa:W(e,f),Nb:[]}},a:(a,b,c,d,e,f,g,h,l,k)=>{ac[a].Nb.push({Zb:T(b),cc:c,cb:W(d,e),bc:f,tc:g,sc:W(h,l),uc:k})},ia:(a,b)=>{b=T(b);S(a,{lc:!0,name:b,Da:()=>{},Ga:()=>{}})},G:()=>{La=!1;bd=0},D:()=>{throw Infinity;},c:(a,b,c)=>{var [d,...e]=ed(a,b),f=d.Ga.bind(d),g=e.map(l=>l.Qa.bind(l));a--;var h=Array(a);b=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;
return dd(qc(b,(l,k,t,n)=>{for(var p=0,x=0;x<a;++x)h[x]=g[x](n+p),p+=8;switch(c){case 0:var q=X(l).apply(null,h);break;case 2:q=Reflect.construct(X(l),h);break;case 3:q=h[0];break;case 1:q=X(l)[gd(k)](...h)}l=[];q=f(l,q);l.length&&(D[t>>2]=V(l));return q}))},U:Sc,aa:(a,b)=>{a=X(a);b=X(b);return a==b},da:a=>{if(0===a)return V(globalThis);a=gd(a);return V(globalThis[a])},n:(a,b)=>{a=X(a);b=X(b);return V(a[b])},w:a=>{9<a&&(Rc[a+1]+=1)},b:(a,b,c,d,e)=>cd[a](b,c,d,e),M:()=>V([]),ea:a=>V(gd(a)),ca:()=>
V({}),z:a=>{var b=X(a);bc(b);Sc(a)},i:(a,b,c)=>{a=X(a);b=X(b);c=X(c);a[b]=c},ba:a=>{a=X(a);return V(typeof a)},N:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();B[b+28>>2]=(hd(a.getFullYear())?jd:kd)[a.getMonth()]+a.getDate()-1|0;B[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();B[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},O:function(a){var b=new Date(B[a+20>>2]+1900,B[a+16>>2],B[a+12>>2],B[a+8>>2],B[a+4>>2],B[a>>2],0),c=B[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?B[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));
B[a+24>>2]=b.getDay();B[a+28>>2]=(hd(b.getFullYear())?jd:kd)[b.getMonth()]+b.getDate()-1|0;B[a>>2]=b.getSeconds();B[a+4>>2]=b.getMinutes();B[a+8>>2]=b.getHours();B[a+12>>2]=b.getDate();B[a+16>>2]=b.getMonth();B[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},L:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=Q(e);if(c&2){if(32768!==(g.node.mode&61440))throw new N(43);d&2||g.wa.ob&&g.wa.ob(g,y.slice(a,a+b),f,b,d)}}catch(h){if("undefined"==
typeof Zb||"ErrnoError"!==h.name)throw h;return-h.Ja}},H:(a,b)=>{ld[a]&&(clearTimeout(ld[a].id),delete ld[a]);if(!b)return 0;var c=setTimeout(()=>{delete ld[a];od(()=>Dd(a,performance.now()))},b);ld[a]={id:c,Nc:b};return 0},P:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(f,e);B[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,
"0")}`};a=b(f);b=b(e);e<f?(M(a,y,c,17),M(b,y,d,17)):(M(a,y,d,17),M(b,y,c,17))},Q:function(a,b,c){if(!(0<=a&&3>=a))return 28;sa[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},k:(a,b,c)=>{pd.length=0;for(var d;d=y[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;pd.push(112==d?D[c>>2]:106==d?sa[c>>3]:105==d?B[c>>2]:ra[c>>3]);c+=e?8:4}return Cd[a](...pd)},X:function(a){if(Y.has(a)){var b=Y.get(a),c=Y;c.Wa[a]=void 0;c.Ob.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},K:()=>
2147483648,l:()=>performance.now(),Z:()=>!ba,J:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){a:{var d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,b+2097152/c)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);va();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Y:function(a,b,c,d,e){function f(C){p?C():od(C)}var g=a+108,h=D[g+36>>2],l=D[g+40>>2],k=D[g+44>>2],t=D[g+48>>2],n=D[g+52>>2],p=!!(n&64),x=C=>{f(()=>{h?J(h)(C):b?.(C)})},q=C=>{f(()=>{k?J(k)(C):
d?.(C)})},u=C=>{f(()=>{l?J(l)(C):c?.(C)})},z=C=>{f(()=>{t?J(t)(C):e?.(C)})},I=C=>{td(C,x,u,q,z)},F=(C,da)=>{wd(C,da.response,Ja=>{f(()=>{h?J(h)(Ja):b?.(Ja)})},Ja=>{f(()=>{h?J(h)(Ja):b?.(Ja)})})},H=C=>{td(C,F,u,q,z)},v=$b(g+0),G=!!(n&16),E=!!(n&4);n=!!(n&32);if("EM_IDB_STORE"===v)I=D[g+84>>2],wd(a,y.slice(I,I+D[g+88>>2]),x,u);else if("EM_IDB_DELETE"===v)yd(a,x,u);else if(G){if(n)return 0;td(a,E?F:x,u,q,z)}else xd(a,x,n?u:E?H:I);return a},S:(a,b)=>{var c=0,d=0,e;for(e of Bd()){var f=b+c;D[a+d>>2]=f;
c+=M(e,y,f,Infinity)+1;d+=4}return 0},T:(a,b)=>{var c=Bd();D[a>>2]=c.length;a=0;for(var d of c)a+=Ya(d)+1;D[b>>2]=a;return 0},$:a=>{la=a;nd(a)},m:function(a){try{var b=Q(a);Qb(b);return 0}catch(c){if("undefined"==typeof Zb||"ErrnoError"!==c.name)throw c;return c.Ja}},t:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],l=D[a+4>>2];a+=8;var k=e,t=h,n=l,p=f,x=w;if(0>n||0>p)throw new N(28);if(null===k.Ua)throw new N(8);if(1===(k.flags&2097155))throw new N(8);if(P(k.node.mode))throw new N(31);
if(!k.wa.read)throw new N(28);var q="undefined"!=typeof p;if(!q)p=k.position;else if(!k.seekable)throw new N(70);var u=k.wa.read(k,x,t,n,p);q||(k.position+=u);var z=u;if(0>z){var I=-1;break a}b+=z;if(z<l)break;"undefined"!=typeof f&&(f+=z)}I=b}D[d>>2]=I;return 0}catch(F){if("undefined"==typeof Zb||"ErrnoError"!==F.name)throw F;return F.Ja}},R:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Q(a);Rb(e,b,c);sa[d>>3]=BigInt(e.position);e.yb&&0===
b&&0===c&&(e.yb=null);return 0}catch(f){if("undefined"==typeof Zb||"ErrnoError"!==f.name)throw f;return f.Ja}},s:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],l=D[a+4>>2];a+=8;var k=Sb(e,w,h,l,f);if(0>k){var t=-1;break a}b+=k;if(k<l)break;"undefined"!=typeof f&&(f+=k)}t=b}D[d>>2]=t;return 0}catch(n){if("undefined"==typeof Zb||"ErrnoError"!==n.name)throw n;return n.Ja}},_:function(){var a=stackTrace(),b=Ya(a)+1,c=ud(b);M(a,y,c,b);return c},A:Hd,r:Id,B:Jd,C:Kd,F:nd,
I:function(a,b){try{return Ta(y.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Zb||"ErrnoError"!==c.name)throw c;return c.Ja}}},Md=await (async function(){function a(c){Md=c.exports;oa=Md.ja;va();Na=Md.oa;c=Md;Ic=c.la;Jc=c.ma;ud=c.na;fb=c.pa;Dd=c.qa;Ed=c.ra;Fd=c.sa;Gd=c.ta;za("wasm-instantiate");return Md}ya("wasm-instantiate");var b={a:Ld};if(m.instantiateWasm)return new Promise(c=>{m.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Ba??=m.locateFile?m.locateFile("BlinkCardWasmSDK.wasm",ea):
ea+"BlinkCardWasmSDK.wasm";return a((await Ea(b)).instance)}());function Id(a,b){var c=Gd();try{J(a)(b)}catch(d){Fd(c);if(d!==d+0)throw d;Ed(1,0)}}function Kd(a,b,c,d){var e=Gd();try{J(a)(b,c,d)}catch(f){Fd(e);if(f!==f+0)throw f;Ed(1,0)}}function Jd(a,b,c){var d=Gd();try{J(a)(b,c)}catch(e){Fd(d);if(e!==e+0)throw e;Ed(1,0)}}function Hd(a,b,c,d){var e=Gd();try{return J(a)(b,c,d)}catch(f){Fd(e);if(f!==f+0)throw f;Ed(1,0)}}
function Nd(){function a(){m.calledRun=!0;if(!ka){ua=!0;if(!m.noFSInit&&!ub){var b,c;ub=!0;b??=m.stdin;c??=m.stdout;d??=m.stderr;b?Wb("/dev","stdin",b):Mb("/dev/tty","/dev/stdin");c?Wb("/dev","stdout",null,c):Mb("/dev/tty","/dev/stdout");d?Wb("/dev","stderr",null,d):Mb("/dev/tty1","/dev/stderr");Pb("/dev/stdin",0);Pb("/dev/stdout",1);Pb("/dev/stderr",1)}Md.ka();vb=!1;ma?.(m);m.onRuntimeInitialized?.();if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var d=
m.postRun.shift();Ha.push(d)}Ga(Ha)}}if(0<wa)xa=Nd;else{if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)Ka();Ga(Ia);0<wa?xa=Nd:m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),1);a()},1)):a()}}if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.shift()();Nd();moduleRtn=ua?m:new Promise((a,b)=>{ma=a;na=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=BlinkCardWasmSDK;module.exports.default=BlinkCardWasmSDK}else if(typeof define==="function"&&define["amd"])define([],()=>BlinkCardWasmSDK);
